// src/components/external/TransactionsOverview/components/Balances/BalancesCard.tsx
import { memo } from 'preact/compat';
import { useMemo, useState } from 'preact/hooks';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import ExpandableCard from '../../../../internal/ExpandableCard/ExpandableCard';
import { BalanceItem } from '../BalanceItem/BalanceItem';
import { IBalanceWithKey, BalancesCardProps } from './types';
import { useMaxWidthsState } from '../../hooks/useMaxWidths';
import { uniqueId } from '../../../../../utils';

export const BalancesCard = memo(({ balances, isLoading, hiddenField, fullWidth, ...ariaAttributes }: BalancesCardProps) => {
    const { i18n } = useCoreContext();
    const [maxWidths, setMaxWidths] = useMaxWidthsState();
    const [isHovered, setIsHovered] = useState(false);

    const localizedPlainCurrencyText = useMemo(() => i18n.get('transactions.overview.balances.currency.label'), [i18n]);

    const [firstBalance, ...restOfBalances] = useMemo<Required<IBalanceWithKey>[]>(() => {
        return balances.map((t: IBalanceWithKey) => ({
            ...t,
            key: t.currency,
            availableBalanceElemId: uniqueId('elem'),
            reservedBalanceElemId: uniqueId('elem'),
        }));
    }, [balances]);

    const balancesListLabel = useMemo(() => {
        switch (hiddenField) {
            case 'available':
                return i18n.get('transactions.overview.balances.lists.reserved');
            case 'reserved':
                return i18n.get('transactions.overview.balances.lists.available');
            default:
                return i18n.get('transactions.overview.balances.lists.default');
        }
    }, [i18n, hiddenField]);

    const renderFirstBalance = useMemo(
        () => (
            <div
                role="listitem"
                aria-label={firstBalance ? `${localizedPlainCurrencyText}: ${firstBalance.currency}` : undefined}
                aria-describedby={firstBalance ? `${firstBalance.availableBalanceElemId} ${firstBalance.reservedBalanceElemId}` : undefined}
            >
                <BalanceItem
                    showLabelUnderline={isHovered}
                    balance={firstBalance}
                    hiddenField={hiddenField}
                    widths={maxWidths}
                    isHeader
                    isSkeleton={isLoading}
                    isLoading={isLoading}
                    onWidthsSet={setMaxWidths}
                    reservedBalanceElemId={firstBalance?.reservedBalanceElemId}
                    availableBalanceElemId={firstBalance?.availableBalanceElemId}
                />
            </div>
        ),
        [isHovered, firstBalance, hiddenField, maxWidths, isLoading, setMaxWidths, localizedPlainCurrencyText]
    );

    const renderRestOfBalances = useMemo(() => {
        return !isLoading && restOfBalances.length ? (
            <>
                {restOfBalances.map(total => (
                    <div
                        role="listitem"
                        key={total.key}
                        aria-label={`${localizedPlainCurrencyText}: ${total.currency}`}
                        aria-describedby={`${total.availableBalanceElemId} ${total.reservedBalanceElemId}`}
                    >
                        <BalanceItem
                            showLabelUnderline={isHovered}
                            balance={total}
                            hiddenField={hiddenField}
                            widths={maxWidths}
                            onWidthsSet={setMaxWidths}
                            reservedBalanceElemId={total.reservedBalanceElemId}
                            availableBalanceElemId={total.availableBalanceElemId}
                        />
                    </div>
                ))}
            </>
        ) : undefined;
    }, [isLoading, restOfBalances, isHovered, hiddenField, maxWidths, setMaxWidths, localizedPlainCurrencyText]);

    return (
        <ExpandableCard
            renderContent={({ collapsibleContent }) => (
                <div role="list" aria-label={balancesListLabel}>
                    {renderFirstBalance}
                    {collapsibleContent}
                </div>
            )}
            fullWidth={fullWidth}
            onMouseEnter={() => setIsHovered(true)}
            onFocus={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
            onBlur={() => setIsHovered(false)}
            {...ariaAttributes}
        >
            {renderRestOfBalances}
        </ExpandableCard>
    );
});

// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/BalancesCard.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { BentoCard } from '@adyen/bento-vue3';
import BalanceItem from './BalanceItem.vue';
import { useCoreContext } from '../../../core/Context';
import { useMaxWidthsState } from '../composables/useMaxWidths';
import type { IBalance } from '../types';

type IBalanceWithKey = IBalance & {
    availableBalanceElemId?: string;
    reservedBalanceElemId?: string;
    key?: string;
};

const props = defineProps<{
    balances: readonly Readonly<IBalance>[];
    hiddenField?: 'available' | 'reserved';
    isLoading: boolean;
    fullWidth?: boolean;
    ariaLabel?: string;
}>();

const { i18n } = useCoreContext();
const { maxWidths, setMaxWidths } = useMaxWidthsState();
const isHovered = ref(false);

let _idCounter = 0;
function uniqueId(prefix = 'elem'): string {
    return `${prefix}-${++_idCounter}`;
}

const balancesWithKeys = computed<IBalanceWithKey[]>(() =>
    props.balances.map(b => ({
        ...b,
        key: b.currency,
        availableBalanceElemId: uniqueId('elem'),
        reservedBalanceElemId: uniqueId('elem'),
    }))
);

const firstBalance = computed(() => balancesWithKeys.value[0]);
const restOfBalances = computed(() => balancesWithKeys.value.slice(1));

const hasExpandableContent = computed(() => !props.isLoading && restOfBalances.value.length > 0);

const balancesListLabel = computed(() => {
    switch (props.hiddenField) {
        case 'available':
            return i18n.get('transactions.overview.balances.lists.reserved');
        case 'reserved':
            return i18n.get('transactions.overview.balances.lists.available');
        default:
            return i18n.get('transactions.overview.balances.lists.default');
    }
});
</script>

<template>
    <bento-card
        :expandable="hasExpandableContent"
        :closed="hasExpandableContent"
        :aria-label="props.ariaLabel"
        @mouseenter="isHovered = true"
        @mouseleave="isHovered = false"
        @focus="isHovered = true"
        @blur="isHovered = false"
    >
        <div role="list" :aria-label="balancesListLabel">
            <div
                v-if="firstBalance || props.isLoading"
                role="listitem"
                :aria-label="firstBalance ? `${i18n.get('transactions.overview.balances.currency.label')}: ${firstBalance.currency}` : undefined"
                :aria-describedby="firstBalance ? `${firstBalance.availableBalanceElemId} ${firstBalance.reservedBalanceElemId}` : undefined"
            >
                <BalanceItem
                    :show-label-underline="isHovered"
                    :balance="firstBalance"
                    :hidden-field="props.hiddenField"
                    :widths="maxWidths"
                    :is-header="true"
                    :is-skeleton="props.isLoading"
                    :is-loading="props.isLoading"
                    :on-widths-set="setMaxWidths"
                    :available-balance-elem-id="firstBalance?.availableBalanceElemId"
                    :reserved-balance-elem-id="firstBalance?.reservedBalanceElemId"
                />
            </div>
        </div>

        <template v-if="hasExpandableContent" #content>
            <div
                v-for="balance in restOfBalances"
                :key="balance.key"
                role="listitem"
                :aria-label="`${i18n.get('transactions.overview.balances.currency.label')}: ${balance.currency}`"
                :aria-describedby="`${balance.availableBalanceElemId} ${balance.reservedBalanceElemId}`"
            >
                <BalanceItem
                    :show-label-underline="isHovered"
                    :balance="balance"
                    :hidden-field="props.hiddenField"
                    :widths="maxWidths"
                    :on-widths-set="setMaxWidths"
                    :available-balance-elem-id="balance.availableBalanceElemId"
                    :reserved-balance-elem-id="balance.reservedBalanceElemId"
                />
            </div>
        </template>
    </bento-card>
</template>
