// packages/domains/transactions/preact/src/TransactionsOverview/components/Balances/Balances.tsx
import { memo } from 'preact/compat';
import { BalancesCard } from './BalancesCard';
import { BASE_CLASS, ITEM_CLASS } from './constants';
import { BalancesProps } from './types';
import { containerQueries, useResponsiveContainer } from '../../../../../../../../src/hooks/useResponsiveContainer';
import useCoreContext from '../../../../../../../../src/core/Context/useCoreContext';
import './Balances.scss';

const Balances = memo(({ balances, loadingBalances }: BalancesProps) => {
    const { i18n } = useCoreContext();
    const isXsContainer = useResponsiveContainer(containerQueries.only.xs);
    const isNarrowContainer = useResponsiveContainer(containerQueries.down.sm);

    return (
        <div className={BASE_CLASS}>
            {isXsContainer ? (
                <>
                    <div className={ITEM_CLASS}>
                        <BalancesCard
                            aria-label={i18n.get('transactions.overview.balances.labels.available')}
                            balances={balances}
                            isLoading={loadingBalances}
                            hiddenField="reserved"
                            fullWidth={isNarrowContainer}
                        />
                    </div>
                    <div className={ITEM_CLASS}>
                        <BalancesCard
                            aria-label={i18n.get('transactions.overview.balances.labels.reserved')}
                            balances={balances}
                            isLoading={loadingBalances}
                            hiddenField="available"
                            fullWidth={isNarrowContainer}
                        />
                    </div>
                </>
            ) : (
                <BalancesCard
                    aria-label={i18n.get('transactions.overview.balances.labels.default')}
                    balances={balances}
                    isLoading={loadingBalances}
                    fullWidth={isNarrowContainer}
                />
            )}
        </div>
    );
});

export default Balances;

// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/Balances.vue
<script setup lang="ts">
import { useCoreContext } from '../../../core/Context';
import BalancesCard from './BalancesCard.vue';
import type { IBalance } from '../types';

const props = defineProps<{
    balances: readonly Readonly<IBalance>[];
    loadingBalances: boolean;
}>();

const { i18n } = useCoreContext();

const BASE_CLASS = 'adyen-pe-balances';
</script>

<template>
    <div :class="BASE_CLASS">
        <!-- TODO: Add responsive container logic for xs breakpoint -->
        <BalancesCard
            :aria-label="i18n.get('transactions.overview.balances.labels.default')"
            :balances="props.balances"
            :is-loading="props.loadingBalances"
        />
    </div>
</template>
