// src/components/external/TransactionsOverview/components/InsightsTotals/InsightsTotals.tsx
import cx from 'classnames';
import { memo } from 'preact/compat';
import { useMemo } from 'preact/hooks';
import { classes } from './constants';
import { TranslationKey } from '../../../../../translations';
import { ITransactionCategory } from '../../../../../types';
import { getTransactionCategory } from '../../../../utils/translation/getters';
import { StructuredListItem } from '../../../../internal/StructuredList/types';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { ErrorMessageDisplay } from '../../../../internal/ErrorMessageDisplay/ErrorMessageDisplay';
import AmountDisplay, { AmountDisplayProps } from '../AmountDisplay/AmountDisplay';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import useTransactionsTotals from '../../hooks/useTransactionsTotals';
import useCurrenciesLookup from '../../hooks/useCurrenciesLookup';
import Typography from '../../../../internal/Typography/Typography';
import StructuredList from '../../../../internal/StructuredList';
import './InsightsTotals.scss';

interface InsightsTotalsProps {
    currency?: string;
    currenciesLookupResult: ReturnType<typeof useCurrenciesLookup>;
    transactionsTotalsResult: ReturnType<typeof useTransactionsTotals>;
}

const InsightsTotals = ({ currency, currenciesLookupResult, transactionsTotalsResult }: InsightsTotalsProps) => {
    const { i18n } = useCoreContext();
    const { currenciesDictionary } = currenciesLookupResult;

    const data = (currency && currenciesDictionary[currency]?.totals) || undefined;

    if (transactionsTotalsResult.isWaiting || !data) {
        const breakdownArray = Array.from({ length: 2 });
        const breakdownListArray = Array.from({ length: 3 });
        const className = cx(classes.skeleton, classes.skeletonLoading);

        return (
            <div className={classes.root}>
                <span className={cx(className, classes.skeletonAmount, classes.skeletonAmountLarge)} />

                <div className={classes.breakdowns}>
                    {breakdownArray.map((_, index) => (
                        <div className={classes.breakdown} key={`breakdown-${index}`}>
                            <span className={cx(className, classes.skeletonAmount)} />

                            <div className={classes.breakdownList}>
                                {breakdownListArray.map((_, index) => (
                                    <span className={className} key={`breakdown-${index}`} />
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        );
    }

    return (
        <div className={classes.root}>
            {transactionsTotalsResult.error ? (
                <div className={classes.errorContainer}>
                    <ErrorMessageDisplay
                        title={'common.errors.somethingWentWrong'}
                        message={['common.errors.retry']}
                        absolutePosition={false}
                        outlined={false}
                        withImage
                        refreshComponent
                        onRefreshComponent={transactionsTotalsResult.refresh}
                    />
                </div>
            ) : (
                <>
                    <AmountDisplay
                        amount={data.total}
                        currency={data.currency}
                        label={i18n.get('transactions.overview.totals.tags.periodResult')}
                        large
                    />

                    <div className={classes.breakdowns}>
                        <InsightsTotals.Breakdown
                            amount={data.incomings}
                            breakdown={data.breakdown.incomings}
                            currency={data.currency}
                            label={i18n.get('transactions.overview.totals.tags.incoming')}
                        />
                        <InsightsTotals.Breakdown
                            amount={data.expenses}
                            breakdown={data.breakdown.expenses}
                            currency={data.currency}
                            label={i18n.get('transactions.overview.totals.tags.outgoing')}
                        />
                    </div>
                </>
            )}
        </div>
    );
};

interface BreakdownProps extends AmountDisplayProps {
    ariaLabel?: string;
    breakdown: readonly { category: ITransactionCategory; value: number }[];
}

InsightsTotals.Breakdown = ({ ariaLabel, breakdown, ...amountDisplayProps }: BreakdownProps) => {
    const { currency } = amountDisplayProps;
    const { i18n } = useCoreContext();

    const listItems = useMemo(
        () =>
            breakdown.map(
                ({ category, value }): StructuredListItem => ({
                    key: getTransactionCategory(i18n, category) as TranslationKey,
                    value: `${i18n.amount(value, currency)} ${currency}`,
                })
            ),
        [i18n, breakdown, currency]
    );

    return (
        <div className={classes.breakdown}>
            <AmountDisplay {...amountDisplayProps} />
            <StructuredList
                items={listItems}
                aria-label={ariaLabel}
                classNames={classes.breakdownList}
                renderLabel={label => (
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                        {label}
                    </Typography>
                )}
                renderValue={value => (
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION} stronger>
                        {value}
                    </Typography>
                )}
            />
        </div>
    );
};

export default memo(InsightsTotals);

// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/InsightsTotals.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoStructuredList, BentoStructuredListItem, BentoButton, BentoLoadingIndicator } from '@adyen/bento-vue3';
import AmountDisplay from './AmountDisplay.vue';
import { useCoreContext } from '../../../core/Context';
import type { ITransactionTotal } from '../types';
import type { CurrencyLookupRecord } from '../composables/useCurrenciesLookup';

const props = defineProps<{
    currency?: string;
    currenciesDictionary: Readonly<Record<string, CurrencyLookupRecord>>;
    isWaiting: boolean;
    error?: Error;
    refresh: () => void;
    totals: readonly Readonly<ITransactionTotal>[];
}>();

const { i18n } = useCoreContext();

const data = computed(() => (props.currency && props.currenciesDictionary[props.currency]?.totals) || undefined);

const BASE_CLASS = 'adyen-pe-insights-totals';
</script>

<template>
    <div :class="BASE_CLASS">
        <!-- Loading state -->
        <template v-if="props.isWaiting || !data">
            <bento-loading-indicator />
        </template>

        <!-- Error state -->
        <template v-else-if="props.error">
            <div :class="`${BASE_CLASS}__error-container`">
                <p>{{ i18n.get('common.errors.somethingWentWrong') }}</p>
                <bento-button variant="secondary" @click="props.refresh">{{ i18n.get('common.errors.retry') }}</bento-button>
            </div>
        </template>

        <!-- Data display -->
        <template v-else>
            <AmountDisplay
                :amount="data.total"
                :currency="data.currency"
                :label="i18n.get('transactions.overview.totals.tags.periodResult')"
                :large="true"
            />

            <div :class="`${BASE_CLASS}__breakdowns`">
                <!-- Incoming breakdown -->
                <div :class="`${BASE_CLASS}__breakdown`">
                    <AmountDisplay
                        :amount="data.incomings"
                        :currency="data.currency"
                        :label="i18n.get('transactions.overview.totals.tags.incoming')"
                    />
                    <bento-structured-list layout="50-50">
                        <bento-structured-list-item
                            v-for="item in data.breakdown.incomings"
                            :key="item.category"
                            :label="i18n.get(`transactions.common.types.${item.category}`)"
                        >
                            {{ i18n.amount(item.value, data.currency) }} {{ data.currency }}
                        </bento-structured-list-item>
                    </bento-structured-list>
                </div>

                <!-- Outgoing breakdown -->
                <div :class="`${BASE_CLASS}__breakdown`">
                    <AmountDisplay
                        :amount="data.expenses"
                        :currency="data.currency"
                        :label="i18n.get('transactions.overview.totals.tags.outgoing')"
                    />
                    <bento-structured-list layout="50-50">
                        <bento-structured-list-item
                            v-for="item in data.breakdown.expenses"
                            :key="item.category"
                            :label="i18n.get(`transactions.common.types.${item.category}`)"
                        >
                            {{ i18n.amount(item.value, data.currency) }} {{ data.currency }}
                        </bento-structured-list-item>
                    </bento-structured-list>
                </div>
            </div>
        </template>
    </div>
</template>
