// packages/domains/transactions/preact/src/TransactionsOverview/components/TransactionsTable/PaymentMethodCell.tsx
import useCoreContext from '../../../../../../../../src/core/Context/useCoreContext';
import { IBankAccount, IPaymentMethod } from '../../../../../../../../src/types';
import { Image } from '../../../../../../../../src/components/internal/Image/Image';
import { Tag } from '../../../../../../../../src/components/internal/Tag/Tag';
import { TagVariant } from '../../../../../../../../src/components/internal/Tag/types';
import { TypographyVariant } from '../../../../../../../../src/components/internal/Typography/types';
import Typography from '../../../../../../../../src/components/internal/Typography/Typography';
import { containerQueries, useResponsiveContainer } from '../../../../../../../../src/hooks/useResponsiveContainer';
import { parsePaymentMethodType } from '../utils';
import { PAYMENT_METHOD_CLASS, PAYMENT_METHOD_LOGO_CLASS, PAYMENT_METHOD_LOGO_CONTAINER_CLASS } from './constants';

const PaymentMethodCell = ({ paymentMethod, bankAccount }: { paymentMethod?: IPaymentMethod; bankAccount?: IBankAccount }) => {
    const { i18n } = useCoreContext();
    const isSmContainer = useResponsiveContainer(containerQueries.down.xs);

    return (
        <div className={PAYMENT_METHOD_CLASS}>
            {paymentMethod || bankAccount ? (
                <>
                    <div className={PAYMENT_METHOD_LOGO_CONTAINER_CLASS}>
                        <Image
                            name={paymentMethod ? paymentMethod.type : 'bankTransfer'}
                            alt={paymentMethod ? paymentMethod.type : 'bankTransfer'}
                            folder={'logos/'}
                            className={PAYMENT_METHOD_LOGO_CLASS}
                        />
                    </div>
                    <Typography variant={TypographyVariant.BODY} stronger={isSmContainer}>
                        {paymentMethod ? parsePaymentMethodType(paymentMethod) : bankAccount?.accountNumberLastFourDigits}
                    </Typography>
                </>
            ) : (
                <Tag label={i18n.get('common.tags.noData')} variant={TagVariant.LIGHT_WITH_OUTLINE} />
            )}
        </div>
    );
};

export default PaymentMethodCell;

// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/PaymentMethodCell.vue
<script setup lang="ts">
import { BentoTag } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import { parsePaymentMethodType } from '../utils';
import type { IPaymentMethod, IBankAccount } from '../types';

const props = defineProps<{
    paymentMethod?: IPaymentMethod;
    bankAccount?: IBankAccount;
}>();

const { i18n } = useCoreContext();

const BASE_CLASS = 'adyen-pe-transactions-table';
const PAYMENT_METHOD_CLASS = `${BASE_CLASS}__payment-method`;
const PAYMENT_METHOD_LOGO_CONTAINER_CLASS = `${BASE_CLASS}__payment-method-logo-container`;
const PAYMENT_METHOD_LOGO_CLASS = `${BASE_CLASS}__payment-method-logo`;
</script>

<template>
    <div :class="PAYMENT_METHOD_CLASS">
        <template v-if="props.paymentMethod || props.bankAccount">
            <div :class="PAYMENT_METHOD_LOGO_CONTAINER_CLASS">
                <img
                    :src="`logos/${props.paymentMethod ? props.paymentMethod.type : 'bankTransfer'}.svg`"
                    :alt="props.paymentMethod ? props.paymentMethod.type : 'bankTransfer'"
                    :class="PAYMENT_METHOD_LOGO_CLASS"
                />
            </div>
            <span>
                {{ props.paymentMethod ? parsePaymentMethodType(props.paymentMethod) : props.bankAccount?.accountNumberLastFourDigits }}
            </span>
        </template>
        <template v-else>
            <bento-tag>{{ i18n.get('common.tags.noData') }}</bento-tag>
        </template>
    </div>
</template>
