// packages/domains/transactions/preact/src/TransactionsOverview/components/TransactionTotals/TotalsCard.tsx
import { memo } from 'preact/compat';
import { useMemo, useState } from 'preact/hooks';
import useCoreContext from '../../../../../../../../src/core/Context/useCoreContext';
import ExpandableCard from '../../../../../../../../src/components/internal/ExpandableCard/ExpandableCard';
import { TransactionTotalItem } from '../TransactionTotalItem/TransactionTotalItem';
import { ITransactionTotalWithKey, TotalsCardProps } from './types';
import { useMaxWidthsState } from '../../hooks/useMaxWidths';
import { uniqueId } from '../../../../../../../../src/utils';

export const TotalsCard = memo(({ totals, isLoading, hiddenField, fullWidth, ...ariaAttributes }: TotalsCardProps) => {
    const { i18n } = useCoreContext();
    const [maxWidths, setMaxWidths] = useMaxWidthsState();
    const [isHovered, setIsHovered] = useState(false);

    const localizedPlainCurrencyText = useMemo(() => i18n.get('transactions.overview.totals.currency.label'), [i18n]);

    const [firstTotal, ...restOfTotals] = useMemo<Required<ITransactionTotalWithKey>[]>(() => {
        return totals.map((t: ITransactionTotalWithKey) => ({
            ...t,
            key: t.currency,
            expensesElemId: uniqueId('elem'),
            incomingsElemId: uniqueId('elem'),
        }));
    }, [totals]);

    const totalsListLabel = useMemo(() => {
        switch (hiddenField) {
            case 'expenses':
                return i18n.get('transactions.overview.totals.lists.incoming');
            case 'incomings':
                return i18n.get('transactions.overview.totals.lists.outgoing');
            default:
                return i18n.get('transactions.overview.totals.lists.default');
        }
    }, [i18n, hiddenField]);

    const renderFirstTotal = useMemo(
        () => (
            <div
                role="listitem"
                aria-label={firstTotal ? `${localizedPlainCurrencyText}: ${firstTotal.currency}` : undefined}
                aria-describedby={firstTotal ? `${firstTotal.incomingsElemId} ${firstTotal.expensesElemId}` : undefined}
            >
                <TransactionTotalItem
                    showLabelUnderline={isHovered}
                    total={firstTotal}
                    hiddenField={hiddenField}
                    widths={maxWidths}
                    isHeader
                    isSkeleton={isLoading}
                    isLoading={isLoading}
                    onWidthsSet={setMaxWidths}
                    expensesElemId={firstTotal?.expensesElemId}
                    incomingsElemId={firstTotal?.incomingsElemId}
                />
            </div>
        ),
        [isHovered, firstTotal, hiddenField, maxWidths, isLoading, setMaxWidths, localizedPlainCurrencyText]
    );

    const renderRestOfTotals = useMemo(() => {
        return !isLoading && restOfTotals.length ? (
            <>
                {restOfTotals.map(total => (
                    <div
                        role="listitem"
                        key={total.key}
                        aria-label={`${localizedPlainCurrencyText}: ${total.currency}`}
                        aria-describedby={`${total.incomingsElemId} ${total.expensesElemId}`}
                    >
                        <TransactionTotalItem
                            showLabelUnderline={isHovered}
                            total={total}
                            hiddenField={hiddenField}
                            widths={maxWidths}
                            onWidthsSet={setMaxWidths}
                            expensesElemId={total.expensesElemId}
                            incomingsElemId={total.incomingsElemId}
                        />
                    </div>
                ))}
            </>
        ) : undefined;
    }, [isLoading, restOfTotals, isHovered, hiddenField, maxWidths, setMaxWidths, localizedPlainCurrencyText]);

    return (
        <ExpandableCard
            renderContent={({ collapsibleContent }) => (
                <div role="list" aria-label={totalsListLabel}>
                    {renderFirstTotal}
                    {collapsibleContent}
                </div>
            )}
            fullWidth={fullWidth}
            onMouseEnter={() => setIsHovered(true)}
            onFocus={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
            onBlur={() => setIsHovered(false)}
            {...ariaAttributes}
        >
            {renderRestOfTotals}
        </ExpandableCard>
    );
});

// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/TotalsCard.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { BentoCard } from '@adyen/bento-vue3';
import TransactionTotalItem from './TransactionTotalItem.vue';
import { useCoreContext } from '../../../core/Context';
import { useMaxWidthsState } from '../composables/useMaxWidths';
import type { ITransactionTotal } from '../types';

type ITransactionTotalWithKey = ITransactionTotal &
    Partial<{
        expensesElemId: string;
        incomingsElemId: string;
        key: string;
    }>;

const props = defineProps<{
    totals: readonly Readonly<ITransactionTotal>[];
    hiddenField?: 'incomings' | 'expenses';
    isLoading: boolean;
    fullWidth?: boolean;
    ariaLabel?: string;
}>();

const { i18n } = useCoreContext();
const { maxWidths, setMaxWidths } = useMaxWidthsState();
const isHovered = ref(false);

let _idCounter = 0;
function uniqueId(prefix = 'elem'): string {
    return `${prefix}-${++_idCounter}`;
}

const totalsWithKeys = computed<ITransactionTotalWithKey[]>(() =>
    props.totals.map(t => ({
        ...t,
        key: t.currency,
        expensesElemId: uniqueId('elem'),
        incomingsElemId: uniqueId('elem'),
    }))
);

const firstTotal = computed(() => totalsWithKeys.value[0]);
const restOfTotals = computed(() => totalsWithKeys.value.slice(1));

const hasExpandableContent = computed(() => !props.isLoading && restOfTotals.value.length > 0);

const totalsListLabel = computed(() => {
    switch (props.hiddenField) {
        case 'expenses':
            return i18n.get('transactions.overview.totals.lists.incoming');
        case 'incomings':
            return i18n.get('transactions.overview.totals.lists.outgoing');
        default:
            return i18n.get('transactions.overview.totals.lists.default');
    }
});
</script>

<template>
    <bento-card
        :expandable="hasExpandableContent"
        closed
        :aria-label="props.ariaLabel"
        @mouseenter="isHovered = true"
        @mouseleave="isHovered = false"
        @focus="isHovered = true"
        @blur="isHovered = false"
    >
        <div role="list" :aria-label="totalsListLabel">
            <div
                v-if="firstTotal || props.isLoading"
                role="listitem"
                :aria-label="firstTotal ? `${i18n.get('transactions.overview.totals.currency.label')}: ${firstTotal.currency}` : undefined"
                :aria-describedby="firstTotal ? `${firstTotal.incomingsElemId} ${firstTotal.expensesElemId}` : undefined"
            >
                <TransactionTotalItem
                    :show-label-underline="isHovered"
                    :total="firstTotal"
                    :hidden-field="props.hiddenField"
                    :widths="maxWidths"
                    :is-header="true"
                    :is-skeleton="props.isLoading"
                    :is-loading="props.isLoading"
                    :on-widths-set="setMaxWidths"
                    :expenses-elem-id="firstTotal?.expensesElemId"
                    :incomings-elem-id="firstTotal?.incomingsElemId"
                />
            </div>
        </div>

        <template v-if="hasExpandableContent" #content>
            <div
                v-for="total in restOfTotals"
                :key="total.key"
                role="listitem"
                :aria-label="`${i18n.get('transactions.overview.totals.currency.label')}: ${total.currency}`"
                :aria-describedby="`${total.incomingsElemId} ${total.expensesElemId}`"
            >
                <TransactionTotalItem
                    :show-label-underline="isHovered"
                    :total="total"
                    :hidden-field="props.hiddenField"
                    :widths="maxWidths"
                    :on-widths-set="setMaxWidths"
                    :expenses-elem-id="total.expensesElemId"
                    :incomings-elem-id="total.incomingsElemId"
                />
            </div>
        </template>
    </bento-card>
</template>
