// src/components/external/TransactionsOverview/components/TransactionsExport/TransactionsExport.tsx
import { h } from 'preact';
import cx from 'classnames';
import Icon from '../../../../internal/Icon';
import Spinner from '../../../../internal/Spinner';
import Alert from '../../../../internal/Alert/Alert';
import Popover from '../../../../internal/Popover/Popover';
import Typography from '../../../../internal/Typography/Typography';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import useDownload from '../../../../internal/Button/DownloadButton/useDownload';
import useAnalyticsContext from '../../../../../core/Context/analytics/useAnalyticsContext';
import ToggleSwitch, { ToggleSwitchProps } from '../../../../internal/ToggleSwitch/ToggleSwitch';
import ButtonActions from '../../../../internal/Button/ButtonActions/ButtonActions';
import FilterButton from '../../../../internal/FilterBar/components/FilterButton/FilterButton';
import { DEFAULT_EXPORT_COLUMNS, EXPORT_COLUMNS, TRANSACTION_ANALYTICS_CATEGORY, TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } from '../../constants';
import { ButtonActionObject, ButtonActionsLayoutBasic } from '../../../../internal/Button/ButtonActions/types';
import { containerQueries, useResponsiveContainer } from '../../../../../hooks/useResponsiveContainer';
import { PopoverContainerPosition, PopoverContainerVariant } from '../../../../internal/Popover/types';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { downloadBlob, EMPTY_ARRAY, isFunction, uniqueId } from '../../../../../utils';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { useConfigContext } from '../../../../../core/ConfigContext';
import { AlertTypeOption } from '../../../../internal/Alert/types';
import { ButtonVariant } from '../../../../internal/Button/types';
import { fixedForwardRef } from '../../../../../utils/preact';
import { getTransactionsFilterQueryParams } from '../utils';
import { TranslationKey } from '../../../../../translations';
import { Tag } from '../../../../internal/Tag/Tag';
import { TransactionsFilters } from '../../types';
import { PropsWithChildren } from 'preact/compat';
import { classes } from './constants';
import './TransactionsExport.scss';

const sharedAnalyticsEventProperties = {
    category: TRANSACTION_ANALYTICS_CATEGORY,
    subCategory: TRANSACTION_ANALYTICS_SUBCATEGORY_LIST,
} as const;

/* HELPER COMPONENTS */
const Text = ({
    children,
    el = TypographyElement.DIV,
    variant = TypographyVariant.BODY,
    ...typographyProps
}: PropsWithChildren<{
    el?: TypographyElement;
    variant?: TypographyVariant;
    stronger?: boolean;
    className?: string;
    id?: string;
}>) => (
    <Typography {...typographyProps} el={el} variant={variant}>
        {children}
    </Typography>
);

const ExportColumn = fixedForwardRef<PropsWithChildren<{ className?: string } & ToggleSwitchProps>, HTMLInputElement>(
    ({ children, className, ...toggleSwitchProps }, ref) => (
        <ToggleSwitch ref={ref} className={cx([classes.popoverColumn, className])} {...toggleSwitchProps} name="columns">
            <Text el={TypographyElement.SPAN}>{children}</Text>
        </ToggleSwitch>
    )
);

const SectionTitle = ({ children, ...textProps }: PropsWithChildren<{ id?: string }>) => (
    <Text {...textProps} className={classes.popoverSectionTitle} stronger>
        {children}
    </Text>
);

const TransactionsExport = ({ disabled, filters, now }: { disabled?: boolean; filters: Readonly<TransactionsFilters>; now: number }) => {
    const { i18n } = useCoreContext();
    const userEvents = useAnalyticsContext();
    const isSmContainer = useResponsiveContainer(containerQueries.down.xs);

    const [popoverOpen, setPopoverOpen] = useState(false);
    const [exportError, setExportError] = useState<Error>();
    const [exportStarted, setExportStarted] = useState(false);
    const [exportColumns, setExportColumns] = useState([] as readonly (typeof EXPORT_COLUMNS)[number][]);

    const [activeFilters, exportParams] = useMemo(() => {
        const { balanceAccount, paymentPspReference, createdDate, categories, currencies /*, statuses*/ } = filters;

        const activeFilters: readonly TranslationKey[] = [
            ...(balanceAccount?.id ? (['transactions.overview.export.filters.types.account'] as const) : EMPTY_ARRAY),
            ...(createdDate ? (['transactions.overview.export.filters.types.date'] as const) : EMPTY_ARRAY),
            // ...(statuses.length ? (['transactions.overview.export.filters.types.status'] as const) : EMPTY_ARRAY),
            ...(categories.length ? (['transactions.overview.export.filters.types.category'] as const) : EMPTY_ARRAY),
            ...(currencies.length ? (['transactions.overview.export.filters.types.currency'] as const) : EMPTY_ARRAY),
            ...(paymentPspReference ? (['transactions.overview.export.filters.types.paymentPspReference'] as const) : EMPTY_ARRAY),
        ] as const;

        const exportParams = {
            ...getTransactionsFilterQueryParams(filters, now),
            sortDirection: 'desc' as const,
        };

        return [activeFilters, exportParams];
    }, [filters, now]);

    const { downloadTransactions } = useConfigContext().endpoints;
    const canDownloadTransactions = isFunction(downloadTransactions);
    const canExportTransactions = canDownloadTransactions && popoverOpen && exportStarted && !!exportColumns.length;

    const { error, isFetching } = useDownload(
        'downloadTransactions',
        { query: { ...exportParams, columns: exportColumns } },
        canExportTransactions,
        downloadBlob
    );

    const exportButtonRef = useRef<HTMLButtonElement | null>(null);
    const exportButtonLabel = useMemo(() => i18n.get('transactions.overview.export.button.label'), [i18n]);
    const exportingButtonLabel = useMemo(() => i18n.get('transactions.overview.export.button.inProgress'), [i18n]);
    const cancelButtonLabel = useMemo(() => i18n.get('transactions.overview.export.actions.cancel'), [i18n]);
    const downloadButtonLabel = useMemo(() => i18n.get('transactions.overview.export.actions.download'), [i18n]);
    const activeFiltersTitle = useMemo(() => i18n.get('transactions.overview.export.filters.title'), [i18n]);
    const exportColumnsTitle = useMemo(() => i18n.get('transactions.overview.export.columns.title'), [i18n]);
    const exportColumnsTitleId = useMemo(uniqueId, []);

    const columnSwitches = useMemo(
        () =>
            EXPORT_COLUMNS.map(column => ({
                label: i18n.get(`transactions.overview.export.columns.types.${column}`),
                id: uniqueId(),
                value: column,
            })),
        [i18n]
    );

    const masterSwitchLabel = useMemo(() => {
        return i18n.get('transactions.overview.export.columns.types.all', {
            values: { count: EXPORT_COLUMNS.length },
        });
    }, [i18n]);

    const masterSwitchId = useMemo(uniqueId, []);
    const masterSwitchRef = useRef<HTMLInputElement | null>(null);
    const masterSwitchAriaControls = useMemo(() => columnSwitches.map(({ id }) => id).join(' '), [columnSwitches]);
    const masterSwitchChecked = exportColumns.length === EXPORT_COLUMNS.length;

    const onExportColumnChange = useCallback(
        (evt: h.JSX.TargetedEvent<HTMLInputElement>) => {
            const checkbox = evt.currentTarget;
            const checkedColumn = checkbox.value as (typeof EXPORT_COLUMNS)[number];
            const checked = checkbox.checked;

            const isMasterSwitch = checkbox.id === masterSwitchId;

            setExportColumns(exportColumns => {
                if (isMasterSwitch) return checked ? EXPORT_COLUMNS : EMPTY_ARRAY;
                if (EXPORT_COLUMNS.includes(checkedColumn)) {
                    const columnIndex = exportColumns.indexOf(checkedColumn);
                    if (checked) {
                        // Include checked column
                        if (columnIndex < 0) return [...exportColumns, checkedColumn];
                    } else if (columnIndex >= 0) {
                        // Exclude unchecked column
                        return [...exportColumns.slice(0, columnIndex), ...exportColumns.slice(columnIndex + 1)];
                    }
                }
                return exportColumns;
            });
        },
        [masterSwitchId]
    );

    const sendPopoverToggleEvent = useCallback(
        (popoverOpen: boolean) => {
            popoverOpen
                ? userEvents.addEvent?.('Cancelled export', sharedAnalyticsEventProperties)
                : userEvents.addEvent?.('Clicked button', { ...sharedAnalyticsEventProperties, label: 'Export' });
        },
        [userEvents]
    );

    const dismissPopover = useCallback(
        (exportCancelled = true) => {
            setPopoverOpen(false);
            if (!exportCancelled) return;
            sendPopoverToggleEvent(true);
        },
        [sendPopoverToggleEvent]
    );

    const togglePopover = useCallback(() => {
        setPopoverOpen(prev => !prev);
        sendPopoverToggleEvent(popoverOpen);
    }, [popoverOpen, sendPopoverToggleEvent]);

    const dismissExportError = useCallback(() => setExportError(undefined), []);

    const cancelAction = useMemo<ButtonActionObject>(
        () => ({
            event: () => dismissPopover(),
            variant: ButtonVariant.SECONDARY,
            title: cancelButtonLabel,
        }),
        [cancelButtonLabel, dismissPopover]
    );

    const downloadAction = useMemo<ButtonActionObject>(
        () => ({
            disabled: !exportColumns.length,
            event: () => setExportStarted(true),
            variant: ButtonVariant.PRIMARY,
            title: downloadButtonLabel,
        }),
        [downloadButtonLabel, exportColumns.length]
    );

    useEffect(() => {
        setExportError(error);
    }, [error]);

    useEffect(() => {
        if (popoverOpen) {
            dismissExportError();
        } else {
            setExportColumns(DEFAULT_EXPORT_COLUMNS);
        }
    }, [popoverOpen, dismissExportError]);

    useEffect(() => {
        if (exportStarted) {
            setExportStarted(false);
            dismissPopover(false);

            let exportedFields: 'All' | 'Custom' | 'Default' = 'Custom';
            let exportingOnlyDefaultFields = true;
            let exportingAllFields = true;

            EXPORT_COLUMNS.forEach(column => {
                const isExportedField = exportColumns.includes(column);
                const isDefaultField = DEFAULT_EXPORT_COLUMNS.includes(column);
                exportingOnlyDefaultFields &&= isExportedField ? isDefaultField : !isDefaultField;
                exportingAllFields &&= isExportedField;
            });

            if (exportingAllFields) {
                exportedFields = 'All';
            } else if (exportingOnlyDefaultFields) {
                exportedFields = 'Default';
            }

            userEvents.addEvent?.('Completed export', {
                ...sharedAnalyticsEventProperties,
                exportedFields,
            });
        }
    }, [exportColumns, exportStarted, dismissPopover, userEvents]);

    useEffect(() => {
        (function attemptFocusCapture() {
            if (masterSwitchRef.current) {
                masterSwitchRef.current.focus();
            } else requestAnimationFrame(attemptFocusCapture);
        })();
    }, []);

    const renderAlertError = useCallback(
        () => (
            <Alert onClose={dismissExportError} className={classes.errorAlert} type={AlertTypeOption.CRITICAL}>
                <Typography variant={TypographyVariant.BODY}>{i18n.get('transactions.overview.export.actions.error')}</Typography>
            </Alert>
        ),
        [i18n, dismissExportError]
    );

    return canDownloadTransactions ? (
        <div className={classes.root}>
            <>
                <FilterButton
                    aria-label={exportButtonLabel}
                    ref={exportButtonRef}
                    className={classes.button}
                    classNameModifiers={popoverOpen ? ['active'] : undefined}
                    disabled={disabled || isFetching}
                    onClick={togglePopover}
                    tabIndex={0}
                >
                    <div className="adyen-pe-filter-button__default-container">
                        <Text className="adyen-pe-filter-button__label">
                            {isFetching ? <Spinner size="x-small" /> : <Icon name="download" />}
                            {!isSmContainer && <span>{isFetching ? exportingButtonLabel : exportButtonLabel}</span>}
                        </Text>
                    </div>
                </FilterButton>
                {exportError && renderAlertError()}
            </>

            {popoverOpen && (
                <Popover
                    disableFocusTrap={false}
                    dismissible={false}
                    dismiss={dismissPopover}
                    open={popoverOpen}
                    position={isSmContainer ? PopoverContainerPosition.BOTTOM : PopoverContainerPosition.BOTTOM_RIGHT}
                    variant={PopoverContainerVariant.POPOVER}
                    showOverlay={isSmContainer}
                    targetElement={exportButtonRef}
                    title={exportButtonLabel}
                >
                    <div className={classes.popover}>
                        <div className={classes.popoverSections}>
                            <div className={cx(classes.popoverSection, classes.filtersSection)}>
                                <SectionTitle>{`${activeFiltersTitle}:`}</SectionTitle>
                                {activeFilters.map(filter => (
                                    <Tag label={i18n.get(filter)} key={filter} />
                                ))}
                            </div>

                            <div className={cx(classes.popoverSection, classes.columnsSection)}>
                                <div role="group" aria-labelledby={exportColumnsTitleId}>
                                    <SectionTitle id={exportColumnsTitleId}>{exportColumnsTitle}</SectionTitle>
                                    <div className={classes.popoverSectionContent}>
                                        <ExportColumn
                                            ref={masterSwitchRef}
                                            className={classes.popoverColumnAll}
                                            aria-controls={masterSwitchAriaControls}
                                            checked={masterSwitchChecked}
                                            onChange={onExportColumnChange}
                                            id={masterSwitchId}
                                        >
                                            {masterSwitchLabel}
                                        </ExportColumn>

                                        {columnSwitches.map(({ id, label, value }) => (
                                            <ExportColumn
                                                checked={exportColumns.includes(value)}
                                                onChange={onExportColumnChange}
                                                value={value}
                                                key={value}
                                                id={id}
                                            >
                                                {label}
                                            </ExportColumn>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className={classes.popoverActions}>
                            <Alert
                                type={AlertTypeOption.HIGHLIGHT}
                                className={classes.popoverActionsAlert}
                                title={i18n.get('transactions.overview.export.actions.download.info')}
                            />
                            <ButtonActions actions={[downloadAction, cancelAction]} layout={ButtonActionsLayoutBasic.BUTTONS_END} />
                        </div>
                    </div>
                </Popover>
            )}
        </div>
    ) : null;
};

export default TransactionsExport;

// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/TransactionsExport.vue
<script setup lang="ts">
import { ref, computed, watch, toRaw } from 'vue';
import { BentoButton, BentoPopover, BentoToggle, BentoTag } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import { useConfigContext } from '../../../core/ConfigContext';
import { getTransactionsFilterQueryParams, isFunction } from '../utils';
import { EXPORT_COLUMNS, DEFAULT_EXPORT_COLUMNS } from '../constants';
import type { TransactionsFilters } from '../types';

const props = defineProps<{
    disabled?: boolean;
    filters: Readonly<TransactionsFilters>;
    now: number;
}>();

const { i18n } = useCoreContext();
const { endpoints } = useConfigContext();

const popoverOpen = ref(false);
const triggerRef = ref<HTMLElement | null>(null);
const exportError = ref<Error | undefined>();
const exportColumns = ref<readonly (typeof EXPORT_COLUMNS)[number][]>([...DEFAULT_EXPORT_COLUMNS]);
const isExporting = ref(false);

const downloadTransactions = computed(() => endpoints.downloadTransactions);
const canDownloadTransactions = computed(() => isFunction(downloadTransactions.value));

const exportButtonLabel = computed(() => i18n.get('transactions.overview.export.button.label'));
const exportingButtonLabel = computed(() => i18n.get('transactions.overview.export.button.inProgress'));
const activeFiltersTitle = computed(() => i18n.get('transactions.overview.export.filters.title'));
const exportColumnsTitle = computed(() => i18n.get('transactions.overview.export.columns.title'));

const masterSwitchChecked = computed(() => exportColumns.value.length === EXPORT_COLUMNS.length);

const columnSwitches = computed(() =>
    EXPORT_COLUMNS.map(column => ({
        label: i18n.get(`transactions.overview.export.columns.types.${column}`),
        value: column,
    }))
);

const masterSwitchLabel = computed(() => i18n.get('transactions.overview.export.columns.types.all', { values: { count: EXPORT_COLUMNS.length } }));

const activeFilters = computed(() => {
    const { balanceAccount, paymentPspReference, createdDate, categories, currencies } = props.filters;
    const filters: string[] = [];
    if (balanceAccount?.id) filters.push(i18n.get('transactions.overview.export.filters.types.account'));
    if (createdDate) filters.push(i18n.get('transactions.overview.export.filters.types.date'));
    if (categories.length) filters.push(i18n.get('transactions.overview.export.filters.types.category'));
    if (currencies.length) filters.push(i18n.get('transactions.overview.export.filters.types.currency'));
    if (paymentPspReference) filters.push(i18n.get('transactions.overview.export.filters.types.paymentPspReference'));
    return filters;
});

function togglePopover() {
    popoverOpen.value = !popoverOpen.value;
}

function dismissPopover() {
    console.log('trigger dismissPopover', triggerRef.value);
    popoverOpen.value = false;
}

function onExportColumnChange(column: (typeof EXPORT_COLUMNS)[number], checked: boolean) {
    if (checked) {
        if (!exportColumns.value.includes(column)) {
            exportColumns.value = [...exportColumns.value, column];
        }
    } else {
        exportColumns.value = exportColumns.value.filter(c => c !== column);
    }
}

function onMasterSwitchChange(checked: boolean) {
    exportColumns.value = checked ? [...EXPORT_COLUMNS] : [];
}

async function startExport() {
    const fn = downloadTransactions.value;
    if (!isFunction(fn) || !exportColumns.value.length) return;

    isExporting.value = true;
    exportError.value = undefined;
    dismissPopover();

    try {
        const exportParams = {
            ...getTransactionsFilterQueryParams(toRaw(props.filters), props.now),
            sortDirection: 'desc' as const,
            columns: exportColumns.value as string[],
        };
        const result = await fn({}, { query: exportParams as any });
        // Handle blob download
        if (result?.blob) {
            const url = URL.createObjectURL(result.blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = result.filename || 'transactions.csv';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }
    } catch (e) {
        exportError.value = e as Error;
    } finally {
        isExporting.value = false;
    }
}

// Reset columns when popover opens
watch(popoverOpen, open => {
    if (!open) {
        exportColumns.value = [...DEFAULT_EXPORT_COLUMNS];
    }
    exportError.value = undefined;
});

const popoverActions = computed(() => [
    { title: i18n.get('transactions.overview.export.actions.download'), event: startExport, disabled: !exportColumns.value.length },
    { title: i18n.get('transactions.overview.export.actions.cancel'), event: dismissPopover },
]);

const BASE_CLASS = 'adyen-pe-transactions-export';
</script>

<template>
    <div v-if="canDownloadTransactions" :class="BASE_CLASS">
        <bento-button
            :disabled="props.disabled || isExporting"
            variant="secondary"
            @click="togglePopover"
            :aria-label="exportButtonLabel"
            ref="triggerRef"
        >
            {{ isExporting ? exportingButtonLabel : exportButtonLabel }}
        </bento-button>

        <!-- Export error alert -->
        <div v-if="exportError" :class="`${BASE_CLASS}__error-alert`" role="alert">
            <p>{{ i18n.get('transactions.overview.export.actions.error') }}</p>
            <bento-button variant="tertiary" size="small" @click="exportError = undefined">&times;</bento-button>
        </div>

        <!-- Export popover -->
        <bento-popover
            v-if="triggerRef"
            :open="popoverOpen"
            :target-element="triggerRef"
            position="bottom-end"
            :title="exportButtonLabel"
            :dismissible="true"
            :actions="popoverActions"
            @dismiss="dismissPopover"
        >
            <div :class="`${BASE_CLASS}__popover-sections`">
                <!-- Active filters section -->
                <div :class="`${BASE_CLASS}__popover-section ${BASE_CLASS}__popover-section--filters`">
                    <div :class="`${BASE_CLASS}__popover-section-title`">{{ activeFiltersTitle }}:</div>
                    <BentoTag v-for="filter in activeFilters" :key="filter">{{ filter }}</BentoTag>
                </div>

                <!-- Columns section -->
                <div :class="`${BASE_CLASS}__popover-section ${BASE_CLASS}__popover-section--columns`">
                    <div :class="`${BASE_CLASS}__popover-section-title`">{{ exportColumnsTitle }}</div>
                    <div :class="`${BASE_CLASS}__popover-section-content`">
                        <!-- Master switch -->
                        <BentoToggle :value="masterSwitchChecked" @input="onMasterSwitchChange">
                            {{ masterSwitchLabel }}
                        </BentoToggle>

                        <!-- Individual column switches -->
                        <BentoToggle
                            v-for="col in columnSwitches"
                            :key="col.value"
                            :value="exportColumns.includes(col.value)"
                            @input="(checked: boolean) => onExportColumnChange(col.value, checked)"
                        >
                            {{ col.label }}
                        </BentoToggle>
                    </div>
                </div>
            </div>

            <p>{{ i18n.get('transactions.overview.export.actions.download.info') }}</p>
        </bento-popover>
    </div>
</template>
