// packages/domains/transactions/preact/src/TransactionsOverview/components/TransactionsList/TransactionDetailsModal.tsx
import { useEffect } from 'preact/hooks';
import { classes } from '../../constants';
import { FC, PropsWithChildren } from 'preact/compat';
import { TransactionDetailsProps } from '../../../TransactionDetails';
import { popoverUtil } from '../../../../../../../../src/components/internal/Popover/utils/popoverUtil';
import useCoreContext from '../../../../../../../../src/core/Context/useCoreContext';
import useModalDetails from '../../../../../../../../src/hooks/useModalDetails/useModalDetails';
import TransactionData from '../../../TransactionDetails/components/TransactionData';
import Modal from '../../../../../../../../src/components/internal/Modal';

export interface DataOverviewDisplayProps {
    onContactSupport?: () => void;
    dataCustomization?: TransactionDetailsProps['dataCustomization'];
    resetDetails: ReturnType<typeof useModalDetails>['resetDetails'];
    selectedDetail: ReturnType<typeof useModalDetails>['selectedDetail'];
}

export const TransactionDetailsModal: FC<DataOverviewDisplayProps> = ({
    children,
    dataCustomization,
    onContactSupport,
    selectedDetail,
    resetDetails,
}: PropsWithChildren<DataOverviewDisplayProps>) => {
    const { i18n } = useCoreContext();
    const isModalOpen = !!selectedDetail;

    useEffect(() => {
        if (isModalOpen) {
            popoverUtil.closeAll();
        }
    }, [isModalOpen]);

    return (
        <div className={classes.details}>
            {children}
            {selectedDetail && (
                <Modal
                    isOpen={isModalOpen}
                    aria-label={i18n.get('transactions.details.title')}
                    onClose={resetDetails}
                    isDismissible={true}
                    headerWithBorder={false}
                    size={selectedDetail.modalSize || 'large'}
                >
                    <TransactionData
                        id={selectedDetail.selection.data}
                        dataCustomization={dataCustomization}
                        onContactSupport={onContactSupport}
                        hideTitle
                    />
                </Modal>
            )}
        </div>
    );
};

// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/TransactionDetailsModal.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoModal } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import { ModalProvider } from '../../../core/ModalContext';
import TransactionData from '../../TransactionDetails/TransactionData.vue';
import { classes } from '../constants';

const props = defineProps<{
    onContactSupport?: () => void;
    dataCustomization?: {
        details?: {
            fields?: Record<string, { visibility?: 'hidden' | 'visible'; label?: string }>;
            onDataRetrieve?: (data: any) => Promise<Record<string, any>> | Record<string, any>;
        };
    };
    selectedDetail?: {
        selection: { data: string; type: string; balanceAccount?: any };
        modalSize?: string;
    } | null;
    resetDetails: () => void;
}>();

const { i18n } = useCoreContext();
const isModalOpen = computed(() => !!props.selectedDetail);

const modalSize = computed(() => {
    const size = props.selectedDetail?.modalSize;
    if (size === 'small') return 'small';
    if (size === 'medium') return 'medium';
    return 'large';
});
</script>

<template>
    <div :class="classes.details">
        <slot />

        <bento-modal
            :is-open="isModalOpen"
            :size="modalSize"
            :is-dismissible="true"
            :aria-label="i18n.get('transactions.details.title')"
            @close-modal="props.resetDetails"
        >
            <template #content>
                <ModalProvider :within-modal="true">
                    <TransactionData
                        v-if="props.selectedDetail"
                        :id="props.selectedDetail.selection.data"
                        :data-customization="props.dataCustomization"
                        :on-contact-support="props.onContactSupport"
                        :hide-title="true"
                    />
                </ModalProvider>
            </template>
        </bento-modal>
    </div>
</template>
