// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/TransactionsOverviewList.vue
<script setup lang="ts">
import { useCoreContext } from '../../../core/Context';
import TransactionTotals from './TransactionTotals.vue';
import Balances from './Balances.vue';
import TransactionsList from './TransactionsList.vue';
import { classes } from '../constants';
import type { IBalanceAccountBase, ITransaction, ITransactionTotal, IBalance } from '../types';

const props = defineProps<{
    balanceAccount?: IBalanceAccountBase;
    balanceAccounts: IBalanceAccountBase[] | undefined;
    isLoadingBalanceAccount: boolean;
    onContactSupport?: () => void;
    onRecordSelection?: (record: { id: string }) => void;
    showDetails?: boolean;
    dataCustomization?: any;
    // Account balances
    balancesError?: Error;
    loadingBalances: boolean;
    sortedBalances: readonly Readonly<IBalance>[];
    balancesCanRefresh: boolean;
    balancesRefresh: () => void;
    // Transaction totals
    totalsError?: Error;
    loadingTotals: boolean;
    sortedTotals: readonly Readonly<ITransactionTotal>[];
    totalsCanRefresh: boolean;
    totalsRefresh: () => void;
    // Currencies
    currenciesSortedCurrencies: readonly string[];
    // Transactions list
    transactionsError?: Error;
    transactionsFetching: boolean;
    transactions: ITransaction[] | undefined;
    hasNext: boolean;
    hasPrevious: boolean;
    goToNextPage: () => void;
    goToPreviousPage: () => void;
    limit: number;
    limitOptions?: number[];
    updateLimit: (limit: number) => void;
    currentPage?: number;
}>();

const { i18n } = useCoreContext();
</script>

<template>
    <div>
        <div :class="classes.summary">
            <div :class="classes.summaryItem">
                <!-- Totals error or card -->
                <div v-if="props.totalsError" :class="classes.totalsError" class="adyen-pe-alert adyen-pe-alert--warning">
                    <p>{{ i18n.get('transactions.overview.totals.error') }}</p>
                    <button :disabled="!props.totalsCanRefresh" @click="props.totalsRefresh">
                        {{ i18n.get('common.actions.refresh.labels.default') }}
                    </button>
                </div>
                <TransactionTotals v-else :totals="props.sortedTotals" :loading-totals="props.loadingTotals" />
            </div>

            <div :class="classes.summaryItem">
                <!-- Balances error or card -->
                <div v-if="props.balancesError" :class="classes.totalsError" class="adyen-pe-alert adyen-pe-alert--warning">
                    <p>{{ i18n.get('transactions.overview.balances.error') }}</p>
                    <button :disabled="!props.balancesCanRefresh" @click="props.balancesRefresh">
                        {{ i18n.get('common.actions.refresh.labels.default') }}
                    </button>
                </div>
                <Balances v-else :balances="props.sortedBalances" :loading-balances="props.loadingBalances" />
            </div>
        </div>

        <TransactionsList
            :balance-account="props.balanceAccount"
            :currencies-sorted-currencies="props.currenciesSortedCurrencies"
            :loading-balance-accounts="props.isLoadingBalanceAccount || !props.balanceAccounts"
            :data-customization="props.dataCustomization"
            :on-contact-support="props.onContactSupport"
            :on-record-selection="props.onRecordSelection"
            :show-details="props.showDetails"
            :transactions-error="props.transactionsError"
            :transactions-fetching="props.transactionsFetching"
            :transactions="props.transactions"
            :has-next="props.hasNext"
            :has-previous="props.hasPrevious"
            :go-to-next-page="props.goToNextPage"
            :go-to-previous-page="props.goToPreviousPage"
            :limit="props.limit"
            :limit-options="props.limitOptions"
            :update-limit="props.updateLimit"
            :current-page="props.currentPage"
        />
    </div>
</template>

// src/components/external/Transactions/TransactionsOverview/components/TransactionsOverview/TransactionsOverviewList.tsx
import { useCallback, useMemo } from 'preact/hooks';
import { TransactionOverviewProps } from '../../types';
import { IBalanceAccountBase } from '../../../../../../types';
import { TransactionsListProps } from '../TransactionsList/types';
import { classes, TRANSACTION_ANALYTICS_CATEGORY, TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } from '../../constants';
import { useLandedPageEvent } from '../../../../../../hooks/useAnalytics/useLandedPageEvent';
import { useDurationEvent } from '../../../../../../hooks/useAnalytics/useDurationEvent';
import useAccountBalances from '../../../../../../hooks/useAccountBalances';
import useTransactionsTotals from '../../hooks/useTransactionsTotals';
import useTransactionsList from '../../hooks/useTransactionsList';
import TransactionsList from '../TransactionsList/TransactionsList';
import TransactionTotals from '../TransactionTotals/TransactionTotals';
import Balances from '../Balances/Balances';
import Alert from '../../../../../internal/Alert/Alert';
import Button from '../../../../../internal/Button';
import useCoreContext from '../../../../../../core/Context/useCoreContext';
import { AlertTypeOption } from '../../../../../internal/Alert/types';
import { ButtonVariant } from '../../../../../internal/Button/types';

const sharedAnalyticsEventProperties = {
    category: TRANSACTION_ANALYTICS_CATEGORY,
    subCategory: TRANSACTION_ANALYTICS_SUBCATEGORY_LIST,
} as const;

interface TransactionsOverviewListProps
    extends Omit<TransactionsListProps, 'loadingBalanceAccounts'>,
        Pick<TransactionOverviewProps, 'balanceAccounts' | 'isLoadingBalanceAccount'> {
    balanceAccount?: Readonly<IBalanceAccountBase>;
    accountBalancesResult: ReturnType<typeof useAccountBalances>;
    transactionsListResult: ReturnType<typeof useTransactionsList>;
    transactionsTotalsResult: ReturnType<typeof useTransactionsTotals>;
}

const TransactionsOverviewList = ({
    accountBalancesResult,
    balanceAccount,
    balanceAccounts,
    isLoadingBalanceAccount,
    transactionsListResult,
    transactionsTotalsResult,
    ...transactionsListProps
}: TransactionsOverviewListProps) => {
    const { i18n, updateCore } = useCoreContext();
    const { isWaiting: loadingBalances, balances } = accountBalancesResult;
    const { isWaiting: loadingTotals, totals, error } = transactionsTotalsResult;
    const defaultCurrencyCode = balanceAccount?.defaultCurrencyCode;

    const defaultCurrencyFirstSortFn = useCallback(
        <T extends { currency: string }>({ currency: firstCurrency }: T, { currency: secondCurrency }: T) => {
            if (defaultCurrencyCode) {
                if (firstCurrency === defaultCurrencyCode) return -1;
                if (secondCurrency === defaultCurrencyCode) return 1;
            }
            return firstCurrency.localeCompare(secondCurrency);
        },
        [defaultCurrencyCode]
    );

    const sortedBalances = useMemo(() => [...balances].sort(defaultCurrencyFirstSortFn), [balances, defaultCurrencyFirstSortFn]);
    const sortedTotals = useMemo(() => [...totals].sort(defaultCurrencyFirstSortFn), [totals, defaultCurrencyFirstSortFn]);

    useLandedPageEvent(sharedAnalyticsEventProperties);
    useDurationEvent(sharedAnalyticsEventProperties);

    return (
        <>
            <div className={classes.summary}>
                {error ? (
                    <Alert
                        className={classes.totalsError}
                        type={AlertTypeOption.WARNING}
                        title={i18n.get('transactions.overview.totals.error')}
                        description={
                            <div>
                                <Button variant={ButtonVariant.TERTIARY} onClick={updateCore}>
                                    {i18n.get('common.actions.refresh.labels.default')}
                                </Button>
                            </div>
                        }
                    />
                ) : (
                    <div className={classes.summaryItem}>
                        <TransactionTotals totals={sortedTotals} loadingTotals={loadingTotals} />
                    </div>
                )}
                <div className={classes.summaryItem}>
                    <Balances balances={sortedBalances} loadingBalances={loadingBalances} />
                </div>
            </div>

            <TransactionsList
                accountBalancesResult={accountBalancesResult}
                balanceAccount={balanceAccount}
                loadingBalanceAccounts={isLoadingBalanceAccount || !balanceAccounts}
                transactionsListResult={transactionsListResult}
                {...transactionsListProps}
            />
        </>
    );
};

export default TransactionsOverviewList;
