// adyen-platform-experience-web-vue/src/components/TransactionDetails/PaymentRefund/PaymentRefundNotice.vue
<script setup lang="ts">
import { BentoTypography } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import { useModalContext } from '../../../core/ModalContext';
import { TX_DATA_CONTAINER, TX_DATA_HEAD_CONTAINER } from '../constants';

const { i18n } = useCoreContext();
const { withinModal } = useModalContext();
</script>

<template>
    <div :class="[TX_DATA_CONTAINER, TX_DATA_HEAD_CONTAINER]">
        <component :is="withinModal ? 'h2' : 'div'">
            <bento-typography variant="subtitle" weight="stronger">
                {{ i18n.get('transactions.details.refund.title') }}
            </bento-typography>
        </component>
        <bento-typography variant="body">
            {{ i18n.get('transactions.details.refund.processingInfo') }}
        </bento-typography>
    </div>
</template>

// packages/domains/transactions/preact/src/TransactionDetails/components/PaymentRefund/PaymentRefundNotice.tsx
import cx from 'classnames';
import { memo } from 'preact/compat';
import { useModalContext } from '../../../../../../../../src/components/internal/Modal/Modal';
import { TX_DATA_CONTAINER, TX_DATA_HEAD_CONTAINER } from '../../constants';
import { TypographyElement, TypographyVariant } from '../../../../../../../../src/components/internal/Typography/types';
import useCoreContext from '../../../../../../../../src/core/Context/useCoreContext';
import Typography from '../../../../../../../../src/components/internal/Typography/Typography';

const PaymentRefundNotice = memo(() => {
    const { i18n } = useCoreContext();
    const { withinModal } = useModalContext();
    const titleEl = withinModal ? TypographyElement.H2 : TypographyElement.DIV;

    return (
        <div className={cx(TX_DATA_CONTAINER, TX_DATA_HEAD_CONTAINER)}>
            <Typography el={titleEl} variant={TypographyVariant.SUBTITLE} stronger>
                {i18n.get('transactions.details.refund.title')}
            </Typography>
            <Typography variant={TypographyVariant.BODY}>{i18n.get('transactions.details.refund.processingInfo')}</Typography>
        </div>
    );
});

export default PaymentRefundNotice;
