// packages/shared/core/src/vue/Context/eventDispatcher/EventDispatcherProvider.vue
<script setup lang="ts">
import { provide, computed, watchEffect } from 'vue';
import { setupAnalytics } from '../../../setupAnalytics';
import type { ExternalComponentType } from '@integration-components/types';
import type { EventQueueItem } from '../../../EventDispatcher/eventDispatcher/user-events';
import { usePushAnalyticEvent } from '../../useEventDispatcher/usePushAnalyticEvent';
import { EVENT_DISPATCHER_CONTEXT_KEY } from './constants';

interface Props {
    componentName?: string;
    analyticsEnabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
    analyticsEnabled: false,
});

const pushAnalyticEvent = usePushAnalyticEvent();

const pushEvent = (data: EventQueueItem) => {
    const { name, properties } = data;
    pushAnalyticEvent({
        event: name,
        properties: properties || {},
    });
};

const analytics = computed(() =>
    setupAnalytics({
        analyticsEnabled: props.analyticsEnabled ?? false,
        componentName: props.componentName as ExternalComponentType,
    })
);

watchEffect(onCleanup => {
    const unsubscribe = analytics.value.subscribe(pushEvent);
    onCleanup(unsubscribe);
});

const userEvents = computed(() => analytics.value.userEvents);

provide(EVENT_DISPATCHER_CONTEXT_KEY, userEvents);
</script>

<template>
    <slot />
</template>

// packages/shared/core/src/preact/EventDispatcherProvider.tsx
import type { ComponentChildren } from 'preact';
import { PropsWithChildren } from 'preact/compat';
import { useCallback, useEffect, useMemo } from 'preact/hooks';
import { setupAnalytics } from '../setupAnalytics';
import type { EventQueueItem } from '../EventDispatcher/eventDispatcher/user-events';
import { usePushAnalyticEvent } from './useEventDispatcher/usePushAnalyticEvent';
import type { ExternalComponentType } from '@integration-components/types';
import { EventDispatcherContext } from './EventDispatcherContext';

export interface AnalyticsProviderProps {
    componentName?: ExternalComponentType;
    analyticsEnabled: boolean;
    children?: ComponentChildren;
}

export const AnalyticsProvider = ({ children, componentName, analyticsEnabled }: PropsWithChildren<AnalyticsProviderProps>) => {
    const pushAnalyticsEvent = usePushAnalyticEvent();

    const pushEvent = useCallback(
        (data: EventQueueItem) => {
            const { name, properties } = data;
            pushAnalyticsEvent({
                event: name,
                properties: properties || {},
            });
        },
        [pushAnalyticsEvent]
    );

    const { userEvents, subscribe } = useMemo(() => setupAnalytics({ analyticsEnabled, componentName }), [analyticsEnabled, componentName]);

    useEffect(() => subscribe(pushEvent), [subscribe, pushEvent]);

    return <EventDispatcherContext.Provider value={userEvents}>{children}</EventDispatcherContext.Provider>;
};
