// packages/domains/capital/vue/src/CapitalOverview/components/PreQualified/PreQualified.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { EnhancedCapitalState, OnFundsRequestCallback } from '@integration-components/capital/domain';
import CapitalHeader from '../../../shared/CapitalHeader/CapitalHeader.vue';
import PreQualifiedIntro from '../PreQualifiedIntro/PreQualifiedIntro.vue';
import CapitalOffer from '../../../CapitalOffer/components/CapitalOffer.vue';

const props = defineProps<{
    capitalState: EnhancedCapitalState;
    hideTitle?: boolean;
    onFundsRequest: OnFundsRequestCallback;
    onOfferDismiss?: () => void;
    onOfferOptionsRequest?: () => void;
    skipPreQualifiedIntro?: boolean;
}>();

type PreQualifiedState = 'noOffer' | 'intro' | 'offer';

const getStateFromProps = (): PreQualifiedState => (!props.capitalState.dynamicOffer ? 'noOffer' : props.skipPreQualifiedIntro ? 'offer' : 'intro');

const state = ref<PreQualifiedState>(getStateFromProps());

watch([() => props.capitalState.dynamicOffer, () => props.skipPreQualifiedIntro], () => {
    state.value = getStateFromProps();
});

const handleOfferOptionsRequest = () => {
    if (props.onOfferOptionsRequest) {
        props.onOfferOptionsRequest();
    } else {
        state.value = 'offer';
    }
};

const isOfferDismissButtonVisible = computed(() => !props.skipPreQualifiedIntro || !!props.onOfferDismiss);

const handleOfferDismiss = () => {
    if (props.onOfferDismiss) {
        props.onOfferDismiss();
    } else {
        state.value = 'intro';
    }
};
</script>

<template>
    <div v-if="state === 'noOffer' || state === 'offer'">
        <CapitalHeader v-if="state === 'noOffer'" :hide-title="props.hideTitle" title-key="capital.overview.common.titles.qualificationIntro" />
        <CapitalOffer
            :hide-title="state === 'noOffer' ? true : props.hideTitle"
            :on-funds-request="props.onFundsRequest"
            :external-capital-state="props.capitalState"
            :on-offer-dismiss="isOfferDismissButtonVisible && state === 'offer' ? handleOfferDismiss : undefined"
        />
    </div>
    <PreQualifiedIntro
        v-else-if="state === 'intro' && props.capitalState.dynamicOffer?.maxAmount"
        :hide-title="props.hideTitle"
        :max-amount="props.capitalState.dynamicOffer.maxAmount"
        :on-offer-options-request="handleOfferOptionsRequest"
        :region="props.capitalState.region"
    />
</template>

// packages/domains/capital/preact/src/CapitalOverview/components/PreQualified/PreQualified.tsx
import PreQualifiedIntro from '../PreQualifiedIntro/PreQualifiedIntro';
import { useCallback, useMemo, useState } from 'preact/hooks';
import { CapitalOffer } from '../../../CapitalOffer/components/CapitalOffer/CapitalOffer';
import { EnhancedCapitalState } from '../../../utils/capital/getCapitalState';
import { OnFundsRequestCallback } from '../../../types';
import { CapitalHeader } from '../../../internal/CapitalHeader';

type PreQualifiedProps = {
    capitalState: EnhancedCapitalState;
    hideTitle: boolean | undefined;
    onFundsRequest: OnFundsRequestCallback;
    onOfferDismiss?: () => void;
    onOfferOptionsRequest?: () => void;
    skipPreQualifiedIntro?: boolean;
};

export const PreQualified = ({
    capitalState,
    hideTitle,
    skipPreQualifiedIntro,
    onOfferOptionsRequest,
    onFundsRequest,
    onOfferDismiss,
}: PreQualifiedProps) => {
    const [state, setState] = useState<'noOffer' | 'intro' | 'offer'>(
        !capitalState.dynamicOffer ? 'noOffer' : skipPreQualifiedIntro ? 'offer' : 'intro'
    );

    const handleOfferOptionsRequest = useCallback(() => {
        if (onOfferOptionsRequest) {
            onOfferOptionsRequest();
        } else {
            setState('offer');
        }
    }, [onOfferOptionsRequest]);

    const isOfferDismissButtonVisible = useMemo(() => !skipPreQualifiedIntro || !!onOfferDismiss, [onOfferDismiss, skipPreQualifiedIntro]);
    const handleOfferDismiss = useCallback(() => {
        if (onOfferDismiss) {
            onOfferDismiss();
        } else {
            setState('intro');
        }
    }, [onOfferDismiss]);

    return (
        <>
            {state === 'noOffer' && (
                <div>
                    <CapitalHeader hideTitle={hideTitle} titleKey={'capital.overview.common.titles.qualificationIntro'} />
                    <CapitalOffer hideTitle onFundsRequest={onFundsRequest} externalCapitalState={capitalState} />
                </div>
            )}
            {state === 'intro' && capitalState.dynamicOffer?.maxAmount && (
                <PreQualifiedIntro
                    hideTitle={hideTitle}
                    maxAmount={capitalState.dynamicOffer.maxAmount}
                    onOfferOptionsRequest={handleOfferOptionsRequest}
                    region={capitalState.region}
                />
            )}
            {state === 'offer' && (
                <CapitalOffer
                    hideTitle={hideTitle}
                    onFundsRequest={onFundsRequest}
                    onOfferDismiss={isOfferDismissButtonVisible ? handleOfferDismiss : undefined}
                    externalCapitalState={capitalState}
                />
            )}
        </>
    );
};
