// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/AmountDisplay.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '../../../core/Context';

const props = defineProps<{
    amount: number;
    currency: string;
    description?: string;
    label: string;
    large?: boolean;
}>();

const { i18n } = useCoreContext();

const formattedAmount = computed(() => i18n.amount(props.amount, props.currency));

const BASE_CLASS = 'adyen-pe-amount-display';
</script>

<template>
    <div :class="BASE_CLASS">
        <div :class="`${BASE_CLASS}__label`">
            <span>{{ props.label }}</span>
            <!-- TODO: Add Tooltip with description if provided -->
        </div>

        <div :class="[`${BASE_CLASS}__amount`, { [`${BASE_CLASS}__amount--large`]: props.large }]">
            <span :class="props.large ? 'title-large' : 'subtitle-stronger'">
                {{ formattedAmount }}
            </span>
            <span :class="[`${BASE_CLASS}__currency`, props.large ? 'subtitle-stronger' : 'caption-stronger']">
                {{ props.currency }}
            </span>
        </div>
    </div>
</template>

// packages/domains/transactions/preact/src/TransactionsOverview/components/AmountDisplay/AmountDisplay.tsx
import cx from 'classnames';
import Icon from '../../../../../../../../src/components/internal/Icon';
import Typography from '../../../../../../../../src/components/internal/Typography/Typography';
import useCoreContext from '../../../../../../../../src/core/Context/useCoreContext';
import { TypographyElement, TypographyVariant } from '../../../../../../../../src/components/internal/Typography/types';
import { Tooltip } from '../../../../../../../../src/components/internal/Tooltip/Tooltip';
import { useMemo } from 'preact/hooks';
import { classes } from './constants';
import './AmountDisplay.scss';

export interface AmountDisplayProps {
    amount: number;
    currency: string;
    description?: string;
    label: string;
    large?: boolean;
}

const AmountDisplay = ({ amount, currency, description, label, large }: AmountDisplayProps) => {
    const { i18n } = useCoreContext();

    const [amountTypographyProps, currencyTypographyProps] = useMemo(() => {
        const amountTypographyProps = large
            ? ({ variant: TypographyVariant.TITLE, large: true } as const)
            : ({ variant: TypographyVariant.SUBTITLE, stronger: true } as const);

        const currencyTypographyProps = large
            ? ({ variant: TypographyVariant.SUBTITLE, stronger: true } as const)
            : ({ variant: TypographyVariant.CAPTION, stronger: true } as const);

        return [amountTypographyProps, currencyTypographyProps] as const;
    }, [large]);

    const formattedAmount = useMemo(() => i18n.amount(amount, currency), [i18n, amount, currency]);

    return (
        <div className={classes.root}>
            <div className={classes.label}>
                <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                    {label}
                </Typography>

                {description && (
                    <Tooltip content={description}>
                        <span>
                            <Icon name="info" />
                        </span>
                    </Tooltip>
                )}
            </div>

            <div className={cx(classes.amount, { [classes.amountLarge]: large })}>
                <Typography el={TypographyElement.SPAN} {...amountTypographyProps}>
                    {formattedAmount}
                </Typography>

                <Typography el={TypographyElement.SPAN} className={classes.currency} {...currencyTypographyProps}>
                    {currency}
                </Typography>
            </div>
        </div>
    );
};

export default AmountDisplay;
