// packages/domains/transactions/vue/src/TransactionsOverview/components/TransactionsList/TransactionsOverviewList.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { useLandedPageEvent, useDurationEvent } from '@integration-components/composables-vue';
import { BentoAlert, BentoButton } from '@adyen/bento-vue3';
import TransactionTotals from '../TransactionTotals/TransactionTotals.vue';
import Balances from '../Balances/Balances.vue';
import TransactionsTable from '../TransactionsTable/TransactionsTable.vue';
import { useTransactionsOverviewContext } from '../../composables/useTransactionsOverviewState';
import { TRANSACTION_ANALYTICS_CATEGORY, TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } from '@integration-components/transactions/domain';
import type { ITransaction } from '@integration-components/types';
import type { IBalanceAccountBase, TransactionsOverviewExternalProps } from '../../types';
import { BREAKPOINTS } from '@integration-components/utils';

const props = defineProps<{
    balanceAccounts?: IBalanceAccountBase[];
    isLoadingBalanceAccount: boolean;
    onContactSupport?: () => void;
    onRecordSelection?: TransactionsOverviewExternalProps['onRecordSelection'];
    showDetails?: boolean;
    dataCustomization?: TransactionsOverviewExternalProps['dataCustomization'];
    onRowClick: (transaction: ITransaction) => void;
}>();

const { i18n } = useCoreContext();
const { filters, currenciesLookupResult, accountBalancesResult, transactionsTotalsResult, transactionsListResult } = useTransactionsOverviewContext();

const { currenciesDictionary, defaultCurrencySortedCurrencies, sortedCurrencies } = currenciesLookupResult;

const sortedBalances = computed(() => defaultCurrencySortedCurrencies.value.map(c => currenciesDictionary.value[c]!.balances));
const sortedTotals = computed(() => defaultCurrencySortedCurrencies.value.map(c => currenciesDictionary.value[c]!.totals));

const loadingTotals = computed(() => transactionsTotalsResult.isWaiting.value || props.isLoadingBalanceAccount);
const loadingBalances = computed(() => accountBalancesResult.isFetching.value || props.isLoadingBalanceAccount);
const totalsError = computed(() => transactionsTotalsResult.error.value);
const balancesError = computed(() => accountBalancesResult.error.value);

const activeBalanceAccount = computed(() => props.balanceAccounts?.find(a => a.id === filters.value.balanceAccountId));

const loadingTable = computed(() => transactionsListResult.fetching.value || props.isLoadingBalanceAccount || !props.balanceAccounts);

const availableCurrencies = computed(() => sortedCurrencies.value as string[]);

const sharedAnalyticsProps = { category: TRANSACTION_ANALYTICS_CATEGORY, subCategory: TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } as const;

const summaryEl = ref<HTMLElement | null>(null);
const totalsSectionEl = ref<HTMLElement | null>(null);
const balancesSectionEl = ref<HTMLElement | null>(null);

useLandedPageEvent(sharedAnalyticsProps);
useDurationEvent(sharedAnalyticsProps);

function updateSummaryLayout() {
    const totalsHeight = totalsSectionEl.value?.clientHeight ?? 0;
    const balancesHeight = balancesSectionEl.value?.clientHeight ?? 0;
    const maxHeight = Math.max(totalsHeight, balancesHeight);
    summaryEl.value?.style.setProperty('--adyen-pe-summary-height', `${maxHeight}px`);
}

watch([totalsError, balancesError], ([newTotalsError, newBalancesError], [oldTotalsError, oldBalancesError]) => {
    const isMdUp = (summaryEl.value?.clientWidth ?? 0) >= BREAKPOINTS.md;

    // Before the DOM updates, capture the width of sections that are about to switch to an alert
    const totalsWidth = isMdUp && !oldTotalsError && newTotalsError ? balancesSectionEl.value?.offsetWidth : undefined;
    const balancesWidth = isMdUp && !oldBalancesError && newBalancesError ? totalsSectionEl.value?.offsetWidth : undefined;

    nextTick(() => {
        if (totalsWidth !== undefined) {
            totalsSectionEl.value?.style.setProperty('min-width', `${totalsWidth}px`);
        } else if (!newTotalsError) {
            totalsSectionEl.value?.style.removeProperty('min-width');
        }

        if (balancesWidth !== undefined) {
            balancesSectionEl.value?.style.setProperty('min-width', `${balancesWidth}px`);
        } else if (!newBalancesError) {
            balancesSectionEl.value?.style.removeProperty('min-width');
        }

        updateSummaryLayout();
    });
});

onMounted(() => {
    updateSummaryLayout();
});
</script>

<template>
    <div ref="summaryEl" class="adyen-pe-transactions-overview__summary">
        <div ref="totalsSectionEl" class="adyen-pe-transactions-overview__summary-section adyen-pe-transactions-overview__summary-section--totals">
            <BentoAlert v-if="totalsError" type="warning">
                <template #default>{{ i18n.get('transactions.overview.totals.error') }}</template>
                <template #actions>
                    <BentoButton variant="tertiary" :disabled="!transactionsTotalsResult.canRefresh.value" @click="transactionsTotalsResult.refresh">
                        {{ i18n.get('common.actions.refresh.labels.default') }}
                    </BentoButton>
                </template>
            </BentoAlert>
            <TransactionTotals v-else :totals="sortedTotals" :loading-totals="loadingTotals" />
        </div>
        <div
            ref="balancesSectionEl"
            class="adyen-pe-transactions-overview__summary-section adyen-pe-transactions-overview__summary-section--balances"
        >
            <BentoAlert v-if="balancesError" type="warning">
                <template #default>{{ i18n.get('transactions.overview.balances.error') }}</template>
                <template #actions>
                    <BentoButton variant="tertiary" :disabled="!accountBalancesResult.canRefresh.value" @click="accountBalancesResult.refresh">
                        {{ i18n.get('common.actions.refresh.labels.default') }}
                    </BentoButton>
                </template>
            </BentoAlert>
            <Balances v-else :balances="sortedBalances" :loading-balances="loadingBalances" />
        </div>
    </div>

    <TransactionsTable
        :active-balance-account="activeBalanceAccount"
        :available-currencies="availableCurrencies"
        :error="transactionsListResult.error.value as any"
        :has-multiple-currencies="availableCurrencies.length > 1"
        :loading="loadingTable"
        :on-contact-support="props.onContactSupport"
        :on-row-click="props.onRowClick"
        :show-details="props.showDetails"
        :transactions="transactionsListResult.records.value"
        :custom-columns="transactionsListResult.fields.value"
        :has-next="transactionsListResult.hasNext.value"
        :has-previous="transactionsListResult.hasPrevious.value"
        :go-to-next-page="transactionsListResult.goToNextPage"
        :go-to-previous-page="transactionsListResult.goToPreviousPage"
        :limit="transactionsListResult.limit.value"
        :limit-options="transactionsListResult.limitOptions.value"
        :update-limit="transactionsListResult.updateLimit"
        :current-page="transactionsListResult.page.value + 1"
    />
</template>

// packages/domains/transactions/preact/src/TransactionsOverview/components/TransactionsOverview/TransactionsOverviewList.tsx
import { useCallback, useMemo } from 'preact/hooks';
import { classes, TRANSACTION_ANALYTICS_CATEGORY, TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } from '../../constants';
import { useTransactionsOverviewContext } from '../../context/TransactionsOverviewContext';
import { useLandedPageEvent } from '@integration-components/hooks-preact/useEventDispatcher/useLandedPageEvent';
import { useDurationEvent } from '@integration-components/hooks-preact/useEventDispatcher/useDurationEvent';
import TransactionsList from '../TransactionsList/TransactionsList';
import TransactionTotals from '../TransactionTotals/TransactionTotals';
import Balances from '../Balances/Balances';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import Button from '@integration-components/ui-components-preact/Button';
import { useCoreContext } from '@integration-components/core/preact';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';
import { ButtonVariant } from '@integration-components/types';
import { TranslationKey } from '@integration-components/core';

const sharedAnalyticsEventProperties = {
    category: TRANSACTION_ANALYTICS_CATEGORY,
    subCategory: TRANSACTION_ANALYTICS_SUBCATEGORY_LIST,
} as const;

const TransactionsOverviewList = () => {
    const {
        accountBalancesResult,
        balanceAccounts,
        currenciesLookupResult,
        isLoadingBalanceAccount,
        filters,
        onContactSupport,
        onRecordSelection,
        showDetails,
        transactionsListResult,
        transactionsTotalsResult,
        dataCustomization,
    } = useTransactionsOverviewContext();

    const { i18n } = useCoreContext();
    const { error: balancesError, isWaiting: loadingBalances } = accountBalancesResult;
    const { error: totalsError, isWaiting: loadingTotals } = transactionsTotalsResult;
    const { currenciesDictionary, defaultCurrencySortedCurrencies } = currenciesLookupResult;

    const { sortedBalances, sortedTotals } = useMemo(() => {
        const sortedBalances = defaultCurrencySortedCurrencies.map(currency => currenciesDictionary[currency]!.balances);
        const sortedTotals = defaultCurrencySortedCurrencies.map(currency => currenciesDictionary[currency]!.totals);
        return { sortedBalances, sortedTotals } as const;
    }, [currenciesDictionary, defaultCurrencySortedCurrencies]);

    const renderErrorAlert = useCallback(
        <T extends { canRefresh: boolean; refresh: () => void }>({ canRefresh, refresh }: T, titleKey: TranslationKey) => (
            <Alert
                className={classes.totalsError}
                type={AlertTypeOption.WARNING}
                title={i18n.get(titleKey)}
                description={
                    <div>
                        <Button variant={ButtonVariant.TERTIARY} onClick={refresh} disabled={!canRefresh}>
                            {i18n.get('common.actions.refresh.labels.default')}
                        </Button>
                    </div>
                }
            />
        ),
        [i18n]
    );

    useLandedPageEvent(sharedAnalyticsEventProperties);
    useDurationEvent(sharedAnalyticsEventProperties);

    return (
        <>
            <div className={classes.summary}>
                <div className={classes.summaryItem}>
                    {totalsError ? (
                        renderErrorAlert(transactionsTotalsResult, 'transactions.overview.totals.error')
                    ) : (
                        <TransactionTotals totals={sortedTotals} loadingTotals={loadingTotals} />
                    )}
                </div>

                <div className={classes.summaryItem}>
                    {balancesError ? (
                        renderErrorAlert(accountBalancesResult, 'transactions.overview.balances.error')
                    ) : (
                        <Balances balances={sortedBalances} loadingBalances={loadingBalances} />
                    )}
                </div>
            </div>

            <TransactionsList
                balanceAccount={filters.balanceAccount}
                currenciesLookupResult={currenciesLookupResult}
                dataCustomization={dataCustomization}
                loadingBalanceAccounts={isLoadingBalanceAccount || !balanceAccounts}
                onContactSupport={onContactSupport}
                onRecordSelection={onRecordSelection}
                showDetails={showDetails}
                transactionsListResult={transactionsListResult}
            />
        </>
    );
};

export default TransactionsOverviewList;
