// src/components/external/CapitalOverview/components/GrantList/GrantsDisplay.tsx
import { IGrant } from '../../../../../types';
import { BaseList } from '../../../../internal/BaseList/BaseList';
import { GrantItem } from '../GrantItem/GrantItem';
import { getGrantConfig } from '../GrantItem/utils';
import { FunctionalComponent } from 'preact';
import { GrantsProps } from './types';
import { GRANT_ADJUSTMENT_DETAILS } from '../GrantAdjustmentDetails/constants';
import { GrantAdjustmentDetail, GrantAdjustmentDetailCallback } from '../GrantAdjustmentDetails/types';
import { GrantRepaymentDetails } from '../GrantRepaymentDetails/GrantRepaymentDetails';
import { sharedCapitalOverviewAnalyticsEventProperties } from '../../constants';
import SegmentedControl from '../../../../internal/SegmentedControl/SegmentedControl';
import useAnalyticsContext from '../../../../../core/Context/analytics/useAnalyticsContext';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { CapitalHeader } from '../../../../internal/CapitalHeader';
import Button from '../../../../internal/Button/Button';
import { ButtonVariant } from '../../../../internal/Button/types';

const List = ({ grants, showDetails }: { grants: IGrant[]; showDetails: GrantAdjustmentDetailCallback }) => {
    return (
        <BaseList classNames={'adyen-pe-grant-list__items'}>
            {grants.map(grant => (
                <li key={grant.id}>
                    <GrantItem grant={grant} showDetails={showDetails.bind(null, grant)} />
                </li>
            ))}
        </BaseList>
    );
};

export const GrantsDisplay: FunctionalComponent<GrantsProps> = ({ grantList, hideTitle, newOfferAvailable, onNewOfferRequest }) => {
    const [selectedGrantDetail, setSelectedGrantDetail] = useState<GrantAdjustmentDetail>();
    const [selectedGrant, setSelectedGrant] = useState<IGrant>();
    const { i18n } = useCoreContext();

    const userEvents = useAnalyticsContext();

    const [activeGrants, inactiveGrants] = useMemo(() => {
        const active: IGrant[] = [];
        const inactive: IGrant[] = [];

        grantList?.forEach(grant => {
            if (grant.status === 'Active' || grant.status === 'Pending') {
                active.push(grant);
            } else {
                inactive.push(grant);
            }
        });

        return [active, inactive];
    }, [grantList]);

    const displayMode = useMemo<'UnifiedGrants' | 'SegmentedGrants'>(() => {
        if (grantList.length > 1 && activeGrants.length && inactiveGrants.length) return 'SegmentedGrants';
        return 'UnifiedGrants';
    }, [activeGrants.length, grantList.length, inactiveGrants.length]);

    const showNewOfferButton = useMemo(() => {
        return newOfferAvailable && !activeGrants.some(grant => grant.status === 'Pending');
    }, [activeGrants, newOfferAvailable]);

    const onNewOfferRequestWithTracking = useCallback<typeof onNewOfferRequest>(() => {
        try {
            return onNewOfferRequest();
        } finally {
            userEvents.addEvent?.('Clicked button', {
                ...sharedCapitalOverviewAnalyticsEventProperties,
                subCategory: 'Grant Overview',
                label: 'See new offer',
            });
        }
    }, [onNewOfferRequest, userEvents]);

    const selectedGrantConfig = useMemo(() => selectedGrant && getGrantConfig(selectedGrant), [selectedGrant]);

    const hideGrantDetails = useCallback(() => setSelectedGrantDetail(undefined), []);

    const showGrantDetails = useCallback<GrantAdjustmentDetailCallback>((grant, detail) => {
        setSelectedGrantDetail(detail);
        setSelectedGrant(grant);
    }, []);

    const logPageEvent = useRef(true);

    useEffect(() => {
        if (logPageEvent.current) {
            // Log page event only when the component is mounted
            logPageEvent.current = false;

            const grant = activeGrants[0];

            userEvents.addEvent?.('Landed on page', {
                ...sharedCapitalOverviewAnalyticsEventProperties,
                ...(grant
                    ? {
                          grantId: grant.id,
                          grants: grant.status,
                      }
                    : {}),
                subCategory: 'Grants view',
                label: 'Capital Overview',
            });
        }
    }, [userEvents, activeGrants]);

    if (selectedGrant) {
        switch (selectedGrantDetail) {
            case GRANT_ADJUSTMENT_DETAILS.unscheduledRepayment: {
                if (selectedGrantConfig?.hasUnscheduledRepaymentDetails) {
                    return <GrantRepaymentDetails grant={selectedGrant} onDetailsClose={hideGrantDetails} />;
                }
                break;
            }

            // The grant revocation account details is currently not ready to be rendered.
            // A future iteration of this component might include revocation account details.
            // Only then should the following lines be uncommented.
            //
            // case GRANT_DETAILS_VIEWS.revocation:
            //     if (selectedGrantConfig?.hasRevocationDetails) {
            //         return <GrantRevocationDetails grant={selectedGrant} onDetailsClose={hideGrantDetailsView} />;
            //     }
            //     break;
        }
    }

    return (
        <div className="adyen-pe-grant-list">
            <div className="adyen-pe-grant-list__header-container">
                <CapitalHeader hideTitle={hideTitle} titleKey={'capital.common.title'} />
                {showNewOfferButton ? (
                    <Button onClick={onNewOfferRequestWithTracking} className={'adyen-pe-grant-list__offer-button'} variant={ButtonVariant.SECONDARY}>
                        {i18n.get('capital.overview.grants.list.actions.newOffer')}
                    </Button>
                ) : null}
            </div>

            {displayMode === 'UnifiedGrants' && <List grants={grantList} showDetails={showGrantDetails} />}
            {displayMode === 'SegmentedGrants' && (
                <SegmentedControl
                    items={[
                        {
                            label: 'capital.overview.grants.list.tabs.labels.inProgress',
                            content: <List grants={activeGrants} showDetails={showGrantDetails} />,
                            id: 'active',
                        },
                        {
                            label: 'capital.overview.grants.list.tabs.labels.closed',
                            content: <List grants={inactiveGrants} showDetails={showGrantDetails} />,
                            id: 'inactive',
                        },
                    ]}
                    activeItem={'active'}
                    aria-label={i18n.get('capital.overview.grants.list.tabs.a11y.label')}
                />
            )}
        </div>
    );
};

// packages/domains/capital/vue/src/CapitalOverview/components/GrantsDisplay/GrantsDisplay.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { BentoAlert, BentoButton, BentoList, BentoListItem, BentoSegmentedControl, type BentoSegmentedControlItem } from '@adyen/bento-vue3';
import { getGrantConfig, getGroupedGrants, getHasGrantGroups, type EnhancedCapitalState } from '@integration-components/capital/domain';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/vue';
import { GRANT_ADJUSTMENT_DETAILS, sharedCapitalOverviewAnalyticsEventProperties } from '../../../../../domain/src/CapitalOverview/constants';
import type { IGrant } from '@integration-components/types';
import CapitalHeader from '../../../shared/CapitalHeader/CapitalHeader.vue';
import GrantItem from '../GrantItem/GrantItem.vue';
import GrantRepaymentDetails from '../GrantRepaymentDetails/GrantRepaymentDetails.vue';
import './GrantsDisplay.scss';

const props = defineProps<{
    capitalState: EnhancedCapitalState;
    grants: IGrant[];
    hideTitle?: boolean;
    onNewOfferRequest: () => void;
}>();

const { i18n } = useCoreContext();
const userEvents = useEventDispatcherContext();

const analyticsProperties = {
    ...sharedCapitalOverviewAnalyticsEventProperties,
    subCategory: 'Grants overview',
} as const;

const selectedGrantGroup = ref<'active' | 'inactive'>('active');
type GrantAdjustmentDetail = 'revocation' | 'unscheduledRepayment';
const selectedGrantDetail = ref<GrantAdjustmentDetail>();
const selectedGrant = ref<IGrant>();
const grantGroups = computed(() => getGroupedGrants(props.grants));
const hasGrantGroups = computed(() => getHasGrantGroups(grantGroups.value));
const maxAmount = computed(() => props.capitalState.dynamicOffer?.maxAmount);
const selectedGrantConfig = computed(() => (selectedGrant.value ? getGrantConfig(selectedGrant.value) : undefined));
const shouldShowRepaymentDetails = computed(
    () =>
        selectedGrant.value &&
        selectedGrantDetail.value === GRANT_ADJUSTMENT_DETAILS.unscheduledRepayment &&
        selectedGrantConfig.value?.hasUnscheduledRepaymentDetails
);

const grantGroupItems = computed<BentoSegmentedControlItem[]>(() => [
    { label: i18n.get('capital.overview.grants.list.tabs.labels.inProgress'), value: 'active' },
    { label: i18n.get('capital.overview.grants.list.tabs.labels.closed'), value: 'inactive' },
]);

const displayedGrants = computed(() => {
    if (!hasGrantGroups.value) {
        return props.grants;
    }

    return selectedGrantGroup.value === 'active' ? grantGroups.value.ongoing : grantGroups.value.closed;
});

const onNewOfferRequestWithTracking = () => {
    try {
        props.onNewOfferRequest();
    } finally {
        userEvents.addEvent?.('Clicked button', { ...analyticsProperties, label: 'Request a new loan' });
    }
};

const showGrantDetails = (grant: IGrant, detail?: GrantAdjustmentDetail) => {
    selectedGrantDetail.value = detail;
    selectedGrant.value = grant;
};

const getShowGrantDetails = (grant: IGrant) => (detail?: GrantAdjustmentDetail) => {
    showGrantDetails(grant, detail);
};

const hideGrantDetails = () => {
    selectedGrantDetail.value = undefined;
};

onMounted(() => {
    userEvents.addEvent?.('Landed on page', { ...analyticsProperties, label: 'Capital overview' });
});
</script>

<template>
    <GrantRepaymentDetails v-if="shouldShowRepaymentDetails && selectedGrant" :grant="selectedGrant" :on-details-close="hideGrantDetails" />

    <div v-else class="adyen-pe-grant-list">
        <CapitalHeader :hide-title="props.hideTitle" :region="props.capitalState.region" title-key="capital.common.title" />

        <div v-if="maxAmount" class="adyen-pe-grant-list__new-grant-banner">
            <BentoAlert type="highlight">
                {{ i18n.get('capital.overview.grants.newGrant.title.part1') }}
                <strong>
                    {{
                        i18n.get('capital.overview.grants.newGrant.title.part2', {
                            values: { amount: i18n.amount(maxAmount.value, maxAmount.currency, { minimumFractionDigits: 0 }) },
                        })
                    }}
                </strong>
                <template v-if="props.capitalState.renewableGrants.length" #description>
                    {{ i18n.get('capital.overview.grants.newGrant.earlyRenewalNotice') }}
                </template>
                <template #actions>
                    <BentoButton class="adyen-pe-grant-list__offer-button" @click="onNewOfferRequestWithTracking">
                        {{ i18n.get('capital.overview.grants.newGrant.actions.newGrant') }}
                    </BentoButton>
                </template>
            </BentoAlert>
        </div>

        <BentoSegmentedControl
            v-if="hasGrantGroups"
            v-model="selectedGrantGroup"
            :aria-label="i18n.get('capital.overview.grants.list.tabs.a11y.label')"
            :items="grantGroupItems"
        />

        <BentoList class="adyen-pe-grant-list__items">
            <BentoListItem v-for="grant in displayedGrants" :key="grant.id">
                <template #content>
                    <GrantItem :grant="grant" :show-details="getShowGrantDetails(grant)" />
                </template>
            </BentoListItem>
        </BentoList>
    </div>
</template>
