// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/TransactionsOverviewList.vue
<script setup lang="ts">
import { useCoreContext } from '../../../core/Context';
import TransactionTotals from './TransactionTotals.vue';
import Balances from './Balances.vue';
import TransactionsList from './TransactionsList.vue';
import { classes } from '../constants';
import type { IBalanceAccountBase, ITransaction, ITransactionTotal, IBalance } from '../types';

const props = defineProps<{
    balanceAccount?: IBalanceAccountBase;
    balanceAccounts: IBalanceAccountBase[] | undefined;
    isLoadingBalanceAccount: boolean;
    onContactSupport?: () => void;
    onRecordSelection?: (record: { id: string }) => void;
    showDetails?: boolean;
    dataCustomization?: any;
    // Account balances
    balancesError?: Error;
    loadingBalances: boolean;
    sortedBalances: readonly Readonly<IBalance>[];
    balancesCanRefresh: boolean;
    balancesRefresh: () => void;
    // Transaction totals
    totalsError?: Error;
    loadingTotals: boolean;
    sortedTotals: readonly Readonly<ITransactionTotal>[];
    totalsCanRefresh: boolean;
    totalsRefresh: () => void;
    // Currencies
    currenciesSortedCurrencies: readonly string[];
    // Transactions list
    transactionsError?: Error;
    transactionsFetching: boolean;
    transactions: ITransaction[] | undefined;
    hasNext: boolean;
    hasPrevious: boolean;
    goToNextPage: () => void;
    goToPreviousPage: () => void;
    limit: number;
    limitOptions?: number[];
    updateLimit: (limit: number) => void;
    currentPage?: number;
}>();

const { i18n } = useCoreContext();
</script>

<template>
    <div>
        <div :class="classes.summary">
            <div :class="classes.summaryItem">
                <!-- Totals error or card -->
                <div v-if="props.totalsError" :class="classes.totalsError" class="adyen-pe-alert adyen-pe-alert--warning">
                    <p>{{ i18n.get('transactions.overview.totals.error') }}</p>
                    <button :disabled="!props.totalsCanRefresh" @click="props.totalsRefresh">
                        {{ i18n.get('common.actions.refresh.labels.default') }}
                    </button>
                </div>
                <TransactionTotals v-else :totals="props.sortedTotals" :loading-totals="props.loadingTotals" />
            </div>

            <div :class="classes.summaryItem">
                <!-- Balances error or card -->
                <div v-if="props.balancesError" :class="classes.totalsError" class="adyen-pe-alert adyen-pe-alert--warning">
                    <p>{{ i18n.get('transactions.overview.balances.error') }}</p>
                    <button :disabled="!props.balancesCanRefresh" @click="props.balancesRefresh">
                        {{ i18n.get('common.actions.refresh.labels.default') }}
                    </button>
                </div>
                <Balances v-else :balances="props.sortedBalances" :loading-balances="props.loadingBalances" />
            </div>
        </div>

        <TransactionsList
            :balance-account="props.balanceAccount"
            :currencies-sorted-currencies="props.currenciesSortedCurrencies"
            :loading-balance-accounts="props.isLoadingBalanceAccount || !props.balanceAccounts"
            :data-customization="props.dataCustomization"
            :on-contact-support="props.onContactSupport"
            :on-record-selection="props.onRecordSelection"
            :show-details="props.showDetails"
            :transactions-error="props.transactionsError"
            :transactions-fetching="props.transactionsFetching"
            :transactions="props.transactions"
            :has-next="props.hasNext"
            :has-previous="props.hasPrevious"
            :go-to-next-page="props.goToNextPage"
            :go-to-previous-page="props.goToPreviousPage"
            :limit="props.limit"
            :limit-options="props.limitOptions"
            :update-limit="props.updateLimit"
            :current-page="props.currentPage"
        />
    </div>
</template>

// src/components/external/TransactionsOverview/components/TransactionsOverview/TransactionsOverviewList.tsx
import { useCallback, useMemo } from 'preact/hooks';
import { classes, TRANSACTION_ANALYTICS_CATEGORY, TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } from '../../constants';
import { useTransactionsOverviewContext } from '../../context/TransactionsOverviewContext';
import { useLandedPageEvent } from '../../../../../hooks/useAnalytics/useLandedPageEvent';
import { useDurationEvent } from '../../../../../hooks/useAnalytics/useDurationEvent';
import TransactionsList from '../TransactionsList/TransactionsList';
import TransactionTotals from '../TransactionTotals/TransactionTotals';
import Balances from '../Balances/Balances';
import Alert from '../../../../internal/Alert/Alert';
import Button from '../../../../internal/Button';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import { AlertTypeOption } from '../../../../internal/Alert/types';
import { ButtonVariant } from '../../../../internal/Button/types';
import { TranslationKey } from '../../../../../translations';

const sharedAnalyticsEventProperties = {
    category: TRANSACTION_ANALYTICS_CATEGORY,
    subCategory: TRANSACTION_ANALYTICS_SUBCATEGORY_LIST,
} as const;

const TransactionsOverviewList = () => {
    const {
        accountBalancesResult,
        balanceAccounts,
        currenciesLookupResult,
        isLoadingBalanceAccount,
        filters,
        onContactSupport,
        onRecordSelection,
        showDetails,
        transactionsListResult,
        transactionsTotalsResult,
        dataCustomization,
    } = useTransactionsOverviewContext();

    const { i18n } = useCoreContext();
    const { error: balancesError, isWaiting: loadingBalances } = accountBalancesResult;
    const { error: totalsError, isWaiting: loadingTotals } = transactionsTotalsResult;
    const { currenciesDictionary, defaultCurrencySortedCurrencies } = currenciesLookupResult;

    const { sortedBalances, sortedTotals } = useMemo(() => {
        const sortedBalances = defaultCurrencySortedCurrencies.map(currency => currenciesDictionary[currency]!.balances);
        const sortedTotals = defaultCurrencySortedCurrencies.map(currency => currenciesDictionary[currency]!.totals);
        return { sortedBalances, sortedTotals } as const;
    }, [currenciesDictionary, defaultCurrencySortedCurrencies]);

    const renderErrorAlert = useCallback(
        <T extends { canRefresh: boolean; refresh: () => void }>({ canRefresh, refresh }: T, titleKey: TranslationKey) => (
            <Alert
                className={classes.totalsError}
                type={AlertTypeOption.WARNING}
                title={i18n.get(titleKey)}
                description={
                    <div>
                        <Button variant={ButtonVariant.TERTIARY} onClick={refresh} disabled={!canRefresh}>
                            {i18n.get('common.actions.refresh.labels.default')}
                        </Button>
                    </div>
                }
            />
        ),
        [i18n]
    );

    useLandedPageEvent(sharedAnalyticsEventProperties);
    useDurationEvent(sharedAnalyticsEventProperties);

    return (
        <>
            <div className={classes.summary}>
                <div className={classes.summaryItem}>
                    {totalsError ? (
                        renderErrorAlert(transactionsTotalsResult, 'transactions.overview.totals.error')
                    ) : (
                        <TransactionTotals totals={sortedTotals} loadingTotals={loadingTotals} />
                    )}
                </div>

                <div className={classes.summaryItem}>
                    {balancesError ? (
                        renderErrorAlert(accountBalancesResult, 'transactions.overview.balances.error')
                    ) : (
                        <Balances balances={sortedBalances} loadingBalances={loadingBalances} />
                    )}
                </div>
            </div>

            <TransactionsList
                balanceAccount={filters.balanceAccount}
                currenciesLookupResult={currenciesLookupResult}
                dataCustomization={dataCustomization}
                loadingBalanceAccounts={isLoadingBalanceAccount || !balanceAccounts}
                onContactSupport={onContactSupport}
                onRecordSelection={onRecordSelection}
                showDetails={showDetails}
                transactionsListResult={transactionsListResult}
            />
        </>
    );
};

export default TransactionsOverviewList;
