// packages/domains/reports/vue/src/ReportsOverview/components/ReportsTable.vue
<script setup lang="ts">
import { ref, computed, onUnmounted, watch } from 'vue';
import { BentoButton, BentoDataGrid, BentoTypography } from '@adyen/bento-vue3';
import { useCoreContext, useConfigContext } from '@integration-components/core/vue';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import {
    useCustomColumnsData,
    useTableColumns,
    CustomDataCell,
    useResponsiveContainer,
    containerQueries,
} from '@integration-components/composables-vue';
import { DATE_FORMAT_REPORTS } from '@integration-components/utils';
import DownloadIcon from '@adyen/ui-assets-icons-16/vue/download';
import type { BentoDatagridDataItem, BentoDataGridRowActionsProp } from '@adyen/bento-vue3';
import type { CustomColumn, IReport, OnDataRetrievedCallback, CustomDataRetrieved } from '@integration-components/types';
import type { StringWithAutocompleteOptions } from '@integration-components/utils/types';
import { AdyenPlatformExperienceError, TranslationKey } from '@integration-components/core';
import { getReportType, REPORTS_TABLE_CLASS_NAMES, REPORTS_DOWNLOAD_DISABLED_TIMEOUT, REPORTS_TABLE_FIELDS } from '../../../../domain/src';
import '../styles/ReportsTable.scss';

export type ReportsTableFields = (typeof REPORTS_TABLE_FIELDS)[number];

const props = defineProps<{
    balanceAccountId: string | undefined;
    loading: boolean;
    error?: Error;
    onContactSupport?: () => void;
    showPagination: boolean;
    data: IReport[] | undefined;
    customColumns?: CustomColumn<StringWithAutocompleteOptions<ReportsTableFields>>[];
    onDataRetrieve?: OnDataRetrievedCallback<IReport[]>;
    hasNext?: boolean;
    hasPrevious?: boolean;
    goToNextPage?: () => void;
    goToPreviousPage?: () => void;
    limit?: number;
    limitOptions?: number[];
    updateLimit?: (limit: number) => void;
    currentPage?: number;
}>();

const { i18n } = useCoreContext();
// Keep the reactive proxy here — destructuring `useConfigContext()` would unwrap
// the `refreshing` primitive into a one-time snapshot and capture a stale
// `endpoints` reference, breaking reactivity when the session is refreshed.
const config = useConfigContext();

// ── Download freeze logic ──
const frozen = ref(false);
let freezeTimeoutId: ReturnType<typeof setTimeout> | undefined;

function freeze() {
    if (frozen.value) return;
    frozen.value = true;
    freezeTimeoutId = setTimeout(() => {
        frozen.value = false;
    }, REPORTS_DOWNLOAD_DISABLED_TIMEOUT);
}

onUnmounted(() => {
    if (freezeTimeoutId) {
        clearTimeout(freezeTimeoutId);
        freezeTimeoutId = undefined;
    }
});

// ── Download error alert ──
const alert = ref<{ title: string; description: string } | null>(null);

function removeAlert() {
    alert.value = null;
}

function onDownloadErrorAlert(error?: AdyenPlatformExperienceError) {
    const errorCode = error?.errorCode;
    if (errorCode === '999_429_001') {
        alert.value = {
            title: i18n.get('reports.overview.errors.download'),
            description: i18n.get('reports.overview.errors.tooManyDownloads'),
        };
    } else {
        alert.value = {
            title: i18n.get('reports.overview.errors.download'),
            description: i18n.get('reports.overview.errors.retryDownload'),
        };
    }
}

// ── Download handler ──
async function handleDownload(item: IReport) {
    const downloadReport = config.endpoints.downloadReport;
    if (typeof downloadReport !== 'function') return;

    freeze();
    alert.value = null;

    try {
        const result = await downloadReport(
            {},
            {
                query: {
                    balanceAccountId: props.balanceAccountId ?? '',
                    createdAt: item.createdAt ?? '',
                    type: item.type ?? '',
                },
            }
        );
        if (result?.blob) {
            const url = URL.createObjectURL(result.blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = result.filename || 'report.csv';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }
    } catch (e) {
        onDownloadErrorAlert(e as AdyenPlatformExperienceError);
    }
}

// ── Responsive ──
const isMobile = useResponsiveContainer(containerQueries.down.sm);

// ── Custom columns ──
const {
    columns: desktopColumns,
    customFieldKeys,
    hasCustomColumn,
} = useTableColumns({
    fields: REPORTS_TABLE_FIELDS,
    customColumns: () => props.customColumns,
    fieldsKeys: {
        createdAt: 'reports.overview.list.fields.createdAt',
        reportType: 'reports.overview.list.fields.reportType',
    },
    resolveCustomColumnLabel: key => {
        const labelKey = `reports.overview.list.fields.${key}` as any;
        return i18n.has(labelKey) ? i18n.get(labelKey) : i18n.get(key as TranslationKey);
    },
});

const { customRecords, loadingCustomRecords } = useCustomColumnsData<IReport>({
    records: () => props.data ?? [],
    hasCustomColumn: () => hasCustomColumn.value,
    onDataRetrieve: () => props.onDataRetrieve,
    mergeCustomData: ({ records, retrievedData }) =>
        records.map(record => {
            const match = (retrievedData as CustomDataRetrieved[]).find(m => m.createdAt === record.createdAt);
            // Custom data layers on top of the original record so consumer-supplied
            // custom fields (the whole point of `onDataRetrieve`) are not silently
            // overwritten by the original record.
            return match ? ({ ...record, ...match } as IReport & Record<string, any>) : record;
        }),
});

// ── Grid columns ──
const columns = computed(() => {
    if (isMobile.value) {
        return [{ field: 'dateAndReportType', label: i18n.get('reports.overview.list.fields.reportType'), autoWidth: true }];
    }
    return desktopColumns.value;
});

const isLoading = computed(() => props.loading || config.refreshing || loadingCustomRecords.value);

// ── Grid data ──
const gridData = computed<BentoDatagridDataItem[]>(() => {
    const source = customRecords.value as Array<IReport & Record<string, any>>;
    if (!source.length) return [];
    const keys = customFieldKeys.value;
    return source.map((report, idx) => {
        const row: BentoDatagridDataItem = {
            id: `${report.createdAt}-${idx}`,
            createdAt: report.createdAt ?? '',
            reportType: getReportType(i18n, report.type) ?? report.type,
            _raw: report,
        };
        for (const key of keys) {
            row[key] = report[key];
        }
        return row;
    });
});

// ── Row actions ──
const getRowActions: BentoDataGridRowActionsProp = (item: BentoDatagridDataItem) => [
    {
        title: i18n.get('reports.overview.list.controls.downloadReport.label'),
        event: () => handleDownload(item._raw as IReport),
        tooltipText: i18n.get('reports.overview.list.controls.downloadReport.label'),
        disabled: frozen.value,
        iconLeft: DownloadIcon,
    },
];

const paginationProps = computed(() => {
    if (!props.showPagination) return undefined;
    return {
        page: props.currentPage ?? 1,
        size: props.limit ?? 10,
        hasNext: props.hasNext ?? false,
        hasPrevious: props.hasPrevious ?? false,
        hidePageSize: !props.limitOptions || props.limitOptions.length <= 1,
    };
});

const emptyStateProps = computed(() => ({
    title: i18n.get('reports.overview.errors.listEmpty'),
    description: i18n.get('common.errors.updateFilters'),
}));

function handleNavigate(page: number) {
    if (page > (props.currentPage ?? 1)) {
        props.goToNextPage?.();
    } else {
        props.goToPreviousPage?.();
    }
}

function handleItemsPage(size: number) {
    props.updateLimit?.(size);
}

const { dateFormat } = useTimezoneAwareDateFormatting('UTC');

function formatDate(dateStr: string): string {
    return dateFormat(dateStr, DATE_FORMAT_REPORTS);
}

// Clear alert whenever a new fetch begins. This must be a watcher; a top-level
// `if (props.loading) ...` would only run once during component setup.
watch(
    () => props.loading,
    loading => {
        if (loading) alert.value = null;
    },
    { immediate: true }
);
</script>

<template>
    <div :class="REPORTS_TABLE_CLASS_NAMES.base">
        <!-- Download error alert -->
        <div v-if="alert" class="adyen-pe-reports-table-alert" role="alert">
            <div>
                <strong>{{ alert.title }}</strong>
                <p>{{ alert.description }}</p>
            </div>
            <BentoButton variant="tertiary" size="small" @click="removeAlert">&times;</BentoButton>
        </div>

        <!-- Error state -->
        <div v-if="props.error" class="adyen-pe-data-overview-error">
            <p>{{ i18n.get('reports.overview.errors.listUnavailable') }}</p>
            <BentoButton v-if="props.onContactSupport" variant="tertiary" @click="props.onContactSupport">
                {{ i18n.get('common.actions.contactSupport.labels.default') }}
            </BentoButton>
        </div>

        <BentoDataGrid
            v-else
            outline
            :columns="columns"
            :data="gridData"
            :loading="isLoading"
            :pagination="paginationProps"
            :empty-state="emptyStateProps"
            :row-actions="getRowActions"
            :has-resizable-columns="false"
            :allow-column-drag-and-drop="false"
            @navigate="handleNavigate"
            @items-page="handleItemsPage"
        >
            <template #item-createdAt="{ item }">
                <time v-if="item.createdAt" :datetime="item.createdAt">
                    <BentoTypography variant="body">{{ formatDate(item.createdAt) }}</BentoTypography>
                </time>
            </template>
            <template #item-reportType="{ item }">
                {{ item.reportType }}
            </template>
            <template #item-dateAndReportType="{ item }">
                <div :class="REPORTS_TABLE_CLASS_NAMES.dateReportType">
                    <BentoTypography v-if="item.reportType" variant="body" stronger>{{ item.reportType }}</BentoTypography>
                    <time v-if="item.createdAt" :datetime="item.createdAt">
                        <BentoTypography variant="body" :class="REPORTS_TABLE_CLASS_NAMES.dateReportTypeDate">{{
                            formatDate(item.createdAt)
                        }}</BentoTypography>
                    </time>
                </div>
            </template>
            <template v-for="key in customFieldKeys" #[`item-${key}`]="{ item }" :key="key">
                <CustomDataCell :value="item[key]" />
            </template>
        </BentoDataGrid>
    </div>
</template>

// packages/domains/reports/preact/src/ReportsOverview/components/ReportsTable/ReportsTable.tsx
import { FC } from 'preact/compat';
import { useCallback, useMemo, useState } from 'preact/hooks';
import { AdyenPlatformExperienceError, TranslationKey } from '@integration-components/core';
import type { CustomColumn, IReport } from '@integration-components/types';
import { DATE_FORMAT_REPORTS } from '@integration-components/utils';
import type { StringWithAutocompleteOptions } from '@integration-components/utils/types';
import { getReportType, REPORTS_DOWNLOAD_DISABLED_TIMEOUT, REPORTS_TABLE_CLASS_NAMES } from '@integration-components/reports/domain';
import {
    containerQueries,
    useFreezePeriod,
    useResponsiveContainer,
    useTableColumns,
    useTimezoneAwareDateFormatting,
} from '@integration-components/hooks-preact';
import { useConfigContext, useCoreContext } from '@integration-components/core/preact';
import Alert from '../../../../../../../../src/components/internal/Alert/Alert';
import Icon from '../../../../../../../../src/components/internal/Icon';
import { AlertTypeOption } from '../../../../../../../../src/components/internal/Alert/types';
import DownloadButton from '../../../../../../../../src/components/internal/Button/DownloadButton/DownloadButton';
import DataGrid from '../../../../../../../../src/components/internal/DataGrid';
import DataOverviewError from '../../../../../../../../src/components/internal/DataOverviewError/DataOverviewError';
import Pagination from '../../../../../../../../src/components/internal/Pagination';
import { PaginationProps, WithPaginationLimitSelection } from '../../../../../../../../src/components/internal/Pagination/types';
import { TypographyElement, TypographyVariant } from '../../../../../../../../src/components/internal/Typography/types';
import Typography from '../../../../../../../../src/components/internal/Typography/Typography';
import './ReportsTable.scss';

export const FIELDS = ['createdAt', 'dateAndReportType', 'reportType', 'reportFile'] as const;
export type ReportsTableFields = (typeof FIELDS)[number];

const FIELDS_KEYS = {
    createdAt: 'reports.overview.list.fields.createdAt',
    reportFile: 'reports.overview.list.fields.reportFile',
    reportType: 'reports.overview.list.fields.reportType',
} as const satisfies Partial<Record<ReportsTableFields, TranslationKey>>;

export interface ReportsTableProps extends WithPaginationLimitSelection<PaginationProps> {
    balanceAccountId: string | undefined;
    loading: boolean;
    error?: AdyenPlatformExperienceError;
    onContactSupport?: () => void;
    showPagination: boolean;
    data: IReport[] | undefined;
    customColumns?: CustomColumn<StringWithAutocompleteOptions<ReportsTableFields>>[];
}

export const ReportsTable: FC<ReportsTableProps> = ({
    error,
    loading,
    balanceAccountId,
    onContactSupport,
    showPagination,
    data,
    customColumns,
    ...paginationProps
}) => {
    const { i18n } = useCoreContext();
    const { dateFormat } = useTimezoneAwareDateFormatting('UTC');
    const { freeze, frozen } = useFreezePeriod(REPORTS_DOWNLOAD_DISABLED_TIMEOUT);
    const [alert, setAlert] = useState<null | { title: string; description: string }>(null);
    const { refreshing } = useConfigContext();
    const isLoading = useMemo(() => loading || refreshing, [loading, refreshing]);
    const isSmAndUpContainer = useResponsiveContainer(containerQueries.up.sm);
    const isXsAndDownContainer = useResponsiveContainer(containerQueries.down.xs);

    const columns = useTableColumns({
        customColumns,
        fields: FIELDS,
        fieldsKeys: FIELDS_KEYS,
        columnConfig: useMemo(
            () => ({
                dateAndReportType: { visible: isXsAndDownContainer },
                createdAt: { visible: isSmAndUpContainer },
                reportType: { visible: isSmAndUpContainer },
                reportFile: { visible: true, position: isXsAndDownContainer ? 'right' : undefined },
            }),
            [isSmAndUpContainer, isXsAndDownContainer]
        ),
    });

    const removeAlert = useCallback(() => {
        setAlert(null);
    }, []);

    const EMPTY_TABLE_MESSAGE = {
        title: 'reports.overview.errors.listEmpty',
        message: ['common.errors.updateFilters'],
    } satisfies { title: TranslationKey; message: TranslationKey | TranslationKey[] };

    const errorDisplay = useMemo(
        () => () => <DataOverviewError error={error} errorMessage={'reports.overview.errors.listUnavailable'} onContactSupport={onContactSupport} />,
        [error, onContactSupport]
    );

    const errorIcon = useMemo(() => <Icon name="warning" />, []);

    const onDownloadErrorAlert = useMemo(
        () => (error?: AdyenPlatformExperienceError) => {
            const alertDetails: Partial<{ key: number; description: string; title: string }> = {};
            switch (error?.errorCode) {
                case '999_429_001':
                    alertDetails.title = i18n.get('reports.overview.errors.download');
                    alertDetails.description = i18n.get('reports.overview.errors.tooManyDownloads');
                    break;
                case '00_500':
                default:
                    alertDetails.title = i18n.get('reports.overview.errors.download');
                    alertDetails.description = i18n.get('reports.overview.errors.retryDownload');
                    break;
            }
            setAlert(alertDetails as { title: string; description: string });
        },
        [i18n]
    );

    if (loading) setAlert(null);

    return (
        <div className={REPORTS_TABLE_CLASS_NAMES.base}>
            {alert && <Alert onClose={removeAlert} type={AlertTypeOption.WARNING} className={REPORTS_TABLE_CLASS_NAMES.alert} {...alert} />}
            <DataGrid
                errorDisplay={errorDisplay}
                error={error}
                columns={columns}
                data={data}
                loading={isLoading}
                outline={false}
                emptyTableMessage={EMPTY_TABLE_MESSAGE}
                customCells={{
                    createdAt: ({ value }) => {
                        if (!value) return null;
                        return (
                            value && (
                                <time dateTime={value}>
                                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                                        {dateFormat(value, DATE_FORMAT_REPORTS)}
                                    </Typography>
                                </time>
                            )
                        );
                    },
                    dateAndReportType: ({ item }) => {
                        return (
                            <div className={REPORTS_TABLE_CLASS_NAMES.dateReportType}>
                                {item?.type && (
                                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                                        {getReportType(i18n, item.type)}
                                    </Typography>
                                )}
                                <time dateTime={item.createdAt}>
                                    <Typography
                                        className={REPORTS_TABLE_CLASS_NAMES.dateReportTypeDate}
                                        el={TypographyElement.SPAN}
                                        variant={TypographyVariant.BODY}
                                    >
                                        {dateFormat(item.createdAt, DATE_FORMAT_REPORTS)}
                                    </Typography>
                                </time>
                            </div>
                        );
                    },
                    reportType: ({ item }) => {
                        return (
                            item?.type && (
                                <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                                    {getReportType(i18n, item.type)}
                                </Typography>
                            )
                        );
                    },
                    reportFile: ({ item }) => {
                        const queryParam = {
                            query: { balanceAccountId: balanceAccountId, createdAt: item.createdAt, type: item.type },
                        };
                        return (
                            <DownloadButton
                                className={REPORTS_TABLE_CLASS_NAMES.download}
                                endpointName={'downloadReport'}
                                disabled={frozen}
                                requestParams={queryParam}
                                onDownloadRequested={freeze}
                                setError={onDownloadErrorAlert}
                                errorDisplay={errorIcon}
                                aria-label={i18n.get('reports.overview.list.controls.downloadReport.label')}
                            />
                        );
                    },
                }}
            >
                {showPagination && (
                    <DataGrid.Footer>
                        <Pagination
                            {...paginationProps}
                            ariaLabelKey="reports.overview.pagination.label"
                            limitSelectAriaLabelKey="reports.overview.pagination.controls.limitSelect.label"
                        />
                    </DataGrid.Footer>
                )}
            </DataGrid>
        </div>
    );
};
