// packages/domains/payByLink/vue/src/PaymentLinkDetails/components/PaymentLinkExpiration/PaymentLinkExpiration.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { BentoAlert, BentoButtonActions, BentoTypography, type BentoButtonActionsList } from '@adyen/bento-vue3';
import { useConfigContext, useCoreContext, useModalContext } from '@integration-components/core/vue';
import { isFunction } from '@integration-components/utils';
import type { IPaymentLinkDetails } from '@integration-components/types';
import styles from './PaymentLinkExpiration.module.scss';

const props = defineProps<{
    paymentLink: IPaymentLinkDetails;
    onCancel: () => void;
    onExpirationSuccess: () => void;
}>();

const { i18n } = useCoreContext();
const { withinModal } = useModalContext();
const config = useConfigContext();

const isLoading = ref(false);
const hasError = ref(false);

async function handleConfirmExpire() {
    const fn = config.endpoints.expirePayByLinkPaymentLink;
    if (!isFunction(fn) || isLoading.value) return;

    isLoading.value = true;
    hasError.value = false;
    try {
        await fn({}, { path: { paymentLinkId: props.paymentLink.linkInformation.paymentLinkId } });
        props.onExpirationSuccess();
    } catch {
        hasError.value = true;
    } finally {
        isLoading.value = false;
    }
}

const actionButtons = computed<BentoButtonActionsList>(() => [
    {
        title: i18n.get('payByLink.details.expiration.actions.confirmExpiration'),
        event: handleConfirmExpire,
        variant: 'primary',
        disabled: isLoading.value,
        state: isLoading.value ? 'loading' : undefined,
    },
    {
        title: i18n.get('payByLink.details.expiration.actions.goBack'),
        event: () => props.onCancel(),
        variant: 'secondary',
        disabled: isLoading.value,
    },
]);
</script>

<template>
    <div :class="styles.root">
        <BentoTypography v-if="!withinModal" el="h2" variant="subtitle" stronger>
            {{ i18n.get('payByLink.details.expiration.title') }}
        </BentoTypography>

        <BentoTypography variant="body">
            {{ i18n.get('payByLink.details.expiration.description') }}
        </BentoTypography>

        <BentoAlert v-if="hasError" type="critical" role="alert">
            {{ i18n.get('payByLink.details.expiration.errorTitle') }}
            <template #description>
                {{ i18n.get('payByLink.details.expiration.errorDescription') }}
            </template>
        </BentoAlert>

        <BentoButtonActions :actions="actionButtons" />
    </div>
</template>

// src/components/external/PaymentLinkDetails/components/PaymentLinkExpiration/PaymentLinkExpiration.tsx
import { useCallback, useMemo } from 'preact/hooks';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { IPaymentLinkDetails } from '../../../../../types';
import ButtonActions from '@integration-components/ui-components-preact/Button/ButtonActions/ButtonActions';
import useMutation from '../../../../../hooks/useMutation/useMutation';
import { useConfigContext } from '../../../../../core/ConfigContext';
import { EMPTY_OBJECT } from '../../../../../utils';
import { useModalContext } from '@integration-components/ui-components-preact/Modal/Modal';
import { ButtonActionsList, ButtonVariant } from '@integration-components/types';
import './PaymentLinkExpiration.scss';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';

const CLASSNAMES = {
    root: 'adyen-pe-payment-link-expiration',
    title: 'adyen-pe-payment-link-expiration__title',
};

type PaymentLinkExpirationProps = {
    paymentLink: IPaymentLinkDetails;
    onCancel: () => void;
    onExpirationSuccess: () => void;
};

export const PaymentLinkExpiration = ({ paymentLink, onCancel, onExpirationSuccess }: PaymentLinkExpirationProps) => {
    const { i18n } = useCoreContext();
    const { withinModal } = useModalContext();
    const titleEl = withinModal ? TypographyElement.H2 : TypographyElement.DIV;

    const { expirePayByLinkPaymentLink } = useConfigContext().endpoints;
    const expirePaymentLinkMutation = useMutation({
        queryFn: expirePayByLinkPaymentLink,
        options: {
            onSuccess: onExpirationSuccess,
        },
    });

    const handleConfirmExpire = useCallback(
        () => expirePaymentLinkMutation.mutate(EMPTY_OBJECT, { path: { paymentLinkId: paymentLink.linkInformation.paymentLinkId } }),
        [expirePaymentLinkMutation, paymentLink.linkInformation.paymentLinkId]
    );

    const actionButtons: ButtonActionsList = useMemo(
        () => [
            {
                title: i18n.get('payByLink.details.expiration.actions.confirmExpiration'),
                event: handleConfirmExpire,
                variant: ButtonVariant.PRIMARY,
                disabled: expirePaymentLinkMutation.isLoading,
                state: expirePaymentLinkMutation.isLoading ? 'loading' : 'default',
            },
            {
                title: i18n.get('payByLink.details.expiration.actions.goBack'),
                event: onCancel,
                variant: ButtonVariant.SECONDARY,
                disabled: expirePaymentLinkMutation.isLoading,
            },
        ],
        [expirePaymentLinkMutation.isLoading, handleConfirmExpire, i18n, onCancel]
    );

    return (
        <div className={CLASSNAMES.root}>
            <Typography el={titleEl} variant={TypographyVariant.SUBTITLE} stronger>
                {i18n.get('payByLink.details.expiration.title')}
            </Typography>
            <Typography variant={TypographyVariant.BODY}>{i18n.get('payByLink.details.expiration.description')}</Typography>
            {expirePaymentLinkMutation.error && (
                <Alert
                    type={AlertTypeOption.CRITICAL}
                    title={i18n.get('payByLink.details.expiration.errorTitle')}
                    description={i18n.get('payByLink.details.expiration.errorDescription')}
                />
            )}
            <ButtonActions actions={actionButtons} />
        </div>
    );
};
