// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/PaymentLinkThemeContainer.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { TranslationKey } from '@integration-components/core';
import { usePaymentLinkSettingsContext } from '../composables/context';
import { isThemeData } from '../utils/typeGuards';
import LoadingSkeleton from './LoadingSkeleton.vue';
import SettingsError from './SettingsError.vue';
import ThemeForm from './ThemeForm.vue';
import type { ThemeFormData } from '../types';

const ERROR_MESSAGE_KEY: TranslationKey = 'payByLink.settings.theme.errors.couldNotLoad';

const { savedData: theme, themeError, isLoadingContent } = usePaymentLinkSettingsContext();

const data = computed<ThemeFormData>(() => {
    if (!isLoadingContent.value && !themeError.value && theme.value && typeof theme.value === 'object' && Object.keys(theme.value).length > 0) {
        return theme.value as ThemeFormData;
    }
    return { brandName: '' };
});
</script>

<template>
    <section v-if="themeError" class="adyen-pe-payment-link-theme">
        <SettingsError :error="themeError" :error-message="ERROR_MESSAGE_KEY" />
    </section>
    <LoadingSkeleton v-else-if="!theme || !isThemeData(data)" :row-number="3" />
    <section v-else class="adyen-pe-payment-link-theme">
        <ThemeForm :theme="data" />
    </section>
</template>

// src/components/external/PaymentLinkSettings/components/PaymentLinkThemeContainer/PaymentLinkThemeContainer.tsx
import './PaymentLinkThemeContainer.scss';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import usePaymentLinkSettingsContext from '../PaymentLinkSettingsContainer/context/context';
import { useEffect, useMemo, useState } from 'preact/hooks';
import { ThemeForm } from './components/ThemeForm';
import { isThemeData, isThemePayload } from './types';
import LoadingSkeleton from '../PaymentLinkSettingsContainer/components/LoadingSkeleton/LoadingSkeleton';
import SettingsError from '../PaymentLinkSettingsContainer/components/SettingsError/SettingsError';
import { ThemeFormData } from '../PaymentLinkSettingsContainer/context/types';

const ERROR_MESSAGE_KEY = 'payByLink.settings.theme.errors.couldNotLoad';

const PaymentLinkThemeContainer = () => {
    const { i18n } = useCoreContext();
    const { payload, setSavedData, savedData: theme, themeError, isLoadingContent } = usePaymentLinkSettingsContext();
    const [initialPayload, setInitialPayload] = useState<FormData>();

    useEffect(() => {
        if (isThemePayload(payload)) {
            setInitialPayload(payload);
        }
    }, [payload, setSavedData, setInitialPayload]);

    const data = useMemo(() => {
        if (!isLoadingContent && !themeError) {
            return theme && typeof theme === 'object' && Object.keys(theme).length > 0 ? (theme as ThemeFormData) : { brandName: '' };
        }
        return { brandName: '' };
    }, [theme, isLoadingContent, themeError]);

    if (themeError) {
        return (
            <section className="adyen-pe-payment-link-theme">
                <SettingsError error={themeError} errorMessage={ERROR_MESSAGE_KEY} />
            </section>
        );
    }

    if (!theme || !isThemeData(data) || !initialPayload) {
        return <LoadingSkeleton rowNumber={3} />;
    }

    return (
        <section className="adyen-pe-payment-link-theme">
            <div className="adyen-pe-payment-link-settings__content-header">
                <Typography variant={TypographyVariant.TITLE} medium>
                    {i18n.get('payByLink.settings.theme.title')}
                </Typography>
                <Typography variant={TypographyVariant.BODY} wide className="adyen-pe-payment-link-settings-terms-and-conditions-disclaimer">
                    {i18n.get('payByLink.settings.theme.subtitle')}
                </Typography>
            </div>
            <ThemeForm theme={data} initialPayload={initialPayload} />
        </section>
    );
};

export default PaymentLinkThemeContainer;
