// packages/domains/capital/preact/src/CapitalOffer/components/RenewalHighlightedFields.tsx
import { useCoreContext } from '@integration-components/core/preact';
import { useMemo } from 'preact/hooks';
import { CapitalHighlightedFields } from './CapitalHighlightedFields/CapitalHighlightedFields';
import { IAmount } from '@integration-components/types';
import { getRenewalAmountBreakdown } from '@integration-components/capital/domain';

type RenewalHighlightedFieldsProps = {
    newGrantAmount: IAmount;
    remainingGrantAmount: IAmount;
};

export const RenewalHighlightedFields = ({ newGrantAmount, remainingGrantAmount }: RenewalHighlightedFieldsProps) => {
    const { i18n } = useCoreContext();

    const highlightedFields = useMemo(() => {
        const breakdown = getRenewalAmountBreakdown(newGrantAmount.value, remainingGrantAmount);
        const amountConfig = { minimumFractionDigits: 0 };

        return [
            {
                label: i18n.get('capital.offer.selection.earlyRenewal.newGrantAmount'),
                value: i18n.amount(breakdown.newGrantAmountValue, breakdown.currency, amountConfig),
            },
            {
                value: '-',
            },
            {
                label: i18n.get('capital.offer.selection.earlyRenewal.currentGrantAmount'),
                value: i18n.amount(breakdown.remainingGrantAmountValue, breakdown.currency, amountConfig),
            },
            {
                value: '=',
            },
            {
                label: i18n.get('capital.offer.selection.earlyRenewal.amountToReceive'),
                value: i18n.amount(breakdown.amountToReceive, breakdown.currency, amountConfig),
            },
        ];
    }, [i18n, newGrantAmount, remainingGrantAmount]);

    return <CapitalHighlightedFields fields={highlightedFields} />;
};

// packages/domains/capital/vue/src/CapitalOffer/components/RenewalHighlightedFields/RenewalHighlightedFields.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoTypography } from '@adyen/bento-vue3';
import { getRenewalAmountBreakdown } from '@integration-components/capital/domain';
import { useCoreContext } from '@integration-components/core/vue';
import type { IAmount } from '@integration-components/types';
import styles from './RenewalHighlightedFields.module.scss';

const props = defineProps<{
    newGrantAmountValue: number;
    remainingGrantAmount: IAmount;
}>();

const { i18n } = useCoreContext();

const fields = computed(() => {
    const breakdown = getRenewalAmountBreakdown(props.newGrantAmountValue, props.remainingGrantAmount);
    const formatAmount = (value: number) => i18n.amount(value, breakdown.currency, { minimumFractionDigits: 0 });

    return [
        {
            label: i18n.get('capital.offer.selection.earlyRenewal.newGrantAmount'),
            value: formatAmount(breakdown.newGrantAmountValue),
        },
        { value: '-' },
        {
            label: i18n.get('capital.offer.selection.earlyRenewal.currentGrantAmount'),
            value: formatAmount(breakdown.remainingGrantAmountValue),
        },
        { value: '=' },
        {
            label: i18n.get('capital.offer.selection.earlyRenewal.amountToReceive'),
            value: formatAmount(breakdown.amountToReceive),
        },
    ];
});
</script>

<template>
    <div :class="styles.root">
        <div v-for="field in fields" :key="field.label ?? field.value" :class="styles.item">
            <BentoTypography v-if="field.label" variant="caption" :class="styles.label">
                {{ field.label }}
            </BentoTypography>
            <BentoTypography variant="body" strongest>
                {{ field.value }}
            </BentoTypography>
        </div>
    </div>
</template>
