// src/components/external/TransactionsOverview/components/TransactionsOverview/TransactionsOverviewShell.tsx
import cx from 'classnames';
import { useMemo } from 'preact/hooks';
import { classes } from '../../constants';
import { PropsWithChildren } from 'preact/compat';
import { Header } from '../../../../internal/Header';
import { FilterBarMobileSwitch } from '../../../../internal/FilterBar';
import { useTransactionsOverviewContext } from '../../context/TransactionsOverviewContext';
import SegmentedControl from '../../../../internal/SegmentedControl/SegmentedControl';
import TransactionsFilters from '../TransactionFilters/TransactionFilters';
import TransactionsExport from '../TransactionsExport/TransactionsExport';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import './TransactionsOverview.scss';

const TransactionsOverviewShell = ({ children }: PropsWithChildren<{}>) => {
    const { filterBarState, hideTitle, isTransactionsView, transactionsListResult, transactionsViewState } = useTransactionsOverviewContext();
    const { activeView, onViewChange, viewTabs } = transactionsViewState;
    const { isMobileContainer } = filterBarState;
    const { i18n } = useCoreContext();

    const exportButton = useMemo(
        () => (isTransactionsView ? <TransactionsExport disabled={!transactionsListResult.page} /> : null),
        [isTransactionsView, transactionsListResult.page]
    );

    const viewSwitcher = useMemo(
        () =>
            viewTabs.length > 1 ? (
                <SegmentedControl
                    aria-label={i18n.get('transactions.overview.viewSelect.a11y.label')}
                    activeItem={activeView}
                    items={viewTabs}
                    onChange={onViewChange}
                />
            ) : null,
        [activeView, onViewChange, viewTabs, i18n]
    );

    return (
        <div className={cx(classes.root, { [classes.rootSmall]: isMobileContainer })}>
            <Header hideTitle={hideTitle} titleKey="transactions.overview.title">
                <div className={cx({ [classes.filterBarSmall]: isMobileContainer })}>
                    {isMobileContainer && exportButton}
                    <FilterBarMobileSwitch {...filterBarState} />
                    {!isMobileContainer && <>{viewSwitcher}</>}
                </div>
            </Header>

            {isMobileContainer && <>{viewSwitcher}</>}

            <div role="toolbar" className={classes.toolbar}>
                <TransactionsFilters />
                {!isMobileContainer && <>{exportButton}</>}
            </div>

            {children}
        </div>
    );
};

export default TransactionsOverviewShell;

// packages/domains/transactions/vue/src/TransactionsOverview/components/TransactionsOverview/TransactionsOverviewShell.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoTypography, BentoSegmentedControl, BentoCard } from '@adyen/bento-vue3';
import type { BentoSegmentedControlItem } from '@adyen/bento-vue3';
import { useTransactionsOverviewContext } from '../../composables/useTransactionsOverviewState';
import { BASE_CLASS } from '../../constants';
import type { IBalanceAccountBase } from '../../types';
import './TransactionsOverview.scss';

defineProps<{
    hideTitle?: boolean;
    balanceAccounts?: IBalanceAccountBase[];
}>();

const { i18n } = useCoreContext();
const { transactionsViewState } = useTransactionsOverviewContext();
const { activeView, onViewChange, viewTabs } = transactionsViewState;

const bentoViewTabs = computed<BentoSegmentedControlItem[]>(() => viewTabs.value.map(tab => ({ value: tab.id, label: i18n.get(tab.label) })));
</script>

<template>
    <div :class="BASE_CLASS">
        <div class="adyen-pe-transactions-overview-header">
            <BentoTypography v-if="!hideTitle" variant="title">{{ i18n.get('transactions.overview.title') }}</BentoTypography>
            <!-- Empty div for space between -->
            <div v-else />
            <BentoSegmentedControl
                v-if="viewTabs.length > 1"
                :aria-label="i18n.get('transactions.overview.viewSelect.a11y.label')"
                :items="bentoViewTabs"
                :model-value="activeView"
                @update:model-value="onViewChange"
            />
        </div>
        <BentoCard>
            <template #content>
                <slot />
            </template>
        </BentoCard>
    </div>
</template>
