// packages/domains/disputes/vue/src/DisputeManagement/components/AcceptDisputeFlow.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { BentoAlert, BentoButton, BentoButtonActions, BentoCheckbox, BentoTypography } from '@adyen/bento-vue3';
import SuccessIcon from '@adyen/ui-assets-icons-16/vue/checkmark-circle-fill';
import { useConfigContext, useCoreContext } from '@integration-components/core/vue';
import { isFunction } from '@integration-components/utils';
import { useDisputeFlow } from '../composables/useDisputeFlow';
import type { DisputeManagementProps } from '../types';

const props = defineProps<{
    onDisputeAccept?: DisputeManagementProps['onDisputeAccept'];
}>();

const { i18n } = useCoreContext();
const { acceptDispute } = useConfigContext().endpoints;
const { dispute, clearStates, goBack } = useDisputeFlow();
const cachedDispute = dispute.value;
const disputePspReference = cachedDispute?.dispute.pspReference;
const isRequestForInformation = cachedDispute?.dispute.type === 'REQUEST_FOR_INFORMATION';

const termsAgreed = ref(false);
const disputeAccepted = ref(false);
const isLoading = ref(false);
const callbackCalled = ref(false);

const acceptedLabel = computed(() =>
    isRequestForInformation
        ? i18n.get('disputes.management.accept.requestForInformation.accepted')
        : i18n.get('disputes.management.accept.chargeback.accepted')
);
const acceptDisclaimer = computed(() =>
    isRequestForInformation
        ? i18n.get('disputes.management.accept.requestForInformation.disclaimer')
        : i18n.get('disputes.management.accept.chargeback.disclaimer')
);
const acceptTitle = computed(() =>
    isRequestForInformation
        ? i18n.get('disputes.management.accept.requestForInformation.title')
        : i18n.get('disputes.management.accept.chargeback.title')
);
const acceptButtonTitle = computed(() =>
    isRequestForInformation
        ? i18n.get('disputes.management.accept.requestForInformation.actions.accept')
        : i18n.get('disputes.management.accept.chargeback.actions.accept')
);
const interactionsDisabled = computed(() => isLoading.value || disputeAccepted.value);
const canAcceptDispute = computed(() => termsAgreed.value && !interactionsDisabled.value && isFunction(acceptDispute) && !!disputePspReference);
const actionButtons = computed(() => [
    {
        title: acceptButtonTitle.value,
        disabled: !canAcceptDispute.value,
        event: () => void acceptDisputeCallback(),
        state: isLoading.value ? 'loading' : 'start',
    },
    {
        title: i18n.get('disputes.management.common.actions.goBack'),
        disabled: isLoading.value,
        event: goBack,
        variant: 'secondary',
    },
]);

const acceptError = ref(false);

async function acceptDisputeCallback() {
    if (!canAcceptDispute.value || !isFunction(acceptDispute) || !disputePspReference) return;

    isLoading.value = true;
    acceptError.value = false;
    try {
        await acceptDispute({}, { path: { disputePspReference } });
        clearStates();
        disputeAccepted.value = true;
    } catch {
        acceptError.value = true;
    } finally {
        isLoading.value = false;
    }
}

watch(disputeAccepted, accepted => {
    if (!accepted || callbackCalled.value || !disputePspReference || !isFunction(props.onDisputeAccept)) return;
    callbackCalled.value = true;
    props.onDisputeAccept({ id: disputePspReference });
});
</script>

<template>
    <div class="adyen-pe-accept-dispute__container">
        <div v-if="disputeAccepted" class="adyen-pe-accept-dispute__success">
            <SuccessIcon class="adyen-pe-accept-dispute__success-icon" aria-hidden="true" />
            <BentoTypography variant="title">
                {{ acceptedLabel }}
            </BentoTypography>
            <BentoButton variant="secondary" @click="goBack">
                {{ i18n.get('disputes.management.common.actions.showDetails') }}
            </BentoButton>
        </div>
        <template v-else>
            <BentoTypography class="adyen-pe-accept-dispute__title" el="h2" variant="title">
                {{ acceptTitle }}
            </BentoTypography>
            <BentoTypography variant="body">
                {{ acceptDisclaimer }}
            </BentoTypography>
            <div class="adyen-pe-accept-dispute__input">
                <BentoCheckbox v-model="termsAgreed" :disabled="interactionsDisabled" required>
                    {{ i18n.get('disputes.management.accept.common.agree') }}
                </BentoCheckbox>
            </div>
            <BentoAlert v-if="acceptError" type="critical" role="alert">
                <template #description>
                    {{ i18n.get('disputes.management.common.errors.unavailable') }}
                </template>
            </BentoAlert>
            <div class="adyen-pe-accept-dispute__actions">
                <BentoButtonActions :actions="actionButtons" />
            </div>
        </template>
    </div>
</template>

// packages/domains/disputes/preact/src/DisputeManagement/components/AcceptDisputeFlow/AcceptDisputeFlow.tsx
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import { useModalContext } from '@integration-components/ui-components-preact/Modal/Modal';
import { useCoreContext, useConfigContext } from '@integration-components/core/preact';
import ButtonActions from '@integration-components/ui-components-preact/Button/ButtonActions/ButtonActions';
import { ButtonActionsList } from '@integration-components/types';
import { ButtonVariant } from '@integration-components/ui-components-preact/Button/types';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { useDisputeFlow } from '../../context/dispute/context';
import useMutation from '@integration-components/hooks-preact/useMutation/useMutation';
import { EMPTY_OBJECT, isFunction, uniqueId } from '@integration-components/utils';
import { TranslationKey } from '@integration-components/core';
import { DisputeManagementProps } from '../../types';
import Button from '@integration-components/ui-components-preact/Button';
import Icon from '@integration-components/ui-components-preact/Icon';
import SuccessIcon from '@integration-components/ui-components-preact/SuccessIcon/SuccessIcon';
import './AcceptDisputeFlow.scss';

export const AcceptDisputeFlow = ({ onDisputeAccept }: Pick<DisputeManagementProps, 'onDisputeAccept'>) => {
    const { i18n } = useCoreContext();
    const { acceptDispute } = useConfigContext().endpoints;
    const { dispute, clearStates, goBack } = useDisputeFlow();
    const { withinModal } = useModalContext();

    const cachedDispute = useRef(dispute).current ?? dispute;
    const titleEl = withinModal ? TypographyElement.H2 : TypographyElement.DIV;

    const disputePspReference = cachedDispute?.dispute.pspReference;
    const disputeType = cachedDispute?.dispute.type;
    const isRequestForInformation = disputeType === 'REQUEST_FOR_INFORMATION';

    const acceptedLabel = useRef<TranslationKey>('disputes.management.accept.chargeback.accepted');
    const acceptDisclaimer = useRef<TranslationKey>('disputes.management.accept.chargeback.disclaimer');
    const acceptTitle = useRef<TranslationKey>('disputes.management.accept.chargeback.title');
    const acceptButtonTitle = useRef<TranslationKey>('disputes.management.accept.chargeback.actions.accept');
    const isRFI = useRef(isRequestForInformation);

    if ((isRFI.current ||= isRequestForInformation)) {
        acceptedLabel.current = 'disputes.management.accept.requestForInformation.accepted';
        acceptDisclaimer.current = 'disputes.management.accept.requestForInformation.disclaimer';
        acceptTitle.current = 'disputes.management.accept.requestForInformation.title';
        acceptButtonTitle.current = 'disputes.management.accept.requestForInformation.actions.accept';
    }

    const [termsAgreed, setTermsAgreed] = useState(false);
    const [disputeAccepted, setDisputeAccepted] = useState(false);

    const acceptDisputeMutation = useMutation({
        queryFn: acceptDispute,
        options: {
            onSuccess: useCallback(() => {
                clearStates();
                setDisputeAccepted(true);
            }, [clearStates]),
        },
    });

    const interactionsDisabled = acceptDisputeMutation.isLoading || disputeAccepted;
    const canAcceptDispute = termsAgreed && !interactionsDisabled;

    const acceptDisputeCallback = useCallback(() => {
        if (!canAcceptDispute) return;
        void acceptDisputeMutation.mutate(EMPTY_OBJECT, { path: { disputePspReference: disputePspReference! } });
    }, [canAcceptDispute, disputePspReference, acceptDisputeMutation]);

    const toggleTermsAgreement = useCallback(() => {
        if (interactionsDisabled) return;
        setTermsAgreed(prev => !prev);
    }, [interactionsDisabled]);

    const actionButtons = useMemo<ButtonActionsList>(() => {
        return [
            {
                title: i18n.get(acceptButtonTitle.current),
                disabled: !canAcceptDispute,
                state: acceptDisputeMutation.isLoading ? 'loading' : 'default',
                variant: ButtonVariant.PRIMARY,
                event: acceptDisputeCallback,
                classNames: disputeAccepted ? ['adyen-pe-accept-dispute__accepted-btn'] : undefined,
                renderTitle: title => {
                    if (disputeAccepted) {
                        return (
                            <>
                                <Icon name="checkmark-circle-fill" className="adyen-pe-accept-dispute__accepted-icon" />
                                {i18n.get('disputes.management.accept.common.accepted')}
                            </>
                        );
                    }
                    return title;
                },
            },
            {
                title: i18n.get('disputes.management.common.actions.goBack'),
                disabled: acceptDisputeMutation.isLoading,
                variant: ButtonVariant.SECONDARY,
                event: goBack,
            },
        ];
    }, [i18n, acceptDisputeCallback, acceptDisputeMutation.isLoading, canAcceptDispute, goBack, disputeAccepted]);

    const acceptCallbackHasBeenCalled = useRef(false);
    const termsAgreementInputId = useRef(uniqueId()).current;

    useEffect(() => {
        if (acceptCallbackHasBeenCalled.current) return;

        if (disputeAccepted && disputePspReference && isFunction(onDisputeAccept)) {
            acceptCallbackHasBeenCalled.current = true;
            onDisputeAccept({ id: disputePspReference });
        }
    }, [disputeAccepted, disputePspReference, onDisputeAccept]);

    return (
        <div className="adyen-pe-accept-dispute__container">
            {disputeAccepted ? (
                <div className="adyen-pe-accept-dispute__success">
                    <SuccessIcon className="adyen-pe-accept-dispute__success-icon" />
                    <Typography variant={TypographyVariant.TITLE}>{i18n.get(acceptedLabel.current)}</Typography>
                    <Button variant={ButtonVariant.SECONDARY} onClick={goBack}>
                        {i18n.get('disputes.management.common.actions.showDetails')}
                    </Button>
                </div>
            ) : (
                <>
                    <Typography className="adyen-pe-accept-dispute__title" el={titleEl} variant={TypographyVariant.TITLE} medium>
                        {i18n.get(acceptTitle.current)}
                    </Typography>
                    <Typography variant={TypographyVariant.BODY} medium>
                        {i18n.get(acceptDisclaimer.current)}
                    </Typography>
                    <div className="adyen-pe-accept-dispute__input">
                        <input
                            type="checkbox"
                            disabled={interactionsDisabled}
                            className="adyen-pe-visually-hidden"
                            id={termsAgreementInputId}
                            onInput={toggleTermsAgreement}
                        />

                        <label className="adyen-pe-accept-dispute__label" htmlFor={termsAgreementInputId}>
                            {termsAgreed ? <Icon name="checkmark-square-fill" /> : <Icon name="square" />}
                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                                {i18n.get('disputes.management.accept.common.agree')}
                            </Typography>
                        </label>
                    </div>

                    <div className="adyen-pe-accept-dispute__actions">
                        <ButtonActions actions={actionButtons} />
                    </div>
                </>
            )}
        </div>
    );
};
