// packages/domains/disputes/vue/src/DisputeManagement/components/DisputeDataProperties.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { BentoAlert, BentoButton, BentoLink, BentoStructuredList, BentoStructuredListItem, BentoTag, BentoTypography } from '@adyen/bento-vue3';
import DownloadIcon from '@adyen/ui-assets-icons-16/vue/download';
import { useConfigContext, useCoreContext } from '@integration-components/core/vue';
import type { TranslationKey } from '@integration-components/core';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import {
    DISPUTE_DETAILS_RESERVED_FIELDS_SET,
    getDefenseDocumentContent,
    getDefenseReasonContent,
    getDisputeReason,
    isDisputeActionNeeded,
    type DisputeDetailsCustomization,
    type TranslationConfigItem,
} from '@integration-components/disputes/domain';
import { DATE_FORMAT_DISPUTE_DETAILS, isFunction } from '@integration-components/utils';
import type { IDisputeDetail, IDisputeStatus } from '@integration-components/types/api/models/disputes';
import { useDisputeFlow } from '../composables/useDisputeFlow';

type CustomDataValue = {
    type?: string;
    value?: unknown;
    visibility?: string;
    config?: {
        className?: string;
        href?: string;
        target?: string;
        src?: string;
        alt?: string;
    };
};

type DetailItem =
    | { id: string; label: TranslationKey; kind: 'text'; value: string | undefined }
    | { id: string; label: TranslationKey; kind: 'date'; value: string }
    | { id: string; label: TranslationKey; kind: 'evidence'; value: string[] };

const DISPUTE_STATUSES_WITH_ACCEPTED_DATE: IDisputeStatus[] = ['ACCEPTED', 'EXPIRED'];

const props = defineProps<{
    dispute: IDisputeDetail;
    dataCustomization?: { details?: DisputeDetailsCustomization };
    defenseReasonConfig: Record<string, TranslationConfigItem>;
    extraFields?: Record<string, unknown>;
}>();

const { i18n } = useCoreContext();
const config = useConfigContext();
const { defenseDocumentConfig } = useDisputeFlow();
const { dateFormat } = useTimezoneAwareDateFormatting(props.dispute.payment.balanceAccount?.timeZone);
const downloadErrors = ref<Set<string>>(new Set());

const hiddenFields = computed(
    () => new Set((props.dataCustomization?.details?.fields ?? []).filter(field => field.visibility === 'hidden').map(field => String(field.key)))
);

function isVisible(id: string) {
    return !hiddenFields.value.has(id);
}

function isCustomDataObject(value: unknown): value is CustomDataValue {
    return !!value && typeof value === 'object' && 'value' in value;
}

function formatDate(date: string) {
    return dateFormat(date, DATE_FORMAT_DISPUTE_DETAILS);
}

const items = computed<DetailItem[]>(() => {
    const { pspReference: disputeReference, reason: disputeReason, acceptedDate, createdAt, dueDate, status, type } = props.dispute.dispute;
    const { pspReference: paymentReference, merchantReference, balanceAccount } = props.dispute.payment;
    const { reason: defenseReason, defendedOn, suppliedDocuments } = props.dispute.defense || {};
    const isFraudNotification = type === 'NOTIFICATION_OF_FRAUD';
    const isExpiredDispute = status === 'EXPIRED' || (status === 'LOST' && !isFraudNotification && !defendedOn);
    const isActionableDispute = isDisputeActionNeeded(props.dispute.dispute) && props.dispute.dispute.defensibility !== 'NOT_ACTIONABLE';

    return [
        {
            id: 'disputeReason',
            label: 'disputes.management.details.fields.disputeReason',
            kind: 'text',
            value: `${getDisputeReason(i18n, disputeReason.category)} - ${disputeReason.title}`,
        },
        !isFraudNotification
            ? {
                  id: 'reasonCode',
                  label: 'disputes.management.details.fields.reasonCode',
                  kind: 'text',
                  value: disputeReason.code,
              }
            : undefined,
        {
            id: 'openedOn',
            label: 'disputes.management.details.fields.openedOn',
            kind: 'date',
            value: createdAt,
        },
        dueDate && isActionableDispute
            ? {
                  id: 'respondBy',
                  label: 'disputes.management.details.fields.respondBy',
                  kind: 'date',
                  value: dueDate,
              }
            : undefined,
        {
            id: 'disputeId',
            label: 'disputes.management.details.fields.disputeReference',
            kind: 'text',
            value: disputeReference,
        },
        {
            id: 'account',
            label: 'disputes.management.details.fields.account',
            kind: 'text',
            value: balanceAccount?.description,
        },
        {
            id: 'paymentPspReference',
            label: 'disputes.management.details.fields.paymentReference',
            kind: 'text',
            value: paymentReference,
        },
        merchantReference
            ? {
                  id: 'paymentMerchantReference',
                  label: 'disputes.management.details.fields.merchantReference',
                  kind: 'text',
                  value: merchantReference,
              }
            : undefined,
        defenseReason
            ? {
                  id: 'defenseReason',
                  label: 'disputes.management.details.fields.defenseReason',
                  kind: 'text',
                  value: getDefenseReasonContent(props.defenseReasonConfig, i18n, defenseReason)?.title ?? defenseReason,
              }
            : undefined,
        defendedOn
            ? {
                  id: 'defendedOn',
                  label: 'disputes.management.details.fields.defendedOn',
                  kind: 'date',
                  value: defendedOn,
              }
            : undefined,
        suppliedDocuments?.length
            ? {
                  id: 'disputeEvidence',
                  label: 'disputes.management.details.fields.evidence',
                  kind: 'evidence',
                  value: suppliedDocuments,
              }
            : undefined,
        acceptedDate && DISPUTE_STATUSES_WITH_ACCEPTED_DATE.includes(status)
            ? {
                  id: 'acceptedOn',
                  label: 'disputes.management.details.fields.acceptedOn',
                  kind: 'date',
                  value: acceptedDate,
              }
            : undefined,
        dueDate && isExpiredDispute
            ? {
                  id: 'expiredOn',
                  label: 'disputes.management.details.fields.expiredOn',
                  kind: 'date',
                  value: dueDate,
              }
            : undefined,
    ].filter((item): item is DetailItem => !!item && isVisible(item.id));
});

const extraDetails = computed(() =>
    Object.entries(props.extraFields ?? {})
        .filter(([key, value]) => !DISPUTE_DETAILS_RESERVED_FIELDS_SET.has(key as never) && !isHiddenCustomValue(value) && !isCustomButton(value))
        .map(([key, value]) => ({
            key,
            value: isCustomDataObject(value) ? value.value : value,
            type: isCustomDataObject(value) ? value.type : 'text',
            config: isCustomDataObject(value) ? value.config : undefined,
        }))
);

function isCustomButton(value: unknown) {
    return isCustomDataObject(value) && value.type === 'button';
}

function isHiddenCustomValue(value: unknown) {
    return isCustomDataObject(value) && value.visibility === 'hidden';
}

function getCopyValue(item: DetailItem) {
    return ['disputeId', 'paymentPspReference', 'paymentMerchantReference'].includes(item.id) && item.kind === 'text' ? item.value : undefined;
}

async function downloadEvidence(documentType: string) {
    const downloadDefenseDocument = config.endpoints.downloadDefenseDocument;
    if (!isFunction(downloadDefenseDocument)) return;

    try {
        const response = await downloadDefenseDocument(
            {},
            {
                path: { disputePspReference: props.dispute.dispute.pspReference },
                query: { documentType },
            }
        );
        const url = URL.createObjectURL(response.blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = response.filename || documentType;
        link.click();
        URL.revokeObjectURL(url);
    } catch {
        downloadErrors.value = new Set([...downloadErrors.value, documentType]);
    }
}
</script>

<template>
    <BentoStructuredList class="adyen-pe-dispute-data__list">
        <BentoStructuredListItem v-for="item in items" :key="item.id" :copy="getCopyValue(item)" :label="i18n.get(item.label)">
            <time v-if="item.kind === 'date'" :datetime="item.value">
                <BentoTypography variant="body">{{ formatDate(item.value) }}</BentoTypography>
            </time>
            <div v-else-if="item.kind === 'evidence'" class="adyen-pe-dispute-data__list--evidence">
                <template v-for="documentType in item.value" :key="documentType">
                    <BentoTag :label="getDefenseDocumentContent(defenseDocumentConfig, i18n, documentType)?.title ?? documentType" />
                    <BentoButton
                        variant="tertiary"
                        :aria-label="i18n.get('disputes.management.details.actions.downloadEvidence')"
                        @click="downloadEvidence(documentType)"
                    >
                        <DownloadIcon aria-hidden="true" />
                    </BentoButton>
                    <BentoAlert
                        v-if="downloadErrors.has(documentType)"
                        class="adyen-pe-dispute-data__list-evidence-error-message"
                        type="critical"
                        variant="tip"
                    >
                        <template #description>
                            {{ i18n.get('disputes.management.details.errors.downloadFailure') }}
                        </template>
                    </BentoAlert>
                </template>
            </div>
            <BentoTypography v-else variant="body">
                {{ item.value }}
            </BentoTypography>
        </BentoStructuredListItem>

        <BentoStructuredListItem v-for="item in extraDetails" :key="item.key" :label="i18n.get(item.key as never)">
            <BentoLink
                v-if="item.type === 'link' && item.config?.href"
                :class="item.config.className"
                :to="item.config.href"
                :target="item.config.target || '_blank'"
                rel="noopener noreferrer"
                external
            >
                {{ item.value }}
            </BentoLink>
            <div v-else-if="item.type === 'icon' && item.config?.src" :class="item.config.className">
                <img :src="item.config.src" :alt="item.config.alt || String(item.value ?? '')" />
                <BentoTypography variant="body">
                    {{ item.value }}
                </BentoTypography>
            </div>
            <BentoTypography v-else variant="body" :class="item.config?.className">
                {{ item.value }}
            </BentoTypography>
        </BentoStructuredListItem>
    </BentoStructuredList>
</template>

// packages/domains/disputes/preact/src/DisputeManagement/components/DisputesData/DisputeDataProperties.tsx
import cx from 'classnames';
import { useMemo } from 'preact/hooks';
import { DATE_FORMAT_DISPUTE_DETAILS, normalizeCustomFields } from '@integration-components/utils';
import { useTimezoneAwareDateFormatting } from '@integration-components/hooks-preact';
import { TranslationKey } from '@integration-components/core';
import { IDisputeDetail, IDisputeStatus } from '@integration-components/types/api/models/disputes';
import DownloadButton from '@integration-components/ui-components-preact/Button/DownloadButton/DownloadButton';
import CopyText from '@integration-components/ui-components-preact/CopyText/CopyText';
import Icon from '@integration-components/ui-components-preact/DataGrid/components/Icon';
import { isCustomDataObject } from '@integration-components/ui-components-preact/DataGrid/components/TableCells';
import Link from '@integration-components/ui-components-preact/Link/Link';
import StructuredList from '@integration-components/ui-components-preact/StructuredList';
import { StructuredListProps } from '@integration-components/ui-components-preact/StructuredList/types';
import { Tag } from '@integration-components/ui-components-preact/Tag/Tag';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import type { CustomDataRetrieved } from '@integration-components/types';
import { DisputeDetailsCustomization } from '../../types';
import {
    DISPUTE_DETAILS_FIELDS_REMAPS,
    DISPUTE_DETAILS_RESERVED_FIELDS_SET,
    getDefenseDocumentContent,
    getDefenseReasonContent,
    getDisputeReason,
    isDisputeActionNeeded,
    TranslationConfigItem,
} from '@integration-components/disputes/domain';
import { DISPUTE_DATA_LABEL, DISPUTE_DATA_LIST, DISPUTE_DATA_LIST_EVIDENCE, DISPUTE_DATA_LIST_EVIDENCE_ERROR_MESSAGE } from './constants';
import { useCoreContext } from '@integration-components/core/preact';
import SVGIcon from '@integration-components/ui-components-preact/Icon';
import { useDisputeFlow } from '../../context/dispute/context';

type DisputeDataPropertiesProps = {
    dispute: IDisputeDetail;
    dataCustomization?: { details?: DisputeDetailsCustomization };
    extraFields?: CustomDataRetrieved;
    defenseReasonConfig: Record<string, TranslationConfigItem>;
};

const disputeDataKeys = {
    acceptedOn: 'disputes.management.details.fields.acceptedOn',
    account: 'disputes.management.details.fields.account',
    defendedOn: 'disputes.management.details.fields.defendedOn',
    defenseReason: 'disputes.management.details.fields.defenseReason',
    disputeEvidence: 'disputes.management.details.fields.evidence',
    disputeReason: 'disputes.management.details.fields.disputeReason',
    disputeReference: 'disputes.management.details.fields.disputeReference',
    expiredOn: 'disputes.management.details.fields.expiredOn',
    merchantReference: 'disputes.management.details.fields.merchantReference',
    openedOn: 'disputes.management.details.fields.openedOn',
    paymentReference: 'disputes.management.details.fields.paymentReference',
    reasonCode: 'disputes.management.details.fields.reasonCode',
    respondBy: 'disputes.management.details.fields.respondBy',
} satisfies Record<string, TranslationKey>;

const DISPUTE_STATUSES_WITH_ACCEPTED_DATE: IDisputeStatus[] = ['ACCEPTED', 'EXPIRED'];

const DisputeDataProperties = ({ dispute, dataCustomization, defenseReasonConfig, extraFields }: DisputeDataPropertiesProps) => {
    const { i18n } = useCoreContext();
    const { dateFormat } = useTimezoneAwareDateFormatting(dispute.payment.balanceAccount.timeZone);
    const { defenseDocumentConfig } = useDisputeFlow();

    return useMemo(() => {
        const { pspReference: disputeReference, reason: disputeReason, acceptedDate, createdAt, dueDate, status, type } = dispute.dispute;
        const { pspReference: paymentReference, merchantReference, balanceAccount } = dispute.payment;
        const { reason: defenseReason, defendedOn, suppliedDocuments } = dispute.defense || {};

        const isFraudNotification = type === 'NOTIFICATION_OF_FRAUD';
        const isExpiredDispute = status === 'EXPIRED' || (status === 'LOST' && !isFraudNotification && !defendedOn);
        const isActionableDispute = isDisputeActionNeeded(dispute.dispute) && dispute.dispute.defensibility !== 'NOT_ACTIONABLE';
        const customizedFields = normalizeCustomFields(dataCustomization?.details?.fields, DISPUTE_DETAILS_FIELDS_REMAPS);

        const SKIP_ITEM: StructuredListProps['items'][number] = null!;

        const listItems: StructuredListProps['items'] = [
            // dispute reason
            {
                key: disputeDataKeys.disputeReason,
                value: `${getDisputeReason(i18n, disputeReason.category)} - ${disputeReason.title}`, // [NOTE]: Not translated at the moment (maybe in the future)
                id: 'disputeReason',
            },

            // reason code
            !isFraudNotification
                ? {
                      key: disputeDataKeys.reasonCode,
                      value: disputeReason.code,
                      id: 'reasonCode',
                  }
                : SKIP_ITEM,

            // created at
            {
                key: disputeDataKeys.openedOn,
                value: <time dateTime={createdAt}>{dateFormat(createdAt, DATE_FORMAT_DISPUTE_DETAILS)}</time>,
                id: 'openedOn',
            },

            // respond by
            dueDate && isActionableDispute
                ? {
                      key: disputeDataKeys.respondBy,
                      value: <time dateTime={dueDate}>{dateFormat(dueDate, DATE_FORMAT_DISPUTE_DETAILS)}</time>,
                      id: 'respondBy',
                  }
                : SKIP_ITEM,

            // dispute reference
            {
                key: disputeDataKeys.disputeReference,
                value: (
                    <CopyText
                        copyButtonAriaLabelKey="disputes.management.details.actions.copyDisputeReference"
                        type={'Default' as const}
                        textToCopy={disputeReference}
                        showCopyTextTooltip={false}
                    />
                ),
                id: 'disputeId',
            },

            // balance account
            {
                key: disputeDataKeys.account,
                value: balanceAccount.description,
                id: 'account',
            },

            // psp reference
            {
                key: disputeDataKeys.paymentReference,
                value: (
                    <CopyText
                        copyButtonAriaLabelKey="disputes.management.details.actions.copyPaymentReference"
                        type={'Default' as const}
                        textToCopy={paymentReference}
                        showCopyTextTooltip={false}
                    />
                ),
                id: 'paymentPspReference',
            },

            // merchant reference
            merchantReference
                ? {
                      key: disputeDataKeys.merchantReference,
                      value: (
                          <CopyText
                              copyButtonAriaLabelKey="disputes.management.details.actions.copyMerchantReference"
                              type={'Default' as const}
                              textToCopy={merchantReference}
                              showCopyTextTooltip={false}
                          />
                      ),
                      id: 'paymentMerchantReference',
                  }
                : SKIP_ITEM,

            // defense reason
            defenseReason
                ? {
                      key: disputeDataKeys.defenseReason,
                      value: getDefenseReasonContent(defenseReasonConfig, i18n, defenseReason)?.title ?? defenseReason,
                      id: 'defenseReason',
                  }
                : SKIP_ITEM,

            // defended on
            defendedOn
                ? {
                      key: disputeDataKeys.defendedOn,
                      value: <time dateTime={defendedOn}>{dateFormat(defendedOn, DATE_FORMAT_DISPUTE_DETAILS)}</time>,
                      id: 'defendedOn',
                  }
                : SKIP_ITEM,

            // evidence
            suppliedDocuments && suppliedDocuments.length > 0
                ? {
                      key: disputeDataKeys.disputeEvidence,
                      value: (
                          <>
                              {suppliedDocuments.map((document, index) => {
                                  const queryParam = {
                                      path: { disputePspReference: disputeReference },
                                      query: { documentType: document },
                                  };
                                  return (
                                      <div key={`${document}-${index}`} className={DISPUTE_DATA_LIST_EVIDENCE}>
                                          <Tag label={getDefenseDocumentContent(defenseDocumentConfig, i18n, document)?.title ?? document} />
                                          <DownloadButton
                                              className={'adyen-pe-dispute-document-download'}
                                              endpointName={'downloadDefenseDocument'}
                                              disabled={false}
                                              requestParams={queryParam}
                                              iconButton={true}
                                              errorMessage={() => {
                                                  return (
                                                      <div className={DISPUTE_DATA_LIST_EVIDENCE_ERROR_MESSAGE}>
                                                          <SVGIcon name="info-filled" />
                                                          <Typography variant={TypographyVariant.CAPTION} el={TypographyElement.SPAN}>
                                                              {i18n.get('disputes.management.details.errors.downloadFailure')}
                                                          </Typography>
                                                      </div>
                                                  );
                                              }}
                                              setError={() => console.warn('Download failed for', document)}
                                              aria-label={i18n.get('disputes.management.details.actions.downloadEvidence')}
                                          />
                                      </div>
                                  );
                              })}
                          </>
                      ),
                      id: 'disputeEvidence',
                  }
                : SKIP_ITEM,

            // accepted on
            acceptedDate && DISPUTE_STATUSES_WITH_ACCEPTED_DATE.includes(status)
                ? {
                      key: disputeDataKeys.acceptedOn,
                      value: <time dateTime={acceptedDate}>{dateFormat(acceptedDate, DATE_FORMAT_DISPUTE_DETAILS)}</time>,
                      id: 'acceptedOn',
                  }
                : SKIP_ITEM,

            // expired on
            dueDate && isExpiredDispute
                ? {
                      key: disputeDataKeys.expiredOn,
                      value: <time dateTime={dueDate}>{dateFormat(dueDate, DATE_FORMAT_DISPUTE_DETAILS)}</time>,
                      id: 'expiredOn',
                  }
                : SKIP_ITEM,
        ]
            .filter(Boolean)
            .filter(val => !customizedFields?.some(field => field.key === val.id && field.visibility === 'hidden'));

        // Add custom data
        const itemsWithExtraFields = [
            ...listItems,
            ...(Object.entries(extraFields || {}) as [string, CustomDataRetrieved[string]][])
                .filter(
                    ([key, value]) => !DISPUTE_DETAILS_RESERVED_FIELDS_SET.has(key as any) && (!isCustomDataObject(value) || value.type !== 'button')
                )
                .map(([key, value]) => ({
                    key: key as TranslationKey,
                    value: isCustomDataObject(value) ? value.value : value,
                    type: isCustomDataObject(value) ? value.type : 'text',
                    config: isCustomDataObject(value) ? value.config : undefined,
                })),
        ];

        return (
            <StructuredList
                classNames={DISPUTE_DATA_LIST}
                items={itemsWithExtraFields}
                layout="4-8"
                align="start"
                renderLabel={label => <div className={DISPUTE_DATA_LABEL}>{label}</div>}
                renderValue={(val, key, type, config) => {
                    if (type === 'link' && config) {
                        return (
                            <Link classNames={[cx(config?.className)]} href={config.href} target={config.target || '_blank'}>
                                {val}
                            </Link>
                        );
                    }
                    if (type === 'icon' && config) {
                        const icon = { url: config?.src, alt: config.alt || val };
                        return (
                            <div className={cx('adyen-pe-dispute-data__list-icon-value', config?.className)}>
                                <Icon {...icon} />
                                <Typography variant={TypographyVariant.BODY}>{val}</Typography>
                            </div>
                        );
                    }
                    return (
                        <Typography className={cx(config?.className)} variant={TypographyVariant.BODY}>
                            {val}
                        </Typography>
                    );
                }}
            />
        );
    }, [
        dispute.dispute,
        dispute.payment,
        dispute.defense,
        i18n,
        dateFormat,
        defenseReasonConfig,
        extraFields,
        defenseDocumentConfig,
        dataCustomization?.details?.fields,
    ]);
};

export default DisputeDataProperties;
