// packages/domains/reports/preact/src/ReportsOverview/components/ReportsOverview/ReportsOverview.tsx
import { useCallback, useEffect, useMemo } from 'preact/hooks';
import { AdyenPlatformExperienceError } from '@integration-components/core';
import type { CustomDataRetrieved, ExternalUIComponentProps, IBalanceAccountBase, IReport } from '@integration-components/types';
import { FilterParam } from '@integration-components/types';
import { hasCustomField, isFunction, mergeRecords } from '@integration-components/utils';
import { useBalanceAccountSelection, useCustomColumnsData, useDefaultOverviewFilterParams } from '@integration-components/hooks-preact';
import { useConfigContext } from '@integration-components/core/preact';
import { EARLIEST_PAYOUT_SINCE_DATE, REPORTS_OVERVIEW_CLASS_NAMES, type ReportsOverviewComponentProps } from '@integration-components/reports/domain';
import FilterBar, { FilterBarMobileSwitch, useFilterBarState } from '../../../../../../../../src/components/internal/FilterBar';
import DateFilter from '../../../../../../../../src/components/internal/FilterBar/filters/DateFilter/DateFilter';
import BalanceAccountSelector from '../../../../../../../../src/components/internal/FormFields/Select/BalanceAccountSelector';
import { DEFAULT_PAGE_LIMIT, LIMIT_OPTIONS } from '../../../../../../../../src/components/internal/Pagination/constants';
import { useCursorPaginatedRecords } from '../../../../../../../../src/components/internal/Pagination/hooks';
import { Header } from '../../../../../../../../src/components/internal/Header';
import { FIELDS, ReportsTable } from '../ReportsTable/ReportsTable';
import './ReportsOverview.scss';

export const ReportsOverview = ({
    onFiltersChanged,
    balanceAccounts,
    allowLimitSelection = true,
    preferredLimit = DEFAULT_PAGE_LIMIT,
    isLoadingBalanceAccount,
    onContactSupport,
    hideTitle,
    dataCustomization,
}: ExternalUIComponentProps<
    ReportsOverviewComponentProps & { balanceAccounts: IBalanceAccountBase[] | undefined; isLoadingBalanceAccount: boolean }
>) => {
    const { getReports: reportsEndpointCall } = useConfigContext().endpoints;
    const { activeBalanceAccount, balanceAccountSelectionOptions, onBalanceAccountSelection } = useBalanceAccountSelection({ balanceAccounts });
    const { defaultParams, nowTimestamp, refreshNowTimestamp } = useDefaultOverviewFilterParams('reports', activeBalanceAccount);

    const getReports = useCallback(
        async (pageRequestParams: Record<FilterParam | 'cursor', string>, signal?: AbortSignal) => {
            const requestOptions = { signal, errorLevel: 'error' } as const;

            return reportsEndpointCall!(requestOptions, {
                query: {
                    ...pageRequestParams,
                    type: 'payout',
                    createdSince:
                        pageRequestParams[FilterParam.CREATED_SINCE] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_SINCE],
                    createdUntil:
                        pageRequestParams[FilterParam.CREATED_UNTIL] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_UNTIL],
                    balanceAccountId: activeBalanceAccount?.id ?? '',
                },
            });
        },
        [activeBalanceAccount?.id, defaultParams, reportsEndpointCall]
    );

    // FILTERS
    const filterBarState = useFilterBarState();
    const _onFiltersChanged = useMemo(() => (isFunction(onFiltersChanged) ? onFiltersChanged : void 0), [onFiltersChanged]);
    const preferredLimitOptions = useMemo(() => (allowLimitSelection ? LIMIT_OPTIONS : undefined), [allowLimitSelection]);

    const { canResetFilters, error, fetching, filters, limit, limitOptions, records, resetFilters, updateFilters, updateLimit, ...paginationProps } =
        useCursorPaginatedRecords<IReport, 'data', string, FilterParam>({
            fetchRecords: getReports,
            dataField: 'data',
            filterParams: defaultParams.current.defaultFilterParams,
            initialFiltersSameAsDefault: true,
            onFiltersChanged: _onFiltersChanged,
            preferredLimit,
            preferredLimitOptions,
            enabled: !!activeBalanceAccount?.id && !!reportsEndpointCall,
        });

    const mergeCustomData = useCallback(
        ({ records, retrievedData }: { records: IReport[]; retrievedData: CustomDataRetrieved[] }) =>
            mergeRecords(records, retrievedData, (modifiedRecord, record) => modifiedRecord.createdAt === record.createdAt),
        []
    );

    const hasCustomColumn = useMemo(() => hasCustomField(dataCustomization?.list?.fields, FIELDS), [dataCustomization?.list?.fields]);
    const { customRecords: reports, loadingCustomRecords } = useCustomColumnsData<IReport>({
        records,
        hasCustomColumn,
        onDataRetrieve: dataCustomization?.list?.onDataRetrieve,
        mergeCustomData,
    });

    useEffect(() => {
        refreshNowTimestamp();
    }, [filters, refreshNowTimestamp]);

    return (
        <div className={REPORTS_OVERVIEW_CLASS_NAMES.base}>
            <Header hideTitle={hideTitle} titleKey="reports.overview.title" subtitleKey="reports.overview.generateInfo">
                <FilterBarMobileSwitch {...filterBarState} />
            </Header>
            <FilterBar {...filterBarState} ariaLabelKey="reports.overview.filters.label">
                <BalanceAccountSelector
                    activeBalanceAccount={activeBalanceAccount}
                    balanceAccountSelectionOptions={balanceAccountSelectionOptions}
                    onBalanceAccountSelection={onBalanceAccountSelection}
                />
                <DateFilter
                    canResetFilters={canResetFilters}
                    defaultParams={defaultParams}
                    filters={filters}
                    nowTimestamp={nowTimestamp}
                    refreshNowTimestamp={refreshNowTimestamp}
                    sinceDate={EARLIEST_PAYOUT_SINCE_DATE}
                    timezone={'UTC'}
                    updateFilters={updateFilters}
                />
            </FilterBar>
            <ReportsTable
                balanceAccountId={activeBalanceAccount?.id}
                loading={fetching || isLoadingBalanceAccount || !balanceAccounts || !activeBalanceAccount || loadingCustomRecords}
                data={dataCustomization?.list?.onDataRetrieve ? reports : records}
                showPagination={true}
                limit={limit}
                limitOptions={limitOptions}
                onContactSupport={onContactSupport}
                onLimitSelection={updateLimit}
                error={error as AdyenPlatformExperienceError}
                customColumns={dataCustomization?.list?.fields}
                {...paginationProps}
            />
        </div>
    );
};

// packages/domains/reports/vue/src/ReportsOverview/components/ReportsOverview.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { getTimezoneAwareDateRangeQueryParams } from '@integration-components/composables-vue';
import ReportsFilters from './ReportsFilters.vue';
import ReportsTable from './ReportsTable.vue';
import { useReportsList } from '../composables/useReportsList';
import { EARLIEST_REPORT_SINCE_DATE, REPORTS_OVERVIEW_CLASS_NAMES } from '../../../../domain/src';
import { quickSelectDateRanges, startOfDay } from '@integration-components/utils';
import type { IBalanceAccountBase } from '../types';
import { BentoTypography } from '@adyen/bento-vue3';
import '../styles/index.scss';

const props = defineProps<{
    balanceAccountId?: string;
    allowLimitSelection?: boolean;
    preferredLimit?: number;
    hideTitle?: boolean;
    onContactSupport?: () => void;
    onFiltersChanged?: (filters: Record<string, string | undefined>) => any;
    dataCustomization?: any;
    balanceAccounts: IBalanceAccountBase[] | undefined;
    isLoadingBalanceAccount: boolean;
}>();

const { i18n } = useCoreContext();

const initialDateRangeQueryParams = getTimezoneAwareDateRangeQueryParams({
    dateRange: quickSelectDateRanges.last30Days,
    earliestDate: startOfDay(new Date(EARLIEST_REPORT_SINCE_DATE)),
    timezone: 'UTC',
});

const filterParams = ref<{
    balanceAccountId: string | undefined;
    createdSince: string;
    createdUntil: string;
}>({
    balanceAccountId: undefined,
    ...initialDateRangeQueryParams,
});

function onFiltersChange(params: { balanceAccountId: string | undefined; createdSince: string; createdUntil: string }) {
    filterParams.value = params;
}

const activeBalanceAccount = computed(() => {
    const id = filterParams.value.balanceAccountId;
    return props.balanceAccounts?.find((a: IBalanceAccountBase) => a.id === id);
});

const reportsListResult = useReportsList(() => ({
    fetchEnabled: !!filterParams.value.balanceAccountId,
    balanceAccountId: filterParams.value.balanceAccountId,
    createdSince: filterParams.value.createdSince,
    createdUntil: filterParams.value.createdUntil,
    allowLimitSelection: props.allowLimitSelection,
    preferredLimit: props.preferredLimit,
    onFiltersChanged: props.onFiltersChanged,
}));

const isLoading = computed(
    () => reportsListResult.fetching.value || props.isLoadingBalanceAccount || !props.balanceAccounts || !activeBalanceAccount.value
);

// Computed to avoid inline `as Type | Union` casts in the template (vue/no-deprecated-filter)
const listError = computed(() => reportsListResult.error.value as Error | undefined);
</script>

<template>
    <div :class="REPORTS_OVERVIEW_CLASS_NAMES.base">
        <div v-if="!props.hideTitle" class="adyen-pe-reports-overview-header">
            <BentoTypography variant="title">{{ i18n.get('reports.overview.title') }}</BentoTypography>
            <BentoTypography variant="body" class="adyen-pe-reports-overview-header__description">{{
                i18n.get('reports.overview.generateInfo')
            }}</BentoTypography>
        </div>

        <ReportsFilters :balance-accounts="props.balanceAccounts" :on-change="onFiltersChange" />

        <ReportsTable
            :balance-account-id="activeBalanceAccount?.id"
            :loading="isLoading"
            :data="reportsListResult.records.value"
            :show-pagination="true"
            :error="listError"
            :on-contact-support="props.onContactSupport"
            :custom-columns="props.dataCustomization?.list?.fields"
            :on-data-retrieve="props.dataCustomization?.list?.onDataRetrieve"
            :has-next="reportsListResult.hasNext.value"
            :has-previous="reportsListResult.hasPrevious.value"
            :go-to-next-page="reportsListResult.goToNextPage"
            :go-to-previous-page="reportsListResult.goToPreviousPage"
            :limit="reportsListResult.limit.value"
            :limit-options="reportsListResult.limitOptions.value"
            :update-limit="reportsListResult.updateLimit"
            :current-page="reportsListResult.page.value + 1"
        />
    </div>
</template>
