// packages/domains/payByLink/preact/src/PaymentLinkCreation/components/Form/FormSuccess/FormSuccess.tsx
import cx from 'classnames';
import { useCoreContext } from '@integration-components/core/preact';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import Icon from '@integration-components/ui-components-preact/Icon/Icon';
import SuccessIcon from '@integration-components/ui-components-preact/SuccessIcon/SuccessIcon';
import Button from '@integration-components/ui-components-preact/Button/Button';
import { ButtonVariant } from '@integration-components/ui-components-preact/Button/types';
import './FormSuccess.scss';
import { useCallback, useEffect, useRef, useState } from 'preact/hooks';

type FormSuccessProps = {
    onGoToDetails: () => void;
    paymentLinkUrl: string;
};
export const FormSuccess = ({ onGoToDetails, paymentLinkUrl }: FormSuccessProps) => {
    const { i18n } = useCoreContext();

    const [copied, setCopied] = useState(false);
    const copiedTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    useEffect(() => {
        return () => {
            if (copiedTimeoutRef.current) {
                clearTimeout(copiedTimeoutRef.current);
            }
        };
    }, []);

    const onCopy = useCallback(async () => {
        if (!paymentLinkUrl) return;
        try {
            await navigator.clipboard.writeText(paymentLinkUrl);

            setCopied(true);
            if (copiedTimeoutRef.current) {
                clearTimeout(copiedTimeoutRef.current);
            }
            copiedTimeoutRef.current = setTimeout(() => {
                setCopied(false);
                copiedTimeoutRef.current = null;
            }, 3000);
        } catch {
            // no-op
        }
    }, [paymentLinkUrl]);

    return (
        <section className={cx('adyen-pe-payment-link-creation-form-success')}>
            <div className="adyen-pe-payment-link-creation-form-success__content">
                <SuccessIcon className="adyen-pe-payment-link-creation-form-success__icon" />
                <Typography variant={TypographyVariant.TITLE} className="adyen-pe-payment-link-creation-form-success__title">
                    {i18n.get('payByLink.creation.success.title')}
                </Typography>
                <Typography variant={TypographyVariant.BODY} className="adyen-pe-payment-link-creation-form-success__description">
                    {i18n.get('payByLink.creation.success.description')}
                </Typography>
            </div>
            <div className="adyen-pe-payment-link-creation-form-success__actions">
                <Button variant={ButtonVariant.SECONDARY} onClick={onGoToDetails}>
                    {i18n.get('payByLink.creation.success.showDetails')}
                </Button>
                <Button variant={ButtonVariant.PRIMARY} onClick={onCopy} iconLeft={<Icon name={copied ? 'checkmark' : 'copy'} />}>
                    {copied ? i18n.get('payByLink.creation.success.copiedToClipboard') : i18n.get('payByLink.creation.success.copyLink')}
                </Button>
            </div>
        </section>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/Form/FormSuccess/FormSuccess.vue
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoButton, BentoTypography } from '@adyen/bento-vue3';
import CheckmarkCircleFillIcon from '@adyen/ui-assets-icons-40/vue/checkmark-circle-filled';
import styles from './FormSuccess.module.scss';

const props = defineProps<{
    paymentLinkUrl: string;
    onShowDetails?: () => void;
}>();

const { i18n } = useCoreContext();

const copied = ref(false);
let copiedTimeout: ReturnType<typeof setTimeout> | null = null;

onBeforeUnmount(() => {
    if (copiedTimeout) clearTimeout(copiedTimeout);
});

async function onCopy() {
    if (!props.paymentLinkUrl || !navigator.clipboard) return;
    try {
        await navigator.clipboard.writeText(props.paymentLinkUrl);
        copied.value = true;
        if (copiedTimeout) clearTimeout(copiedTimeout);
        copiedTimeout = setTimeout(() => {
            copied.value = false;
            copiedTimeout = null;
        }, 3000);
    } catch {
        // no-op
    }
}
</script>

<template>
    <section :class="styles.root">
        <div :class="styles.content">
            <CheckmarkCircleFillIcon :class="styles.icon" />
            <BentoTypography variant="title" medium :class="styles.title">
                {{ i18n.get('payByLink.creation.success.title') }}
            </BentoTypography>
            <BentoTypography variant="body" :class="styles.description">
                {{ i18n.get('payByLink.creation.success.description') }}
            </BentoTypography>
        </div>
        <div :class="styles.actions">
            <BentoButton variant="secondary" @click="props.onShowDetails?.()">
                {{ i18n.get('payByLink.creation.success.showDetails') }}
            </BentoButton>
            <BentoButton variant="primary" @click="onCopy">
                {{ copied ? i18n.get('payByLink.creation.success.copiedToClipboard') : i18n.get('payByLink.creation.success.copyLink') }}
            </BentoButton>
        </div>
    </section>
</template>
