// packages/domains/payouts/vue/src/PayoutsOverview/components/PayoutsOverview.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoTypography } from '@adyen/bento-vue3';
import { getTimezoneAwareDateRangeQueryParams } from '@integration-components/composables-vue';
import { quickSelectDateRanges, startOfDay } from '@integration-components/utils';
import PayoutsFilters from './PayoutsFilters.vue';
import PayoutsTable from './PayoutsTable.vue';
import PayoutDetailsModal from './PayoutDetailsModal.vue';
import { usePayoutsList } from '../composables/usePayoutsList';
import { EARLIEST_PAYOUT_SINCE_DATE } from '../constants';
import type { IBalanceAccountBase, PayoutsOverviewExternalProps } from '../types';
import type { IPayout } from '@integration-components/types';
import styles from './PayoutsOverview.module.scss';

const props = defineProps<{
    balanceAccountId?: string;
    allowLimitSelection?: boolean;
    preferredLimit?: number;
    hideTitle?: boolean;
    showDetails?: boolean;
    onContactSupport?: () => void;
    onFiltersChanged?: (filters: Record<string, string | undefined>) => any;
    onRecordSelection?: PayoutsOverviewExternalProps['onRecordSelection'];
    dataCustomization?: PayoutsOverviewExternalProps['dataCustomization'];
    balanceAccounts: IBalanceAccountBase[] | undefined;
    isLoadingBalanceAccount: boolean;
}>();

const { i18n } = useCoreContext();

const initialDateRangeQueryParams = getTimezoneAwareDateRangeQueryParams({
    dateRange: quickSelectDateRanges.last30Days,
    earliestDate: startOfDay(new Date(EARLIEST_PAYOUT_SINCE_DATE)),
    timezone: 'UTC',
});

const filterParams = ref<{
    balanceAccountId: string | undefined;
    createdSince: string;
    createdUntil: string;
}>({
    balanceAccountId: undefined,
    ...initialDateRangeQueryParams,
});

function onFiltersChange(params: { balanceAccountId: string | undefined; createdSince: string; createdUntil: string }) {
    filterParams.value = params;
}

const activeBalanceAccount = computed(() => {
    const id = filterParams.value.balanceAccountId;
    return props.balanceAccounts?.find((a: IBalanceAccountBase) => a.id === id);
});

const payoutsListResult = usePayoutsList(() => ({
    fetchEnabled: !!filterParams.value.balanceAccountId,
    balanceAccountId: filterParams.value.balanceAccountId,
    createdSince: filterParams.value.createdSince,
    createdUntil: filterParams.value.createdUntil,
    allowLimitSelection: props.allowLimitSelection,
    preferredLimit: props.preferredLimit,
    onFiltersChanged: props.onFiltersChanged,
}));

const isLoading = computed(
    () => payoutsListResult.fetching.value || props.isLoadingBalanceAccount || !props.balanceAccounts || !activeBalanceAccount.value
);

const payoutsError = computed(() => payoutsListResult.error.value as Error | undefined);

// ── Details modal ──
const isModalOpen = ref(false);
const selectedPayout = ref<IPayout | null>(null);

function showModal() {
    isModalOpen.value = true;
}

function onRowClick(payout: IPayout) {
    if (props.showDetails === false && !props.onRecordSelection) return;
    selectedPayout.value = payout;
    const balanceAccountId = activeBalanceAccount.value?.id ?? '';

    // Notify the consumer first so they can intercept and decide whether to
    // call `showModal` themselves. If no consumer callback is provided we open
    // the modal directly.
    if (props.onRecordSelection) {
        props.onRecordSelection({
            balanceAccountId,
            date: payout.createdAt ?? '',
            showModal,
        });
    } else if (props.showDetails !== false) {
        showModal();
    }
}

function closeModal() {
    isModalOpen.value = false;
    selectedPayout.value = null;
}
</script>

<template>
    <div :class="styles.root">
        <div v-if="!props.hideTitle" :class="styles.header">
            <BentoTypography variant="title">{{ i18n.get('payouts.overview.title') }}</BentoTypography>
            <BentoTypography variant="body" :class="styles.description">{{ i18n.get('payouts.overview.generateInfo') }}</BentoTypography>
        </div>

        <div role="toolbar" :class="styles.toolbar">
            <PayoutsFilters :balance-accounts="props.balanceAccounts" :on-change="onFiltersChange" />
        </div>

        <PayoutsTable
            :balance-account-id="activeBalanceAccount?.id"
            :loading="isLoading"
            :data="payoutsListResult.records.value"
            :show-pagination="true"
            :show-details="props.showDetails"
            :error="payoutsError"
            :on-row-click="onRowClick"
            :on-contact-support="props.onContactSupport"
            :custom-columns="props.dataCustomization?.list?.fields"
            :on-data-retrieve="props.dataCustomization?.list?.onDataRetrieve"
            :has-next="payoutsListResult.hasNext.value"
            :has-previous="payoutsListResult.hasPrevious.value"
            :go-to-next-page="payoutsListResult.goToNextPage"
            :go-to-previous-page="payoutsListResult.goToPreviousPage"
            :limit="payoutsListResult.limit.value"
            :limit-options="payoutsListResult.limitOptions.value"
            :update-limit="payoutsListResult.updateLimit"
            :current-page="payoutsListResult.page.value + 1"
        />

        <PayoutDetailsModal
            v-if="isModalOpen && selectedPayout && activeBalanceAccount"
            :id="activeBalanceAccount.id"
            :balance-account-description="activeBalanceAccount.description"
            :date="selectedPayout.createdAt ?? ''"
            :data-customization="props.dataCustomization"
            :on-contact-support="props.onContactSupport"
            :on-close="closeModal"
        />
    </div>
</template>

// packages/domains/payouts/preact/src/PayoutsOverview/components/PayoutsOverview/PayoutsOverview.tsx
import { useCallback, useEffect, useMemo } from 'preact/hooks';
import { AdyenPlatformExperienceError } from '@integration-components/core';
import type { CustomDataRetrieved, ExternalUIComponentProps, IBalanceAccountBase, IPayout } from '@integration-components/types';
import { FilterParam } from '@integration-components/types';
import { hasCustomField, isFunction, mergeRecords } from '@integration-components/utils';
import { useBalanceAccountSelection, useCustomColumnsData, useDefaultOverviewFilterParams } from '@integration-components/hooks-preact';
import useModalDetails from '@integration-components/hooks-preact/useModalDetails';
import { useConfigContext } from '@integration-components/core/preact';
import type { PayoutsOverviewComponentProps } from '@integration-components/payouts/domain';
import { BASE_CLASS, BASE_CLASS_DETAILS, EARLIEST_PAYOUT_SINCE_DATE } from './constants';
import { PAYOUT_TABLE_FIELDS, PayoutsTable } from '../PayoutsTable/PayoutsTable';
import FilterBar, { FilterBarMobileSwitch, useFilterBarState } from '@integration-components/ui-components-preact/FilterBar';
import BalanceAccountSelector from '@integration-components/ui-components-preact/FormFields/Select/BalanceAccountSelector';
import { DEFAULT_PAGE_LIMIT, LIMIT_OPTIONS } from '@integration-components/ui-components-preact/Pagination/constants';
import { useCursorPaginatedRecords } from '@integration-components/ui-components-preact/Pagination/hooks';
import DateFilter from '@integration-components/ui-components-preact/FilterBar/filters/DateFilter/DateFilter';
import { Header } from '@integration-components/ui-components-preact/Header';
import { DataDetailsModal } from '../../../internal/DataOverviewDisplay/DataDetailsModal';
import './PayoutsOverview.scss';

export const PayoutsOverview = ({
    onFiltersChanged,
    balanceAccounts,
    allowLimitSelection = true,
    preferredLimit = DEFAULT_PAGE_LIMIT,
    onRecordSelection,
    showDetails,
    isLoadingBalanceAccount,
    onContactSupport,
    hideTitle,
    dataCustomization,
}: ExternalUIComponentProps<
    PayoutsOverviewComponentProps & { balanceAccounts: IBalanceAccountBase[] | undefined; isLoadingBalanceAccount: boolean }
>) => {
    const { getPayouts: payoutsEndpointCall } = useConfigContext().endpoints;
    const { activeBalanceAccount, balanceAccountSelectionOptions, onBalanceAccountSelection } = useBalanceAccountSelection({ balanceAccounts });
    const { defaultParams, nowTimestamp, refreshNowTimestamp } = useDefaultOverviewFilterParams('payouts', activeBalanceAccount);

    const getPayouts = useCallback(
        async (pageRequestParams: Record<FilterParam | 'cursor', string>, signal?: AbortSignal) => {
            const requestOptions = { signal, errorLevel: 'error' } as const;

            return payoutsEndpointCall!(requestOptions, {
                query: {
                    ...pageRequestParams,
                    createdSince:
                        pageRequestParams[FilterParam.CREATED_SINCE] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_SINCE],
                    createdUntil:
                        pageRequestParams[FilterParam.CREATED_UNTIL] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_UNTIL],
                    balanceAccountId: activeBalanceAccount?.id ?? '',
                },
            });
        },
        [activeBalanceAccount?.id, defaultParams, payoutsEndpointCall]
    );

    // FILTERS
    const filterBarState = useFilterBarState();
    const _onFiltersChanged = useMemo(() => (isFunction(onFiltersChanged) ? onFiltersChanged : void 0), [onFiltersChanged]);
    const preferredLimitOptions = useMemo(() => (allowLimitSelection ? LIMIT_OPTIONS : undefined), [allowLimitSelection]);

    const { canResetFilters, error, fetching, filters, limit, limitOptions, records, resetFilters, updateFilters, updateLimit, ...paginationProps } =
        useCursorPaginatedRecords<IPayout, 'data', string, FilterParam>({
            fetchRecords: getPayouts,
            dataField: 'data',
            filterParams: defaultParams.current.defaultFilterParams,
            initialFiltersSameAsDefault: true,
            onFiltersChanged: _onFiltersChanged,
            preferredLimit,
            preferredLimitOptions,
            enabled: !!activeBalanceAccount?.id && !!payoutsEndpointCall,
        });

    useEffect(() => {
        refreshNowTimestamp();
    }, [filters, refreshNowTimestamp]);

    const payoutDetails = useMemo(
        () => ({
            showDetails: showDetails ?? true,
            callback: onRecordSelection,
        }),
        [showDetails, onRecordSelection]
    );

    const mergeCustomData = useCallback(
        ({ records, retrievedData }: { records: IPayout[]; retrievedData: CustomDataRetrieved[] }) =>
            mergeRecords(records, retrievedData, (modifiedRecord, record) => modifiedRecord.createdAt === record.createdAt),
        []
    );

    const hasCustomColumn = useMemo(() => hasCustomField(dataCustomization?.list?.fields, PAYOUT_TABLE_FIELDS), [dataCustomization?.list?.fields]);
    const { customRecords, loadingCustomRecords } = useCustomColumnsData<IPayout>({
        records,
        hasCustomColumn,
        onDataRetrieve: dataCustomization?.list?.onDataRetrieve,
        mergeCustomData,
    });

    const modalOptions = useMemo(() => ({ payout: payoutDetails }), [payoutDetails]);

    const { updateDetails, resetDetails, selectedDetail } = useModalDetails(modalOptions);

    const onRowClick = useCallback(
        (value: IPayout) => {
            updateDetails({
                selection: {
                    type: 'payout',
                    data: { id: activeBalanceAccount?.id, balanceAccountDescription: activeBalanceAccount?.description || '', date: value.createdAt },
                },
                modalSize: 'small',
            }).callback({ balanceAccountId: activeBalanceAccount?.id || '', date: value.createdAt });
        },
        [updateDetails, activeBalanceAccount?.id, activeBalanceAccount?.description]
    );

    return (
        <div className={BASE_CLASS}>
            <Header hideTitle={hideTitle} titleKey="payouts.overview.title" subtitleKey="payouts.overview.generateInfo">
                <FilterBarMobileSwitch {...filterBarState} />
            </Header>
            <FilterBar {...filterBarState} ariaLabelKey="payouts.overview.filters.label">
                <BalanceAccountSelector
                    activeBalanceAccount={activeBalanceAccount}
                    balanceAccountSelectionOptions={balanceAccountSelectionOptions}
                    onBalanceAccountSelection={onBalanceAccountSelection}
                />
                <DateFilter
                    canResetFilters={canResetFilters}
                    defaultParams={defaultParams}
                    filters={filters}
                    nowTimestamp={nowTimestamp}
                    refreshNowTimestamp={refreshNowTimestamp}
                    sinceDate={EARLIEST_PAYOUT_SINCE_DATE}
                    timezone={'UTC'}
                    updateFilters={updateFilters}
                />
            </FilterBar>
            <DataDetailsModal
                ariaLabelKey="payouts.details.title"
                className={BASE_CLASS_DETAILS}
                onContactSupport={onContactSupport}
                selectedDetail={selectedDetail as ReturnType<typeof useModalDetails>['selectedDetail']}
                resetDetails={resetDetails}
                dataCustomization={dataCustomization?.details}
            >
                <PayoutsTable
                    loading={fetching || isLoadingBalanceAccount || !balanceAccounts || loadingCustomRecords}
                    data={dataCustomization?.list?.onDataRetrieve ? customRecords : records}
                    showPagination={true}
                    onRowClick={onRowClick}
                    showDetails={showDetails}
                    limit={limit}
                    limitOptions={limitOptions}
                    onContactSupport={onContactSupport}
                    onLimitSelection={updateLimit}
                    error={error as AdyenPlatformExperienceError}
                    customColumns={dataCustomization?.list?.fields}
                    {...paginationProps}
                />
            </DataDetailsModal>
        </div>
    );
};
