// src/components/external/PaymentLinksOverview/components/PaymentLinkDetailsModal/PaymentLinkDetailsModal.tsx
import { useCallback, useState } from 'preact/hooks';
import { FC, PropsWithChildren } from 'preact/compat';
import Modal from '@integration-components/ui-primitives-preact/Modal';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import useModalDetails from '../../../../../hooks/useModalDetails';
import { PaymentLinkDetails } from '../../../PaymentLinkDetails/components/PaymentLinkDetails/PaymentLinkDetails';

export interface PaymentLinkDetailsModalProps {
    onUpdate: () => void;
    selectedDetail: ReturnType<typeof useModalDetails>['selectedDetail'];
    resetDetails: ReturnType<typeof useModalDetails>['resetDetails'];
}

export const PaymentLinkDetailsModal: FC<PaymentLinkDetailsModalProps> = ({
    children,
    selectedDetail,
    resetDetails,
    onUpdate,
}: PropsWithChildren<PaymentLinkDetailsModalProps>) => {
    const { i18n } = useCoreContext();
    const [isPaymentLinkUpdated, setIsPaymentLinkUpdated] = useState(false);
    const isModalOpen = !!selectedDetail;

    const handleDismiss = useCallback(() => {
        if (isPaymentLinkUpdated) {
            setIsPaymentLinkUpdated(false);
            onUpdate();
        }
        resetDetails();
    }, [isPaymentLinkUpdated, onUpdate, resetDetails]);

    const handlePaymentLinkUpdate = useCallback(() => {
        setIsPaymentLinkUpdated(true);
    }, []);

    return (
        <div>
            {children}
            {selectedDetail && (
                <Modal
                    isOpen={isModalOpen}
                    aria-label={i18n.get('payByLink.details.title')}
                    onClose={handleDismiss}
                    isDismissible={true}
                    headerWithBorder={false}
                    size={selectedDetail.modalSize || 'large'}
                >
                    <PaymentLinkDetails
                        id={selectedDetail.selection.data}
                        onUpdate={handlePaymentLinkUpdate}
                        onDismiss={handleDismiss}
                        hideTitle
                        isDismissButtonHidden
                    />
                </Modal>
            )}
        </div>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinksOverview/components/PaymentLinkDetailsModal.vue
<script setup lang="ts">
import { defineAsyncComponent } from 'vue';
import { BentoLoadingIndicator, BentoModal } from '@adyen/bento-vue3';
import { ModalContextProvider, useCoreContext } from '@integration-components/core/vue';

const props = defineProps<{
    id: string;
    onContactSupport?: () => void;
    onClose: () => void;
    onUpdate: () => void;
}>();

const { i18n } = useCoreContext();
const PaymentLinkDetails = defineAsyncComponent({
    loader: () => import('../../PaymentLinkDetails/components/PaymentLinkDetails/PaymentLinkDetails.vue'),
    loadingComponent: BentoLoadingIndicator,
    delay: 0,
});
</script>

<template>
    <BentoModal :is-open="true" size="large" :is-dismissible="true" :aria-label="i18n.get('payByLink.details.title')" @close-modal="props.onClose">
        <template #content>
            <ModalContextProvider>
                <PaymentLinkDetails
                    :id="props.id"
                    :on-contact-support="props.onContactSupport"
                    :on-dismiss="props.onClose"
                    :on-update="props.onUpdate"
                    is-dismiss-button-hidden
                />
            </ModalContextProvider>
        </template>
    </BentoModal>
</template>
