// src/components/external/PaymentLinksOverview/components/PaymentLinksOverview.tsx
import {
    ACTION_BUTTON_CLASS,
    ACTION_BUTTON_MOBILE_CLASS,
    ACTION_BUTTONS_CONTAINER_CLASS,
    BASE_ACTIONS_CLASS,
    BASE_CLASS,
    BASE_XS_CLASS,
    DEFAULT_PAYMENT_LINK_STATUS_GROUP,
    EARLIEST_PAYMENT_LINK_DATE,
    FILTERS_ALERT_CONTAINER_CLASS,
    FILTERS_CONTAINER_CLASS,
    PAYMENT_LINK_STATUS_GROUPS_FILTER_MAPPING,
    PAYMENT_LINK_STATUS_GROUPS_TABS,
    PAYMENT_LINK_STATUSES,
    PAYMENT_LINK_TYPES,
    TABS_CONTAINER_CLASS,
} from './constants';
import { ExternalUIComponentProps, FilterParam, PaymentLinksOverviewComponentProps } from '../../../types';
import { IPaymentLinkFilters, IPaymentLinkStatus, IPaymentLinkStatusGroup, IPaymentLinkType, IPaymentLinkItem } from '../../../../types';
import useDefaultOverviewFilterParams from '../../../../hooks/useDefaultOverviewFilterParams';
import { FilterBar, FilterBarMobileSwitch, useFilterBarState } from '../../../internal/FilterBar';
import { useCursorPaginatedRecords } from '../../../internal/Pagination/hooks';
import { Header } from '../../../internal/Header';
import { DateFilter } from '../../../internal/FilterBar/filters/DateFilter';
import { MultiSelectionFilter, useMultiSelectionFilter } from '@integration-components/transactions/preact';
import AdyenPlatformExperienceError from '../../../../core/Errors/AdyenPlatformExperienceError';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { isFunction, listFrom } from '../../../../utils';
import { useConfigContext } from '../../../../core/ConfigContext';
import useCoreContext from '../../../../core/Context/useCoreContext';
import { DEFAULT_PAGE_LIMIT, LIMIT_OPTIONS } from '../../../internal/Pagination/constants';
import useModalDetails from '../../../../hooks/useModalDetails';
import { PaymentLinksTable } from './PaymentLinksTable';
import TextFilter from '../../../internal/FilterBar/filters/TextFilter';
import Tabs from '../../../internal/Tabs/Tabs';
import { TabComponentProps } from '../../../internal/Tabs/types';
import './PaymentLinksOverview.scss';
import cx from 'classnames';
import { containerQueries, useResponsiveContainer } from '../../../../hooks/useResponsiveContainer';
import Select from '../../../internal/FormFields/Select';
import { AriaAttributes } from 'preact/compat';
import { PopoverContainerSize } from '../../../internal/Popover/types';
import * as RangePreset from '../../../internal/Calendar/calendar/timerange/presets';
import { PaymentLinkDetailsModal } from './PaymentLinkDetailsModal/PaymentLinkDetailsModal';
import { PaymentLinksOverviewModalType, StoreData } from './types';
import Button from '../../../internal/Button';
import { ButtonVariant } from '../../../internal/Button/types';
import Icon from '../../../internal/Icon';
import { PaymentLinksOverviewModal } from './PaymentLinksOverviewModal';
import Alert from '../../../internal/Alert/Alert';
import { AlertTypeOption, AlertVariantOption } from '../../../internal/Alert/types';
import {
    getTimeRangeSelectionDefaultPresetOptions,
    TIME_RANGE_SELECTION_PRESET_OPTION_KEYS,
} from '../../../internal/DatePicker/components/TimeRangeSelector';

const PAYMENT_LINK_TYPES_FILTER_PARAM = 'linkTypes';
const PAYMENT_LINK_STATUSES_FILTER_PARAM = 'statuses';
const PAYMENT_LINK_STORES_FILTER_PARAM = 'storeIds';
const LAST_REFRESH_TIMESTAMP_PARAM = '_t';
const PAYMENT_LINK_STATUSES_FILTER_VALUES = Object.keys(PAYMENT_LINK_STATUSES) as IPaymentLinkStatus[];

const PaymentLinksOverviewTabsDropdown = ({
    ['aria-label']: ariaLabel,
    activeTab,
    onChange,
}: {
    activeTab: IPaymentLinkStatusGroup;
    onChange: NonNullable<TabComponentProps<IPaymentLinkStatusGroup>['onChange']>;
} & Pick<AriaAttributes, 'aria-label'>) => {
    const { i18n } = useCoreContext();

    const [statusGroup, setStatusGroup] = useState(activeTab);

    const selectItems = useMemo(() => PAYMENT_LINK_STATUS_GROUPS_TABS.map(({ id, label }) => ({ id, name: i18n.get(label) })), [i18n]);

    useEffect(() => {
        const currentTab = PAYMENT_LINK_STATUS_GROUPS_TABS.find(tab => tab.id === statusGroup);
        if (currentTab) {
            onChange(currentTab);
        }
    }, [onChange, statusGroup]);

    useEffect(() => setStatusGroup(activeTab), [activeTab]);

    return (
        <Select
            aria-label={ariaLabel}
            items={selectItems}
            selected={statusGroup}
            onChange={({ target }) => setStatusGroup(target.value as IPaymentLinkStatusGroup)}
            showOverlay={true}
            multiSelect={false}
            filterable={false}
        />
    );
};

interface PaymentLinksPageRequestParams extends Record<FilterParam | 'cursor', string> {
    [LAST_REFRESH_TIMESTAMP_PARAM]: DOMHighResTimeStamp;
}

export const PaymentLinksOverview = ({
    onFiltersChanged,
    allowLimitSelection = true,
    preferredLimit = DEFAULT_PAGE_LIMIT,
    onRecordSelection,
    showDetails,
    onContactSupport,
    hideTitle,
    isFiltersLoading,
    filterParams,
    stores,
    allStores,
    paymentLinkCreation,
    paymentLinkSettings,
    storeIds,
    filterError,
    storeError,
}: ExternalUIComponentProps<
    PaymentLinksOverviewComponentProps & {
        filterParams?: IPaymentLinkFilters;
        stores?: StoreData[];
        isFiltersLoading: boolean;
        filterError?: AdyenPlatformExperienceError | undefined;
        storeError?: AdyenPlatformExperienceError | undefined;
        allStores?: StoreData[];
    }
>) => {
    const { i18n } = useCoreContext();
    const { getPaymentLinks, createPBLPaymentLink, savePayByLinkSettings } = useConfigContext().endpoints;
    const timeRangeOptions = getTimeRangeSelectionDefaultPresetOptions({ exclude: [TIME_RANGE_SELECTION_PRESET_OPTION_KEYS.YEAR_TO_DATE] });
    const { defaultParams, nowTimestamp, refreshNowTimestamp } = useDefaultOverviewFilterParams(
        'paymentLinks',
        undefined,
        undefined,
        timeRangeOptions
    );
    const [statusGroup, setStatusGroup] = useState<IPaymentLinkStatusGroup>(DEFAULT_PAYMENT_LINK_STATUS_GROUP);
    const [statusGroupActiveTab, setStatusGroupActiveTab] = useState<IPaymentLinkStatusGroup | undefined>(statusGroup);
    const [statusGroupFetchPending, setStatusGroupFetchPending] = useState(false);
    const isMobileContainer = useResponsiveContainer(containerQueries.down.xs);
    const [showFiltersAlert, setShowFiltersAlert] = useState(false);

    const getPaymentLinksData = useCallback(
        async ({ [LAST_REFRESH_TIMESTAMP_PARAM]: _, ...pageRequestParams }: PaymentLinksPageRequestParams, signal?: AbortSignal) => {
            const requestOptions = { signal, errorLevel: 'error' } as const;
            const filterStoreIds = listFrom<string>(pageRequestParams[FilterParam.STORE_IDS]);
            const propStoreIds = storeIds ? listFrom<string>(storeIds) : undefined;
            return getPaymentLinks!(requestOptions, {
                query: {
                    ...pageRequestParams,
                    storeIds: filterStoreIds?.length ? filterStoreIds : propStoreIds,
                    statuses: listFrom<IPaymentLinkItem['status']>(pageRequestParams[FilterParam.STATUSES]),
                    linkTypes: listFrom<IPaymentLinkItem['linkType']>(pageRequestParams[FilterParam.LINK_TYPES]),
                    createdSince:
                        pageRequestParams[FilterParam.CREATED_SINCE] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_SINCE],
                    createdUntil:
                        pageRequestParams[FilterParam.CREATED_UNTIL] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_UNTIL],
                    merchantReference:
                        pageRequestParams[FilterParam.MERCHANT_REFERENCE] ??
                        defaultParams.current.defaultFilterParams[FilterParam.MERCHANT_REFERENCE],
                    paymentLinkId:
                        pageRequestParams[FilterParam.PAYMENT_LINK_ID] ?? defaultParams.current.defaultFilterParams[FilterParam.PAYMENT_LINK_ID],
                },
            });
        },
        [defaultParams, getPaymentLinks, storeIds]
    );

    // FILTERS
    const filterBarState = useFilterBarState();
    const _onFiltersChanged = useMemo(() => (isFunction(onFiltersChanged) ? onFiltersChanged : void 0), [onFiltersChanged]);
    const preferredLimitOptions = useMemo(() => (allowLimitSelection ? LIMIT_OPTIONS : undefined), [allowLimitSelection]);

    const defaultFilters = Object.assign(defaultParams.current.defaultFilterParams, {
        [PAYMENT_LINK_TYPES_FILTER_PARAM]: undefined,
        [PAYMENT_LINK_STATUSES_FILTER_PARAM]: undefined,
        statusGroup: DEFAULT_PAYMENT_LINK_STATUS_GROUP,
        [PAYMENT_LINK_STORES_FILTER_PARAM]: undefined,
        [LAST_REFRESH_TIMESTAMP_PARAM]: performance.now(),
    });

    //TODO - Infer the return type of getPaymentLinksData instead of having to specify it
    const { canResetFilters, error, fetching, filters, limit, limitOptions, records, resetFilters, updateFilters, updateLimit, ...paginationProps } =
        useCursorPaginatedRecords<IPaymentLinkItem, 'data', string, FilterParam>({
            fetchRecords: getPaymentLinksData,
            dataField: 'data',
            filterParams: defaultFilters,
            initialFiltersSameAsDefault: true,
            onFiltersChanged: _onFiltersChanged,
            preferredLimit,
            preferredLimitOptions,
            enabled: !!getPaymentLinks && !!allStores?.length,
        });

    const linkStatusFilter = useMultiSelectionFilter({
        mapFilterOptionName: useCallback((status: IPaymentLinkStatus) => i18n.get(PAYMENT_LINK_STATUSES[status]), [i18n]),
        filterParam: PAYMENT_LINK_STATUSES_FILTER_PARAM,
        filterValues: filterParams?.statuses?.[PAYMENT_LINK_STATUS_GROUPS_FILTER_MAPPING[statusGroup!]] ?? PAYMENT_LINK_STATUSES_FILTER_VALUES,
        defaultFilters,
        updateFilters,
        filters,
    });

    const linkTypesFilter = useMultiSelectionFilter({
        mapFilterOptionName: useCallback((linkType: IPaymentLinkType) => i18n.get(PAYMENT_LINK_TYPES[linkType]), [i18n]),
        filterParam: PAYMENT_LINK_TYPES_FILTER_PARAM,
        filterValues: filterParams?.linkTypes,
        defaultFilters,
        updateFilters,
        filters,
    });

    const storesTypesFilter = useMultiSelectionFilter({
        mapFilterOptionName: useCallback((storeId: string) => stores?.find(store => store.id === storeId)?.storeCode ?? storeId, [stores]),
        filterParam: PAYMENT_LINK_STORES_FILTER_PARAM,
        filterValues: useMemo(() => (stores && stores.length > 0 ? stores.filter(store => store.id).map(store => store.id!) : undefined), [stores]),
        defaultFilters,
        updateFilters,
        filters,
    });

    useEffect(() => {
        updateFilters({
            [FilterParam.CURRENCIES]: undefined,
        });
    }, [updateFilters]);

    useEffect(() => {
        refreshNowTimestamp();
    }, [filters, refreshNowTimestamp]);

    const paymentLinkDetails = useMemo(
        () => ({
            showDetails: showDetails ?? true,
            callback: onRecordSelection,
        }),
        [showDetails, onRecordSelection]
    );

    const modalOptions = useMemo(() => ({ paymentLink: paymentLinkDetails }), [paymentLinkDetails]);

    const { updateDetails, resetDetails, selectedDetail } = useModalDetails(modalOptions);

    const onRowClick = useCallback(
        ({ paymentLinkId: id }: IPaymentLinkItem) => {
            updateDetails({
                selection: {
                    type: 'paymentLink',
                    data: id,
                },
                modalSize: 'small',
            }).callback({ id });
        },
        [updateDetails]
    );

    const onMerchantReferenceFilterChange = useCallback(
        (merchantReference?: string) => {
            if (!merchantReference) {
                merchantReference = undefined;
            }
            updateFilters({ merchantReference: merchantReference });
        },
        [updateFilters]
    );

    const onPaymentLinkIDFilterChange = useCallback(
        (paymentLinkId?: string) => {
            if (!paymentLinkId) {
                paymentLinkId = undefined;
            }
            updateFilters({ paymentLinkId: paymentLinkId });
        },
        [updateFilters]
    );

    const debounceTimeoutIdRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    const onStatusGroupChange = useCallback<NonNullable<TabComponentProps<IPaymentLinkStatusGroup>['onChange']>>(
        ({ id: statusGroup }) => {
            if (debounceTimeoutIdRef.current) {
                clearTimeout(debounceTimeoutIdRef.current);
            }

            debounceTimeoutIdRef.current = setTimeout(() => {
                requestAnimationFrame(() => setStatusGroupFetchPending(false));

                const statusFilterParam = PAYMENT_LINK_STATUSES_FILTER_PARAM as FilterParam;
                const filterUpdates = { statusGroup, [statusFilterParam]: undefined } as any;

                updateFilters(filterUpdates);
                debounceTimeoutIdRef.current = null;
            }, 500);

            setStatusGroup(statusGroup);
            setStatusGroupFetchPending(true);

            // Resetting statusGroupActiveTab to undefined here to allow for subsequent
            // programmatic status group tab navigation (will not change the active tab).
            setStatusGroupActiveTab(undefined);
        },
        [updateFilters]
    );

    const statusGroupAriaLabel = useMemo(() => i18n.get('payByLink.overview.list.filters.types.statusGroup'), [i18n]);

    const showTypeFilter = (filterParams?.linkTypes && filterParams?.linkTypes?.length > 0) || !!filterError;
    const showStatusFilter =
        (filterParams?.statuses && filterParams?.statuses?.[statusGroup] && filterParams?.statuses?.[statusGroup]?.length > 0) || !!filterError;
    const showStoreFilter = (stores && stores?.length > 1) || !!storeError;

    const sinceDate = useMemo(() => {
        return new Date(RangePreset.lastNDays(EARLIEST_PAYMENT_LINK_DATE).from).toString();
    }, []);

    const [isModalVisible, setModalVisible] = useState(false);
    const [modalType, setModalType] = useState<PaymentLinksOverviewModalType | undefined>(undefined);

    const openPaymentLinkModal = useCallback(() => {
        setModalType('Creation');
        setModalVisible(true);
    }, []);

    const openSettingsModal = useCallback(() => {
        setModalType('Settings');
        setModalVisible(true);
    }, []);

    const onCloseModal = useCallback(() => {
        setModalVisible(false);
    }, []);

    const refreshPaymentLinkList = useCallback(() => {
        const now = new Date();
        const currentCreatedUntil = filters?.[FilterParam.CREATED_UNTIL];
        const createdUntilDate = currentCreatedUntil ? new Date(currentCreatedUntil) : null;

        const isSameDay = createdUntilDate?.toDateString() === now.toDateString();

        updateFilters({
            ...(isSameDay && { [FilterParam.CREATED_UNTIL]: now.toISOString() }),
            [LAST_REFRESH_TIMESTAMP_PARAM]: performance.now(),
        } as any);
    }, [filters, updateFilters]);

    const sharedModalProps = useMemo(() => {
        return {
            onContactSupport,
            storeIds,
        };
    }, [onContactSupport, storeIds]);

    useEffect(() => {
        setShowFiltersAlert(!!storeError || !!filterError);
    }, [storeError, filterError]);

    const closeFiltersAlert = useCallback(() => {
        setShowFiltersAlert(false);
    }, [setShowFiltersAlert]);

    const hasActionButtons = !!(savePayByLinkSettings || createPBLPaymentLink);

    return (
        <div className={cx(BASE_CLASS, { [BASE_XS_CLASS]: isMobileContainer })}>
            <Header hideTitle={hideTitle} titleKey="payByLink.overview.title">
                <div className={BASE_ACTIONS_CLASS}>
                    {isMobileContainer && createPBLPaymentLink && (
                        <Button
                            iconButton
                            aria-label={i18n.get('payByLink.overview.list.actions.createPaymentLink')}
                            className={ACTION_BUTTON_MOBILE_CLASS}
                            onClick={openPaymentLinkModal}
                        >
                            <Icon name={'plus'} />
                        </Button>
                    )}
                    <FilterBarMobileSwitch {...filterBarState} />
                    {isMobileContainer && savePayByLinkSettings && (
                        <Button
                            iconButton
                            aria-label={i18n.get('payByLink.overview.actions.settings.a11y.label')}
                            variant={ButtonVariant.SECONDARY}
                            className={ACTION_BUTTON_MOBILE_CLASS}
                            onClick={openSettingsModal}
                        >
                            <Icon name="cog" />
                        </Button>
                    )}
                </div>
            </Header>
            <div className={TABS_CONTAINER_CLASS}>
                {isMobileContainer ? (
                    <PaymentLinksOverviewTabsDropdown
                        aria-label={statusGroupAriaLabel}
                        activeTab={statusGroupActiveTab ?? statusGroup}
                        onChange={onStatusGroupChange}
                    />
                ) : (
                    <Tabs
                        aria-label={statusGroupAriaLabel}
                        tabs={PAYMENT_LINK_STATUS_GROUPS_TABS}
                        activeTab={statusGroupActiveTab}
                        onChange={onStatusGroupChange}
                    />
                )}
            </div>
            <>
                {!isFiltersLoading && (
                    <div className={FILTERS_CONTAINER_CLASS}>
                        <FilterBar {...filterBarState} ariaLabelKey="payByLink.overview.filters.label">
                            {showStoreFilter && (
                                <MultiSelectionFilter
                                    {...storesTypesFilter}
                                    isInvalid={!!storeError}
                                    readonly={!!storeError}
                                    placeholder={i18n.get('payByLink.overview.filters.types.stores.label')}
                                />
                            )}
                            <DateFilter
                                canResetFilters={canResetFilters}
                                defaultParams={defaultParams}
                                filters={filters}
                                sinceDate={sinceDate}
                                nowTimestamp={nowTimestamp}
                                refreshNowTimestamp={refreshNowTimestamp}
                                updateFilters={updateFilters}
                            />
                            {showTypeFilter && (
                                <MultiSelectionFilter
                                    {...linkTypesFilter}
                                    isInvalid={!!filterError}
                                    readonly={!!filterError}
                                    placeholder={i18n.get('payByLink.overview.filters.types.linkTypes.label')}
                                />
                            )}
                            {showStatusFilter && (
                                <MultiSelectionFilter
                                    {...linkStatusFilter}
                                    isInvalid={!!filterError}
                                    readonly={!!filterError}
                                    placeholder={i18n.get('payByLink.overview.filters.types.status.label')}
                                />
                            )}
                            <TextFilter
                                name={i18n.get('payByLink.overview.filters.types.merchantReference.label')}
                                label={
                                    filters[FilterParam.MERCHANT_REFERENCE]
                                        ? filters[FilterParam.MERCHANT_REFERENCE]
                                        : i18n.get('payByLink.overview.filters.types.merchantReference.label')
                                }
                                value={filters[FilterParam.MERCHANT_REFERENCE]}
                                onChange={onMerchantReferenceFilterChange}
                                type={'text'}
                                containerSize={PopoverContainerSize.MEDIUM}
                            ></TextFilter>
                            <TextFilter
                                name={i18n.get('payByLink.overview.filters.types.paymentLinkID.label')}
                                label={
                                    filters[FilterParam.PAYMENT_LINK_ID]
                                        ? filters[FilterParam.PAYMENT_LINK_ID]
                                        : i18n.get('payByLink.overview.filters.types.paymentLinkID.label')
                                }
                                value={filters[FilterParam.PAYMENT_LINK_ID]}
                                onChange={onPaymentLinkIDFilterChange}
                                type={'text'}
                                containerSize={PopoverContainerSize.MEDIUM}
                            ></TextFilter>
                            {isMobileContainer && showFiltersAlert && (
                                <Alert
                                    className={cx(FILTERS_ALERT_CONTAINER_CLASS)}
                                    type={AlertTypeOption.CRITICAL}
                                    variant={AlertVariantOption.TIP}
                                    closeButton={true}
                                    onClose={closeFiltersAlert}
                                    description={i18n.get('payByLink.overview.filters.errors.networkError')}
                                />
                            )}
                        </FilterBar>
                        {hasActionButtons && !isMobileContainer && (
                            <div className={ACTION_BUTTONS_CONTAINER_CLASS}>
                                {createPBLPaymentLink && (
                                    <Button variant={ButtonVariant.PRIMARY} className={ACTION_BUTTON_CLASS} onClick={openPaymentLinkModal}>
                                        {i18n.get('payByLink.overview.list.actions.createPaymentLink')}
                                    </Button>
                                )}
                                {savePayByLinkSettings && (
                                    <Button
                                        aria-label={i18n.get('payByLink.overview.actions.settings.a11y.label')}
                                        variant={ButtonVariant.SECONDARY}
                                        className={ACTION_BUTTON_CLASS}
                                        onClick={openSettingsModal}
                                    >
                                        <Icon name="cog" />
                                    </Button>
                                )}
                            </div>
                        )}
                    </div>
                )}
                {!isMobileContainer && showFiltersAlert && (
                    <Alert
                        className={cx(FILTERS_ALERT_CONTAINER_CLASS)}
                        type={AlertTypeOption.CRITICAL}
                        variant={AlertVariantOption.TIP}
                        closeButton={true}
                        onClose={closeFiltersAlert}
                        description={i18n.get('payByLink.overview.filters.errors.networkError')}
                    />
                )}
            </>
            <PaymentLinkDetailsModal
                selectedDetail={selectedDetail as ReturnType<typeof useModalDetails>['selectedDetail']}
                resetDetails={resetDetails}
                onUpdate={refreshPaymentLinkList}
            >
                <PaymentLinksTable
                    stores={stores}
                    storeError={storeError}
                    error={error as AdyenPlatformExperienceError}
                    limit={limit}
                    allStores={allStores}
                    limitOptions={limitOptions}
                    loading={statusGroupFetchPending || fetching || isFiltersLoading}
                    onContactSupport={onContactSupport}
                    onLimitSelection={updateLimit}
                    onRowClick={onRowClick}
                    showPagination={true}
                    paymentLinks={records}
                    {...paginationProps}
                />
            </PaymentLinkDetailsModal>
            <PaymentLinksOverviewModal
                modalType={modalType}
                isModalVisible={isModalVisible}
                onCloseModal={onCloseModal}
                paymentLinkSettings={paymentLinkSettings}
                paymentLinkCreation={paymentLinkCreation}
                storeIds={sharedModalProps.storeIds}
                onContactSupport={sharedModalProps.onContactSupport}
                refreshPaymentLinkList={refreshPaymentLinkList}
            />
        </div>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinksOverview/components/PaymentLinksOverview.vue
<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue';
import { BentoTypography, BentoTabs, BentoTab, BentoButton, BentoAlert, BentoModal } from '@adyen/bento-vue3';
import PlusIcon from '@adyen/ui-assets-icons-16/vue/plus';
import SettingsIcon from '@adyen/ui-assets-icons-16/vue/settings';
import { useCoreContext, useConfigContext } from '@integration-components/core/vue';
import { useResponsiveContainer, containerQueries } from '@integration-components/composables-vue';
import PaymentLinksFilters from './PaymentLinksFilters.vue';
import PaymentLinksTable from './PaymentLinksTable.vue';
import PaymentLinkCreation from '../../PaymentLinkCreation/components/PaymentLinkCreationContainer/PaymentLinkCreationContainer.vue';
import PaymentLinkDetails from '../../PaymentLinkDetails/components/PaymentLinkDetails/PaymentLinkDetails.vue';
import PaymentLinkSettings from '../../PaymentLinkSettings/components/PaymentLinkSettingsContainer.vue';
import { usePaymentLinksList } from '../composables/usePaymentLinksList';
import { DEFAULT_PAYMENT_LINK_STATUS_GROUP, PAYMENT_LINK_STATUS_GROUPS_TABS } from '../constants';
import type { PaymentLinksFiltersValue } from './PaymentLinksFilters.vue';
import type { IPaymentLinkFilters, IPaymentLinkItem, IPaymentLinkStatusGroup } from '@integration-components/types';
import type { StoreData, PaymentLinksOverviewModalType } from '../../../../domain/src';
import { ACCOUNT_MISCONFIGURATION, WRONG_STORE_IDS } from '../../../../domain/src';
import type { PaymentLinksOverviewExternalProps } from '../types';
import { createPaymentLinksError } from '../utils/error';
import styles from './PaymentLinksOverview.module.scss';

const props = defineProps<{
    allowLimitSelection?: boolean;
    hideTitle?: boolean;
    preferredLimit?: number;
    showDetails?: boolean;
    storeIds?: PaymentLinksOverviewExternalProps['storeIds'];
    onFiltersChanged?: PaymentLinksOverviewExternalProps['onFiltersChanged'];
    onRecordSelection?: PaymentLinksOverviewExternalProps['onRecordSelection'];
    onContactSupport?: () => void;
    paymentLinkCreation?: PaymentLinksOverviewExternalProps['paymentLinkCreation'];
    paymentLinkSettings?: PaymentLinksOverviewExternalProps['paymentLinkSettings'];
    stores: StoreData[] | undefined;
    allStores: StoreData[] | undefined;
    isFiltersLoading: boolean;
    storeError?: Error;
    filterOptions: IPaymentLinkFilters | undefined;
    filterOptionsError?: Error;
}>();

const { i18n } = useCoreContext();
const config = useConfigContext();
const isMobile = useResponsiveContainer(containerQueries.down.xs);

let statusGroupDebounceTimer: ReturnType<typeof setTimeout> | undefined;

const statusGroupFetchPending = ref(false);
const statusGroup = ref<IPaymentLinkStatusGroup>(DEFAULT_PAYMENT_LINK_STATUS_GROUP);
const fetchStatusGroup = ref<IPaymentLinkStatusGroup>(statusGroup.value);
const activeStatusGroupTabIndex = computed(() => PAYMENT_LINK_STATUS_GROUPS_TABS.findIndex(tab => tab.id === statusGroup.value));

function onStatusGroupChange(newIndex: number) {
    const tab = PAYMENT_LINK_STATUS_GROUPS_TABS[newIndex];
    if (!tab) return;

    if (statusGroupDebounceTimer) {
        clearTimeout(statusGroupDebounceTimer);
    }

    const nextStatusGroup = tab.id as IPaymentLinkStatusGroup;
    statusGroup.value = nextStatusGroup;
    statusGroupFetchPending.value = true;

    statusGroupDebounceTimer = setTimeout(() => {
        fetchStatusGroup.value = nextStatusGroup;
        requestAnimationFrame(() => (statusGroupFetchPending.value = false));
        statusGroupDebounceTimer = undefined;
    }, 500);
}

const filtersValue = ref<PaymentLinksFiltersValue>({
    statuses: [],
    linkTypes: [],
    storeIds: [],
    merchantReference: undefined,
    paymentLinkId: undefined,
    createdSince: '',
    createdUntil: '',
});
const lastRefreshTimestamp = ref(performance.now());

function onFiltersChange(value: PaymentLinksFiltersValue) {
    filtersValue.value = value;
}

const hasMultipleStores = computed(() => !!props.stores && props.stores.length > 1);
const fetchEnabled = computed(() => !!props.stores?.length);

const paymentLinksListResult = usePaymentLinksList(() => ({
    fetchEnabled: fetchEnabled.value && !statusGroupFetchPending.value,
    statusGroup: fetchStatusGroup.value,
    statuses: filtersValue.value.statuses,
    linkTypes: filtersValue.value.linkTypes,
    filterStoreIds: filtersValue.value.storeIds,
    propStoreIds: props.storeIds,
    merchantReference: filtersValue.value.merchantReference,
    paymentLinkId: filtersValue.value.paymentLinkId,
    createdSince: filtersValue.value.createdSince,
    createdUntil: filtersValue.value.createdUntil,
    allowLimitSelection: props.allowLimitSelection,
    preferredLimit: props.preferredLimit,
    onFiltersChanged: props.onFiltersChanged,
    lastRefreshTimestamp: lastRefreshTimestamp.value,
}));

const showFiltersAlert = computed(() => !!props.storeError || !!props.filterOptionsError);
const filtersAlertDismissed = ref(false);

watch([() => props.storeError, () => props.filterOptionsError], () => {
    filtersAlertDismissed.value = false;
});

function closeFiltersAlert() {
    filtersAlertDismissed.value = true;
}

const noStoresError = computed(() => {
    if (props.isFiltersLoading || props.allStores?.length !== 0 || props.storeError) return undefined;
    return createPaymentLinksError('No stores configured', { errorCode: ACCOUNT_MISCONFIGURATION });
});

const storesFilteredError = computed(() => {
    if (props.isFiltersLoading || (props.allStores && props.allStores.length > 0 && props.stores?.length !== 0)) return undefined;
    return createPaymentLinksError('The provided store IDs do not match any configured stores', { errorCode: WRONG_STORE_IDS });
});

const paymentLinksError = computed(() => noStoresError.value ?? paymentLinksListResult.error.value ?? storesFilteredError.value);

onUnmounted(() => {
    if (statusGroupDebounceTimer) {
        clearTimeout(statusGroupDebounceTimer);
    }
});

const isDetailsModalOpen = ref(false);
const selectedPaymentLink = ref<IPaymentLinkItem | null>(null);
const hasDetailsToRefresh = ref(false);

function showDetailsModal() {
    isDetailsModalOpen.value = true;
}

function onRowClick(paymentLink: IPaymentLinkItem) {
    selectedPaymentLink.value = paymentLink;

    if (props.onRecordSelection) {
        props.onRecordSelection({ id: paymentLink.paymentLinkId, showModal: showDetailsModal });
    } else if (props.showDetails !== false) {
        showDetailsModal();
    }
}

function closeDetailsModal() {
    isDetailsModalOpen.value = false;
    selectedPaymentLink.value = null;
    if (hasDetailsToRefresh.value) {
        refreshPaymentLinkList();
        hasDetailsToRefresh.value = false;
    }
}

function onPaymentLinkUpdate() {
    hasDetailsToRefresh.value = true;
}

// ── Creation / settings modals ──
const isModalVisible = ref(false);
const modalType = ref<PaymentLinksOverviewModalType | undefined>(undefined);
const hasToRefresh = ref(false);

function openPaymentLinkModal() {
    modalType.value = 'Creation';
    isModalVisible.value = true;
}

function openSettingsModal() {
    modalType.value = 'Settings';
    isModalVisible.value = true;
}

function onCloseModal() {
    isModalVisible.value = false;
    if (hasToRefresh.value) {
        refreshPaymentLinkList();
        hasToRefresh.value = false;
    }
}

function refreshPaymentLinkList() {
    const now = new Date();
    const createdUntilDate = filtersValue.value.createdUntil ? new Date(filtersValue.value.createdUntil) : null;

    if (createdUntilDate?.toDateString() === now.toDateString()) {
        filtersValue.value = {
            ...filtersValue.value,
            createdUntil: now.toISOString(),
        };
    }

    lastRefreshTimestamp.value = performance.now();
}

function onPaymentLinkCreated(paymentLink: any) {
    props.paymentLinkCreation?.onPaymentLinkCreated?.(paymentLink);
    hasToRefresh.value = true;
}

const hasActionButtons = computed(() => !!(config.endpoints?.savePayByLinkSettings || config.endpoints?.createPBLPaymentLink));
</script>

<template>
    <div :class="[styles.root, isMobile ? styles.rootXs : '']">
        <div :class="styles.header">
            <BentoTypography v-if="!props.hideTitle" variant="title">
                {{ i18n.get('payByLink.overview.title') }}
            </BentoTypography>
            <div v-else />
            <div v-if="hasActionButtons" :class="styles.actionsContainer">
                <BentoButton v-if="!isMobile && config.endpoints?.createPBLPaymentLink" variant="primary" @click="openPaymentLinkModal">
                    {{ i18n.get('payByLink.overview.list.actions.createPaymentLink') }}
                </BentoButton>
                <BentoButton
                    v-if="!isMobile && config.endpoints?.savePayByLinkSettings"
                    variant="secondary"
                    :class="styles.settingsButton"
                    :aria-label="i18n.get('payByLink.overview.actions.settings.a11y.label')"
                    @click="openSettingsModal"
                >
                    <SettingsIcon />
                </BentoButton>
                <BentoButton
                    v-if="isMobile && config.endpoints?.createPBLPaymentLink"
                    variant="primary"
                    condensed
                    :class="styles.actionButtonXs"
                    :aria-label="i18n.get('payByLink.overview.list.actions.createPaymentLink')"
                    @click="openPaymentLinkModal"
                >
                    <PlusIcon />
                </BentoButton>
                <BentoButton
                    v-if="isMobile && config.endpoints?.savePayByLinkSettings"
                    variant="secondary"
                    condensed
                    :class="styles.actionButtonXs"
                    :aria-label="i18n.get('payByLink.overview.actions.settings.a11y.label')"
                    @click="openSettingsModal"
                >
                    <SettingsIcon />
                </BentoButton>
            </div>
        </div>

        <div :class="styles.tabsContainer">
            <BentoTabs
                :aria-label="i18n.get('payByLink.overview.list.filters.types.statusGroup')"
                :active-tab-index="activeStatusGroupTabIndex"
                @update:active-tab-index="onStatusGroupChange"
            >
                <BentoTab v-for="tab in PAYMENT_LINK_STATUS_GROUPS_TABS" :key="tab.id" :title="i18n.get(tab.label)" />
            </BentoTabs>
        </div>

        <div :class="styles.filtersContainer">
            <PaymentLinksFilters
                :stores="props.stores"
                :store-error="props.storeError"
                :filter-error="props.filterOptionsError"
                :available-link-types="props.filterOptions?.linkTypes"
                :available-statuses="props.filterOptions?.statuses"
                :status-group="statusGroup"
                :on-change="onFiltersChange"
            />
        </div>

        <BentoAlert
            v-if="showFiltersAlert && !filtersAlertDismissed"
            :class="styles.filtersAlertContainer"
            type="critical"
            variant="tip"
            close-button
            @close-alert="closeFiltersAlert"
        >
            <template #description>
                {{ i18n.get('payByLink.overview.filters.errors.networkError') }}
            </template>
        </BentoAlert>

        <PaymentLinksTable
            :error="paymentLinksError"
            :loading="statusGroupFetchPending || paymentLinksListResult.fetching.value || props.isFiltersLoading"
            :on-contact-support="props.onContactSupport"
            :on-row-click="onRowClick"
            :show-pagination="true"
            :payment-links="paymentLinksListResult.records.value"
            :has-multiple-stores="hasMultipleStores"
            :has-next="paymentLinksListResult.hasNext.value"
            :has-previous="paymentLinksListResult.hasPrevious.value"
            :go-to-next-page="paymentLinksListResult.goToNextPage"
            :go-to-previous-page="paymentLinksListResult.goToPreviousPage"
            :limit="paymentLinksListResult.limit.value"
            :limit-options="paymentLinksListResult.limitOptions.value"
            :update-limit="paymentLinksListResult.updateLimit"
            :current-page="paymentLinksListResult.page.value + 1"
        />

        <BentoModal
            :is-open="isDetailsModalOpen"
            size="large"
            :is-dismissible="true"
            :aria-label="i18n.get('payByLink.details.title')"
            @close-modal="closeDetailsModal"
        >
            <template #content>
                <PaymentLinkDetails
                    v-if="selectedPaymentLink"
                    :id="selectedPaymentLink.paymentLinkId"
                    hide-title
                    :on-contact-support="props.onContactSupport"
                    :on-dismiss="closeDetailsModal"
                    :on-update="onPaymentLinkUpdate"
                    is-dismiss-button-hidden
                />
            </template>
        </BentoModal>

        <BentoModal
            :is-open="isModalVisible"
            size="large"
            :is-dismissible="true"
            :aria-label="i18n.get('payByLink.overview.title')"
            @close-modal="onCloseModal"
        >
            <template #content>
                <PaymentLinkCreation
                    v-if="modalType === 'Creation'"
                    :fields-config="props.paymentLinkCreation?.fieldsConfig"
                    :store-ids="props.storeIds"
                    :on-payment-link-created="onPaymentLinkCreated"
                    :on-creation-dismiss="props.paymentLinkCreation?.onCreationDismiss"
                    :on-contact-support="props.onContactSupport"
                    embedded-in-overview
                />
                <PaymentLinkSettings
                    v-else-if="modalType === 'Settings'"
                    v-bind="props.paymentLinkSettings"
                    :store-ids="props.storeIds"
                    :on-contact-support="props.onContactSupport"
                    embedded-in-overview
                />
            </template>
        </BentoModal>
    </div>
</template>
