// src/components/external/PaymentLinksOverview/components/PaymentLinkOverviewModal.tsx
import useCoreContext from '../../../../core/Context/useCoreContext';
import { useCallback, useEffect, useState } from 'preact/hooks';
import { popoverUtil } from '../../../internal/Popover/utils/popoverUtil';
import Modal from '../../../internal/Modal';
import { PaymentLinkOverviewModalType } from './types';
import PaymentLinkCreationContainer from '../../PaymentLinkCreation/components/PaymentLinkCreationContainer/PaymentLinkCreationContainer';
import PaymentLinkSettingsContainer from '../../PaymentLinkSettings/components/PaymentLinkSettingsContainer/PaymentLinkSettingsContainer';
import { PaymentLinkOverviewComponentProps } from '../../../types';
import { StoreIds } from '../types';
import { PaymentLinkCreationFormValues } from '../../PaymentLinkCreation/components/types';

export interface PaymentLinkOverviewModalProps {
    isModalVisible: boolean;
    onCloseModal: () => void;
    onContactSupport?: () => void;
    modalType?: PaymentLinkOverviewModalType;
    paymentLinkCreation: PaymentLinkOverviewComponentProps['paymentLinkCreation'];
    paymentLinkSettings: PaymentLinkOverviewComponentProps['paymentLinkSettings'];
    storeIds?: StoreIds;
    refreshPaymentLinkList?: () => void;
}

export const PaymentLinkOverviewModal = ({
    isModalVisible,
    onCloseModal,
    modalType,
    paymentLinkCreation,
    paymentLinkSettings,
    storeIds,
    onContactSupport,
    refreshPaymentLinkList,
}: PaymentLinkOverviewModalProps) => {
    const { i18n } = useCoreContext();
    const [hasToRefresh, setHasToRefresh] = useState(false);

    const onCloseCallback = useCallback(() => {
        onCloseModal();
        if (hasToRefresh) {
            refreshPaymentLinkList?.();
            setHasToRefresh(false);
        }
    }, [onCloseModal, hasToRefresh, refreshPaymentLinkList]);

    useEffect(() => {
        if (isModalVisible) {
            popoverUtil.closeAll();
        }
    }, [isModalVisible]);

    const onPaymentLinkCreated = useCallback(
        (paymentLink: PaymentLinkCreationFormValues) => {
            paymentLinkCreation?.onPaymentLinkCreated?.(paymentLink);
            setHasToRefresh(true);
        },
        [paymentLinkCreation]
    );

    if (!isModalVisible || !modalType) return null;

    return (
        <div>
            <Modal
                isOpen={isModalVisible}
                aria-label={i18n.get('payByLink.overview.title')}
                onClose={onCloseCallback}
                isDismissible={true}
                headerWithBorder={false}
                size={'large'}
            >
                {modalType === 'Creation' ? (
                    <PaymentLinkCreationContainer
                        {...paymentLinkCreation}
                        onPaymentLinkCreated={onPaymentLinkCreated}
                        storeIds={storeIds}
                        onContactSupport={onContactSupport}
                        embeddedInOverview
                    />
                ) : null}
                {modalType === 'Settings' ? (
                    <PaymentLinkSettingsContainer
                        {...paymentLinkSettings}
                        storeIds={storeIds}
                        onContactSupport={onContactSupport}
                        embeddedInOverview
                    />
                ) : null}
            </Modal>
        </div>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinksOverview/components/PaymentLinkOverviewModal.vue
<script setup lang="ts">
import { defineAsyncComponent } from 'vue';
import { BentoLoadingIndicator, BentoModal } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import type { PaymentLinkCreationFormValues, PaymentLinksOverviewModalType } from '@integration-components/payByLink/domain';
import type { PaymentLinksOverviewExternalProps } from '../types';

const props = defineProps<{
    modalType: PaymentLinksOverviewModalType;
    storeIds?: PaymentLinksOverviewExternalProps['storeIds'];
    paymentLinkCreation?: PaymentLinksOverviewExternalProps['paymentLinkCreation'];
    paymentLinkSettings?: PaymentLinksOverviewExternalProps['paymentLinkSettings'];
    onPaymentLinkCreated: (paymentLink: PaymentLinkCreationFormValues) => void;
    onContactSupport?: () => void;
    onClose: () => void;
}>();

const { i18n } = useCoreContext();
const PaymentLinkCreation = defineAsyncComponent({
    loader: () => import('../../PaymentLinkCreation/components/PaymentLinkCreationContainer/PaymentLinkCreationContainer.vue'),
    loadingComponent: BentoLoadingIndicator,
    delay: 0,
});
const PaymentLinkSettings = defineAsyncComponent({
    loader: () => import('../../PaymentLinkSettings/components/PaymentLinkSettingsContainer.vue'),
    loadingComponent: BentoLoadingIndicator,
    delay: 0,
});
</script>

<template>
    <BentoModal :is-open="true" size="large" :is-dismissible="true" :aria-label="i18n.get('payByLink.overview.title')" @close-modal="props.onClose">
        <template #content>
            <PaymentLinkCreation
                v-if="props.modalType === 'Creation'"
                :fields-config="props.paymentLinkCreation?.fieldsConfig"
                :store-ids="props.storeIds"
                :on-payment-link-created="props.onPaymentLinkCreated"
                :on-dismiss="props.paymentLinkCreation?.onDismiss"
                :on-contact-support="props.onContactSupport"
                embedded-in-overview
            />
            <PaymentLinkSettings
                v-else
                v-bind="props.paymentLinkSettings"
                :store-ids="props.storeIds"
                :on-contact-support="props.onContactSupport"
                embedded-in-overview
            />
        </template>
    </BentoModal>
</template>
