// src/core/Context/preact/CoreProvider.tsx
import { toChildArray } from 'preact';
import { useEffect, useMemo } from 'preact/hooks';
import { CoreContext } from '../CoreContext';
import { CoreProviderProps } from '../types';
import useBooleanState from '../../../hooks/useBooleanState';
import { waitForI18n, createCoreContextValue } from '../setupCore';

const CoreProvider = (props: CoreProviderProps) => {
    const { children } = props;
    const [ready, setReady] = useBooleanState(false);

    useEffect(() => {
        waitForI18n(props.i18n)
            .then(() => setReady(true));
    }, [props.i18n]);

    const coreContextValues = useMemo(
        () => createCoreContextValue(props),
        [
            props.commonProps,
            props.componentRef,
            props.externalErrorHandler,
            props.i18n,
            props.loadingContext,
            props.getImageAsset,
            props.getDatasetAsset,
            props.getCdnConfig,
            props.getCdnDataset,
            props.updateCore,
        ]
    );

    if (!ready) return null;

    return <CoreContext.Provider value={coreContextValues}>{toChildArray(children)}</CoreContext.Provider>;
};

export default CoreProvider;

// packages/shared/core/src/vue/Context/CoreProvider.vue
<script setup lang="ts">
import { provide, ref, computed, onMounted } from 'vue';
import type { CoreProviderProps, CoreContextValue } from './types';
import Localization from '../../Localization';
import { CORE_CONTEXT_KEY } from './constants';

const props = withDefaults(defineProps<CoreProviderProps>(), {
    loadingContext: '',
});

const ready = ref(false);

const coreContextValue = computed<CoreContextValue>(() => ({
    i18n: props.i18n ?? new Localization().i18n,
    commonProps: props.commonProps || {},
    loadingContext: props.loadingContext ?? '',
    updateCore: props.updateCore,
    externalErrorHandler: props.externalErrorHandler,
    getImageAsset: props.getImageAsset,
    getDatasetAsset: props.getDatasetAsset,
    getCdnConfig: props.getCdnConfig,
    getCdnDataset: props.getCdnDataset,
}));

provide(CORE_CONTEXT_KEY, coreContextValue.value);

onMounted(async () => {
    await coreContextValue.value.i18n?.ready;
    ready.value = true;
});
</script>

<template>
    <slot v-if="ready" />
</template>
