// src/core/Context/CoreProvider.tsx
import { toChildArray } from 'preact';
import { useEffect, useMemo } from 'preact/hooks';
import { CoreContext } from './CoreContext';
import { CoreProviderProps } from './types';
import useBooleanState from '../../hooks/useBooleanState';
import Localization from '../Localization';

/**
 * CoreProvider Component
 * Wraps a component delaying the render until after the i18n module is fully loaded
 */
const CoreProvider = ({
    i18n = new Localization().i18n,
    children,
    commonProps: _commonProps,
    loadingContext: _loadingContext,
    updateCore,
    externalErrorHandler,
    componentRef,
    getImageAsset,
    getDatasetAsset,
    getCdnDataset,
    getCdnConfig,
    environment,
}: CoreProviderProps) => {
    const [ready, setReady] = useBooleanState(false);
    const commonProps = useMemo(() => _commonProps || {}, [_commonProps]);
    const loadingContext = useMemo(() => _loadingContext ?? '', [_loadingContext]);

    useEffect(() => {
        (async () => {
            await i18n?.ready;
            setReady(true);
        })().catch();
    }, []);

    const coreContextValues = useMemo(
        () => ({
            i18n,
            commonProps,
            loadingContext,
            updateCore,
            externalErrorHandler,
            componentRef,
            getImageAsset,
            getDatasetAsset,
            getCdnConfig,
            getCdnDataset,
            environment,
        }),
        [
            commonProps,
            componentRef,
            externalErrorHandler,
            i18n,
            loadingContext,
            getImageAsset,
            getDatasetAsset,
            getCdnConfig,
            getCdnDataset,
            updateCore,
            environment,
        ]
    );

    if (!ready) return null;

    return <CoreContext.Provider value={coreContextValues}>{toChildArray(children)}</CoreContext.Provider>;
};

export default CoreProvider;

// packages/shared/core/src/vue/Context/CoreProvider.vue
<script setup lang="ts">
import { provide, ref, computed, onMounted } from 'vue';
import type { CoreProviderProps, CoreContextValue } from './types';
import Localization from '../../Localization';
import { CORE_CONTEXT_KEY } from './constants';

const props = withDefaults(defineProps<CoreProviderProps>(), {
    loadingContext: '',
});

const ready = ref(false);

const coreContextValue = computed<CoreContextValue>(() => ({
    i18n: props.i18n ?? new Localization().i18n,
    commonProps: props.commonProps || {},
    loadingContext: props.loadingContext ?? '',
    updateCore: props.updateCore,
    externalErrorHandler: props.externalErrorHandler,
    getImageAsset: props.getImageAsset,
    getDatasetAsset: props.getDatasetAsset,
    getCdnConfig: props.getCdnConfig,
    getCdnDataset: props.getCdnDataset,
}));

provide(CORE_CONTEXT_KEY, coreContextValue.value);

onMounted(async () => {
    await coreContextValue.value.i18n?.ready;
    ready.value = true;
});
</script>

<template>
    <slot v-if="ready" />
</template>
