// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/TermsAndConditionsContainer.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { TranslationKey } from '@integration-components/core';
import type { IPaymentLinkTermsAndConditions } from '@integration-components/types';
import { usePaymentLinkSettingsContext } from '../composables/context';
import { isTermsAndConditionsData } from '../utils/typeGuards';
import LoadingSkeleton from './LoadingSkeleton.vue';
import SettingsError from './SettingsError.vue';
import TermsAndConditions from './TermsAndConditions.vue';

const ERROR_MESSAGE_KEY: TranslationKey = 'payByLink.settings.termsAndConditions.errors.couldNotLoad';

const { savedData: termsAndConditionsData, termsAndConditionsError } = usePaymentLinkSettingsContext();

const initialData = computed<IPaymentLinkTermsAndConditions>(() =>
    isTermsAndConditionsData(termsAndConditionsData.value) ? termsAndConditionsData.value : { termsOfServiceUrl: '' }
);
</script>

<template>
    <SettingsError v-if="termsAndConditionsError" :error="termsAndConditionsError" :error-message="ERROR_MESSAGE_KEY" />
    <LoadingSkeleton v-else-if="!isTermsAndConditionsData(termsAndConditionsData)" :row-number="2" />
    <TermsAndConditions v-else :data="termsAndConditionsData" :initial-data="initialData" />
</template>

// src/components/external/PaymentLinkSettings/components/TermsAndConditions/TermsAndConditionsContainer.tsx
import './TermsAndConditions.scss';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import { TermsAndConditions } from './TermsAndConditions';
import usePaymentLinkSettingsContext from '../PaymentLinkSettingsContainer/context/context';
import { useState, useEffect } from 'preact/hooks';
import { IPaymentLinkTermsAndConditions } from '../../../../../types';
import cx from 'classnames';
import { isTermsAndConditionsData } from '../PaymentLinkThemeContainer/types';
import SettingsError from '../PaymentLinkSettingsContainer/components/SettingsError/SettingsError';
import LoadingSkeleton from '../PaymentLinkSettingsContainer/components/LoadingSkeleton/LoadingSkeleton';

const ERROR_MESSAGE_KEY = 'payByLink.settings.termsAndConditions.errors.couldNotLoad';

const TermsAndConditionsContainer = () => {
    const { i18n } = useCoreContext();
    const { savedData: termsAndConditionsData, isLoadingContent, termsAndConditionsError, isShowingRequirements } = usePaymentLinkSettingsContext();
    const [initialData, setInitialData] = useState<IPaymentLinkTermsAndConditions>();

    useEffect(() => {
        if (!isLoadingContent && !termsAndConditionsError) {
            const data =
                termsAndConditionsData && typeof termsAndConditionsData === 'object' && Object.keys(termsAndConditionsData).length > 0
                    ? (termsAndConditionsData as IPaymentLinkTermsAndConditions)
                    : { termsOfServiceUrl: '' };
            setInitialData(data);
        }
    }, [termsAndConditionsData, setInitialData, isLoadingContent, termsAndConditionsError]);

    if (termsAndConditionsError) {
        return <SettingsError error={termsAndConditionsError} errorMessage={ERROR_MESSAGE_KEY} />;
    }

    if (!isTermsAndConditionsData(termsAndConditionsData) || !initialData) {
        return <LoadingSkeleton rowNumber={2} />;
    }

    return (
        <section className="adyen-pe-payment-link-settings-terms-and-conditions">
            <div
                className={cx('adyen-pe-payment-link-settings-terms-and-conditions__content-header', {
                    'adyen-pe-payment-link-settings-terms-and-conditions__content-header--hidden': isShowingRequirements,
                })}
            >
                <div className="adyen-pe-payment-link-settings-terms-and-conditions__content-header">
                    <Typography variant={TypographyVariant.TITLE} medium>
                        {i18n.get('payByLink.settings.termsAndConditions.title')}
                    </Typography>
                    <Typography variant={TypographyVariant.BODY} wide className="adyen-pe-payment-link-settings-terms-and-conditions-disclaimer">
                        {i18n.get('payByLink.settings.termsAndConditions.subtitle')}
                    </Typography>
                </div>
            </div>
            <TermsAndConditions data={termsAndConditionsData} initialData={initialData} />
        </section>
    );
};

export default TermsAndConditionsContainer;
