// src/components/external/PaymentLinkCreation/components/Form/StoreForm/StoreForm.tsx
import useCoreContext from '../../../../../../core/Context/useCoreContext';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';
import StoreField from './Fields/StoreField';

import { StateUpdater, useMemo } from 'preact/hooks';
import { useConfigContext } from '../../../../../../core/ConfigContext';
import { PaymentLinkCreationFormValues } from '../../types';
import { useWizardFormContext } from '../../../../../../hooks/form/wizard/WizardFormContext';
import { IPaymentLinkSettings, IPaymentLinkStore } from '../../../../../../types';
import { Dispatch } from 'preact/compat';
import { StoreIds } from '../../../../PaymentLinksOverview/types';
import './StoreForm.scss';

interface StoreFormProps {
    setShowTermsAndConditions: Dispatch<StateUpdater<boolean>>;
    storeIds?: StoreIds;
    settingsData?: IPaymentLinkSettings;
    storesData?: IPaymentLinkStore[];
    selectItems: { id: string; name: string }[];
    termsAndConditionsProvisioned: boolean;
}

export const StoreForm = ({ setShowTermsAndConditions, settingsData, storesData, selectItems, termsAndConditionsProvisioned }: StoreFormProps) => {
    const { i18n } = useCoreContext();
    const { savePayByLinkSettings } = useConfigContext().endpoints;
    const { getValues } = useWizardFormContext<PaymentLinkCreationFormValues>();
    const canModifySettings = !!savePayByLinkSettings;

    const selectedStoreId = getValues('store');

    const alertLabel = useMemo(() => {
        if (!termsAndConditionsProvisioned) {
            if (canModifySettings) {
                return 'payByLink.creation.storeForm.alerts.tcSetupRequired';
            }
            return 'payByLink.creation.storeForm.alerts.tcSetupRequiredWithoutPermissions';
        }
    }, [termsAndConditionsProvisioned, canModifySettings]);

    const alertActions = useMemo(() => {
        if (!canModifySettings) {
            return [];
        }
        return [
            {
                label: i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredAction'),
                onClick: () => {
                    setShowTermsAndConditions(true);
                },
            },
        ];
    }, [canModifySettings, setShowTermsAndConditions, i18n]);

    return (
        <div className="adyen-pe-payment-link-creation-form__fields-container">
            <StoreField items={selectItems} />
            {settingsData && storesData && selectedStoreId && !termsAndConditionsProvisioned && (
                <Alert
                    className="adyen-pe-payment-link-creation-form__tc-alert"
                    title={i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredTitle')}
                    type={AlertTypeOption.WARNING}
                    description={alertLabel && i18n.get(alertLabel)}
                    actions={alertActions}
                />
            )}
        </div>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/Form/StoreForm/StoreForm.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoAlert, BentoButtonActions, type BentoButtonActionsList } from '@adyen/bento-vue3';
import { useWizard } from '../../../composables/wizardContext';
import StoreField from '../../fields/StoreField.vue';
import type { IPaymentLinkSettings, IPaymentLinkStore } from '@integration-components/types';
import type { DomainTranslationKey } from '@integration-components/core/vue';
import layoutStyles from '../FormLayout.module.scss';

const props = defineProps<{
    selectItems: { id: string; name: string; description?: string }[];
    settingsData?: IPaymentLinkSettings;
    storesData?: IPaymentLinkStore[];
    termsAndConditionsProvisioned: boolean;
    canModifySettings: boolean;
}>();

const emit = defineEmits<{
    setupTermsAndConditions: [];
}>();

const wizard = useWizard();
const { i18n } = wizard;

const selectedStoreId = computed(() => wizard.getValue('store'));
const showTcAlert = computed(() => !!props.settingsData && !!props.storesData && !!selectedStoreId.value && !props.termsAndConditionsProvisioned);
const alertDescriptionKey = computed<DomainTranslationKey>(() =>
    props.canModifySettings
        ? 'payByLink.creation.storeForm.alerts.tcSetupRequired'
        : 'payByLink.creation.storeForm.alerts.tcSetupRequiredWithoutPermissions'
);

function handleSetupTermsAndConditions() {
    emit('setupTermsAndConditions');
}

const actionButtons = computed<BentoButtonActionsList>(() => [
    {
        title: i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredAction'),
        event: handleSetupTermsAndConditions,
        variant: 'tertiary',
    },
]);
</script>

<template>
    <div :class="layoutStyles.fieldsContainer">
        <StoreField
            name="store"
            :label="i18n.get('payByLink.creation.fields.store.label')"
            :items="props.selectItems"
            :placeholder="i18n.get('payByLink.creation.inputs.select.placeholder')"
        />
        <BentoAlert v-if="showTcAlert" type="warning" role="alert">
            {{ i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredTitle') }}
            <template #description>
                {{ i18n.get(alertDescriptionKey) }}
            </template>
            <template v-if="props.canModifySettings" #actions>
                <BentoButtonActions layout="buttons-start" :actions="actionButtons" />
            </template>
        </BentoAlert>
    </div>
</template>
