// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/Form/CustomerDetailsForm/fields/ShopperPhoneField.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { BentoDropdown, BentoInputField } from '@adyen/bento-vue3';
import FieldWrapper from '../../../fields/FieldWrapper.vue';
import { useCoreContext } from '@integration-components/core/vue';
import { useWizard } from '../../../../composables/wizardContext';
import { PAYMENT_LINK_CREATION_FIELD_LENGTHS } from '../../../../../../../domain/src';
import './ShopperPhoneField.scss';

const wizard = useWizard();
const { i18n, getCdnDataset } = useCoreContext();

const config = computed(() => wizard.getFieldConfig('telephoneNumber'));
const error = computed(() => wizard.getError('telephoneNumber'));

const phones = ref<Array<{ id: string; prefix: string }>>([]);
const isFetching = ref(true);

onMounted(async () => {
    try {
        if (getCdnDataset) {
            phones.value =
                (await getCdnDataset<Array<{ id: string; prefix: string }>>({ name: 'phonenumbers', extension: 'json', fallback: [] })) ?? [];
        }
    } finally {
        isFetching.value = false;
    }
});

const displayValue = computed(() => wizard.displayValues.value['telephoneNumber'] ?? '');
const currentValue = computed(() => (wizard.values.value['telephoneNumber'] as string | undefined) ?? '');

// Prefix and number are stored joined in the value (`+343002119220`) and separated by a space in the display value (`+34 3002119220`).
const parsedPhone = computed<readonly [string, string]>(() => {
    const source = displayValue.value || currentValue.value;
    if (!source) return ['', ''];
    const [code, ...rest] = source.split(' ');
    return [code ?? '', rest.join(' ')];
});

const phoneCode = computed(() => parsedPhone.value[0]);
const phoneNumber = computed(() => parsedPhone.value[1]);

// Seed the space-separated display value from a prefilled default value on first render.
watch(
    [displayValue, currentValue],
    ([display, current]) => {
        if (!display && current) {
            const [code, ...rest] = current.split(' ');
            const number = rest.join(' ');
            wizard.setValue('telephoneNumber', `${code}${number}`, `${code} ${number}`);
        }
    },
    { immediate: true }
);

// `id` (country code) is unique per entry, unlike `prefix` which several countries share (e.g. +61).
const phoneItems = computed(() => {
    return phones.value.map(({ id, prefix }) => ({ label: `${id} (${prefix})`, value: id })).sort((a, b) => a.label.localeCompare(b.label));
});

// Only the prefix is persisted in the field value, so when several countries share the same
// prefix (e.g. +1 for the US and Canada) we remember the explicitly selected country id instead
// of re-deriving it from the prefix, which would always resolve to the same (first-matching) country.
const selectedCountryId = ref('');

watch(
    [phones, phoneCode],
    ([phoneList, code]) => {
        if (!phoneList.length || !code) {
            selectedCountryId.value = '';
            return;
        }
        const current = phoneList.find(p => p.id === selectedCountryId.value);
        if (current?.prefix !== code) {
            selectedCountryId.value = phoneList.find(p => p.prefix === code)?.id ?? '';
        }
    },
    { immediate: true }
);

const shouldHide = computed(
    () => !isFetching.value && phones.value.length === 0 && !config.value.required && !displayValue.value && !currentValue.value
);

function onPrefixUpdate(value: string | number | { value?: string | number } | Array<unknown> | undefined) {
    if (Array.isArray(value)) return;
    const next = typeof value === 'object' && value !== null ? value.value : value;
    const countryId = next === undefined ? '' : String(next);
    selectedCountryId.value = countryId;
    const code = phones.value.find(p => p.id === countryId)?.prefix ?? '';
    const number = phoneNumber.value;
    wizard.setValue('telephoneNumber', `${code}${number}`, `${code} ${number}`);
}

function onNumberInput(value: string | number) {
    const number = String(value);
    const code = phoneCode.value;
    wizard.setValue('telephoneNumber', `${code}${number}`, `${code} ${number}`);
}
</script>

<template>
    <FieldWrapper v-if="config.visible && !shouldHide" name="telephoneNumber" :error="error">
        <div class="adyen-pe-payment-link-creation-form__phone-container">
            <BentoDropdown
                class="adyen-pe-payment-link-creation-form__phone-prefix"
                :items="phoneItems"
                :label="i18n.get('payByLink.creation.fields.shopperPhone.label')"
                :placeholder="i18n.get('payByLink.creation.fields.shopperPhone.phonePrefix.placeholder')"
                :model-value="selectedCountryId"
                dynamic-filtering
                :optional="!config.required"
                :readonly="isFetching || config.readOnly"
                :error="!!error"
                @update:model-value="onPrefixUpdate"
            />
            <BentoInputField
                class="adyen-pe-payment-link-creation-form__phone-number"
                label=" "
                type="text"
                :model-value="phoneNumber"
                :maxlength="PAYMENT_LINK_CREATION_FIELD_LENGTHS.telephoneNumber.max"
                :readonly="config.readOnly"
                :error="!!error"
                @input="onNumberInput"
            />
        </div>
    </FieldWrapper>
</template>

// src/components/external/PaymentLinkCreation/components/Form/CustomerDetailsForm/Fields/ShopperPhoneField.tsx
import { useCallback, useEffect, useMemo } from 'preact/hooks';
import { Controller } from '../../../../../../../hooks/form';
import { PaymentLinkCreationFormValues } from '../../../types';
import { useWizardFormContext } from '../../../../../../../hooks/form/wizard/WizardFormContext';
import { useFetch } from '../../../../../../../hooks/useFetch';
import { VisibleField } from '@integration-components/ui-components-preact/FormWrappers/VisibleField';
import InputBase from '@integration-components/ui-components-preact/FormFields/InputBase';
import FormField from '@integration-components/ui-components-preact/FormWrappers/FormField';
import useCoreContext from '../../../../../../../core/Context/useCoreContext';
import { PAYMENT_LINK_CREATION_FIELD_LENGTHS } from '../../../../constants';
import { filterDisallowedCharacters } from '@integration-components/ui-components-preact/FormFields/utils';
import { JSX } from 'preact/jsx-runtime';

export const ShopperPhoneField = () => {
    const { i18n, getCdnDataset } = useCoreContext();
    const { control, fieldsConfig, getValues, setValue, setFieldDisplayValue, getDisplayValue, trigger, formState } =
        useWizardFormContext<PaymentLinkCreationFormValues>();

    const displayValue = useMemo(() => getDisplayValue('telephoneNumber'), [getDisplayValue]);
    const currentValue = useMemo(() => getValues('telephoneNumber'), [getValues]);

    const [phoneCode, phoneNumberWithoutPhoneCode] = useMemo(() => {
        if (displayValue) {
            const [code, ...rest] = displayValue.split(' ');
            return [code, rest.join(' ')] as const;
        }
        if (currentValue) {
            const [code, ...rest] = currentValue.split(' ');
            return [code, rest.join(' ')] as const;
        }
        return [undefined, undefined] as const;
    }, [displayValue, currentValue]);

    // Initialize display value from default value on first render
    useEffect(() => {
        if (!displayValue && currentValue) {
            const [code, ...rest] = currentValue.split(' ');
            const number = rest.join(' ');
            setValue('telephoneNumber', `${code}${number}`);
            setFieldDisplayValue('telephoneNumber', `${code} ${number}`);
        }
    }, [displayValue, currentValue, setValue, setFieldDisplayValue]);

    const phonesDatasetQuery = useFetch({
        fetchOptions: { enabled: true },
        queryFn: useCallback(async () => {
            if (getCdnDataset) {
                return (
                    (await getCdnDataset<Array<{ id: string; prefix: string }>>({
                        name: 'phonenumbers',
                        extension: 'json',
                        fallback: [] as Array<{ id: string; prefix: string }>,
                    })) ?? []
                );
            }
            return [] as Array<{ id: string; prefix: string }>;
        }, [getCdnDataset]),
    });

    const phoneCodesDropdown = useMemo(() => {
        const phones = phonesDatasetQuery.data ?? [];
        return phones.map(({ id, prefix }) => ({ id: prefix, name: `${id} (${prefix})` })).sort(({ name: a }, { name: b }) => a.localeCompare(b));
    }, [phonesDatasetQuery.data]);

    // We use some state variables for validation, so it has to happen in an effect to get accurate values
    useEffect(() => {
        if (phoneCode && formState.touchedFields['telephoneNumber'] && formState.errors['telephoneNumber']) {
            trigger('telephoneNumber');
        }
    }, [phoneCode, phoneNumberWithoutPhoneCode, trigger, formState.errors, formState.touchedFields]);

    const isRequired = useMemo(() => fieldsConfig['telephoneNumber']?.required, [fieldsConfig]);
    const isReadOnly = useMemo(() => fieldsConfig['telephoneNumber']?.readOnly, [fieldsConfig]);

    const shouldHideField = useMemo(() => {
        const hasDataset = (phonesDatasetQuery.data?.length ?? 0) > 0;
        const hasValue = !!displayValue || !!currentValue;

        return !phonesDatasetQuery.isFetching && !hasDataset && !isRequired && !hasValue;
    }, [phonesDatasetQuery.data?.length, phonesDatasetQuery.isFetching, isRequired, displayValue, currentValue]);

    const validate = useCallback(() => {
        if (!isRequired && !phoneCode && !phoneNumberWithoutPhoneCode) return { valid: true };
        if (!phoneCode) {
            return { valid: false, message: i18n.get('payByLink.creation.fields.phoneNumber.errors.requiredPhoneCode') };
        }
        if (!phoneNumberWithoutPhoneCode) {
            return { valid: false, message: i18n.get('payByLink.creation.fields.phoneNumber.errors.requiredPhoneNumber') };
        }
        return { valid: true };
    }, [phoneCode, phoneNumberWithoutPhoneCode, i18n, isRequired]);

    if (shouldHideField) return null;

    return (
        <VisibleField<PaymentLinkCreationFormValues> name="telephoneNumber">
            <FormField label={i18n.get('payByLink.creation.fields.shopperPhone.label')} optional={!isRequired} testId="form-field-telephoneNumber">
                <Controller<PaymentLinkCreationFormValues>
                    name="telephoneNumber"
                    control={control}
                    rules={{
                        required: isRequired,
                        validate,
                    }}
                    render={({ field, fieldState }) => {
                        const isInvalid = !!fieldState.error && fieldState.isTouched;
                        return (
                            <InputBase
                                {...field}
                                onKeyDown={e => {
                                    filterDisallowedCharacters({
                                        event: e as JSX.TargetedKeyboardEvent<HTMLInputElement>,
                                        inputType: 'number',
                                    });
                                }}
                                onInput={e => {
                                    const numberValue = (e.target as HTMLInputElement).value;
                                    setValue('telephoneNumber', `${phoneCode ?? ''}${numberValue}`);
                                    setFieldDisplayValue('telephoneNumber', `${phoneCode ?? ''} ${numberValue}`);
                                }}
                                value={phoneNumberWithoutPhoneCode}
                                type="text"
                                dropdown={{
                                    filterable: true,
                                    items: phoneCodesDropdown,
                                    value: phoneCode,
                                    placeholder: i18n.get('payByLink.creation.fields.shopperPhone.phonePrefix.placeholder'),
                                    readonly: phonesDatasetQuery.isFetching || isReadOnly,
                                }}
                                onDropdownInput={val => {
                                    const currentNumber = phoneNumberWithoutPhoneCode || '';
                                    setValue('telephoneNumber', `${val}${currentNumber}`);
                                    setFieldDisplayValue('telephoneNumber', `${val} ${currentNumber}`);
                                }}
                                isValid={!fieldState.error && !!field.value}
                                isInvalid={isInvalid}
                                errorMessage={fieldState.error?.message}
                                errorTestId="field-error-telephoneNumber"
                                maxLength={PAYMENT_LINK_CREATION_FIELD_LENGTHS.telephoneNumber.max}
                                readonly={isReadOnly}
                            />
                        );
                    }}
                />
            </FormField>
        </VisibleField>
    );
};
