// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentDetails/PaymentDetails.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoTabs, BentoTab } from '@adyen/bento-vue3';
import PaymentDetailsStatusBox from './PaymentDetailsStatusBox.vue';
import PaymentDetailsProperties from './PaymentDetailsProperties.vue';
import PaymentDetailsSummary from './PaymentDetailsSummary.vue';
import PaymentDetailsTimeline from './PaymentDetailsTimeline.vue';
import PaymentRefundAlerts from './PaymentRefundAlerts.vue';
import PaymentDetailsActions from './PaymentDetailsActions.vue';
import {
    TX_DETAILS_TABS,
    TX_DATA_CLASS,
    TX_DATA_CONTAINER,
    TX_DATA_TABS,
    ActiveView,
    DetailsTab,
    RefundedState,
    REFUND_STATUSES,
} from '../../../../../domain/src';
import type { TransactionDetails, TransactionDetailsCustomization } from '../../../../../domain/src';
import { useTransaction } from '../../composables/useTransaction.js';
import './PaymentDetails.scss';

type TransactionNavigatorState = ReturnType<typeof useTransaction>['transactionNavigator']['value'];

const props = defineProps<{
    dataCustomization?: { details?: TransactionDetailsCustomization };
    extraFields: Record<string, any> | undefined;
    fullRefundFailed: boolean;
    fullRefundInProgress: boolean;
    refundAmounts: Readonly<Record<(typeof REFUND_STATUSES)[number], readonly number[] | undefined>>;
    refundAvailable: boolean;
    refundCurrency: string;
    refundDisabled: boolean;
    refundedAmount: number;
    refundedState: RefundedState;
    refundLocked: boolean;
    setActiveView: (view: ActiveView) => void;
    transaction: TransactionDetails;
    transactionNavigator: TransactionNavigatorState;
}>();

const { i18n } = useCoreContext();

const navigationTabs = computed(() =>
    TX_DETAILS_TABS.filter(({ id }) => {
        switch (id) {
            case DetailsTab.SUMMARY: {
                const { additions, deductions, originalAmount, amountBeforeDeductions, netAmount } = props.transaction;
                return (
                    (additions && additions.length > 0) ||
                    (deductions && deductions.length > 0) ||
                    (originalAmount && originalAmount.value !== amountBeforeDeductions.value) ||
                    netAmount.value !== amountBeforeDeductions.value
                );
            }
            case DetailsTab.TIMELINE:
                return props.transaction.events && props.transaction.events.length > 0;
            default:
                return true;
        }
    })
);

const activeTab = ref<DetailsTab | undefined>(navigationTabs.value[0]?.id);

const activeTabIndex = computed(() => {
    const idx = navigationTabs.value.findIndex(tab => tab.id === activeTab.value);
    return idx >= 0 ? idx : 0;
});

watch(navigationTabs, tabs => {
    if (!tabs.some(tab => tab.id === activeTab.value)) {
        activeTab.value = tabs[0]?.id;
    }
});

const onTabChange = (newIndex: number) => {
    activeTab.value = navigationTabs.value[newIndex]?.id;
};
</script>

<template>
    <div :class="TX_DATA_CLASS">
        <PaymentDetailsStatusBox :refunded-state="props.refundedState" :transaction="props.transaction" />

        <div :class="TX_DATA_CONTAINER">
            <BentoTabs
                :class="TX_DATA_TABS"
                v-if="navigationTabs.length > 1"
                :aria-label="i18n.get('transactions.details.viewSelect.a11y.label')"
                :activeTabIndex="activeTabIndex"
                @update:active-tab-index="onTabChange"
            >
                <BentoTab v-for="tab in navigationTabs" :key="tab.id" :title="i18n.get(tab.label)" />
            </BentoTabs>

            <PaymentDetailsSummary v-if="activeTab === DetailsTab.SUMMARY" :transaction="props.transaction" />
            <PaymentDetailsProperties
                v-else-if="activeTab === DetailsTab.DETAILS"
                :data-customization="props.dataCustomization"
                :extra-fields="props.extraFields"
                :transaction="props.transaction"
            />
            <PaymentDetailsTimeline v-else-if="activeTab === DetailsTab.TIMELINE" :transaction="props.transaction" />
        </div>

        <PaymentRefundAlerts
            :full-refund-failed="props.fullRefundFailed"
            :full-refund-in-progress="props.fullRefundInProgress"
            :refund-amounts="props.refundAmounts"
            :refund-currency="props.refundCurrency"
            :refunded-amount="props.refundedAmount"
            :refunded-state="props.refundedState"
            :refund-locked="props.refundLocked"
        />

        <PaymentDetailsActions
            :extra-fields="props.extraFields"
            :refund-available="props.refundAvailable"
            :refund-disabled="props.refundDisabled"
            :set-active-view="props.setActiveView"
            :transaction="props.transaction"
            :transaction-navigator="props.transactionNavigator"
        />
    </div>
</template>

// packages/domains/transactions/preact/src/TransactionDetails/components/PaymentDetails/PaymentDetails.tsx
import Tabs from '../../../../../../../../src/components/internal/Tabs/Tabs';
import PaymentRefundAlerts from './PaymentRefundAlerts';
import PaymentDetailsActions from './PaymentDetailsActions';
import PaymentDetailsProperties from './PaymentDetailsProperties';
import PaymentDetailsStatusBox from './PaymentDetailsStatusBox';
import { TransactionDataContentProps } from '../TransactionData/TransactionDataContent';
import PaymentDetailsSummary from './PaymentDetailsSummary';
import PaymentDetailsTimeline from './PaymentDetailsTimeline';
import { useCoreContext } from '@integration-components/core/preact';
import { ActiveView, DetailsTab, RefundedState, TransactionDetails, TransactionDetailsProps } from '../../types';
import { REFUND_STATUSES, TX_DATA_CLASS, TX_DATA_CONTAINER, TX_DETAILS_TABS } from '../../constants';
import { TabProps } from '../../../../../../../../src/components/internal/Tabs/types';
import { useEffect, useMemo, useState } from 'preact/hooks';

export interface PaymentDetailsProps {
    dataCustomization?: TransactionDetailsProps['dataCustomization'];
    extraFields: Record<string, any> | undefined;
    fullRefundFailed: boolean;
    fullRefundInProgress: boolean;
    refundAmounts: Readonly<Record<(typeof REFUND_STATUSES)[number], readonly number[] | undefined>>;
    refundAvailable: boolean;
    refundCurrency: string;
    refundDisabled: boolean;
    refundedAmount: number;
    refundedState: RefundedState;
    refundLocked: boolean;
    setActiveView: (activeView: ActiveView) => void;
    transaction: TransactionDetails;
    transactionNavigator: TransactionDataContentProps['transactionNavigator'];
}

const PaymentDetails = ({
    dataCustomization,
    extraFields,
    fullRefundFailed,
    fullRefundInProgress,
    refundAmounts,
    refundAvailable,
    refundCurrency,
    refundDisabled,
    refundedAmount,
    refundedState,
    refundLocked,
    setActiveView,
    transaction,
    transactionNavigator,
}: PaymentDetailsProps) => {
    const { i18n } = useCoreContext();
    const [activeTab, setActiveTab] = useState<DetailsTab>();

    const navigationTabs = useMemo(
        () =>
            TX_DETAILS_TABS.filter(({ id }) => {
                switch (id) {
                    case DetailsTab.SUMMARY: {
                        const { additions, deductions, originalAmount, amountBeforeDeductions, netAmount } = transaction;
                        return (
                            (additions && additions.length > 0) ||
                            (deductions && deductions.length > 0) ||
                            (originalAmount && originalAmount.value !== amountBeforeDeductions.value) ||
                            netAmount.value !== amountBeforeDeductions.value
                        );
                    }
                    case DetailsTab.TIMELINE:
                        return transaction.events && transaction.events.length > 0;
                    default:
                        return true;
                }
            }),
        [transaction]
    );

    const tabContent = useMemo(
        () => ({
            [DetailsTab.DETAILS]: (
                <PaymentDetailsProperties dataCustomization={dataCustomization} extraFields={extraFields} transaction={transaction} />
            ),
            [DetailsTab.SUMMARY]: <PaymentDetailsSummary transaction={transaction} />,
            [DetailsTab.TIMELINE]: <PaymentDetailsTimeline transaction={transaction} />,
        }),
        [dataCustomization, extraFields, transaction]
    );

    useEffect(() => setActiveTab(navigationTabs[0]?.id), [navigationTabs]);

    return (
        <div className={TX_DATA_CLASS}>
            <PaymentDetailsStatusBox refundedState={refundedState} transaction={transaction} />

            <div className={TX_DATA_CONTAINER}>
                {navigationTabs.length > 1 && (
                    <Tabs
                        aria-label={i18n.get('transactions.details.viewSelect.a11y.label')}
                        onChange={({ id }: TabProps<DetailsTab>) => setActiveTab(id)}
                        tabs={navigationTabs}
                        activeTab={activeTab}
                    />
                )}

                {activeTab && tabContent[activeTab]}
            </div>

            <PaymentRefundAlerts
                fullRefundFailed={fullRefundFailed}
                fullRefundInProgress={fullRefundInProgress}
                refundAmounts={refundAmounts}
                refundCurrency={refundCurrency}
                refundedAmount={refundedAmount}
                refundedState={refundedState}
                refundLocked={refundLocked}
            />

            <PaymentDetailsActions
                extraFields={extraFields}
                refundAvailable={refundAvailable}
                refundDisabled={refundDisabled}
                setActiveView={setActiveView}
                transaction={transaction}
                transactionNavigator={transactionNavigator}
            />
        </div>
    );
};

export default PaymentDetails;
