// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/Form/Summary/FormSummary.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoAlert, BentoDivider, BentoStructuredList, BentoStructuredListItem, BentoTag, BentoTypography } from '@adyen/bento-vue3';
import { useWizard } from '../../../composables/wizardContext';
import { PAYMENT_LINK_CREATION_SUMMARY_INVISIBLE_FIELDS } from '../../../../../../domain/src';
import type { FormFieldConfig } from '../../../../../../domain/src';
import type { TranslationKey } from '@integration-components/core';
import type { IPaymentLinkType } from '@integration-components/types';
import styles from './FormSummary.module.scss';

const props = defineProps<{
    selectItems: { id: string; name: string }[];
    countryDatasetData?: { id: string; name: string }[];
}>();

const wizard = useWizard();
const { i18n } = wizard;

const INVISIBLE = PAYMENT_LINK_CREATION_SUMMARY_INVISIBLE_FIELDS as string[];

interface SummaryRow {
    id: string;
    label: TranslationKey;
    rendered: string;
}

const stepFields = (id: string): FormFieldConfig[] => wizard.steps.value.find(step => step.id === id)?.fields ?? [];

function rawValue(name: string) {
    return wizard.values.value[name];
}
function displayValue(name: string) {
    return wizard.displayValues.value[name];
}

function renderValue(field: FormFieldConfig): string {
    const id = field.fieldName;
    const value = rawValue(id);
    const display = displayValue(id);

    switch (id) {
        case 'linkValidity.quantity': {
            const unit = rawValue('linkValidity.durationUnit');
            if (!value || !unit) return '';
            return i18n.get(`payByLink.creation.fields.validity.linkValidityUnit.${unit}` as TranslationKey, {
                values: { quantity: value },
                count: Number(value),
            });
        }
        case 'amount.value': {
            const currency = rawValue('amount.currency') as string | undefined;
            if (value === undefined || value === '' || !currency) return '';
            return i18n.amount(Number(value), currency);
        }
        case 'linkType':
            return value ? i18n.get(`payByLink.creation.form.linkTypes.${value as IPaymentLinkType}`) : '';
        case 'countryCode':
        case 'deliveryAddress.country':
        case 'billingAddress.country':
            return props.countryDatasetData?.find(country => country.id === value)?.name ?? display ?? `${value ?? ''}`;
        default:
            return display ?? (value === undefined || value === null ? '' : `${value}`);
    }
}

function toRows(fields: FormFieldConfig[]): SummaryRow[] {
    return fields
        .filter(field => field.visible && !INVISIBLE.includes(field.fieldName) && !!field.label)
        .map(field => ({ id: field.fieldName, label: field.label as TranslationKey, rendered: renderValue(field) }))
        .filter(row => row.rendered !== '');
}

const paymentRows = computed<SummaryRow[]>(() => {
    const storeValue = rawValue('store') as string | undefined;
    const storeRow: SummaryRow[] = storeValue
        ? [
              {
                  id: 'store',
                  label: 'payByLink.creation.summary.fields.store' as TranslationKey,
                  rendered: displayValue('store') ?? props.selectItems.find(item => item.id === storeValue)?.name ?? storeValue,
              },
          ]
        : [];
    return [...storeRow, ...toRows(stepFields('payment'))];
});

const customerFields = computed(() => stepFields('customer'));
const nonAddressRows = computed(() =>
    toRows(customerFields.value.filter(field => !field.fieldName.startsWith('deliveryAddress.') && !field.fieldName.startsWith('billingAddress.')))
);
const deliveryRows = computed(() => toRows(customerFields.value.filter(field => field.fieldName.startsWith('deliveryAddress.'))));
const billingRows = computed(() => toRows(customerFields.value.filter(field => field.fieldName.startsWith('billingAddress.'))));

const sendLink = computed(() => rawValue('sendLinkToShopper') === true);
const sendSuccess = computed(() => rawValue('sendSuccessEmailToShopper') === true);
const showEmailNotifications = computed(() => sendLink.value || sendSuccess.value);
</script>

<template>
    <section :class="styles.root">
        <section :class="styles.section">
            <BentoTypography variant="title" :class="styles.sectionTitle">
                {{ i18n.get('payByLink.creation.summary.paymentDetails') }}
            </BentoTypography>
            <BentoStructuredList layout="42-58">
                <BentoStructuredListItem v-for="row in paymentRows" :key="row.id" :label="i18n.get(row.label)">
                    <BentoTypography variant="body">{{ row.rendered }}</BentoTypography>
                </BentoStructuredListItem>
            </BentoStructuredList>
        </section>

        <template v-if="nonAddressRows.length">
            <BentoDivider />
            <section :class="styles.section">
                <BentoTypography variant="title" :class="styles.sectionTitle">
                    {{ i18n.get('payByLink.creation.summary.shopperInformation') }}
                </BentoTypography>
                <BentoStructuredList layout="42-58">
                    <BentoStructuredListItem v-for="row in nonAddressRows" :key="row.id" :label="i18n.get(row.label)">
                        <BentoTypography variant="body">{{ row.rendered }}</BentoTypography>
                    </BentoStructuredListItem>
                    <BentoStructuredListItem v-if="showEmailNotifications" :label="i18n.get('payByLink.creation.summary.fields.emailNotifications')">
                        <div :class="styles.tagsContainer">
                            <BentoTag v-if="sendLink">{{ i18n.get('payByLink.creation.summary.fields.emailNotifications.emailCreation') }}</BentoTag>
                            <BentoTag v-if="sendSuccess">{{
                                i18n.get('payByLink.creation.summary.fields.emailNotifications.paymentSuccess')
                            }}</BentoTag>
                        </div>
                    </BentoStructuredListItem>
                </BentoStructuredList>
            </section>
        </template>

        <section v-if="deliveryRows.length" :class="styles.section">
            <BentoTypography variant="body" stronger :class="styles.sectionTitle">
                {{ i18n.get('payByLink.creation.summary.deliveryAddress') }}
            </BentoTypography>
            <BentoStructuredList layout="42-58">
                <BentoStructuredListItem v-for="row in deliveryRows" :key="row.id" :label="i18n.get(row.label)">
                    <BentoTypography variant="body">{{ row.rendered }}</BentoTypography>
                </BentoStructuredListItem>
            </BentoStructuredList>
        </section>

        <section v-if="billingRows.length" :class="styles.section">
            <BentoTypography variant="body" stronger :class="styles.sectionTitle">
                {{ i18n.get('payByLink.creation.summary.billingAddress') }}
            </BentoTypography>
            <BentoStructuredList layout="42-58">
                <BentoStructuredListItem v-for="row in billingRows" :key="row.id" :label="i18n.get(row.label)">
                    <BentoTypography variant="body">{{ row.rendered }}</BentoTypography>
                </BentoStructuredListItem>
            </BentoStructuredList>
        </section>

        <BentoAlert :class="styles.alert" type="highlight" variant="tip" role="alert">
            <template #description>{{ i18n.get('payByLink.creation.summary.alertDescription') }}</template>
        </BentoAlert>
    </section>
</template>

// packages/domains/payByLink/preact/src/PaymentLinkCreation/components/Form/Summary/FormSummary.tsx
import cx from 'classnames';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import { useCoreContext } from '@integration-components/core/preact';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import StructuredList from '@integration-components/ui-components-preact/StructuredList';
import { AlertTypeOption, AlertVariantOption } from '@integration-components/ui-components-preact/Alert/types';
import { containerQueries, useResponsiveContainer } from '@integration-components/hooks-preact';
import { Divider } from '@integration-components/ui-components-preact/Divider/Divider';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import { invisibleFields } from './constants';
import { useWizardFormContext } from '@integration-components/hooks-preact/form/wizard/WizardFormContext';
import { PaymentLinkCreationFormValues } from '../../types';
import { StructuredListItem } from '@integration-components/ui-components-preact/StructuredList/types';
import { useMemo } from 'preact/hooks';
import { Tag } from '@integration-components/ui-components-preact/Tag/Tag';
import { IPaymentLinkType } from '@integration-components/types';
import type { TranslationKey } from '@integration-components/core';
import './FormSummary.scss';

interface FormSummaryProps {
    countryDatasetData?: { id: string; name: string }[];
}

export const FormSummary = ({ countryDatasetData }: FormSummaryProps) => {
    const { getSummaryData, getValues, getDisplayValue } = useWizardFormContext<PaymentLinkCreationFormValues>();
    const formValues = getSummaryData();
    const { i18n } = useCoreContext();
    const isMobile = useResponsiveContainer(containerQueries.down.xs);

    const paymentListItems = useMemo<StructuredListItem[]>(() => {
        const { payment } = formValues;
        const visibleFields = payment?.fields.filter(({ id }) => !invisibleFields.includes(id));

        // Store step does not exist when only one store is available, so we create it manually
        // Also, we want to show it under the payment details section
        const storeField = {
            id: 'store',
            label: 'payByLink.creation.summary.fields.store',
            value: getValues('store'),
            displayValue: getDisplayValue('store'),
        };

        const jointFields = [...(storeField ? [storeField] : []), ...(visibleFields || [])];

        const items: StructuredListItem[] | undefined = jointFields?.map(({ label, value, id, displayValue }) => ({
            key: (label || id) as TranslationKey,
            value: displayValue || value,
            id,
            render: item => {
                switch (item.id) {
                    case 'linkValidity.quantity': {
                        const durationUnit = payment?.fields?.find(field => field.id === 'linkValidity.durationUnit');
                        return i18n.get(`payByLink.creation.fields.validity.linkValidityUnit.${durationUnit?.value}` as TranslationKey, {
                            values: { quantity: item.value },
                            count: Number(item.value),
                        });
                    }
                    case 'amount.value': {
                        const currencyField = payment?.fields?.find(field => field.id === 'amount.currency');
                        return i18n.amount(item.value, currencyField?.value);
                    }
                    case 'linkType':
                        return i18n.get(`payByLink.creation.form.linkTypes.${item.value as IPaymentLinkType}`);
                    default:
                        return item.value;
                }
            },
        }));

        return items || [];
    }, [formValues, getDisplayValue, getValues, i18n]);

    const customerListItems = useMemo(() => {
        const { customer } = formValues;
        const visibleFields = customer?.fields.filter(({ id }) => !invisibleFields.includes(id));
        const createListItem = ({
            label,
            value,
            id,
            displayValue,
        }: {
            label?: string;
            value: string;
            id?: string;
            displayValue?: string;
        }): StructuredListItem => ({
            key: (label || id) as TranslationKey,
            value: displayValue || value,
            id,
            render: item => {
                switch (item.id) {
                    case 'countryCode':
                    case 'deliveryAddress.country':
                    case 'billingAddress.country':
                        return countryDatasetData?.find(countryData => countryData.id === item.value)?.name;
                    default:
                        return item.value;
                }
            },
        });

        const deliveryAddressItems = visibleFields?.filter(field => field.id?.startsWith('deliveryAddress.'))?.map(createListItem);
        const billingAddressItems = visibleFields?.filter(field => field.id?.startsWith('billingAddress.'))?.map(createListItem);
        const nonAddressItems = visibleFields
            ?.filter(field => !field?.id?.startsWith('deliveryAddress.') && !field?.id?.startsWith('billingAddress.'))
            ?.map(createListItem);

        const sendLinkToShopper = customer?.fields.find(field => field.id === 'sendLinkToShopper' && field.value === true);
        const sendPaymentSuccessToShopper = customer?.fields.find(field => field.id === 'sendSuccessEmailToShopper' && field.value === true);

        if (sendLinkToShopper || sendPaymentSuccessToShopper) {
            nonAddressItems?.splice(3, 0, {
                key: 'payByLink.creation.summary.fields.emailNotifications',
                value: [sendPaymentSuccessToShopper, sendLinkToShopper].filter(Boolean),
                render: () => (
                    <div className="adyen-pe-payment-link-creation-form-summary__tags-container">
                        {sendLinkToShopper && (
                            <Tag>
                                <Typography variant={TypographyVariant.CAPTION} el={TypographyElement.SPAN} stronger>
                                    {i18n.get('payByLink.creation.summary.fields.emailNotifications.emailCreation')}
                                </Typography>
                            </Tag>
                        )}
                        {sendPaymentSuccessToShopper && (
                            <Tag>
                                <Typography variant={TypographyVariant.CAPTION} el={TypographyElement.SPAN} stronger>
                                    {i18n.get('payByLink.creation.summary.fields.emailNotifications.paymentSuccess')}
                                </Typography>
                            </Tag>
                        )}
                    </div>
                ),
            });
        }

        return { nonAddressItems, deliveryAddressItems, billingAddressItems };
    }, [countryDatasetData, formValues, i18n]);

    return (
        <section className={cx('adyen-pe-payment-link-creation-form-summary', { 'adyen-pe-payment-link-creation-form-summary--mobile': isMobile })}>
            <section className="adyen-pe-payment-link-creation-form-summary__section">
                <Typography variant={TypographyVariant.SUBTITLE} className="adyen-pe-payment-link-creation-form-summary__section-title">
                    {i18n.get('payByLink.creation.summary.paymentDetails')}
                </Typography>
                <div>
                    <StructuredList layout={'5-7'} align={'start'} condensed={false} items={paymentListItems} />
                </div>
            </section>
            {customerListItems.nonAddressItems?.length && (
                <>
                    <Divider />
                    <section className="adyen-pe-payment-link-creation-form-summary__section">
                        <Typography variant={TypographyVariant.SUBTITLE} className="adyen-pe-payment-link-creation-form-summary__section-title">
                            {i18n.get('payByLink.creation.summary.shopperInformation')}
                        </Typography>
                        <div>
                            <StructuredList layout={'5-7'} align={'start'} condensed={false} items={customerListItems.nonAddressItems} />
                        </div>
                    </section>
                </>
            )}
            {!!customerListItems.deliveryAddressItems?.length && (
                <section className="adyen-pe-payment-link-creation-form-summary__section">
                    <Typography variant={TypographyVariant.BODY} className="adyen-pe-payment-link-creation-form-summary__section-title">
                        {i18n.get('payByLink.creation.summary.deliveryAddress')}
                    </Typography>
                    <div>
                        <StructuredList layout={'5-7'} align={'start'} condensed={false} items={customerListItems.deliveryAddressItems || []} />
                    </div>
                </section>
            )}
            {!!customerListItems.billingAddressItems?.length && (
                <section className="adyen-pe-payment-link-creation-form-summary__section">
                    <Typography variant={TypographyVariant.BODY} className="adyen-pe-payment-link-creation-form-summary__section-title">
                        {i18n.get('payByLink.creation.summary.billingAddress')}
                    </Typography>
                    <div>
                        <StructuredList layout={'5-7'} align={'start'} condensed={false} items={customerListItems.billingAddressItems || []} />
                    </div>
                </section>
            )}
            <Alert
                className="adyen-pe-payment-link-creation-form-summary__alert"
                variant={AlertVariantOption.TIP}
                type={AlertTypeOption.HIGHLIGHT}
                description={i18n.get('payByLink.creation.summary.alertDescription')}
            />
        </section>
    );
};
