// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/PaymentLinkSettingsContent.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useResponsiveContainer, containerQueries } from '@integration-components/composables-vue';
import type { AdyenPlatformExperienceError } from '@integration-components/core';
import { useSettingsPermission } from '../composables/useSettingsPermission';
import { menuItem, PERMISSION_ERROR } from '../constants';
import type { PaymentLinkSettingsItem } from '../types';
import PaymentLinkThemeContainer from './PaymentLinkThemeContainer.vue';
import TermsAndConditionsContainer from './TermsAndConditionsContainer.vue';
import SettingsError from './SettingsError.vue';
import LoadingSkeleton from './LoadingSkeleton.vue';
import layoutStyles from './PaymentLinkSettingsLayout.module.scss';

const THEME_ERROR_MESSAGE_KEY = 'payByLink.settings.theme.errors.couldNotLoad';
const TERMS_AND_CONDITIONS_ERROR_MESSAGE_KEY = 'payByLink.settings.termsAndConditions.errors.couldNotLoad';

defineProps<{
    activeMenuItem: PaymentLinkSettingsItem | null;
    isLoadingContent: boolean;
}>();

const isSmContainer = useResponsiveContainer(containerQueries.down.xs);
const { themeEnabled, termsAndConditionsEnabled } = useSettingsPermission();

const permissionError = computed<AdyenPlatformExperienceError | undefined>(() => {
    if (themeEnabled.value && termsAndConditionsEnabled.value) return undefined;
    return { errorCode: PERMISSION_ERROR, type: 'error', requestId: '' } as AdyenPlatformExperienceError;
});
</script>

<template>
    <div :class="isSmContainer ? layoutStyles.contentItemMobile : layoutStyles.contentItem">
        <LoadingSkeleton v-if="isLoadingContent" :row-number="activeMenuItem === menuItem.termsAndConditions ? 2 : 3" />
        <template v-else-if="activeMenuItem === menuItem.theme">
            <SettingsError v-if="!themeEnabled" :error="permissionError" :error-message="THEME_ERROR_MESSAGE_KEY" />
            <PaymentLinkThemeContainer v-else />
        </template>
        <template v-else-if="activeMenuItem === menuItem.termsAndConditions">
            <SettingsError v-if="!termsAndConditionsEnabled" :error="permissionError" :error-message="TERMS_AND_CONDITIONS_ERROR_MESSAGE_KEY" />
            <TermsAndConditionsContainer v-else />
        </template>
    </div>
</template>

// src/components/external/PaymentLinkSettings/components/PaymentLinkSettingsContainer/components/PaymentLinkSettingsContent/PaymentLinkSettingsContent.tsx
import TermsAndConditionsContainer from '../../../TermsAndConditions/TermsAndConditionsContainer';
import PaymentLinkThemeContainer from '../../../PaymentLinkThemeContainer/PaymentLinkThemeContainer';
import { MenuItem } from '../../context/constants';
import { containerQueries, useResponsiveContainer } from '../../../../../../../hooks/useResponsiveContainer';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import { AlertTypeOption, AlertVariantOption } from '@integration-components/ui-components-preact/Alert/types';
import useCoreContext from '../../../../../../../core/Context/useCoreContext';
import usePaymentLinkSettingsContext from '../../context/context';
import PaymentLinkSettingsContentLoading from '../PaymentLinkSettingsContentLoading/PaymentLinkSettingsContentLoading';
import { useSettingsPermission } from '../../../../hooks/useSettingsPermission';
import SettingsError from '../SettingsError/SettingsError';
import AdyenPlatformExperienceError from '../../../../../../../core/Errors/AdyenPlatformExperienceError';
import { useMemo } from 'preact/hooks';
import { PERMISSION_ERROR } from '../../utils/getSettingsErrorMessage';

const THEME_ERROR_MESSAGE_KEY = 'payByLink.settings.theme.errors.couldNotLoad';
const TERMS_AND_CONDITIONS_ERROR_MESSAGE_KEY = 'payByLink.settings.termsAndConditions.errors.couldNotLoad';

type PaymentLinkSettingsContentProps = {
    activeMenuItem: string | null;
    isLoadingContent: boolean;
    navigateBack?: () => void;
};

const PaymentLinkSettingsContentItem = ({ activeMenuItem, isLoadingContent }: PaymentLinkSettingsContentProps) => {
    const { themeEnabled, termsAndConditionsEnabled } = useSettingsPermission();

    const permissionError = useMemo(() => {
        if (themeEnabled && termsAndConditionsEnabled) return undefined;
        return {
            errorCode: PERMISSION_ERROR,
            type: 'error',
            requestId: '',
        } as AdyenPlatformExperienceError;
    }, [themeEnabled, termsAndConditionsEnabled]);

    if (isLoadingContent) {
        return <PaymentLinkSettingsContentLoading activeMenuItem={activeMenuItem} />;
    }
    switch (activeMenuItem) {
        case MenuItem.theme: {
            if (!themeEnabled) return <SettingsError error={permissionError} errorMessage={THEME_ERROR_MESSAGE_KEY} />;
            return <PaymentLinkThemeContainer />;
        }
        case MenuItem.termsAndConditions: {
            if (!termsAndConditionsEnabled) return <SettingsError error={permissionError} errorMessage={TERMS_AND_CONDITIONS_ERROR_MESSAGE_KEY} />;
            return <TermsAndConditionsContainer />;
        }
        default:
            return null;
    }
};

const PaymentLinkSettingsContent = ({ activeMenuItem, isLoadingContent, navigateBack }: PaymentLinkSettingsContentProps) => {
    const isSmContainer = useResponsiveContainer(containerQueries.down.xs);
    const { i18n } = useCoreContext();
    const { isSaveSuccess, isSaveError, setIsSaveSuccess, setIsSaveError } = usePaymentLinkSettingsContext();

    return (
        <div className={isSmContainer ? 'adyen-pe-payment-link-settings__content-item--mobile' : 'adyen-pe-payment-link-settings__content-item'}>
            <PaymentLinkSettingsContentItem activeMenuItem={activeMenuItem} isLoadingContent={isLoadingContent} />
            {isSaveSuccess && !navigateBack && (
                <Alert
                    type={AlertTypeOption.SUCCESS}
                    variant={AlertVariantOption.TIP}
                    onClose={() => setIsSaveSuccess(false)}
                    description={i18n.get('payByLink.settings.common.alerts.saveSuccess')}
                    className={'adyen-pe-payment-link-settings__content-item--alert'}
                />
            )}
            {isSaveError && (
                <Alert
                    type={AlertTypeOption.CRITICAL}
                    variant={AlertVariantOption.TIP}
                    onClose={() => setIsSaveError(false)}
                    description={i18n.get('payByLink.settings.common.alerts.saveError')}
                    className={'adyen-pe-payment-link-settings__content-item--alert'}
                />
            )}
        </div>
    );
};

export default PaymentLinkSettingsContent;
