// src/components/external/PayByLink/PayByLinkSettings/components/PayByLinkSettingsContainer/components/LoadingSkeleton/LoadingSkeleton.tsx
import cx from 'classnames';
import './LoadingSkeleton.scss';

const LoadingSkeleton = ({ rowNumber, className }: { rowNumber: number; className?: string }) => {
    return (
        <div className={cx('adyen-pe-pay-by-link-settings__skeleton', className)}>
            <div className="adyen-pe-pay-by-link-settings__skeleton-item adyen-pe-pay-by-link-settings__skeleton-item--header"></div>
            {[...Array(rowNumber)].map((_, index) => (
                <div className="adyen-pe-pay-by-link-settings__skeleton-container" key={index}>
                    <div className="adyen-pe-pay-by-link-settings__skeleton-item adyen-pe-pay-by-link-settings__skeleton-item--small"></div>
                    <div className="adyen-pe-pay-by-link-settings__skeleton-item adyen-pe-pay-by-link-settings__skeleton-item--large"></div>
                </div>
            ))}
        </div>
    );
};

export default LoadingSkeleton;

// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/LoadingSkeleton.vue
<script setup lang="ts">
withDefaults(
    defineProps<{
        rowNumber: number;
    }>(),
    { rowNumber: 3 }
);
</script>

<template>
    <div class="adyen-pe-payment-link-settings__skeleton">
        <div class="adyen-pe-payment-link-settings__skeleton-item adyen-pe-payment-link-settings__skeleton-item--header"></div>
        <div v-for="index in rowNumber" :key="index" class="adyen-pe-payment-link-settings__skeleton-container">
            <div class="adyen-pe-payment-link-settings__skeleton-item adyen-pe-payment-link-settings__skeleton-item--small"></div>
            <div class="adyen-pe-payment-link-settings__skeleton-item adyen-pe-payment-link-settings__skeleton-item--large"></div>
        </div>
    </div>
</template>
