// packages/domains/payByLink/preact/src/PaymentLinkSettings/components/PaymentLinkSettingsContainer/PaymentLinkSettingsContainer.tsx
import { type ExternalUIComponentProps } from '@integration-components/types';
import { PaymentLinkSettingsComponentProps } from '../../types';
import './PaymentLinkSettingsContainer.scss';
import { PaymentLinkSettingsProvider } from './context/context';
import PaymentLinkSettings from './PaymentLinkSettings';
import { PaymentLinkSettingsItem } from './context/types';
import { useMemo } from 'preact/hooks';
import { MENU_ITEMS } from './context/constants';
import { useCoreContext } from '@integration-components/core/preact';

const PaymentLinkSettingsContainer = ({
    settingsItems,
    storeIds,
    embeddedInOverview,
    ...props
}: ExternalUIComponentProps<PaymentLinkSettingsComponentProps> & {
    settingsItems?: PaymentLinkSettingsItem[];
    navigateBack?: () => void;
    embeddedInOverview?: boolean;
}) => {
    const { i18n } = useCoreContext();

    const filteredMenuItems = useMemo(
        () => (settingsItems && settingsItems?.length > 0 ? MENU_ITEMS.filter(item => settingsItems.includes(item.value)) : MENU_ITEMS),
        [settingsItems]
    );

    const paymentLinkSettingsItem = useMemo(() => {
        const settingsItems = filteredMenuItems.length > 0 ? filteredMenuItems : MENU_ITEMS;
        return settingsItems.map(item => ({ ...item, label: i18n.get(item.label) }));
    }, [i18n, filteredMenuItems]);

    return (
        <PaymentLinkSettingsProvider
            embeddedInOverview={embeddedInOverview}
            selectedMenuItems={paymentLinkSettingsItem}
            storeIds={storeIds}
            navigateBack={props?.navigateBack}
        >
            <PaymentLinkSettings {...props} />
        </PaymentLinkSettingsProvider>
    );
};

export default PaymentLinkSettingsContainer;

// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/PaymentLinkSettingsContainer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { providePaymentLinkSettings } from '../composables/context';
import { MENU_ITEMS } from '../constants';
import type { PaymentLinkSettingsProps } from '../types';
import PaymentLinkSettings from './PaymentLinkSettings.vue';

const props = defineProps<PaymentLinkSettingsProps>();

const { i18n } = useCoreContext();

const filteredMenuItems = computed(() =>
    props.settingsItems && props.settingsItems.length > 0 ? MENU_ITEMS.filter(item => props.settingsItems?.includes(item.value)) : MENU_ITEMS
);

const selectedMenuItems = computed(() => {
    const items = filteredMenuItems.value.length > 0 ? filteredMenuItems.value : MENU_ITEMS;
    return items.map(item => ({ ...item, label: i18n.get(item.label) }));
});

providePaymentLinkSettings({
    selectedMenuItems: selectedMenuItems.value,
    storeIds: props.storeIds,
    embeddedInOverview: props.embeddedInOverview,
    navigateBack: props.navigateBack,
});
</script>

<template>
    <PaymentLinkSettings :hide-title="props.hideTitle" :on-contact-support="props.onContactSupport" :navigate-back="props.navigateBack" />
</template>
