// src/components/external/PayByLink/PayByLinkSettings/components/TermsAndConditions/Requirements/Requirements.tsx
import { useCallback, useEffect } from 'preact/hooks';
import useCoreContext from '../../../../../../../core/Context/useCoreContext';
import Typography from '../../../../../../internal/Typography/Typography';
import { TypographyVariant } from '../../../../../../internal/Typography/types';
import { useTermsRequirementsConfig } from './useTermsRequirementsConfig';
import './Requirements.scss';
import Button from '../../../../../../internal/Button';
import { ButtonVariant } from '../../../../../../internal/Button/types';
import Modal from '../../../../../../internal/Modal';

export const Requirements = ({
    onGoBack,
    acceptRequirements,
    termsAndConditionsURL,
    embeddedInOverview = false,
}: {
    onGoBack: () => void;
    acceptRequirements: () => void;
    termsAndConditionsURL?: string;
    embeddedInOverview?: boolean;
}) => {
    const { termsRequirementsConfig, getTermsRequirementsConfig } = useTermsRequirementsConfig();
    const { i18n } = useCoreContext();

    const onAcceptRequirements = useCallback(() => {
        acceptRequirements();
        onGoBack();
    }, [acceptRequirements, onGoBack]);

    useEffect(() => {
        void getTermsRequirementsConfig();
    }, [getTermsRequirementsConfig]);

    const content = (
        <div className="adyen-pe-pay-by-link-requirements">
            <Typography variant={TypographyVariant.SUBTITLE} stronger>
                {i18n.get(termsRequirementsConfig.titleKey)}
            </Typography>
            <div className="adyen-pe-pay-by-link-requirements__sections-container">
                {termsRequirementsConfig.sections.map(section => (
                    <div key={section.id} className="adyen-pe-pay-by-link-requirements__section">
                        <Typography variant={TypographyVariant.SUBTITLE} stronger>
                            {i18n.get(section.titleKey)}
                        </Typography>
                        <div className="adyen-pe-pay-by-link-requirements__section-content">
                            <Typography className="adyen-pe-pay-by-link-requirements__description" variant={TypographyVariant.BODY}>
                                {i18n.get(section.descriptionKey)}
                            </Typography>
                            <ul className="adyen-pe-pay-by-link-requirements__list">
                                {section.items.map(item => (
                                    <li key={item.key}>
                                        <Typography variant={TypographyVariant.BODY}>{i18n.get(item.key)}</Typography>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>
                ))}
            </div>
            <div className="adyen-pe-pay-by-link-requirements__buttons-container">
                <Button variant={ButtonVariant.SECONDARY} onClick={onGoBack}>
                    {i18n.get('payByLink.settings.terms.requirements.actions.goBack')}
                </Button>
                {termsAndConditionsURL && (
                    <Button variant={ButtonVariant.PRIMARY} onClick={onAcceptRequirements}>
                        {i18n.get('payByLink.settings.terms.requirements.actions.confirmRequirements')}
                    </Button>
                )}
            </div>
        </div>
    );

    if (embeddedInOverview) {
        return content;
    }

    return (
        <Modal isOpen onClose={onGoBack} isDismissible={true} headerWithBorder={false} size="large">
            {content}
        </Modal>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/Requirements.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { BentoButton, BentoModal, BentoTypography } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import { useTermsRequirementsConfig } from '../composables/useTermsRequirementsConfig';
import styles from './Requirements.module.scss';

const props = defineProps<{
    termsAndConditionsUrl?: string;
}>();

const emit = defineEmits<{
    goBack: [];
    acceptRequirements: [];
}>();

const { i18n } = useCoreContext();
const { termsRequirementsConfig, getTermsRequirementsConfig } = useTermsRequirementsConfig();

onMounted(() => {
    void getTermsRequirementsConfig();
});

function onAcceptRequirements() {
    emit('acceptRequirements');
    emit('goBack');
}
</script>

<template>
    <BentoModal :is-open="true" :is-dismissible="true" size="large" @close-modal="emit('goBack')">
        {{ i18n.get(termsRequirementsConfig.titleKey) }}
        <template #content>
            <div :class="styles.root">
                <div :class="styles.sectionsContainer">
                    <div v-for="section in termsRequirementsConfig.sections" :key="section.id" :class="styles.section">
                        <BentoTypography variant="title" el="div">
                            {{ i18n.get(section.titleKey) }}
                        </BentoTypography>
                        <div :class="styles.sectionContent">
                            <BentoTypography variant="body">
                                {{ i18n.get(section.descriptionKey) }}
                            </BentoTypography>
                            <ul :class="styles.list">
                                <li v-for="item in section.items" :key="item.key">
                                    <BentoTypography variant="body">
                                        {{ i18n.get(item.key) }}
                                    </BentoTypography>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div :class="styles.buttonsContainer">
                    <BentoButton variant="secondary" @click="emit('goBack')">
                        {{ i18n.get('payByLink.settings.terms.requirements.actions.goBack') }}
                    </BentoButton>
                    <BentoButton v-if="props.termsAndConditionsUrl" variant="primary" @click="onAcceptRequirements">
                        {{ i18n.get('payByLink.settings.terms.requirements.actions.confirmRequirements') }}
                    </BentoButton>
                </div>
            </div>
        </template>
    </BentoModal>
</template>
