// packages/domains/payByLink/preact/src/PaymentLinkSettings/components/PaymentLinkSettingsContainer/components/SettingsError/SettingsError.tsx
import { useCoreContext } from '@integration-components/core/preact';
import { AdyenPlatformExperienceError, TranslationKey } from '@integration-components/core';
import { ErrorMessageDisplay } from '@integration-components/ui-components-preact/ErrorMessageDisplay/ErrorMessageDisplay';
import getSettingsErrorMessage from '../../utils/getSettingsErrorMessage';

const SettingsError = ({
    error,
    errorMessage,
    onContactSupport,
    centered,
    absolutePosition,
}: {
    error: AdyenPlatformExperienceError | undefined;
    errorMessage: TranslationKey;
    centered?: boolean;
    absolutePosition?: boolean;
    onContactSupport?: () => void;
}) => {
    const { getImageAsset } = useCoreContext();

    const { title, message, refreshComponent, translationValues, images } = getSettingsErrorMessage(
        error,
        errorMessage,
        onContactSupport,
        getImageAsset
    );

    return (
        <ErrorMessageDisplay
            imageDesktop={images?.desktop}
            imageMobile={images?.mobile}
            withHeaderOffset
            title={title}
            message={message}
            translationValues={translationValues}
            withImage
            centered={centered ?? false}
            absolutePosition={absolutePosition ?? false}
            refreshComponent={refreshComponent}
            onContactSupport={onContactSupport}
            outlined={false}
        />
    );
};
export default SettingsError;

// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/SettingsError.vue
<script setup lang="ts">
import { computed } from 'vue';
import { ErrorMessageDisplay } from '@integration-components/composables-vue';
import type { AdyenPlatformExperienceError, TranslationKey } from '@integration-components/core';
import { getSettingsErrorMessage } from '../utils/getSettingsErrorMessage';

const props = defineProps<{
    error: AdyenPlatformExperienceError | undefined;
    errorMessage: TranslationKey;
    onContactSupport?: () => void;
}>();

const content = computed(() => getSettingsErrorMessage(props.error, props.errorMessage, props.onContactSupport));

const errorInfo = computed(() =>
    content.value
        ? {
              ...content.value,
              requestId: props.error?.requestId,
              onContactSupport: props.onContactSupport,
          }
        : undefined
);
</script>

<template>
    <div v-if="errorInfo">
        <ErrorMessageDisplay :error-info="errorInfo" with-image :absolute-position="false" />
    </div>
</template>
