// src/components/external/PaymentLinkSettings/components/PaymentLinkThemeContainer/components/ThemeForm/ThemeForm.tsx
import InputText from '@integration-components/ui-components-preact/FormFields/InputText';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import useUniqueId from '../../../../../../../hooks/useUniqueId';
import useCoreContext from '../../../../../../../core/Context/useCoreContext';
import { logoOptions, logoOptionsList } from './constants';
import './ThemeForm.scss';
import { useCallback, useEffect, useState } from 'preact/hooks';
import { h } from 'preact';
import Icon from '@integration-components/ui-components-preact/Icon';
import usePaymentLinkSettingsContext from '../../../PaymentLinkSettingsContainer/context/context';
import { LogoTypes, ThemeFormDataRequest, ThemeFormProps } from '../../types';
import LogoPreview from '../LogoPreview/LogoPreview';
import LogoInput from '../LogoInput/LogoInput';
import { cloneFormData } from '../../../PaymentLinkSettingsContainer/utils/getThemePayload';

export const ThemeForm = ({ theme, initialPayload }: ThemeFormProps) => {
    const { setPayload, saveActionCalled, setSaveActionCalled, setIsValid, isSaving, setIsSaveSuccess, setIsSaveError } =
        usePaymentLinkSettingsContext();

    const { brandName: initialBrandName, logo, fullWidthLogo } = theme;
    const [brandName, setBrandName] = useState(initialBrandName ?? undefined);
    const [logoUrl, setLogoUrl] = useState(logo ?? null);
    const [fullWidthLogoUrl, setFullWidthLogoUrl] = useState(fullWidthLogo ?? null);
    const [themePayload, setThemePayload] = useState<FormData | undefined>();
    const [showMissingBrandName, setShowMissingBrandName] = useState(false);

    const brandInputId = useUniqueId();
    const { i18n } = useCoreContext();

    useEffect(() => {
        setIsValid(!!brandName);
    }, [brandName, setIsValid, themePayload, setPayload]);

    useEffect(() => {
        setThemePayload(initialPayload);
    }, [initialPayload]);

    useEffect(() => {
        if (saveActionCalled) {
            if (!brandName) {
                setShowMissingBrandName(true);
            }
            setSaveActionCalled(false);
            setIsSaveSuccess(false);
            setIsSaveError(false);
        }
    }, [saveActionCalled, setSaveActionCalled, brandName, setShowMissingBrandName, setIsSaveError, setIsSaveSuccess]);

    const addFileToThemePayload = useCallback(
        (field: string, file: File) => {
            setThemePayload(previousFormData => {
                const nextFormData = previousFormData ? cloneFormData(previousFormData) : new FormData();
                nextFormData.set(field, file, file.name);
                nextFormData.set(field, file, file.name);
                setPayload(nextFormData);
                return nextFormData;
            });
        },
        [setPayload]
    );

    const onBrandNameChange = useCallback(
        (e: h.JSX.TargetedEvent<HTMLInputElement>) => {
            const value = e?.currentTarget?.value;
            setShowMissingBrandName(false);
            setBrandName(value);
            setThemePayload(previousFormData => {
                const nextFormData = previousFormData ? cloneFormData(previousFormData) : new FormData();
                nextFormData.set(ThemeFormDataRequest.BRAND, value);
                setPayload(nextFormData);
                return nextFormData;
            });
        },
        [setShowMissingBrandName, setBrandName, setThemePayload, setPayload]
    );

    const removeFieldFromThemePayload = useCallback(
        (field: string) => {
            setThemePayload(previousFormData => {
                if (previousFormData && previousFormData.has(field)) {
                    const nextFormData = cloneFormData(previousFormData);
                    nextFormData.delete(field);
                    setPayload(nextFormData);
                    return nextFormData;
                }
                return previousFormData;
            });
        },
        [setPayload]
    );

    const logoPreview = useCallback(
        (type: LogoTypes, file: File) => {
            const reader = new FileReader();

            reader.onload = function (e) {
                const result = e?.target?.result as string;
                if (type === logoOptions.LOGO) {
                    setLogoUrl(result);
                }
                if (type === logoOptions.FULL_WIDTH_LOGO) {
                    setFullWidthLogoUrl(result);
                }
            };
            reader.readAsDataURL(file);
        },
        [setLogoUrl, setFullWidthLogoUrl]
    );

    const onLogoChange = useCallback(
        (type: LogoTypes, files: File[]) => {
            const file = files[0];
            if (!file) return;
            addFileToThemePayload(type, file);
            logoPreview(type, file);
        },
        [addFileToThemePayload, logoPreview]
    );

    const onRemoveLogoUrl = useCallback(
        (logoType: LogoTypes) => {
            removeFieldFromThemePayload(logoType);
            if (logoType === logoOptions.LOGO) {
                setLogoUrl(null);
            }
            if (logoType === logoOptions.FULL_WIDTH_LOGO) {
                setFullWidthLogoUrl(null);
            }
        },
        [removeFieldFromThemePayload, setLogoUrl, setFullWidthLogoUrl]
    );

    const getLogoUrl = useCallback(
        (logoType: LogoTypes) => {
            return logoType === logoOptions.LOGO ? logoUrl : fullWidthLogoUrl;
        },
        [fullWidthLogoUrl, logoUrl]
    );

    return (
        <div className="adyen-pe-payment-link-theme-form-container">
            <div className="adyen-pe-payment-link-theme-form">
                <div className="adyen-pe-payment-link-settings__input-container">
                    <label htmlFor={brandInputId} aria-labelledby={brandInputId} className="adyen-pe-payment-link-theme-form__brand-input">
                        <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                            {i18n.get('payByLink.settings.theme.brandName.input.label')}
                        </Typography>
                    </label>
                    <InputText
                        type="text"
                        disabled={!!isSaving}
                        readonly={!!isSaving}
                        lang={i18n.locale}
                        uniqueId={brandInputId}
                        value={brandName}
                        onInput={onBrandNameChange}
                        placeholder={i18n.get('payByLink.settings.theme.brandName.input.placeholder')}
                        isInvalid={showMissingBrandName}
                    />
                    {showMissingBrandName && (
                        <div className="adyen-pe-payment-link-theme-form__error">
                            <Icon name="cross-circle-fill" className={'adyen-pe-payment-link-theme-form__error-icon'} />
                            <Typography
                                className={'adyen-pe-payment-link-theme-form__error-text'}
                                el={TypographyElement.SPAN}
                                variant={TypographyVariant.BODY}
                            >
                                {i18n.get('payByLink.settings.theme.inputs.brandName.errors.missing')}
                            </Typography>
                        </div>
                    )}
                </div>
                {logoOptionsList.map(logoType => {
                    const url = getLogoUrl(logoType);
                    return (
                        <div key={logoType} className={'adyen-pe-payment-link-settings__input-container '}>
                            {url ? (
                                <LogoPreview disabled={!!isSaving} logoType={logoType} logoURL={url} onRemoveLogo={onRemoveLogoUrl} />
                            ) : (
                                <LogoInput disabled={!!isSaving} logoType={logoType} onFileInputChange={onLogoChange} />
                            )}
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/ThemeForm.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { BentoAlert, BentoInputField, BentoTypography } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import { usePaymentLinkSettingsContext } from '../composables/context';
import { cloneFormData } from '../utils/getThemePayload';
import { logoOptionsList, ThemeFormDataRequest } from '../constants';
import type { LogoType, ThemeFormData } from '../types';
import LogoInput from './LogoInput.vue';
import LogoPreview from './LogoPreview.vue';

const props = defineProps<{ theme: ThemeFormData }>();

const { i18n } = useCoreContext();
const {
    setPayload,
    saveActionCalled,
    setSaveActionCalled,
    setIsValid,
    isSaving,
    isSaveSuccess,
    isSaveError,
    setIsSaveSuccess,
    setIsSaveError,
    navigateBack,
} = usePaymentLinkSettingsContext();

const brandName = ref(props.theme.brandName ?? '');
const logoUrl = ref<string | null>(props.theme.logo ?? null);
const fullWidthLogoUrl = ref<string | null>(props.theme.fullWidthLogo ?? null);
const touchedLogo = ref(false);
const touchedFullWidthLogo = ref(false);
const showMissingBrandName = ref(false);

function buildInitialPayload(): FormData {
    const formData = new FormData();
    if (props.theme.brandName) formData.set(ThemeFormDataRequest.BRAND, props.theme.brandName);
    if (props.theme.logo) formData.set(ThemeFormDataRequest.LOGO, props.theme.logo);
    if (props.theme.fullWidthLogo) formData.set(ThemeFormDataRequest.FULL_WIDTH_LOGO, props.theme.fullWidthLogo);
    return cloneFormData(formData);
}

let themePayload: FormData = buildInitialPayload();
setPayload(themePayload);
setIsValid(!!brandName.value);

watch(brandName, value => setIsValid(!!value));

watch(saveActionCalled, value => {
    if (value) {
        if (!brandName.value) showMissingBrandName.value = true;
        setSaveActionCalled(false);
        setIsSaveSuccess(false);
        setIsSaveError(false);
    }
});

function addFileToThemePayload(field: string, file: File) {
    const nextFormData = cloneFormData(themePayload);
    nextFormData.set(field, file, file.name);
    themePayload = nextFormData;
    setPayload(nextFormData);
}

function removeFieldFromThemePayload(field: string) {
    if (themePayload.has(field)) {
        const nextFormData = cloneFormData(themePayload);
        nextFormData.delete(field);
        themePayload = nextFormData;
        setPayload(nextFormData);
    }
}

function onBrandNameChange(value: string | number) {
    const name = String(value);
    showMissingBrandName.value = false;
    brandName.value = name;
    const nextFormData = cloneFormData(themePayload);
    nextFormData.set(ThemeFormDataRequest.BRAND, name);
    themePayload = nextFormData;
    setPayload(nextFormData);
}

function logoPreview(type: LogoType, file: File) {
    const reader = new FileReader();
    reader.onload = e => {
        const result = e.target?.result as string;
        if (type === 'logo') logoUrl.value = result;
        if (type === 'fullWidthLogo') fullWidthLogoUrl.value = result;
    };
    reader.readAsDataURL(file);
}

function setTouched(type: LogoType) {
    if (type === 'logo') touchedLogo.value = true;
    if (type === 'fullWidthLogo') touchedFullWidthLogo.value = true;
}

function isTouched(type: LogoType) {
    return type === 'logo' ? touchedLogo.value : touchedFullWidthLogo.value;
}

function onLogoChange(type: LogoType, file: File) {
    setTouched(type);
    addFileToThemePayload(type, file);
    logoPreview(type, file);
}

function onRemoveLogoUrl(type: LogoType) {
    setTouched(type);
    removeFieldFromThemePayload(type);
    if (type === 'logo') logoUrl.value = null;
    if (type === 'fullWidthLogo') fullWidthLogoUrl.value = null;
}

function getLogoUrl(type: LogoType) {
    return type === 'logo' ? logoUrl.value : fullWidthLogoUrl.value;
}
</script>

<template>
    <div class="adyen-pe-payment-link-theme-form-container">
        <BentoAlert v-if="showMissingBrandName" type="critical" :dismissible="false">
            <template #description>{{ i18n.get('payByLink.settings.common.alerts.validationError') }}</template>
        </BentoAlert>
        <BentoAlert v-else-if="isSaveSuccess && !navigateBack" type="success" variant="tip" :dismissible="false">
            <template #description>{{ i18n.get('payByLink.settings.common.alerts.saveSuccess') }}</template>
        </BentoAlert>
        <BentoAlert v-else-if="isSaveError" type="critical" variant="tip" :dismissible="false">
            <template #description>{{ i18n.get('payByLink.settings.common.alerts.saveError') }}</template>
        </BentoAlert>
        <div class="adyen-pe-payment-link-settings__content-header">
            <BentoTypography variant="title" medium el="div">{{ i18n.get('payByLink.settings.theme.title') }}</BentoTypography>
            <BentoTypography variant="body" wide>{{ i18n.get('payByLink.settings.theme.subtitle') }}</BentoTypography>
        </div>
        <div class="adyen-pe-payment-link-theme-form">
            <div class="adyen-pe-payment-link-settings__input-container">
                <BentoInputField
                    type="text"
                    :disabled="!!isSaving"
                    :readonly="!!isSaving"
                    :lang="i18n.locale"
                    :label="i18n.get('payByLink.settings.theme.brandName.input.label')"
                    :model-value="brandName"
                    :placeholder="i18n.get('payByLink.settings.theme.brandName.input.placeholder')"
                    :error-message="showMissingBrandName ? i18n.get('payByLink.settings.theme.inputs.brandName.errors.missing') : undefined"
                    @update:model-value="onBrandNameChange"
                />
            </div>
            <div v-for="logoType in logoOptionsList" :key="logoType" class="adyen-pe-payment-link-settings__input-container">
                <LogoPreview
                    v-if="getLogoUrl(logoType) && !isTouched(logoType)"
                    :disabled="!!isSaving"
                    :logo-type="logoType"
                    :logo-url="getLogoUrl(logoType)!"
                    @remove-logo="onRemoveLogoUrl"
                />
                <LogoInput
                    v-else
                    :disabled="!!isSaving"
                    :logo-type="logoType"
                    :preview-url="isTouched(logoType) ? getLogoUrl(logoType) : null"
                    @file-input-change="onLogoChange"
                    @file-removed="onRemoveLogoUrl"
                />
            </div>
        </div>
    </div>
</template>
