// packages/domains/capital/vue/src/CapitalOverview/components/GrantItem/GrantItem.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
    BentoAlert,
    BentoButton,
    BentoCard,
    BentoTag,
    BentoToggleButton,
    BentoTooltipDirective as vBentoTooltip,
    BentoTypography,
    type BentoTagVariant,
} from '@adyen/bento-vue3';
import ChevronDownIcon from '@adyen/ui-assets-icons-16/vue/chevron-down';
import ChevronUpIcon from '@adyen/ui-assets-icons-16/vue/chevron-up';
import { getGrantConfig, type GrantStatusVariant } from '@integration-components/capital/domain';
import { CopyText, useTimezoneAwareDateFormatting } from '@integration-components/composables-vue';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/vue';
import { DATE_FORMAT_CAPITAL_OVERVIEW } from '@integration-components/utils';
import type { IGrant } from '@integration-components/types';
import { sharedCapitalOverviewAnalyticsEventProperties } from '../../../../../domain/src/CapitalOverview/constants';
import GrantActions from '../GrantActions/GrantActions.vue';
import GrantDetails from '../GrantDetails/GrantDetails.vue';
import styles from './GrantItem.module.scss';

type GrantAdjustmentDetail = 'revocation' | 'unscheduledRepayment';

const props = defineProps<{
    grant: IGrant;
    showDetails?: (detail?: GrantAdjustmentDetail) => void;
}>();

const { i18n } = useCoreContext();
const userEvents = useEventDispatcherContext();
const { dateFormat } = useTimezoneAwareDateFormatting();

const areActionsLocallyCompleted = ref(false);
const isGrantDetailsOpen = ref(false);
const grantConfig = computed(() => getGrantConfig(props.grant, areActionsLocallyCompleted.value));
const formattedAmount = computed(() => i18n.amount(grantConfig.value.amount.value, grantConfig.value.amount.currency));
const termEndLabel = computed(() =>
    i18n.get('capital.overview.grants.item.termEnds', {
        values: { date: dateFormat(grantConfig.value.repaymentPeriodEndDate, DATE_FORMAT_CAPITAL_OVERVIEW) },
    })
);
const statusTooltip = computed(() => (grantConfig.value.statusTooltipKey ? i18n.get(grantConfig.value.statusTooltipKey) : undefined));
const repaymentProgressLabels = computed(() => ({
    current: i18n.get('capital.overview.grants.item.amounts.repaid'),
    max: i18n.get('capital.overview.grants.item.amounts.remaining'),
}));
const shouldDisplayLegend = computed(() => !!(repaymentProgressLabels.value.current || repaymentProgressLabels.value.max));
const repaymentProgressLabel = computed(
    () =>
        `${i18n.amount(props.grant.repaidTotalAmount.value, props.grant.repaidTotalAmount.currency)} ${i18n
            .get('capital.overview.grants.item.amounts.repaid')
            .toLowerCase()}, ${i18n.amount(props.grant.remainingTotalAmount.value, props.grant.remainingTotalAmount.currency)} ${i18n
            .get('capital.overview.grants.item.amounts.remaining')
            .toLowerCase()}`
);

const getStatusTagVariant = (statusVariant: GrantStatusVariant): BentoTagVariant => {
    switch (statusVariant) {
        case 'Error':
            return 'red';
        case 'Light':
            return 'white';
        case 'Warning':
            return 'orange';
        case 'Default':
        default:
            return 'blue';
    }
};

const sendRepayment = () => {
    try {
        props.showDetails?.('unscheduledRepayment');
    } finally {
        userEvents.addEvent?.('Clicked button', {
            ...sharedCapitalOverviewAnalyticsEventProperties,
            subCategory: 'Grant active',
            label: 'Send repayment',
        });
    }
};

const handleActionsComplete = () => {
    areActionsLocallyCompleted.value = true;
};

const toggleGrantDetails = () => {
    if (grantConfig.value.hasDetails) {
        isGrantDetailsOpen.value = !isGrantDetailsOpen.value;
    }
};
</script>

<template>
    <div :class="styles.root">
        <BentoCard
            :aria-label="i18n.get('capital.overview.grants.item.details.a11y.label')"
            :background="grantConfig.isBackgroundFilled ? 'secondary' : 'primary'"
            :clickable="grantConfig.hasDetails"
            :closed="!isGrantDetailsOpen"
            @click="toggleGrantDetails"
        >
            <template #content>
                <div :class="styles.cardContent">
                    <div :class="styles.statusContainer">
                        <BentoTypography
                            variant="caption"
                            :class="{ [styles.textSecondary]: grantConfig.isLabelColorSecondary }"
                            data-testid="grant-amount-label"
                        >
                            {{ i18n.get(grantConfig.amountLabelKey) }}
                        </BentoTypography>

                        <BentoTypography v-if="props.grant.status === 'Active'" variant="caption">
                            <time :datetime="grantConfig.repaymentPeriodEndDate.toISOString()">
                                {{ termEndLabel }}
                            </time>
                        </BentoTypography>

                        <div v-else-if="grantConfig.statusKey" v-bento-tooltip="statusTooltip">
                            <BentoTag :label="i18n.get(grantConfig.statusKey)" :variant="getStatusTagVariant(grantConfig.statusTagVariant)" />
                        </div>
                    </div>

                    <BentoTypography variant="title" medium :class="{ [styles.textSecondary]: grantConfig.isAmountColorSecondary }">
                        {{ formattedAmount }}
                    </BentoTypography>

                    <div v-if="grantConfig.isProgressBarVisible">
                        <progress
                            v-bento-tooltip="repaymentProgressLabel"
                            :class="styles.progressBar"
                            :aria-label="i18n.get('capital.overview.grants.item.progressBar.a11y.label')"
                            :value="props.grant.repaidTotalAmount.value"
                            :max="props.grant.totalAmount.value"
                        />
                        <div v-if="shouldDisplayLegend" :class="styles.progressBarLegend" aria-hidden="true">
                            <BentoTypography
                                v-if="repaymentProgressLabels.current"
                                el="span"
                                variant="caption"
                                :class="styles.progressBarLegendLabel"
                            >
                                {{ repaymentProgressLabels.current }}
                            </BentoTypography>
                            <BentoTypography v-if="repaymentProgressLabels.max" el="span" variant="caption" :class="styles.progressBarLegendLabel">
                                {{ repaymentProgressLabels.max }}
                            </BentoTypography>
                        </div>
                    </div>

                    <div v-if="grantConfig.isGrantIdVisible" :class="styles.grantID">
                        <CopyText
                            copy-button-aria-label-key="capital.overview.grants.item.actions.copyGrantID"
                            data-testid="grant-id-copy-text"
                            is-underline-visible
                            :text-to-copy="props.grant.id"
                            type="Text"
                            :visible-text="i18n.get('capital.common.fields.grantID')"
                        />
                    </div>

                    <div v-if="grantConfig.hasUnscheduledRepaymentDetails" :class="styles.actionsBar">
                        <BentoButton :class="styles.mainActionBtn" variant="secondary" @click.stop="sendRepayment">
                            {{ i18n.get('capital.overview.grants.item.actions.sendRepayment') }}
                        </BentoButton>
                    </div>
                </div>
                <GrantDetails v-if="grantConfig.hasDetails && isGrantDetailsOpen" :grant="props.grant" />
                <BentoToggleButton
                    v-if="grantConfig.hasDetails"
                    :aria-label="i18n.get('capital.overview.grants.item.details.a11y.label')"
                    :class="styles.detailsToggle"
                    :toggled="isGrantDetailsOpen"
                    variant="tertiary"
                    @click="toggleGrantDetails"
                >
                    <ChevronUpIcon v-if="isGrantDetailsOpen" />
                    <ChevronDownIcon v-else />
                </BentoToggleButton>
            </template>
        </BentoCard>

        <template v-if="grantConfig.hasAlerts">
            <GrantActions
                v-if="props.grant.missingActions?.length"
                :class-name="styles.alert"
                :grant-id="props.grant.id"
                :missing-actions="props.grant.missingActions"
                :offer-expires-at="props.grant.offerExpiresAt"
                @complete="handleActionsComplete"
            />
            <BentoAlert v-else :class="styles.alert" type="highlight">
                {{ i18n.get('capital.overview.grants.item.alerts.processingRequest') }}
            </BentoAlert>
        </template>
    </div>
</template>

// packages/domains/capital/preact/src/CapitalOverview/components/GrantItem/GrantItem.tsx
import { FunctionalComponent } from 'preact';
import { useCallback, useMemo, useState } from 'preact/hooks';
import cx from 'classnames';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/preact';
import { useTimezoneAwareDateFormatting } from '@integration-components/hooks-preact';
import { DATE_FORMAT_CAPITAL_OVERVIEW, uniqueId } from '@integration-components/utils';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import { Tag } from '@integration-components/ui-components-preact/Tag/Tag';
import ProgressBar from '@integration-components/ui-components-preact/ProgressBar';
import { GRANT_ITEM_CLASS_NAMES } from './constants';
import './GrantItem.scss';
import { GrantDetails } from '../GrantDetails/GrantDetails';
import CopyText from '@integration-components/ui-components-preact/CopyText/CopyText';
import { Tooltip } from '@integration-components/ui-components-preact/Tooltip/Tooltip';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import Button from '@integration-components/ui-components-preact/Button';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';
import { ButtonVariant, IGrant } from '@integration-components/types';
import ExpandableCard from '@integration-components/ui-components-preact/ExpandableCard/ExpandableCard';
import { GrantActions } from '../GrantActions/GrantActions';
import { sharedCapitalOverviewAnalyticsEventProperties } from '../../../../../domain/src/CapitalOverview/constants';
import { Translation } from '@integration-components/ui-components-preact/Translation';
import { ListWithoutFirst } from '@integration-components/utils/types';
import { GrantAdjustmentDetailCallback } from '../GrantAdjustmentDetails/types';
import { getGrantConfig, GrantStatusVariant } from '@integration-components/capital/domain';
import { TagVariant } from '@integration-components/ui-components-preact/Tag/types';

export interface GrantItemProps {
    grant: IGrant;
    showDetails?: (...args: ListWithoutFirst<Parameters<GrantAdjustmentDetailCallback>>) => ReturnType<GrantAdjustmentDetailCallback>;
}

export const GrantItem: FunctionalComponent<GrantItemProps> = ({ grant, showDetails }) => {
    const { i18n } = useCoreContext();
    const { dateFormat } = useTimezoneAwareDateFormatting();
    const userEvents = useEventDispatcherContext();

    const [areActionsLocallyCompleted, setActionsLocallyCompleted] = useState(false);
    const grantConfig = useMemo(() => getGrantConfig(grant, areActionsLocallyCompleted), [grant, areActionsLocallyCompleted]);

    const getStatusTagVariant = useCallback((statusVariant: GrantStatusVariant) => {
        switch (statusVariant) {
            case 'Default':
                return TagVariant.DEFAULT;
            case 'Error':
                return TagVariant.ERROR;
            case 'Light':
                return TagVariant.LIGHT;
            case 'Warning':
                return TagVariant.WARNING;
        }
    }, []);

    const showUnscheduledRepaymentAccounts = useCallback(() => {
        try {
            return showDetails?.('unscheduledRepayment');
        } finally {
            userEvents.addEvent?.('Clicked button', {
                ...sharedCapitalOverviewAnalyticsEventProperties,
                subCategory: 'Grant active',
                label: 'Send repayment',
            });
        }
    }, [showDetails, userEvents]);

    const elementIds = useMemo(
        () =>
            ({
                grantAmount: uniqueId('elem'),
                grantAmountLabel: uniqueId('elem'),
                grantStatus: uniqueId('elem'),
                termEnds: uniqueId('elem'),
            }) as const,
        []
    );

    const grantOverview = useMemo(
        () => (
            <div className={GRANT_ITEM_CLASS_NAMES.cardContent}>
                <div className={GRANT_ITEM_CLASS_NAMES.statusContainer}>
                    <Typography
                        id={elementIds.grantAmountLabel}
                        variant={TypographyVariant.CAPTION}
                        className={cx({ [GRANT_ITEM_CLASS_NAMES.textSecondary]: grantConfig.isLabelColorSecondary })}
                        testId={'grant-amount-label'}
                    >
                        {i18n.get(grantConfig.amountLabelKey)}
                    </Typography>
                    <div id={elementIds.grantStatus}>
                        {grant.status === 'Active' ? (
                            <>
                                <Typography
                                    id={elementIds.termEnds}
                                    variant={TypographyVariant.CAPTION}
                                    el={TypographyElement.SPAN}
                                    aria-hidden={true}
                                >
                                    <Translation
                                        translationKey="capital.overview.grants.item.termEnds"
                                        fills={{
                                            date: (
                                                <time
                                                    aria-labelledby={elementIds.termEnds}
                                                    dateTime={grantConfig.repaymentPeriodEndDate.toISOString()}
                                                >
                                                    <Typography variant={TypographyVariant.CAPTION} stronger el={TypographyElement.SPAN}>
                                                        {dateFormat(grantConfig.repaymentPeriodEndDate, DATE_FORMAT_CAPITAL_OVERVIEW)}
                                                    </Typography>
                                                </time>
                                            ),
                                        }}
                                    />
                                </Typography>
                            </>
                        ) : grantConfig.statusKey ? (
                            grantConfig.statusTooltipKey ? (
                                <Tooltip content={i18n.get(grantConfig.statusTooltipKey)}>
                                    <div>
                                        <Tag label={i18n.get(grantConfig.statusKey)} variant={getStatusTagVariant(grantConfig.statusTagVariant)} />
                                    </div>
                                </Tooltip>
                            ) : (
                                <Tag label={i18n.get(grantConfig.statusKey)} variant={getStatusTagVariant(grantConfig.statusTagVariant)} />
                            )
                        ) : null}
                    </div>
                </div>
                <Typography
                    id={elementIds.grantAmount}
                    variant={TypographyVariant.TITLE}
                    medium
                    className={cx({
                        [GRANT_ITEM_CLASS_NAMES.textSecondary]: grantConfig.isAmountColorSecondary,
                    })}
                >
                    {i18n.amount(grantConfig.amount.value, grantConfig.amount.currency)}
                </Typography>
                {grantConfig.isProgressBarVisible && (
                    <ProgressBar
                        className={GRANT_ITEM_CLASS_NAMES.progressBar}
                        value={grant.repaidTotalAmount.value}
                        max={grant.totalAmount.value}
                        labels={{
                            ariaLabel: i18n.get('capital.overview.grants.item.progressBar.a11y.label'),
                            current: i18n.get('capital.overview.grants.item.amounts.repaid'),
                            max: i18n.get('capital.overview.grants.item.amounts.remaining'),
                        }}
                        tooltips={{
                            remaining: `${i18n.amount(grant.remainingTotalAmount.value, grant.remainingTotalAmount.currency)} ${i18n
                                .get('capital.overview.grants.item.amounts.remaining')
                                ?.toLowerCase()}`,
                            progress: `${i18n.amount(grant.repaidTotalAmount.value, grant.repaidTotalAmount.currency)} ${i18n
                                .get('capital.overview.grants.item.amounts.repaid')
                                ?.toLowerCase()}`,
                        }}
                    />
                )}
                {grantConfig.isGrantIdVisible ? (
                    <div className={GRANT_ITEM_CLASS_NAMES.grantID}>
                        <CopyText
                            textToCopy={grant.id}
                            visibleText={i18n.get('capital.common.fields.grantID')}
                            copyButtonAriaLabelKey="capital.overview.grants.item.actions.copyGrantID"
                            isUnderlineVisible
                            type={'Text' as const}
                            data-testid="grant-id-copy-text"
                        />
                    </div>
                ) : null}
                {grantConfig.hasUnscheduledRepaymentDetails && (
                    <div className={GRANT_ITEM_CLASS_NAMES.actionsBar}>
                        <Button
                            onClick={showUnscheduledRepaymentAccounts}
                            className={GRANT_ITEM_CLASS_NAMES.mainActionBtn}
                            variant={ButtonVariant.SECONDARY}
                            fullWidth
                        >
                            {i18n.get('capital.overview.grants.item.actions.sendRepayment')}
                        </Button>
                    </div>
                )}
            </div>
        ),
        [elementIds, grantConfig, i18n, grant, dateFormat, getStatusTagVariant, showUnscheduledRepaymentAccounts]
    );

    const handleActionsComplete = useCallback(() => {
        setActionsLocallyCompleted(true);
    }, []);

    return (
        <div className={GRANT_ITEM_CLASS_NAMES.base}>
            <ExpandableCard
                aria-describedby={`${elementIds.grantAmountLabel} ${elementIds.grantAmount} ${elementIds.grantStatus}`}
                aria-label={i18n.get('capital.overview.grants.item.details.a11y.label')}
                filled={grantConfig.isBackgroundFilled}
                renderContent={grantOverview}
                inFlow
            >
                {grantConfig.hasDetails && <GrantDetails grant={grant} />}
            </ExpandableCard>
            {grantConfig.hasAlerts && (
                <>
                    {grant.missingActions && grant.missingActions.length ? (
                        <GrantActions
                            grantId={grant.id}
                            missingActions={grant.missingActions}
                            className={GRANT_ITEM_CLASS_NAMES.alert}
                            offerExpiresAt={grant.offerExpiresAt}
                            onComplete={handleActionsComplete}
                        />
                    ) : (
                        <Alert
                            className={GRANT_ITEM_CLASS_NAMES.alert}
                            type={AlertTypeOption.HIGHLIGHT}
                            title={i18n.get('capital.overview.grants.item.alerts.processingRequest')}
                        />
                    )}
                </>
            )}
        </div>
    );
};
