// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/TransactionTotals.vue
<script setup lang="ts">
import { useCoreContext } from '../../../core/Context';
import TotalsCard from './TotalsCard.vue';
import type { ITransactionTotal } from '../types';

const props = defineProps<{
    totals: readonly Readonly<ITransactionTotal>[];
    loadingTotals: boolean;
}>();

const { i18n } = useCoreContext();

const BASE_CLASS = 'adyen-pe-transaction-totals';
</script>

<template>
    <div :class="BASE_CLASS">
        <!-- TODO: Add responsive container logic for xs breakpoint -->
        <TotalsCard :aria-label="i18n.get('transactions.overview.totals.labels.default')" :totals="props.totals" :is-loading="props.loadingTotals" />
    </div>
</template>

// packages/domains/transactions/preact/src/TransactionsOverview/components/TransactionTotals/TransactionTotals.tsx
import { memo } from 'preact/compat';
import { TotalsCard } from './TotalsCard';
import { BASE_CLASS, ITEM_CLASS } from './constants';
import { TransactionTotalsProps } from './types';
import { containerQueries, useResponsiveContainer } from '../../../../../../../../src/hooks/useResponsiveContainer';
import useCoreContext from '../../../../../../../../src/core/Context/useCoreContext';
import './TransactionTotals.scss';

const TransactionTotals = memo(({ loadingTotals, totals }: TransactionTotalsProps) => {
    const { i18n } = useCoreContext();
    const isXsContainer = useResponsiveContainer(containerQueries.only.xs);
    const isNarrowContainer = useResponsiveContainer(containerQueries.down.sm);

    return (
        <div className={BASE_CLASS}>
            {isXsContainer ? (
                <>
                    <div className={ITEM_CLASS}>
                        <TotalsCard
                            aria-label={i18n.get('transactions.overview.totals.labels.incoming')}
                            totals={totals}
                            isLoading={loadingTotals}
                            hiddenField="expenses"
                            fullWidth={isNarrowContainer}
                        />
                    </div>
                    <div className={ITEM_CLASS}>
                        <TotalsCard
                            aria-label={i18n.get('transactions.overview.totals.labels.outgoing')}
                            totals={totals}
                            isLoading={loadingTotals}
                            hiddenField="incomings"
                            fullWidth={isNarrowContainer}
                        />
                    </div>
                </>
            ) : (
                <TotalsCard
                    aria-label={i18n.get('transactions.overview.totals.labels.default')}
                    totals={totals}
                    isLoading={loadingTotals}
                    fullWidth={isNarrowContainer}
                />
            )}
        </div>
    );
});

export default TransactionTotals;
