// packages/domains/payByLink/preact/src/PaymentLinkDetails/components/PaymentLinkActivity/PaymentLinkActivity.tsx
import { useMemo } from 'preact/hooks';
import { useCoreContext } from '@integration-components/core/preact';
import { TimelineItem } from '@integration-components/ui-components-preact/Timeline/components/TimelineItem';
import Timeline from '@integration-components/ui-components-preact/Timeline/Timeline';
import { TimelineDateFormat } from '@integration-components/ui-components-preact/Timeline/types';
import { IPaymentLinkActivity } from '@integration-components/types';
import { getTitleKey, getDescriptionKey, getStatus } from './utils';

type PaymentLinkActivityProps = {
    activities: IPaymentLinkActivity[];
};

export const PaymentLinkActivity = ({ activities }: PaymentLinkActivityProps) => {
    const { i18n } = useCoreContext();

    const timelineItems = useMemo(
        () =>
            activities.map(activity => ({
                titleKey: getTitleKey(activity),
                descriptionKey: getDescriptionKey(activity),
                date: activity.date,
                status: getStatus(activity),
            })),
        [activities]
    );

    return (
        <Timeline>
            {timelineItems.map(({ titleKey, date, status, descriptionKey }: any) => (
                <TimelineItem
                    key={date}
                    title={i18n.get(titleKey)}
                    timestamp={{
                        date: new Date(date),
                        format: TimelineDateFormat.FULL_DATE_EXACT_TIME,
                    }}
                    status={status}
                    description={i18n.get(descriptionKey)}
                />
            ))}
        </Timeline>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkDetails/components/PaymentLinkActivity/PaymentLinkActivity.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoDateFormat, BentoTimeline, BentoTimelineItem } from '@adyen/bento-vue3';
import { getActivityDescriptionKey, getActivityStatus, getActivityTitleKey } from '../../../../../domain/src';
import type { IPaymentLinkActivity } from '@integration-components/types';
import { usePayByLinkContext } from '../../../integration/context';

const props = defineProps<{
    activities: IPaymentLinkActivity[];
}>();

const { i18n } = usePayByLinkContext();

const timelineItems = computed(() =>
    props.activities.map(activity => {
        const titleKey = getActivityTitleKey(activity);
        const descriptionKey = getActivityDescriptionKey(activity);
        return {
            title: titleKey ? i18n.get(titleKey) : undefined,
            description: descriptionKey ? i18n.get(descriptionKey) : undefined,
            date: new Date(activity.date),
            status: getActivityStatus(activity),
        } as const;
    })
);
</script>

<template>
    <BentoTimeline>
        <BentoTimelineItem
            v-for="(item, index) in timelineItems"
            :key="`${item.date.getTime()}_${index}`"
            :title="item.title"
            :description="item.description"
            :status="item.status"
            :timestamp="{
                date: item.date,
                format: BentoDateFormat.FULL_DATE_EXACT_TIME_WITHOUT_PERIOD,
            }"
        />
    </BentoTimeline>
</template>
