// packages/domains/disputes/vue/src/DisputesOverview/components/DisputeManagementModal.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { BentoModal } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import type { IDisputeStatusGroup } from '@integration-components/types/api/models/disputes';
import type { DisputeDetailsCustomization } from '@integration-components/disputes/domain';
import DisputeDetailsContainer from '../../DisputeManagement/components/DisputeDetailsContainer.vue';

const props = defineProps<{
    disputeId?: string;
    dataCustomization?: DisputeDetailsCustomization;
    onContactSupport?: () => void;
    refreshDisputesList: (statusGroup?: IDisputeStatusGroup) => void;
    onClose: () => void;
}>();

const { i18n } = useCoreContext();

const disputeManagementSuccessful = ref(false);
const isOpen = computed(() => !!props.disputeId);

watch(
    () => props.disputeId,
    id => {
        if (id) disputeManagementSuccessful.value = false;
    }
);

function onDisputeManagementSuccessful() {
    disputeManagementSuccessful.value = true;
}

function onCloseModal() {
    if (disputeManagementSuccessful.value) {
        disputeManagementSuccessful.value = false;
        props.refreshDisputesList('CHARGEBACKS');
    }
    props.onClose();
}
</script>

<template>
    <BentoModal
        :is-open="isOpen"
        size="small"
        :is-dismissible="true"
        :aria-label="i18n.get('disputes.management.common.title')"
        @close-modal="onCloseModal"
    >
        {{ i18n.get('disputes.management.common.title') }}
        <template #content>
            <DisputeDetailsContainer
                v-if="props.disputeId"
                :id="props.disputeId"
                :data-customization="props.dataCustomization ? { details: props.dataCustomization } : undefined"
                :on-contact-support="props.onContactSupport"
                :on-dispute-accept="onDisputeManagementSuccessful"
                :on-dispute-defend="onDisputeManagementSuccessful"
                :on-dismiss="onCloseModal"
                hide-title
            />
        </template>
    </BentoModal>
</template>

// src/components/external/DisputesOverview/components/DisputeManagementModal/DisputeManagementModal.tsx
import { useCallback, useEffect, useState } from 'preact/hooks';
import { FC, PropsWithChildren } from 'preact/compat';
import Modal from '../../../../internal/Modal';
import { DisputeDetailsCustomization } from '../../../DisputeManagement';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import { popoverUtil } from '../../../../internal/Popover/utils/popoverUtil';
import useModalDetails from '../../../../../hooks/useModalDetails';
import { IDisputeStatusGroup } from '../../../../../types/api/models/disputes';
import { DisputeDetailsContainer } from '../../../DisputeManagement/components/DisputeDetailsContainer/DisputeDetailsContainer';
import './DisputeManagementModal.scss';

export interface DisputeManagementModalProps {
    setModalVisible: (modalVisible: boolean) => void;
    refreshDisputesList: (statusGroup?: IDisputeStatusGroup) => void;
    selectedDetail: ReturnType<typeof useModalDetails>['selectedDetail'];
    resetDetails: ReturnType<typeof useModalDetails>['resetDetails'];
    dataCustomization?: { details: DisputeDetailsCustomization };
    onContactSupport?: () => void;
}

export const DisputeManagementModal: FC<DisputeManagementModalProps> = ({
    children,
    selectedDetail,
    resetDetails,
    dataCustomization,
    onContactSupport,
    refreshDisputesList,
    setModalVisible,
}: PropsWithChildren<DisputeManagementModalProps>) => {
    const { i18n } = useCoreContext();
    const [disputeManagementSuccessful, setDisputeManagementSuccessful] = useState(false);
    const isModalOpen = !!selectedDetail;

    const onCloseCallback = useCallback(() => {
        if (disputeManagementSuccessful) {
            setDisputeManagementSuccessful(false);
            refreshDisputesList('CHARGEBACKS');
        }
        setModalVisible(false);
        resetDetails();
    }, [disputeManagementSuccessful, refreshDisputesList, resetDetails, setModalVisible]);

    const onDisputeManagementSuccessful = useCallback(() => {
        setDisputeManagementSuccessful(true);
    }, []);

    useEffect(() => {
        if (isModalOpen) {
            setModalVisible(true);
            popoverUtil.closeAll();
        }
    }, [isModalOpen, setModalVisible]);

    return (
        <div>
            {children}
            {selectedDetail && (
                <Modal
                    isOpen={isModalOpen}
                    aria-label={i18n.get('disputes.disputeManagementTitle')}
                    onClose={onCloseCallback}
                    isDismissible={true}
                    headerWithBorder={false}
                    size={selectedDetail.modalSize || 'large'}
                >
                    <div className="adyen-pe-dispute-management-modal-content">
                        <DisputeDetailsContainer
                            id={selectedDetail.selection.data}
                            dataCustomization={dataCustomization}
                            onDisputeAccept={onDisputeManagementSuccessful}
                            onDisputeDefend={onDisputeManagementSuccessful}
                            onContactSupport={onContactSupport}
                            onDismiss={resetDetails}
                            hideTitle
                        />
                    </div>
                </Modal>
            )}
        </div>
    );
};
