// packages/domains/payouts/vue/src/PayoutDetails/components/PayoutData.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import {
    BentoTypography,
    BentoCard,
    BentoTag,
    BentoLink,
    BentoButtonActions,
    BentoDataGrid,
    BentoStructuredList,
    BentoStructuredListItem,
} from '@adyen/bento-vue3';
import type { BentoColumn, BentoDatagridDataItem } from '@adyen/bento-vue3';
import type { IPayoutDetails } from '@integration-components/types';
import { DATE_FORMAT_PAYOUT_DETAILS } from '@integration-components/utils';
import { formatAmountWithCurrencyCode } from '@integration-components/core/Localization/amount/amount-util';
import { useShouldHideTitles } from '@integration-components/composables-vue';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import { getPayoutAdjustmentType, getPayoutFundsCapturedType } from '@integration-components/payouts/domain';
import type { PayoutDetailsCustomization } from '../types';
import styles from './PayoutData.module.scss';

const props = defineProps<{
    payout?: IPayoutDetails;
    balanceAccountId: string;
    balanceAccountDescription?: string;
    extraFields?: Record<string, any> | undefined;
    dataCustomization?: { details?: PayoutDetailsCustomization };
    hideTitle?: boolean;
}>();

const { i18n } = useCoreContext();
const hideTitles = useShouldHideTitles();
const { dateFormat } = useTimezoneAwareDateFormatting('UTC');

const payoutInner = computed(() => props.payout?.payout);

// Adjustments: split into additions/subtractions, each sorted alphabetically by translation key.
type ListItem = { key: string; value: string };
const adjustments = computed(() => {
    const breakdown = props.payout?.amountBreakdowns?.adjustmentBreakdown;
    if (!breakdown) return undefined;
    const data: { subtractions: ListItem[]; additions: ListItem[] } = { subtractions: [], additions: [] };
    for (const currentValue of breakdown) {
        if (currentValue.category && currentValue.amount?.value) {
            const { currency, value: amount } = currentValue.amount;
            const target = data[amount && amount < 0 ? 'subtractions' : 'additions'];
            target.push({
                key: currentValue.category,
                value: `${i18n.amount(amount, currency, { hideCurrency: true })} ${currency}`,
            });
        }
    }
    data.subtractions.sort((a, b) => a.key.localeCompare(b.key));
    data.additions.sort((a, b) => a.key.localeCompare(b.key));
    return data;
});

// Funds captured breakdown: filter out zero-amount items, sort with `capture` first.
const fundsCaptured = computed<ListItem[] | undefined>(() => {
    const breakdown = props.payout?.amountBreakdowns?.fundsCapturedBreakdown;
    if (!breakdown) return undefined;
    const items: ListItem[] = [];
    for (const item of breakdown) {
        if (item?.amount?.value === 0) continue;
        if (item?.amount?.value && item.category) {
            items.push({
                key: item.category,
                value: `${i18n.amount(item.amount.value, item.amount.currency, { hideCurrency: true })} ${item.amount.currency}`,
            });
        }
    }
    items.sort((a, b) => {
        if (a.key === 'capture') return -1;
        if (b.key === 'capture') return 1;
        return a.key.localeCompare(b.key);
    });
    return items;
});

function isCustomDataObject(value: unknown): value is { type: string; value: any; config?: any } {
    return !!value && typeof value === 'object' && 'value' in value && 'type' in value;
}

interface ExtraDetailItem {
    key: string;
    value: any;
    type: string;
    config?: any;
}

const extraDetails = computed<ExtraDetailItem[]>(() => {
    const fields = props.extraFields as Record<string, any> | undefined;
    if (!fields) return [];
    return Object.entries(fields)
        .filter(([, field]) => (field as any)?.type !== 'button' && (field as any)?.visibility !== 'hidden')
        .map(([key, value]) => ({
            key,
            value: isCustomDataObject(value) ? value.value : value,
            type: isCustomDataObject(value) ? value.type : 'text',
            config: isCustomDataObject(value) ? value.config : undefined,
        }));
});

const buttonActions = computed(() => {
    const fields = props.extraFields as Record<string, any> | undefined;
    if (!fields) return [];
    return (Object.values(fields) as any[])
        .filter(field => field?.type === 'button')
        .map(field => ({
            title: field.value,
            event: field.config?.action,
        }));
});

const titleClass = computed(() => [styles.title, extraDetails.value.length ? styles.titleWithExtraDetails : '']);

function formatPayoutDate(dateStr: string): string {
    return dateFormat(dateStr, DATE_FORMAT_PAYOUT_DETAILS);
}

const formatAmount = (amount: { value: number; currency: string }) => formatAmountWithCurrencyCode(amount.value, i18n.locale, amount.currency);

const fundsCapturedColumns = computed<BentoColumn[]>(() => [
    {
        field: 'label',
        label: i18n.get('payouts.details.breakdown.fields.fundsCaptured'),
        flex: 1,
    },
    {
        field: 'quantity',
        label: '',
        flex: 1,
        numeric: true,
    },
]);

const additionsColumns = computed<BentoColumn[]>(() => [
    {
        field: 'label',
        label: i18n.get('payouts.details.breakdown.fields.additions'),
        flex: 1,
    },
    {
        field: 'quantity',
        label: '',
        flex: 1,
        numeric: true,
    },
]);

const subtractionsColumns = computed<BentoColumn[]>(() => [
    {
        field: 'label',
        label: i18n.get('payouts.details.breakdown.fields.subtractions'),
        flex: 1,
    },
    {
        field: 'quantity',
        label: '',
        flex: 1,
        numeric: true,
    },
]);

const fundsCapturedRows = computed<BentoDatagridDataItem[]>(() =>
    (fundsCaptured.value ?? []).map((item, index) => ({
        id: `${item.key}-${index}`,
        label: getPayoutFundsCapturedType(i18n, item.key),
        quantity: item.value,
    }))
);

const additionsRows = computed<BentoDatagridDataItem[]>(() =>
    (adjustments.value?.additions ?? []).map((item, index) => ({
        id: `${item.key}-${index}`,
        label: getPayoutAdjustmentType(i18n, item.key),
        quantity: item.value,
    }))
);

const subtractionsRows = computed<BentoDatagridDataItem[]>(() =>
    (adjustments.value?.subtractions ?? []).map((item, index) => ({
        id: `${item.key}-${index}`,
        label: getPayoutAdjustmentType(i18n, item.key),
        quantity: item.value,
    }))
);
</script>

<template>
    <div v-if="!props.hideTitle && !hideTitles" :class="styles.pageTitle">
        <BentoTypography variant="title">{{ i18n.get('payouts.details.title') }}</BentoTypography>
    </div>

    <div v-if="payoutInner" :class="styles.root">
        <!-- Title section -->
        <BentoCard>
            <template #content>
                <div :class="titleClass">
                    <div :class="styles.titleContainer">
                        <BentoTypography variant="title" stronger>
                            {{ i18n.get('payouts.details.tags.netPayout') }}
                        </BentoTypography>
                        <BentoTag v-if="payoutInner.isSumOfSameDayPayouts" variant="blue" :label="i18n.get('payouts.details.tags.sameDaySum')" />
                    </div>
                    <BentoTypography v-if="payoutInner.payoutAmount" variant="title" large>
                        {{ formatAmount(payoutInner.payoutAmount) }}
                    </BentoTypography>
                    <time v-if="payoutInner.createdAt" :datetime="payoutInner.createdAt">
                        <BentoTypography variant="body">
                            {{ formatPayoutDate(payoutInner.createdAt) }}
                        </BentoTypography>
                    </time>
                    <div>
                        <BentoTypography v-if="balanceAccountDescription" variant="body" strongest wide>
                            {{ balanceAccountDescription }}
                        </BentoTypography>
                        <BentoTypography variant="caption" :class="styles.balanceAccountId">
                            {{ balanceAccountId }}
                        </BentoTypography>
                    </div>
                </div>
                <!-- Extra details (consumer-supplied) -->
                <BentoStructuredList v-if="extraDetails.length" :class="styles.extraDetails">
                    <BentoStructuredListItem
                        v-for="item in extraDetails"
                        :key="item.key"
                        :label="i18n.get(item.key as any)"
                        :class="styles.extraDetailsLabel"
                    >
                        <BentoLink
                            v-if="item.type === 'link' && item.config"
                            :class="item.config.className"
                            :to="item.config.href"
                            :target="item.config.target || '_blank'"
                            rel="noopener noreferrer"
                            external
                        >
                            {{ item.value }}
                        </BentoLink>
                        <div v-else-if="item.type === 'icon' && item.config" :class="[styles.extraDetailsIcon, item.config.className]">
                            <img :src="item.config.src" :alt="item.config.alt || item.value" :class="item.config.className" />
                            <BentoTypography variant="body">{{ item.value }}</BentoTypography>
                        </div>
                        <BentoTypography v-else variant="body" :class="item.config?.className">{{ item.value }}</BentoTypography>
                    </BentoStructuredListItem>
                </BentoStructuredList>
            </template>
        </BentoCard>

        <!-- Content: funds captured + adjustments + net payout -->
        <div :class="styles.content">
            <!-- Funds captured -->
            <div>
                <template v-if="payoutInner.fundsCapturedAmount">
                    <BentoCard v-if="fundsCaptured && fundsCaptured.length" expandable closed>
                        <template #header>
                            <div :class="styles.cardHeader">
                                <BentoTypography variant="body" strongest>{{
                                    i18n.get('payouts.details.breakdown.fields.fundsCaptured')
                                }}</BentoTypography>
                                <BentoTypography variant="body">{{ formatAmount(payoutInner.fundsCapturedAmount) }}</BentoTypography>
                            </div>
                        </template>
                        <template #content>
                            <div>
                                <div :class="styles.card">
                                    <BentoDataGrid
                                        outline
                                        data-testid="payout-funds-captured-breakdown"
                                        :class="styles.dataGrid"
                                        :columns="fundsCapturedColumns"
                                        :data="fundsCapturedRows"
                                        :allow-row-clicks="false"
                                        :has-resizable-columns="false"
                                        :allow-column-drag-and-drop="false"
                                    >
                                        <template #item-label="{ item }">
                                            <BentoTypography variant="body">{{ item.label }}</BentoTypography>
                                        </template>
                                        <template #item-quantity="{ item }">
                                            <BentoTypography variant="body">{{ item.quantity }}</BentoTypography>
                                        </template>
                                    </BentoDataGrid>
                                </div>
                            </div>
                        </template>
                    </BentoCard>
                    <BentoCard v-else :class="styles.sectionAmount">
                        <template #content>
                            <div :class="styles.cardHeader">
                                <BentoTypography variant="body" strongest>
                                    {{ i18n.get('payouts.details.breakdown.fields.fundsCaptured') }}
                                </BentoTypography>
                                <BentoTypography variant="body">
                                    {{ formatAmount(payoutInner.fundsCapturedAmount) }}
                                </BentoTypography>
                            </div>
                        </template>
                    </BentoCard>
                </template>
            </div>

            <!-- Adjustments -->
            <div>
                <BentoCard v-if="adjustments && (adjustments.additions.length > 0 || adjustments.subtractions.length > 0)" expandable closed>
                    <template #header>
                        <div :class="styles.cardHeader">
                            <BentoTypography variant="body" strongest>
                                {{ i18n.get('payouts.details.breakdown.fields.adjustments') }}
                            </BentoTypography>
                            <BentoTypography v-if="payoutInner.adjustmentAmount" variant="body">
                                {{ formatAmount(payoutInner.adjustmentAmount) }}
                            </BentoTypography>
                        </div>
                    </template>
                    <template #content>
                        <div v-if="adjustments && adjustments.additions.length" :class="styles.card">
                            <div>
                                <BentoDataGrid
                                    outline
                                    data-testid="payout-adjustments-additions-breakdown"
                                    :class="styles.dataGrid"
                                    :columns="additionsColumns"
                                    :data="additionsRows"
                                    :allow-row-clicks="false"
                                    :has-resizable-columns="false"
                                    :allow-column-drag-and-drop="false"
                                >
                                    <template #item-label="{ item }">
                                        <BentoTypography variant="body">{{ item.label }}</BentoTypography>
                                    </template>
                                    <template #item-quantity="{ item }">
                                        <BentoTypography variant="body">{{ item.quantity }}</BentoTypography>
                                    </template>
                                </BentoDataGrid>
                            </div>
                        </div>
                        <div v-if="adjustments && adjustments.subtractions.length" :class="styles.card">
                            <div>
                                <BentoDataGrid
                                    outline
                                    data-testid="payout-adjustments-subtractions-breakdown"
                                    :class="styles.dataGrid"
                                    :columns="subtractionsColumns"
                                    :data="subtractionsRows"
                                    :allow-row-clicks="false"
                                    :has-resizable-columns="false"
                                    :allow-column-drag-and-drop="false"
                                >
                                    <template #item-label="{ item }">
                                        <BentoTypography variant="body">{{ item.label }}</BentoTypography>
                                    </template>
                                    <template #item-quantity="{ item }">
                                        <BentoTypography variant="body">{{ item.quantity }}</BentoTypography>
                                    </template>
                                </BentoDataGrid>
                            </div>
                        </div>
                    </template>
                </BentoCard>
                <BentoCard v-else :class="styles.sectionAmount">
                    <template #content>
                        <div :class="[styles.cardHeader, styles.cardHeaderSummary]">
                            <BentoTypography variant="body" strongest>
                                {{ i18n.get('payouts.details.breakdown.fields.adjustments') }}
                            </BentoTypography>
                            <BentoTypography v-if="payoutInner.adjustmentAmount" variant="body" stronger>
                                {{ formatAmount(payoutInner.adjustmentAmount) }}
                            </BentoTypography>
                        </div>
                    </template>
                </BentoCard>
            </div>

            <!-- Net payout (always shown) -->
            <div>
                <BentoCard>
                    <template #content>
                        <div :class="[styles.cardHeader, styles.cardHeaderSummary]">
                            <BentoTypography variant="body" strongest>
                                {{ i18n.get('payouts.details.breakdown.fields.netPayout') }}
                            </BentoTypography>
                            <BentoTypography v-if="payoutInner.payoutAmount" variant="body" strongest>
                                {{ formatAmount(payoutInner.payoutAmount) }}
                            </BentoTypography>
                        </div>
                    </template>
                </BentoCard>
            </div>
        </div>

        <!-- Unpaid amount -->
        <BentoCard v-if="payoutInner.unpaidAmount" :background="'secondary'">
            <template #content>
                <div :class="[styles.cardHeader, styles.cardHeaderSummary]">
                    <BentoTypography variant="body">{{ i18n.get('payouts.details.breakdown.fields.remainingAmount') }}</BentoTypography>
                    <BentoTypography variant="body">
                        {{ formatAmount(payoutInner.unpaidAmount) }}
                    </BentoTypography>
                </div>
            </template>
        </BentoCard>

        <!-- Button actions -->
        <div v-if="buttonActions.length" :class="styles.buttonActions">
            <BentoButtonActions :actions="buttonActions" layout="BUTTONS_END" />
        </div>
    </div>
</template>

// src/components/external/PayoutDetails/components/PayoutData.tsx
import classnames from 'classnames';
import cx from 'classnames';
import { useMemo } from 'preact/hooks';
import useCoreContext from '../../../../core/Context/useCoreContext';
import { TranslationKey } from '../../../../translations';
import { IPayoutDetails } from '../../../../types';
import { EMPTY_OBJECT } from '../../../../utils';
import Accordion from '../../../internal/Accordion/Accordion';
import Card from '../../../internal/Card/Card';
import { DATE_FORMAT_PAYOUT_DETAILS } from '../../../../constants';
import StructuredList from '../../../internal/StructuredList';
import { ListValue, StructuredListProps } from '../../../internal/StructuredList/types';
import { TypographyElement, TypographyVariant } from '../../../internal/Typography/types';
import Typography from '../../../internal/Typography/Typography';
import DataOverviewDetailsSkeleton from '../../../internal/DataOverviewDetails/DataOverviewDetailsSkeleton';
import useTimezoneAwareDateFormatting from '../../../../hooks/useTimezoneAwareDateFormatting';
import './PayoutData.scss';
import {
    PD_BASE_CLASS,
    PD_BUTTON_ACTIONS,
    PD_CARD_CLASS,
    PD_CARD_TITLE_CLASS,
    PD_CONTENT_CLASS,
    PD_EXTRA_DETAILS_CLASS,
    PD_EXTRA_DETAILS_ICON,
    PD_EXTRA_DETAILS_LABEL,
    PD_SECTION_AMOUNT_CLASS,
    PD_SECTION_CLASS,
    PD_SECTION_GROSS_AMOUNT_CLASS,
    PD_SECTION_NET_AMOUNT_CLASS,
    PD_TITLE_BA_CLASS,
    PD_TITLE_CLASS,
    PD_TITLE_CLASS_WITH_EXTRA_DETAILS,
    PD_TITLE_CONTAINER_CLASS,
    PD_UNPAID_AMOUNT,
} from './constants';
import { Tag } from '../../../internal/Tag/Tag';
import { TagVariant } from '../../../internal/Tag/types';
import Link from '../../../internal/Link/Link';
import Icon from '../../../internal/DataGrid/components/Icon';
import { isCustomDataObject } from '../../../internal/DataGrid/components/TableCells';
import { ButtonVariant } from '../../../internal/Button/types';
import { ButtonActionsLayoutBasic } from '../../../internal/Button/ButtonActions/types';
import ButtonActions from '../../../internal/Button/ButtonActions/ButtonActions';
import { PayoutDetailsCustomization } from '../types';
import { getPayoutAdjustmentType, getPayoutFundsCapturedType } from '../../../utils/translation/getters';
import { TranslationFactoryFunction } from '../../../utils/translation/factory';

export const PayoutData = ({
    balanceAccountId,
    balanceAccountDescription,
    payout: payoutData,
    extraFields,
}: {
    payout?: IPayoutDetails;
    isFetching?: boolean;
    balanceAccountId: string;
    balanceAccountDescription?: string;
    extraFields?: Record<string, any> | undefined;
    dataCustomization?: { details?: PayoutDetailsCustomization };
}) => {
    const { payout } = payoutData ?? (EMPTY_OBJECT as NonNullable<typeof payoutData>);
    const { dateFormat } = useTimezoneAwareDateFormatting('UTC');
    const { i18n } = useCoreContext();

    const adjustments = useMemo(() => {
        const data = payoutData?.amountBreakdowns?.adjustmentBreakdown?.reduce(
            (accumulator, currentValue) => {
                if (currentValue.category && currentValue.amount?.value) {
                    const { currency, value: amount } = currentValue.amount;
                    const targetObj = accumulator[amount && amount < 0 ? 'subtractions' : 'additions'];

                    targetObj.push({
                        key: currentValue.category as TranslationKey,
                        value: i18n.amount(amount, currency, { hideCurrency: true }),
                    });
                }
                return accumulator;
            },
            { subtractions: [] as { key: TranslationKey; value: ListValue }[], additions: [] as { key: TranslationKey; value: ListValue }[] }
        );
        data?.subtractions.sort((a, b) => a.key.localeCompare(b.key));
        data?.additions.sort((a, b) => a.key.localeCompare(b.key));
        return data;
    }, [i18n, payoutData]);

    const fundsCaptured = useMemo(() => {
        const data = payoutData?.amountBreakdowns?.fundsCapturedBreakdown?.reduce(
            (items, breakdown) => {
                if (breakdown?.amount?.value === 0) return items;
                if (breakdown?.amount?.value && breakdown.category) {
                    items.push({
                        key: breakdown.category as TranslationKey,
                        value: i18n.amount(breakdown?.amount?.value, breakdown?.amount?.currency, { hideCurrency: true }),
                    });
                }
                return items;
            },
            [] as { key: TranslationKey; value: ListValue }[]
        );
        data?.sort((a, b) => {
            const captureType = 'capture' as TranslationKey;
            if (a.key === captureType) return -1;
            if (b.key === captureType) return 1;
            return a.key.localeCompare(b.key);
        });
        return data;
    }, [payoutData, i18n]);

    const { payoutAdjustmentTypeLabelRenderer, payoutFundsCapturedTypeLabelRenderer } = useMemo(() => {
        const payoutBreakdownTypeLabelRenderer =
            (translationFn: TranslationFactoryFunction): StructuredListProps['renderLabel'] =>
            (_, type) => {
                return (
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                        {translationFn(i18n, type)}
                    </Typography>
                );
            };

        return {
            payoutAdjustmentTypeLabelRenderer: payoutBreakdownTypeLabelRenderer(getPayoutAdjustmentType),
            payoutFundsCapturedTypeLabelRenderer: payoutBreakdownTypeLabelRenderer(getPayoutFundsCapturedType),
        } as const;
    }, [i18n]);

    const extraDetails: StructuredListProps['items'] =
        Object.entries(extraFields || {})
            .filter(([, field]) => field.type !== 'button' && field.visibility !== 'hidden')
            .map(([key, value]) => ({
                key: key as TranslationKey,
                value: isCustomDataObject(value) ? value.value : value,
                type: isCustomDataObject(value) ? value.type : 'text',
                config: isCustomDataObject(value) ? value.config : undefined,
            })) || [];

    const buttonActions = useMemo(() => {
        const extraActions = extraFields
            ? Object.values(extraFields)
                  .filter(field => field.type === 'button')
                  .map(field => ({
                      title: field.value,
                      variant: ButtonVariant.SECONDARY,
                      event: field.config?.action,
                      classNames: field?.config?.className ? [field?.config?.className] : [],
                  }))
            : [];
        const actions = [...extraActions].filter(Boolean);
        return actions;
    }, [extraFields]);

    return (
        <>
            {!payout ? (
                <DataOverviewDetailsSkeleton skeletonRowNumber={6} />
            ) : (
                <div className={PD_BASE_CLASS}>
                    <div
                        className={cx(PD_TITLE_CLASS, {
                            [PD_TITLE_CLASS_WITH_EXTRA_DETAILS]: extraDetails.length,
                        })}
                    >
                        <div className={PD_TITLE_CONTAINER_CLASS}>
                            <Typography variant={TypographyVariant.SUBTITLE} stronger>
                                {i18n.get('payouts.details.tags.netPayout')}
                            </Typography>
                            {payout.isSumOfSameDayPayouts && (
                                <Tag variant={TagVariant.BLUE} label={i18n.get('payouts.details.tags.sameDaySum')}></Tag>
                            )}
                        </div>
                        <Typography variant={TypographyVariant.TITLE} large>
                            {`${i18n.amount(payout.payoutAmount.value, payout.payoutAmount.currency, {
                                hideCurrency: true,
                            })} ${payout.payoutAmount.currency}`}
                        </Typography>
                        {payout?.createdAt && (
                            <time dateTime={payout.createdAt}>
                                <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                                    {dateFormat(payout.createdAt, DATE_FORMAT_PAYOUT_DETAILS)}
                                </Typography>
                            </time>
                        )}
                        <div className={PD_SECTION_CLASS}>
                            {balanceAccountDescription && (
                                <Typography variant={TypographyVariant.CAPTION} stronger wide>
                                    {`${balanceAccountDescription}`}
                                </Typography>
                            )}
                            <Typography variant={TypographyVariant.CAPTION} className={PD_TITLE_BA_CLASS}>{`${balanceAccountId}`}</Typography>
                        </div>
                    </div>
                    {extraDetails && extraDetails.length > 0 ? (
                        <div>
                            <StructuredList
                                classNames={PD_EXTRA_DETAILS_CLASS}
                                items={extraDetails}
                                align="start"
                                layout="4-8"
                                renderLabel={label => <div className={PD_EXTRA_DETAILS_LABEL}>{label}</div>}
                                renderValue={(val, key, type, config) => {
                                    if (type === 'link' && config) {
                                        return (
                                            <Link classNames={[cx(config?.className)]} href={config.href} target={config.target || '_blank'}>
                                                {val}
                                            </Link>
                                        );
                                    }
                                    if (type === 'icon' && config) {
                                        const icon = { url: config.src, alt: config.alt || val };
                                        return (
                                            <div className={cx(PD_EXTRA_DETAILS_ICON, config?.className)}>
                                                <Icon {...icon} />
                                                <Typography variant={TypographyVariant.BODY}>{val}</Typography>
                                            </div>
                                        );
                                    }
                                    return (
                                        <Typography className={cx(config?.className)} variant={TypographyVariant.BODY}>
                                            {val}
                                        </Typography>
                                    );
                                }}
                            />
                        </div>
                    ) : null}
                    <div className={PD_CONTENT_CLASS}>
                        <div className={PD_SECTION_CLASS}>
                            {payout?.fundsCapturedAmount &&
                                (fundsCaptured && Object.keys(fundsCaptured).length > 0 ? (
                                    <Accordion
                                        header={
                                            <Typography variant={TypographyVariant.BODY}>
                                                {i18n.get('payouts.details.breakdown.fields.fundsCaptured')}
                                            </Typography>
                                        }
                                        headerInformation={
                                            <Typography variant={TypographyVariant.BODY}>
                                                {i18n.amount(payout.fundsCapturedAmount.value, payout.fundsCapturedAmount.currency)}
                                            </Typography>
                                        }
                                    >
                                        <div className={PD_SECTION_CLASS}>
                                            {
                                                <div className={PD_CARD_CLASS}>
                                                    <Card noPadding>
                                                        <StructuredList items={fundsCaptured} renderLabel={payoutFundsCapturedTypeLabelRenderer} />
                                                    </Card>
                                                </div>
                                            }
                                        </div>
                                    </Accordion>
                                ) : (
                                    <div className={classnames(PD_SECTION_AMOUNT_CLASS, PD_SECTION_GROSS_AMOUNT_CLASS)}>
                                        <Typography variant={TypographyVariant.BODY}>
                                            {i18n.get('payouts.details.breakdown.fields.fundsCaptured')}
                                        </Typography>
                                        <Typography variant={TypographyVariant.BODY}>
                                            {i18n.amount(payout.fundsCapturedAmount.value, payout.fundsCapturedAmount.currency)}
                                        </Typography>
                                    </div>
                                ))}
                        </div>
                        <div className={PD_SECTION_CLASS}>
                            {(adjustments?.subtractions && Object.keys(adjustments?.subtractions).length > 0) ||
                            (adjustments?.additions && Object.keys(adjustments?.additions).length > 0) ? (
                                <Accordion
                                    header={
                                        <Typography variant={TypographyVariant.BODY}>
                                            {i18n.get('payouts.details.breakdown.fields.adjustments')}
                                        </Typography>
                                    }
                                    headerInformation={
                                        <Typography variant={TypographyVariant.BODY}>
                                            {i18n.amount(payout.adjustmentAmount.value, payout.adjustmentAmount.currency)}
                                        </Typography>
                                    }
                                >
                                    {adjustments?.additions && Object.keys(adjustments?.additions).length > 0 && (
                                        <div className={PD_CARD_CLASS}>
                                            <Card
                                                noPadding
                                                renderHeader={
                                                    <Typography className={PD_CARD_TITLE_CLASS} variant={TypographyVariant.CAPTION} stronger>
                                                        {i18n.get('payouts.details.breakdown.fields.additions')}
                                                    </Typography>
                                                }
                                            >
                                                <StructuredList items={adjustments?.additions} renderLabel={payoutAdjustmentTypeLabelRenderer} />
                                            </Card>
                                        </div>
                                    )}
                                    {adjustments?.subtractions && Object.keys(adjustments?.subtractions).length > 0 && (
                                        <div className={PD_CARD_CLASS}>
                                            <Card
                                                noPadding
                                                renderHeader={
                                                    <Typography className={PD_CARD_TITLE_CLASS} variant={TypographyVariant.CAPTION} stronger>
                                                        {i18n.get('payouts.details.breakdown.fields.subtractions')}
                                                    </Typography>
                                                }
                                            >
                                                <StructuredList items={adjustments?.subtractions} renderLabel={payoutAdjustmentTypeLabelRenderer} />
                                            </Card>
                                        </div>
                                    )}
                                </Accordion>
                            ) : (
                                <div className={classnames(PD_SECTION_AMOUNT_CLASS, PD_SECTION_GROSS_AMOUNT_CLASS)}>
                                    <Typography variant={TypographyVariant.BODY}>
                                        {i18n.get('payouts.details.breakdown.fields.adjustments')}
                                    </Typography>
                                    <Typography variant={TypographyVariant.BODY}>
                                        {i18n.amount(payout.adjustmentAmount.value, payout.adjustmentAmount.currency)}
                                    </Typography>
                                </div>
                            )}
                        </div>
                        <div className={classnames(PD_SECTION_CLASS)}>
                            <div className={classnames(PD_SECTION_AMOUNT_CLASS, PD_SECTION_NET_AMOUNT_CLASS)}>
                                <Typography variant={TypographyVariant.BODY} stronger>
                                    {i18n.get('payouts.details.breakdown.fields.netPayout')}
                                </Typography>
                                <Typography variant={TypographyVariant.BODY} stronger>
                                    {i18n.amount(payout.payoutAmount.value, payout.payoutAmount.currency)}
                                </Typography>
                            </div>
                        </div>
                    </div>
                    {payoutData?.payout?.unpaidAmount && (
                        <div className={PD_UNPAID_AMOUNT}>
                            <Typography variant={TypographyVariant.BODY}>{i18n.get('payouts.details.breakdown.fields.remainingAmount')}</Typography>
                            <Typography variant={TypographyVariant.BODY}>
                                {i18n.amount(payoutData.payout.unpaidAmount.value, payoutData.payout.unpaidAmount.currency)}
                            </Typography>
                        </div>
                    )}
                    {buttonActions.length ? (
                        <div className={PD_BUTTON_ACTIONS}>
                            <ButtonActions actions={buttonActions} layout={ButtonActionsLayoutBasic.BUTTONS_END} />
                        </div>
                    ) : null}
                </div>
            )}
        </>
    );
};
