// src/components/external/DisputeManagement/components/DisputesData/DisputeData.tsx
import cx from 'classnames';
import { useCallback, useEffect, useMemo, useState } from 'preact/hooks';
import { useConfigContext } from '../../../../../core/ConfigContext';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import { useFetch } from '../../../../../hooks/useFetch';
import { containerQueries, useResponsiveContainer } from '../../../../../hooks/useResponsiveContainer';
import { IDisputeDetail } from '../../../../../types/api/models/disputes';
import { EMPTY_OBJECT, isFunction } from '../../../../../utils';
import './DisputeData.scss';
import Alert from '../../../../internal/Alert/Alert';
import { AlertTypeOption, AlertVariantOption } from '../../../../internal/Alert/types';
import ButtonActions from '../../../../internal/Button/ButtonActions/ButtonActions';
import { ButtonVariant } from '../../../../internal/Button/types';
import StatusBox from '../../../../internal/StatusBox/StatusBox';
import useStatusBoxData from '../../../../internal/StatusBox/useStatusBox';
import { Tag } from '../../../../internal/Tag/Tag';
import { Translation } from '../../../../internal/Translation';
import DisputeStatusTag from '../../../DisputesOverview/components/DisputesTable/DisputeStatusTag';
import { useDisputeFlow } from '../../context/dispute/context';
import { DisputeDetailsCustomization, DisputeManagementProps } from '../../types';
import { isDisputeActionNeeded } from '../../../../utils/disputes/actionNeeded';
import { DISPUTE_TYPES } from '../../../../utils/disputes/constants';
import { DisputeIssuerComments } from './DisputeIssuerComments';
import DisputeDataProperties from './DisputeDataProperties';
import {
    DISPUTE_DATA_ACTION_BAR,
    DISPUTE_DATA_CLASS,
    DISPUTE_DATA_ERROR_CONTAINER,
    DISPUTE_DATA_MOBILE_CLASS,
    DISPUTE_STATUS_BOX,
    DISPUTE_DATA_STATUS_BOX_SKELETON,
    DISPUTE_DATA_SKELETON_CONTAINER,
    DISPUTE_DATA_STATUS_BOX_STATUS,
    DISPUTE_DATA_STATUS_BOX_AMOUNT,
    DISPUTE_DATA_STATUS_BOX_PAYMENT_METHOD,
    DISPUTE_DATA_STATUS_BOX_STATUS_CONTAINER,
    DISPUTE_DATA_STATUS_BOX_PAYMENT_METHOD_CONTAINER,
    DISPUTE_DATA_PROPERTIES_SKELETON,
    DISPUTE_DATA_PROPERTIES_SKELETON_CONTAINER,
    DISPUTE_DATA_PROPERTIES_SKELETON_ELEMENT,
} from './constants';
import Button from '../../../../internal/Button';
import Typography from '../../../../internal/Typography/Typography';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import useTimezoneAwareDateFormatting from '../../../../../hooks/useTimezoneAwareDateFormatting';
import { DATE_FORMAT_RESPONSE_DEADLINE } from '../../../../../constants';
import { ErrorMessageDisplay } from '../../../../internal/ErrorMessageDisplay/ErrorMessageDisplay';
import AdyenPlatformExperienceError from '../../../../../core/Errors/AdyenPlatformExperienceError';
import { getDisputesErrorMessage } from '../../../../utils/disputes/getDisputesErrorMessage';
import { CustomButtonObject } from '../../../../types';

type DisputeDataAlertMode = 'contactSupport' | 'autoDefended' | 'notDefended' | 'notDefendable';

const _isButtonType = (item: any): item is CustomButtonObject => {
    return !!item && typeof item === 'object' && item.type === 'button';
};
const DisputeDataAlert = ({
    alertMode,
    dispute,
    timeZone,
}: {
    alertMode?: DisputeDataAlertMode;
    dispute: IDisputeDetail['dispute'];
    timeZone: string | undefined;
}) => {
    const { i18n } = useCoreContext();
    const { dateFormat } = useTimezoneAwareDateFormatting(timeZone);

    switch (alertMode) {
        case 'contactSupport': {
            const { dueDate, type } = dispute;
            const translationKey =
                type === 'REQUEST_FOR_INFORMATION'
                    ? 'disputes.contactSupport.toDefendRequestForInformation'
                    : type === 'NOTIFICATION_OF_FRAUD'
                    ? 'disputes.contactSupport.toResolveNotificationOfFraud'
                    : 'disputes.contactSupport.toDefendDispute';

            return (
                <Alert
                    type={AlertTypeOption.WARNING}
                    variant={AlertVariantOption.TIP}
                    description={
                        <>
                            {i18n.get(translationKey)}
                            {type !== 'NOTIFICATION_OF_FRAUD' && !!dueDate && (
                                <>
                                    {' '}
                                    <Translation
                                        translationKey={'disputes.alert.responseDeadline'}
                                        fills={{
                                            date: (
                                                <Typography variant={TypographyVariant.CAPTION} el={TypographyElement.SPAN} stronger>
                                                    {dateFormat(dueDate, DATE_FORMAT_RESPONSE_DEADLINE)}
                                                </Typography>
                                            ),
                                        }}
                                    />
                                </>
                            )}
                        </>
                    }
                />
            );
        }
        case 'autoDefended':
            return <Alert type={AlertTypeOption.HIGHLIGHT} variant={AlertVariantOption.TIP} description={i18n.get('disputes.alert.autoDefended')} />;
        case 'notDefended': {
            const translationKey = dispute.status === 'EXPIRED' ? 'disputes.alert.notDefendedExpired' : 'disputes.alert.notDefendedLost';
            return <Alert type={AlertTypeOption.HIGHLIGHT} variant={AlertVariantOption.TIP} description={i18n.get(translationKey)} />;
        }
        case 'notDefendable':
            return <Alert type={AlertTypeOption.HIGHLIGHT} variant={AlertVariantOption.TIP} description={i18n.get('disputes.alert.notDefendable')} />;
    }

    return null;
};

export const DisputeData = ({
    disputeId,
    dataCustomization,
    onContactSupport,
    onDismiss,
}: {
    disputeId: string;
    dataCustomization?: { details?: DisputeDetailsCustomization };
    onContactSupport?: () => void;
    onDismiss: DisputeManagementProps['onDismiss'];
}) => {
    const { i18n } = useCoreContext();
    const { dispute: storedDispute, setDispute, setFlowState } = useDisputeFlow();

    const { getDisputeDetail, getApplicableDefenseDocuments, acceptDispute } = useConfigContext().endpoints;

    //TODO: Also check if /defend endpoint has been returned from setup call which relates to submit button action
    const acceptAuthorization = isFunction(acceptDispute);
    const defendAuthorization = isFunction(getApplicableDefenseDocuments);
    const isSmAndUpContainer = useResponsiveContainer(containerQueries.up.sm);

    const { data, isFetching, error } = useFetch(
        useMemo(
            () => ({
                fetchOptions: {
                    enabled: !!disputeId && !!getDisputeDetail && !storedDispute,
                    onSuccess: ((dispute: IDisputeDetail) => {
                        setDispute(dispute);
                    }) as any,
                },
                queryFn: async () => {
                    return getDisputeDetail!(EMPTY_OBJECT, {
                        path: {
                            disputePspReference: disputeId,
                        },
                    });
                },
            }),
            [storedDispute, disputeId, getDisputeDetail, setDispute]
        )
    );

    const dispute = storedDispute || data;
    const defensibility = dispute?.dispute?.defensibility;

    const statusBoxOptions = useStatusBoxData({
        amountData: dispute?.dispute.amount,
        paymentMethodData: dispute?.payment.paymentMethod,
    } as const);

    const issuerComments = useMemo(() => {
        const { chargeback, preArbitration } = dispute?.dispute.issuerExtraData ?? {};
        const comments = [] as string[];

        [preArbitration, chargeback].forEach(commentGroup => {
            if (!commentGroup) return;
            ['LIABILITY_NOT_ACCEPTED_FULLY', 'PRE_ARB_REASON', 'NOTE'].forEach(commentKey => {
                const raw = commentGroup[commentKey];
                const trimmed = raw?.trim();
                if (trimmed) comments.push(trimmed);
            });
        });

        return comments.filter(Boolean);
    }, [dispute]);

    const disputeType = useMemo(() => {
        const type = dispute?.dispute.type;
        return type && i18n.get(DISPUTE_TYPES[type]);
    }, [i18n, dispute]);

    const showContactSupport =
        (!!defensibility && ['ACCEPTABLE', 'DEFENDABLE_EXTERNALLY'].includes(defensibility)) || dispute?.dispute.type === 'NOTIFICATION_OF_FRAUD';
    const isDefendable = !!defensibility && defensibility === 'DEFENDABLE' && defendAuthorization;
    const isAcceptable = !!defensibility && ['ACCEPTABLE', 'DEFENDABLE'].includes(defensibility) && acceptAuthorization;

    const onAcceptClick = useCallback(() => {
        setFlowState('accept');
    }, [setFlowState]);

    const onDefendClick = useCallback(() => {
        setFlowState('defendReasonSelectionView');
    }, [setFlowState]);

    const [extraButtons, setExtraButtons] = useState<CustomButtonObject[]>([]);

    const getCustomButtons = useCallback(async () => {
        const customData = data && (await dataCustomization?.details?.onDataRetrieve?.(data));
        if (customData) {
            return setExtraButtons(
                Object.values(customData).filter(config => {
                    return _isButtonType(config);
                }) as CustomButtonObject[]
            );
        }
    }, [data, dataCustomization?.details]);

    useEffect(() => {
        void getCustomButtons();
    }, [getCustomButtons]);

    const actionButtons = useMemo(() => {
        const ctaButtons = [];
        if (isDefendable)
            ctaButtons.push({
                title: i18n.get('disputes.defend.chargeback'),
                event: onDefendClick,
            });
        if (isAcceptable) {
            ctaButtons.push({
                title: i18n.get('disputes.accept'),
                event: onAcceptClick,
                variant: ButtonVariant.SECONDARY,
            });
        }
        if (showContactSupport && isFunction(onContactSupport)) {
            ctaButtons.push({
                title: i18n.get('contactSupport'),
                event: onContactSupport,
                variant: ButtonVariant.SECONDARY,
            });
        }

        if (extraButtons && extraButtons.length) {
            extraButtons.forEach((config: CustomButtonObject) => {
                ctaButtons.push({
                    title: config?.value,
                    event: config?.config?.action,
                    variant: ButtonVariant.SECONDARY,
                });
            });
        }
        return ctaButtons;
    }, [isDefendable, i18n, onDefendClick, isAcceptable, showContactSupport, onContactSupport, extraButtons, onAcceptClick]);

    const actionNeeded = useMemo(() => !!dispute && isDisputeActionNeeded(dispute.dispute), [dispute]);

    const renderBackButton = useCallback(() => {
        return (
            <Button variant={ButtonVariant.SECONDARY} onClick={onDismiss}>
                {i18n.get('disputes.goBack')}
            </Button>
        );
    }, [i18n, onDismiss]);

    if ((!dispute && !error) || isFetching) {
        const skeletonRows = Array.from({ length: 5 });

        return (
            <div className={cx(DISPUTE_DATA_CLASS, { [DISPUTE_DATA_MOBILE_CLASS]: !isSmAndUpContainer })}>
                <div className={DISPUTE_DATA_SKELETON_CONTAINER}>
                    <div className={DISPUTE_DATA_STATUS_BOX_SKELETON}>
                        <div className={DISPUTE_DATA_STATUS_BOX_STATUS_CONTAINER}>
                            <span className={DISPUTE_DATA_STATUS_BOX_STATUS}></span>
                            <span className={DISPUTE_DATA_STATUS_BOX_STATUS}></span>
                        </div>
                        <span className={DISPUTE_DATA_STATUS_BOX_AMOUNT}></span>
                        <div className={DISPUTE_DATA_STATUS_BOX_PAYMENT_METHOD_CONTAINER}>
                            <span className={DISPUTE_DATA_STATUS_BOX_PAYMENT_METHOD}></span>
                            <span className={DISPUTE_DATA_STATUS_BOX_PAYMENT_METHOD}></span>
                        </div>
                    </div>
                    <div className={DISPUTE_DATA_PROPERTIES_SKELETON_CONTAINER}>
                        {skeletonRows.map((_, index) => (
                            <div className={DISPUTE_DATA_PROPERTIES_SKELETON} key={`skeleton-${index}`}>
                                <span className={DISPUTE_DATA_PROPERTIES_SKELETON_ELEMENT} />
                                <span className={DISPUTE_DATA_PROPERTIES_SKELETON_ELEMENT} />
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        );
    }

    const isFraudNotification = dispute?.dispute.type === 'NOTIFICATION_OF_FRAUD';
    const isDefended = !!(dispute?.defense && dispute.defense.defendedOn);

    let disputeAlertMode: DisputeDataAlertMode | undefined = undefined;

    if (dispute?.defense?.autodefended === true) {
        disputeAlertMode = 'autoDefended';
    } else if (actionNeeded && defensibility === 'NOT_ACTIONABLE') {
        disputeAlertMode = 'notDefendable';
    } else if ((actionNeeded && showContactSupport) || (showContactSupport && isFraudNotification)) {
        disputeAlertMode = 'contactSupport';
    } else if (dispute?.dispute.status === 'EXPIRED') {
        disputeAlertMode = 'notDefended';
    } else if (dispute?.dispute.status === 'LOST' && !(isFraudNotification || isDefended)) {
        disputeAlertMode = 'notDefended';
    }

    const errorProps = getDisputesErrorMessage(error as AdyenPlatformExperienceError, 'disputes.error.weCouldNotLoadYourDispute', onContactSupport);

    return (
        <div className={cx(DISPUTE_DATA_CLASS, { [DISPUTE_DATA_MOBILE_CLASS]: !isSmAndUpContainer })}>
            {error ? (
                <div className={DISPUTE_DATA_ERROR_CONTAINER}>
                    <ErrorMessageDisplay
                        renderSecondaryButton={onDismiss ? renderBackButton : undefined}
                        withImage
                        outlined={false}
                        absolutePosition={false}
                        withBackground={false}
                        {...errorProps}
                    />
                </div>
            ) : dispute ? (
                <>
                    <div className={DISPUTE_STATUS_BOX}>
                        <StatusBox
                            {...statusBoxOptions}
                            tag={
                                <>
                                    {disputeType && <Tag label={disputeType} />}
                                    {!isFraudNotification && <DisputeStatusTag dispute={dispute.dispute} />}
                                </>
                            }
                        />
                    </div>

                    {issuerComments.length > 0 && <DisputeIssuerComments issuerComments={issuerComments} />}

                    {disputeAlertMode && (
                        <DisputeDataAlert
                            alertMode={disputeAlertMode}
                            dispute={dispute.dispute}
                            timeZone={dispute.payment.balanceAccount?.timeZone}
                        />
                    )}

                    <DisputeDataProperties dispute={dispute} dataCustomization={dataCustomization} />

                    {actionButtons.length > 0 ? (
                        <div className={DISPUTE_DATA_ACTION_BAR}>
                            <ButtonActions actions={actionButtons} />
                        </div>
                    ) : null}
                </>
            ) : null}
        </div>
    );
};

export default DisputeData;

// packages/domains/disputes/vue/src/DisputeManagement/components/DisputeData.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { BentoButton, BentoButtonActions, BentoCard, BentoLoadingIndicator, BentoPaymentMethod, BentoTag, BentoTypography } from '@adyen/bento-vue3';
import { useConfigContext, useCoreContext } from '@integration-components/core/vue';
import { ErrorMessageDisplay } from '@integration-components/composables-vue';
import {
    DISPUTE_DETAILS_RESERVED_FIELDS_SET,
    getDisputeType,
    isDisputeActionNeeded,
    type DisputeDetailsCustomization,
} from '@integration-components/disputes/domain';
import { isFunction, parsePaymentMethodType } from '@integration-components/utils';
import type { CustomButtonObject, CustomDataRetrieved } from '@integration-components/types';
import { useDisputeDetails } from '../composables/useDisputeDetails';
import { DisputeFlowState, useDisputeFlow } from '../composables/useDisputeFlow';
import DisputeDataAlert from './DisputeDataAlert.vue';
import DisputeDataProperties from './DisputeDataProperties.vue';
import DisputeIssuerComments from './DisputeIssuerComments.vue';
import DisputeStatusTag from './DisputeStatusTag.vue';
import type { DisputeDataAlertMode, DisputeManagementProps } from '../types';
import styles from './DisputeData.module.scss';

const props = defineProps<{
    disputeId: string;
    dataCustomization?: { details?: DisputeDetailsCustomization };
    onContactSupport?: () => void;
    onDismiss?: DisputeManagementProps['onDismiss'];
}>();

const { i18n } = useCoreContext();
const config = useConfigContext();
const { dispute: storedDispute, setDispute, setFlowState, defenseReasonConfig } = useDisputeFlow();

const { data, error, isFetching, refetch } = useDisputeDetails(() => ({
    disputeId: props.disputeId,
    fetchEnabled: !!props.disputeId && !storedDispute.value,
}));

watch(data, nextData => {
    if (nextData) setDispute(nextData);
});

const dispute = computed(() => storedDispute.value || data.value);
const defensibility = computed(() => dispute.value?.dispute.defensibility);
const acceptAuthorization = computed(() => isFunction(config.endpoints?.acceptDispute));
const defendAuthorization = computed(() => isFunction(config.endpoints?.getApplicableDefenseDocuments));
const showLoadingPlaceholder = computed(() => (!dispute.value && !error.value) || isFetching.value);
const disputeType = computed(() => getDisputeType(i18n, dispute.value?.dispute.type));
const isFraudNotification = computed(() => dispute.value?.dispute.type === 'NOTIFICATION_OF_FRAUD');
const isDefended = computed(() => !!dispute.value?.defense?.defendedOn);
const actionNeeded = computed(() => !!dispute.value && isDisputeActionNeeded(dispute.value.dispute));
const showContactSupport = computed(
    () =>
        (!!defensibility.value && ['ACCEPTABLE', 'DEFENDABLE_EXTERNALLY'].includes(defensibility.value)) ||
        dispute.value?.dispute.type === 'NOTIFICATION_OF_FRAUD'
);
const isDefendable = computed(() => !!defensibility.value && defensibility.value === 'DEFENDABLE' && defendAuthorization.value);
const isAcceptable = computed(() => !!defensibility.value && ['ACCEPTABLE', 'DEFENDABLE'].includes(defensibility.value) && acceptAuthorization.value);

const issuerComments = computed(() => {
    const { chargeback, preArbitration } = dispute.value?.dispute.issuerExtraData ?? {};
    const comments: string[] = [];

    [preArbitration, chargeback].forEach(commentGroup => {
        if (!commentGroup) return;
        ['LIABILITY_NOT_ACCEPTED_FULLY', 'PRE_ARB_REASON', 'NOTE'].forEach(commentKey => {
            const raw = commentGroup[commentKey];
            const trimmed = typeof raw === 'string' ? raw.trim() : '';
            if (trimmed) comments.push(trimmed);
        });
    });

    return comments;
});

const alertMode = computed<DisputeDataAlertMode | undefined>(() => {
    const currentDispute = dispute.value;
    if (!currentDispute) return undefined;
    if (currentDispute.defense?.autodefended === true) return 'autoDefended';
    if (actionNeeded.value && defensibility.value === 'NOT_ACTIONABLE') return 'notDefendable';
    if ((actionNeeded.value && showContactSupport.value) || (showContactSupport.value && isFraudNotification.value)) return 'contactSupport';
    if (currentDispute.dispute.status === 'EXPIRED') return 'notDefended';
    if (currentDispute.dispute.status === 'LOST' && !(isFraudNotification.value || isDefended.value)) return 'notDefended';
    return undefined;
});

const defendButtonLabel = computed(() =>
    dispute.value?.dispute.type === 'REQUEST_FOR_INFORMATION'
        ? i18n.get('disputes.management.details.actions.submitInformation')
        : i18n.get('disputes.management.details.actions.defendChargeback')
);

const extraFields = ref<Record<string, unknown> | undefined>();
let extraFieldsRequestId = 0;

function isButtonType(value: unknown): value is CustomButtonObject {
    return !!value && typeof value === 'object' && 'type' in value && value.type === 'button';
}

watch(
    () => [dispute.value, props.dataCustomization] as const,
    async ([nextDispute]) => {
        const requestId = ++extraFieldsRequestId;
        const detailsCustomization = props.dataCustomization?.details;
        if (!nextDispute || !detailsCustomization || !isFunction(detailsCustomization.onDataRetrieve)) {
            extraFields.value = undefined;
            return;
        }

        try {
            const retrieved = (await detailsCustomization.onDataRetrieve(nextDispute)) as CustomDataRetrieved | undefined;
            if (requestId !== extraFieldsRequestId) return;
            if (!retrieved) {
                extraFields.value = undefined;
                return;
            }

            extraFields.value = (detailsCustomization.fields ?? []).reduce<Record<string, unknown>>((acc, field) => {
                const key = typeof field?.key === 'string' ? field.key : '';
                if (!key) return acc;
                if (DISPUTE_DETAILS_RESERVED_FIELDS_SET.has(key as never)) return acc;
                if (field?.visibility === 'hidden') return acc;
                if (retrieved[key] !== undefined) acc[key] = retrieved[key];
                return acc;
            }, {});
        } catch {
            extraFields.value = undefined;
        }
    },
    { immediate: true }
);

const extraButtons = computed(() => Object.values(extraFields.value ?? {}).filter(isButtonType));

function onAcceptClick() {
    setFlowState(DisputeFlowState.Accept);
}

function onDefendClick() {
    setFlowState(DisputeFlowState.DefendReasonSelection);
}

const actionButtons = computed(() => {
    const buttons = [];
    if (isDefendable.value) {
        buttons.push({
            title: defendButtonLabel.value,
            event: onDefendClick,
        });
    }
    if (isAcceptable.value) {
        buttons.push({
            title: i18n.get('disputes.management.details.actions.accept'),
            event: onAcceptClick,
            variant: 'secondary',
        });
    }
    if (showContactSupport.value && props.onContactSupport) {
        buttons.push({
            title: i18n.get('disputes.management.details.actions.contactSupport'),
            event: props.onContactSupport,
            variant: 'secondary',
        });
    }
    return buttons;
});

function retryFetch() {
    void refetch();
}

const paymentMethodType = computed(() => dispute.value?.payment.paymentMethod?.type ?? null);
const paymentMethodDetail = computed(() =>
    dispute.value?.payment.paymentMethod ? parsePaymentMethodType(dispute.value.payment.paymentMethod, 'detail') : null
);
</script>

<template>
    <div :class="styles.root">
        <div v-if="showLoadingPlaceholder" aria-busy="true">
            <BentoLoadingIndicator />
        </div>

        <div v-else-if="error" :class="styles.errorContainer">
            <ErrorMessageDisplay
                :error="error"
                :error-message="'disputes.management.common.errors.unavailable'"
                :not-found-message="'disputes.management.common.errors.notFound'"
                :on-contact-support="props.onContactSupport"
                :on-dismiss="props.onDismiss"
                :dismiss-label="'disputes.management.common.actions.goBack'"
                :on-refresh="retryFetch"
                with-image
                :outlined="false"
                :absolute-position="false"
                :with-background="false"
            />
        </div>

        <template v-else-if="dispute">
            <div :class="styles.statusBox">
                <BentoCard>
                    <template #content>
                        <div :class="styles.summary">
                            <div :class="styles.summaryTags">
                                <BentoTag v-if="disputeType" :label="disputeType" data-testid="dispute-type-tag" />
                                <DisputeStatusTag v-if="!isFraudNotification" :dispute="dispute.dispute" />
                            </div>
                            <BentoTypography variant="title" large>
                                {{ i18n.amount(dispute.dispute.amount.value, dispute.dispute.amount.currency, { hideCurrency: true }) }}
                                {{ dispute.dispute.amount.currency }}
                            </BentoTypography>
                            <div v-if="paymentMethodType" :class="styles.paymentMethod">
                                <div :class="styles.paymentMethodLogoContainer">
                                    <BentoPaymentMethod :type="paymentMethodType" />
                                </div>
                                <BentoTypography v-if="paymentMethodDetail" variant="title">
                                    {{ paymentMethodDetail }}
                                </BentoTypography>
                            </div>
                        </div>
                    </template>
                </BentoCard>
            </div>

            <DisputeIssuerComments v-if="issuerComments.length > 0" :issuer-comments="issuerComments" />

            <DisputeDataAlert v-if="alertMode" :alert-mode="alertMode" :dispute="dispute" />

            <DisputeDataProperties
                :dispute="dispute"
                :data-customization="props.dataCustomization"
                :defense-reason-config="defenseReasonConfig"
                :extra-fields="extraFields"
            />

            <div v-if="actionButtons.length || extraButtons.length" :class="styles.actionBar">
                <BentoButtonActions v-if="actionButtons.length" :actions="actionButtons" />
                <BentoButton
                    v-for="button in extraButtons"
                    :key="String(button.value)"
                    variant="secondary"
                    :class="button.config?.className"
                    @click="button.config?.action"
                >
                    {{ button.value }}
                </BentoButton>
            </div>
        </template>
    </div>
</template>
