// src/components/external/Disputes/DisputeManagement/components/DisputeDetailsContainer/DisputeDetailsContainer.tsx
import { useCallback, useState } from 'preact/hooks';
import { DisputeContextProvider } from '../../context/dispute/context';
import { DisputeDetails } from '../DisputeDetails/DisputeDetails';
import type { ExternalUIComponentProps } from '../../../../../types';
import { DisputeManagementProps } from '../../types';
import { IDisputeDetail } from '../../../../../../types/api/models/disputes';
import './DisputeDetailsContainer.scss';

export const DisputeDetailsContainer = (props: ExternalUIComponentProps<DisputeManagementProps>) => {
    const [dispute, setDispute] = useState<IDisputeDetail | undefined>();

    const setDisputeCallback = useCallback((dispute: IDisputeDetail | undefined) => {
        setDispute(dispute);
    }, []);

    return (
        <DisputeContextProvider dispute={dispute} setDispute={setDisputeCallback}>
            <div className="adyen-pe-dispute__container">
                <DisputeDetails {...props} />
            </div>
        </DisputeContextProvider>
    );
};

// packages/domains/disputes/vue/src/DisputeManagement/components/DisputeDetailsContainer.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { IDisputeDetail } from '@integration-components/types/api/models/disputes';
import { provideDisputeFlow } from '../composables/useDisputeFlow';
import DisputeDetails from './DisputeDetails.vue';
import type { DisputeManagementProps } from '../types';
import '../styles/DisputeManagement.scss';

const props = defineProps<DisputeManagementProps>();
const dispute = ref<IDisputeDetail | undefined>();

provideDisputeFlow(dispute);
</script>

<template>
    <div class="adyen-pe-dispute__container">
        <DisputeDetails
            :id="props.id"
            :hide-title="props.hideTitle"
            :data-customization="props.dataCustomization"
            :on-contact-support="props.onContactSupport"
            :on-dispute-accept="props.onDisputeAccept"
            :on-dispute-defend="props.onDisputeDefend"
            :on-dismiss="props.onDismiss"
        />
    </div>
</template>
