// src/components/external/Disputes/DisputesOverview/components/DisputesTable/DisputeStatusTag.tsx
import { useMemo } from 'preact/hooks';
import useCoreContext from '../../../../../../core/Context/useCoreContext';
import { getDisputeStatus } from '../../../../../utils/translation/getters';
import { IDispute, IDisputeListItem } from '../../../../../../types/api/models/disputes';
import { isDisputeActionNeededUrgently } from '../../../../../utils/disputes/actionNeeded';
import { Tag } from '../../../../../internal/Tag/Tag';
import { TagVariant } from '../../../../../internal/Tag/types';
import { PropsWithChildren } from 'preact/compat';

const DisputeStatusTag = ({ dispute }: PropsWithChildren<{ dispute: IDisputeListItem | IDispute }>) => {
    const { i18n } = useCoreContext();
    const disputeStatus = useMemo(() => getDisputeStatus(i18n, dispute.status), [i18n, dispute]);

    const variant = useMemo<TagVariant>(() => {
        if (dispute.status === 'WON') return TagVariant.SUCCESS;
        if ((dispute as any)?.defensibility === 'NOT_ACTIONABLE') return TagVariant.DEFAULT;
        if (isDisputeActionNeededUrgently(dispute)) return TagVariant.ERROR;
        return TagVariant.DEFAULT;
    }, [dispute]);

    return <Tag variant={variant} label={disputeStatus} />;
};

export default DisputeStatusTag;

// packages/domains/disputes/vue/src/DisputeManagement/components/DisputeStatusTag.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoTag } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import { getDisputeStatus, isDisputeActionNeededUrgently } from '@integration-components/disputes/domain';
import type { IDispute } from '@integration-components/types/api/models/disputes';

const props = defineProps<{
    dispute: IDispute;
}>();

const { i18n } = useCoreContext();
const label = computed(() => getDisputeStatus(i18n, props.dispute.status));
const variant = computed(() => {
    if (props.dispute.status === 'WON') return 'green';
    if (props.dispute.defensibility === 'NOT_ACTIONABLE') return 'grey';
    if (isDisputeActionNeededUrgently(props.dispute)) return 'red';
    return 'grey';
});
</script>

<template>
    <BentoTag v-if="label" :label="label" :variant="variant" />
</template>
