// src/components/external/DisputeManagement/components/DisputeDetails/DisputeDetails.tsx
import cx from 'classnames';
import { PropsWithChildren } from 'preact/compat';
import type { ExternalUIComponentProps } from '../../../../types';
import { useModalContext } from '../../../../internal/Modal/Modal';
import { useDisputeFlow } from '../../context/dispute/context';
import { Header } from '../../../../internal/Header';
import { DisputeManagementProps } from '../../types';
import { AcceptDisputeFlow } from '../AcceptDisputeFlow/AcceptDisputeFlow';
import { DefendDisputeFlow } from '../DefendDisputeFlow/DefendDisputeFlow';
import DisputeData from '../DisputesData/DisputeData';
import { useEffect } from 'preact/hooks';

const DisputeDetailsContainer = ({ children, hideTitle }: PropsWithChildren<Pick<ExternalUIComponentProps<DisputeManagementProps>, 'hideTitle'>>) => {
    const { flowState } = useDisputeFlow();
    const { withinModal } = useModalContext();
    return (
        <>
            <div className={cx({ ['adyen-pe-visually-hidden']: flowState !== 'details' })}>
                <Header hideTitle={hideTitle} forwardedToRoot={!withinModal} titleKey="disputes.management.common.title" />
            </div>
            {children}
        </>
    );
};

export const DisputeDetails = ({
    id,
    hideTitle,
    dataCustomization,
    onContactSupport,
    onDisputeAccept,
    onDisputeDefend,
    onDismiss,
}: ExternalUIComponentProps<DisputeManagementProps>) => {
    const { flowState, getDisputesConfig } = useDisputeFlow();

    useEffect(() => {
        void getDisputesConfig();
    }, [getDisputesConfig]);

    switch (flowState) {
        case 'details':
            return (
                <DisputeDetailsContainer hideTitle={hideTitle}>
                    <DisputeData disputeId={id} dataCustomization={dataCustomization} onContactSupport={onContactSupport} onDismiss={onDismiss} />
                </DisputeDetailsContainer>
            );
        case 'accept':
            return (
                <DisputeDetailsContainer hideTitle={hideTitle}>
                    <AcceptDisputeFlow onDisputeAccept={onDisputeAccept} />
                </DisputeDetailsContainer>
            );
        case 'defendReasonSelectionView':
        case 'defenseSubmitResponseView':
        case 'uploadDefenseFilesView':
            return (
                <DisputeDetailsContainer hideTitle={hideTitle}>
                    <DefendDisputeFlow onDisputeDefend={onDisputeDefend} />
                </DisputeDetailsContainer>
            );
        default:
            return null;
    }
};

// packages/domains/disputes/vue/src/DisputeManagement/components/DisputeDetails.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { BentoTypography } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import { useDisputeFlow } from '../composables/useDisputeFlow';
import AcceptDisputeFlow from './AcceptDisputeFlow.vue';
import DefendDisputeFlow from './DefendDisputeFlow.vue';
import DisputeData from './DisputeData.vue';
import type { DisputeManagementProps } from '../types';

const props = defineProps<DisputeManagementProps>();
const { i18n } = useCoreContext();
const { flowState, getDisputesConfig } = useDisputeFlow();

onMounted(() => {
    void getDisputesConfig();
});
</script>

<template>
    <div :class="{ 'adyen-pe-visually-hidden': flowState !== 'details' }">
        <BentoTypography v-if="!props.hideTitle" el="h1" variant="title">
            {{ i18n.get('disputes.management.common.title') }}
        </BentoTypography>
    </div>

    <DisputeData
        v-if="flowState === 'details'"
        :dispute-id="props.id"
        :data-customization="props.dataCustomization"
        :on-contact-support="props.onContactSupport"
        :on-dismiss="props.onDismiss"
    />
    <AcceptDisputeFlow v-else-if="flowState === 'accept'" :on-dispute-accept="props.onDisputeAccept" />
    <DefendDisputeFlow v-else :on-dispute-defend="props.onDisputeDefend" />
</template>
