// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentDetails/PaymentDetailsProperties.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/vue';
import { BentoStructuredList, BentoStructuredListItem, BentoTypography, BentoLink, BentoButton } from '@adyen/bento-vue3';
import {
    getTransactionRefundReason,
    TX_DATA_LIST,
    TX_DETAILS_FIELDS_REMAPS,
    sharedTransactionDetailsEventProperties,
} from '../../../../../domain/src';
import { normalizeCustomFields } from '@integration-components/utils';
import type { TransactionDetails, TransactionDetailsCustomization } from '../../../../../domain/src';
import type { TranslationKey } from '@integration-components/core';
import CopyIcon from '@adyen/ui-assets-icons-16/vue/copy';

const props = defineProps<{
    dataCustomization?: { details?: TransactionDetailsCustomization };
    extraFields: Record<string, any> | undefined;
    transaction: TransactionDetails;
}>();

const { i18n } = useCoreContext();
const userEvents = useEventDispatcherContext();

const paymentDataKeys = {
    account: 'transactions.details.fields.account',
    id: 'transactions.details.fields.referenceID',
    merchantReference: 'transactions.details.fields.merchantReference',
    pspReference: 'transactions.details.fields.pspReference',
    refundPspReference: 'transactions.details.fields.refundPspReference',
    refundReason: 'transactions.details.fields.refundReason',
} as const;

const paymentDataCopyButtonKeys = {
    referenceId: 'transactions.details.actions.copyReferenceID',
    merchantReference: 'transactions.details.actions.copyMerchantReference',
    pspReference: 'transactions.details.actions.copyPspReference',
} as const satisfies Record<string, TranslationKey>;

interface ListItem {
    id?: string;
    key: TranslationKey;
    value: string;
    copyable?: boolean;
    copyAriaLabelKey?: TranslationKey;
    trackingName?: string;
}

const standardItems = computed<ListItem[]>(() => {
    const { balanceAccount, category, id, merchantReference, paymentPspReference, refundMetadata } = props.transaction;
    const account = balanceAccount?.description || balanceAccount?.id;
    const isRefund = category === 'Refund';

    const customizedFields = normalizeCustomFields(props.dataCustomization?.details?.fields, TX_DETAILS_FIELDS_REMAPS, props.transaction);
    const isVisible = customizedFields ? (fid: string) => customizedFields.find(f => f.key === fid)?.visibility !== 'hidden' : () => true;

    const items: (ListItem | null)[] = [
        account && isVisible('account') ? { id: 'account', key: paymentDataKeys.account as TranslationKey, value: account } : null,
        isRefund && refundMetadata?.refundReason && isVisible('refundReason')
            ? {
                  id: 'refundReason',
                  key: paymentDataKeys.refundReason as TranslationKey,
                  value: getTransactionRefundReason(i18n, refundMetadata.refundReason) as string,
              }
            : null,
        isVisible('id')
            ? {
                  id: 'id',
                  key: paymentDataKeys.id as TranslationKey,
                  value: id,
                  copyable: true,
                  copyAriaLabelKey: paymentDataCopyButtonKeys.referenceId,
                  trackingName: 'Reference ID',
              }
            : null,
        merchantReference && isVisible('merchantReference')
            ? {
                  id: 'merchantReference',
                  key: paymentDataKeys.merchantReference as TranslationKey,
                  value: merchantReference,
                  copyable: true,
                  copyAriaLabelKey: paymentDataCopyButtonKeys.merchantReference,
                  trackingName: 'Merchant reference',
              }
            : null,
        paymentPspReference && isVisible('paymentPspReference')
            ? {
                  id: 'paymentPspReference',
                  key: paymentDataKeys.pspReference as TranslationKey,
                  value: paymentPspReference,
                  copyable: true,
                  copyAriaLabelKey: paymentDataCopyButtonKeys.pspReference,
                  trackingName: 'PSP reference',
              }
            : null,
        isRefund && refundMetadata?.refundPspReference && isVisible('refundPspReference')
            ? { id: 'refundPspReference', key: paymentDataKeys.refundPspReference as TranslationKey, value: refundMetadata.refundPspReference }
            : null,
    ];

    return items.filter(Boolean) as ListItem[];
});

const customItems = computed(() =>
    Object.entries(props.extraFields ?? {})
        .filter(([, value]) => (value as any)?.type !== 'button')
        .map(([key, value]) => ({
            key: key as TranslationKey,
            value: (value as any)?.value ?? value,
            type: (value as any)?.type ?? 'text',
            config: (value as any)?.config,
        }))
);

function onCopyText(text: string, trackingName?: string) {
    navigator.clipboard?.writeText(text);
    if (trackingName) {
        userEvents.addEvent?.('Clicked button', {
            ...sharedTransactionDetailsEventProperties,
            sectionName: 'Details',
            label: 'Copy button',
            subSectionName: trackingName,
        });
    }
}
</script>

<template>
    <BentoStructuredList :class="TX_DATA_LIST">
        <BentoStructuredListItem v-for="item in standardItems" :key="item.id ?? item.key" :label="i18n.get(item.key)">
            <template v-if="item.copyable" #default>
                <div style="display: flex; align-items: center; gap: 4px">
                    <BentoTypography variant="body">{{ item.value }}</BentoTypography>
                    <BentoButton
                        variant="tertiary"
                        :aria-label="item.copyAriaLabelKey ? i18n.get(item.copyAriaLabelKey) : undefined"
                        @click="() => onCopyText(item.value, item.trackingName)"
                    >
                        <CopyIcon />
                    </BentoButton>
                </div>
            </template>
            <template v-else #default>
                <BentoTypography variant="body">{{ item.value }}</BentoTypography>
            </template>
        </BentoStructuredListItem>

        <BentoStructuredListItem v-for="item in customItems" :key="item.key" :label="i18n.get(item.key)">
            <BentoLink
                v-if="item.type === 'link' && item.config"
                :class="item.config.className"
                :to="item.config.href"
                :target="item.config.target || '_blank'"
                rel="noopener noreferrer"
                external
            >
                {{ item.value }}
            </BentoLink>
            <div v-else-if="item.type === 'icon' && item.config" :class="item.config.className">
                <img :src="item.config.src" :alt="item.config.alt || item.value" />
                <BentoTypography variant="body">{{ item.value }}</BentoTypography>
            </div>
            <BentoTypography v-else variant="body" :class="item.config?.className">{{ item.value }}</BentoTypography>
        </BentoStructuredListItem>
    </BentoStructuredList>
</template>

// src/components/external/Transactions/TransactionDetails/components/PaymentDetails/PaymentDetailsProperties.tsx
import { memo } from 'preact/compat';
import { useCallback, useMemo } from 'preact/hooks';
import { TranslationKey } from '../../../../../../translations';
import { TransactionDetails, TransactionDetailsProps } from '../../types';
import { StructuredListProps } from '../../../../../internal/StructuredList/types';
import { getTransactionRefundReason } from '../../../../../utils/translation/getters';
import { isCustomDataObject } from '../../../../../internal/DataGrid/components/TableCells';
import { TypographyElement, TypographyVariant } from '../../../../../internal/Typography/types';
import { TX_DATA_LABEL, TX_DATA_LIST, TX_DETAILS_FIELDS_REMAPS, sharedTransactionDetailsEventProperties } from '../../constants';
import normalizeCustomFields from '../../../../../utils/customData/normalizeCustomFields';
import useAnalyticsContext from '../../../../../../core/Context/analytics/useAnalyticsContext';
import useCoreContext from '../../../../../../core/Context/useCoreContext';
import StructuredList from '../../../../../internal/StructuredList';
import Typography from '../../../../../internal/Typography/Typography';
import Icon from '../../../../../internal/DataGrid/components/Icon';
import CopyText from '../../../../../internal/CopyText/CopyText';
import Link from '../../../../../internal/Link/Link';
import cx from 'classnames';

const copyButtonAnalyticsEventProperties = {
    ...sharedTransactionDetailsEventProperties,
    sectionName: 'Details',
    label: 'Copy button',
} as const;

const paymentDataKeys = {
    account: 'transactions.details.fields.account',
    id: 'transactions.details.fields.referenceID',
    merchantReference: 'transactions.details.fields.merchantReference',
    pspReference: 'transactions.details.fields.pspReference',
    refundPspReference: 'transactions.details.fields.refundPspReference',
    refundReason: 'transactions.details.fields.refundReason',
} satisfies Record<string, TranslationKey>;

const paymentDataCopyButtonKeys = {
    id: 'transactions.details.actions.copyReferenceID',
    merchantReference: 'transactions.details.actions.copyMerchantReference',
    pspReference: 'transactions.details.actions.copyPspReference',
} satisfies Record<string, TranslationKey>;

const SKIP_ITEM: StructuredListProps['items'][number] = null!;

export interface PaymentDetailsPropertiesProps {
    dataCustomization?: TransactionDetailsProps['dataCustomization'];
    extraFields: Record<string, any> | undefined;
    transaction: TransactionDetails;
}

const PaymentDetailsProperties = ({ dataCustomization, extraFields, transaction }: PaymentDetailsPropertiesProps) => {
    const { i18n } = useCoreContext();

    const standardPropertiesList = useMemo<StructuredListProps['items']>(() => {
        const { balanceAccount, category, id, merchantReference, paymentPspReference, refundMetadata } = transaction;
        const account = balanceAccount?.description || balanceAccount?.id;
        const isRefundTransaction = category === 'Refund';

        const customizedFields = normalizeCustomFields(dataCustomization?.details?.fields, TX_DETAILS_FIELDS_REMAPS, transaction);

        const listItems: StructuredListProps['items'] = [
            // balance account
            account ? { id: 'account', key: paymentDataKeys.account, value: account } : SKIP_ITEM,

            // refund reason
            isRefundTransaction && refundMetadata?.refundReason
                ? {
                      id: 'refundReason',
                      key: paymentDataKeys.refundReason,
                      value: getTransactionRefundReason(i18n, refundMetadata.refundReason),
                  }
                : SKIP_ITEM,

            // reference id
            {
                id: 'id',
                key: paymentDataKeys.id,
                value: (
                    <PaymentDetailsProperties.CopyText
                        copyButtonAriaLabelKey={paymentDataCopyButtonKeys.id}
                        trackingName="Reference ID"
                        textToCopy={id}
                    />
                ),
            },

            // merchant reference
            merchantReference
                ? {
                      id: 'merchantReference',
                      key: paymentDataKeys.merchantReference,
                      value: (
                          <PaymentDetailsProperties.CopyText
                              copyButtonAriaLabelKey={paymentDataCopyButtonKeys.merchantReference}
                              trackingName="Merchant reference"
                              textToCopy={merchantReference}
                          />
                      ),
                  }
                : SKIP_ITEM,

            // payment psp reference
            paymentPspReference
                ? {
                      id: 'paymentPspReference',
                      key: paymentDataKeys.pspReference,
                      value: (
                          <PaymentDetailsProperties.CopyText
                              copyButtonAriaLabelKey={paymentDataCopyButtonKeys.pspReference}
                              trackingName="PSP reference"
                              textToCopy={paymentPspReference}
                          />
                      ),
                  }
                : SKIP_ITEM,

            // refund psp reference
            isRefundTransaction && refundMetadata?.refundPspReference
                ? {
                      id: 'refundPspReference',
                      key: paymentDataKeys.refundPspReference,
                      value: refundMetadata.refundPspReference,
                  }
                : SKIP_ITEM,
        ] as const;

        const isVisibleField = customizedFields
            ? (id: string) => customizedFields.find(field => field.key === id)?.visibility !== 'hidden'
            : () => true;

        return listItems.filter(item => item?.id && isVisibleField(item.id));
    }, [i18n, dataCustomization, transaction]);

    const customPropertiesList = useMemo<StructuredListProps['items']>(
        () =>
            Object.entries(extraFields || {})
                .filter(([, value]) => value?.type !== 'button')
                .map(([key, value]) => ({
                    key: key as TranslationKey,
                    value: isCustomDataObject(value) ? value.value : value,
                    type: isCustomDataObject(value) ? value.type : 'text',
                    config: isCustomDataObject(value) ? value.config : undefined,
                })),
        [extraFields]
    );

    const listItems = useMemo(() => [...standardPropertiesList, ...customPropertiesList], [customPropertiesList, standardPropertiesList]);

    const renderListPropertyLabel = useCallback<NonNullable<StructuredListProps['renderLabel']>>(
        label => <div className={TX_DATA_LABEL}>{label}</div>,
        []
    );

    const renderListPropertyValue = useCallback<NonNullable<StructuredListProps['renderValue']>>((val, key, type, config) => {
        if (config) {
            switch (type) {
                case 'icon':
                    return (
                        <div className={cx(config.className, 'adyen-pe-transaction-data__list-icon-value')}>
                            <Icon url={config.src} alt={config.alt || val} />
                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                                {' '}
                                {val}
                            </Typography>
                        </div>
                    );
                case 'link':
                    return (
                        <Link classNames={[cx(config.className)]} href={config.href} target={config.target || '_blank'}>
                            {val}
                        </Link>
                    );
            }
        }
        return (
            <Typography el={TypographyElement.DIV} variant={TypographyVariant.BODY} className={cx(config?.className)}>
                {val}
            </Typography>
        );
    }, []);

    return (
        <StructuredList
            align="start"
            layout="5-7"
            items={listItems}
            classNames={TX_DATA_LIST}
            renderLabel={renderListPropertyLabel}
            renderValue={renderListPropertyValue}
        />
    );
};

interface PaymentDetailsPropertiesCopyTextProps {
    copyButtonAriaLabelKey: TranslationKey;
    textToCopy: string;
    trackingName?: string;
}

PaymentDetailsProperties.CopyText = memo(({ trackingName, ...copyTextProps }: PaymentDetailsPropertiesCopyTextProps) => {
    const userEvents = useAnalyticsContext();

    const onCopyText = useCallback(() => {
        if (trackingName) {
            userEvents.addEvent?.('Clicked button', {
                ...copyButtonAnalyticsEventProperties,
                subSectionName: trackingName,
            });
        }
    }, [trackingName, userEvents]);

    return <CopyText {...copyTextProps} onCopyText={onCopyText} showCopyTextTooltip={false} type="Default" />;
});

export default memo(PaymentDetailsProperties);
