// packages/domains/disputes/preact/src/DisputesOverview/components/DisputesTable/DisputesTable.tsx
import cx from 'classnames';
import { FC } from 'preact/compat';
import { useCallback, useEffect, useMemo, useState } from 'preact/hooks';
import { useConfigContext, useCoreContext } from '@integration-components/core/preact';
import { AdyenPlatformExperienceError, TranslationKey } from '@integration-components/core';
import { containerQueries, useResponsiveContainer, useTableColumns, useTimezoneAwareDateFormatting } from '@integration-components/hooks-preact';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import Icon from '@integration-components/ui-components-preact/Icon';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';
import DataGrid from '@integration-components/ui-components-preact/DataGrid';
import {
    DisputesTableFields,
    EMPTY_TABLE_MESSAGE_KEYS,
    getDisputeDeadlineTimeRemaining,
    FIELD_KEYS,
    getDisputeReason,
    isDisputeActionNeededUrgently,
} from '@integration-components/disputes/domain';
import { DATE_FORMAT_DISPUTES, DATE_FORMAT_RESPONSE_DEADLINE } from '@integration-components/utils';
import DataOverviewError from '@integration-components/ui-components-preact/DataOverviewError/DataOverviewError';
import Pagination from '@integration-components/ui-components-preact/Pagination';
import { PaginationProps, WithPaginationLimitSelection } from '@integration-components/ui-components-preact/Pagination/types';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { BASE_CLASS } from './constants';
import type { CustomColumn, IBalanceAccountBase } from '@integration-components/types';
import type { StringWithAutocompleteOptions } from '@integration-components/utils/types';
import { IDisputeListItem, IDisputeStatusGroup } from '@integration-components/types/api/models/disputes';
import PaymentMethodCell from '@integration-components/ui-components-preact/PaymentMethodCell/PaymentMethodCell';
import DisputeStatusTag from './DisputeStatusTag';
import { Tag } from '@integration-components/ui-components-preact/Tag/Tag';
import { Tooltip } from '@integration-components/ui-components-preact/Tooltip/Tooltip';
import { Translation } from '@integration-components/ui-components-preact/Translation';
import './DisputesTable.scss';

export const FIELDS = Object.keys(FIELD_KEYS) as readonly DisputesTableFields[];

const classes = {
    cellContent: `${BASE_CLASS}__cell-content`,
    cellContentVStack: `${BASE_CLASS}__cell-content--vstack`,
    cellTextGrey: `${BASE_CLASS}__cell-text--grey`,
    dateContentUrgent: `${BASE_CLASS}__date-content--urgent`,
    statusContent: `${BASE_CLASS}__status-content`,
    statusContentUrgent: `${BASE_CLASS}__status-content--urgent`,
};

export interface DisputesTableProps extends WithPaginationLimitSelection<PaginationProps> {
    balanceAccountId: string | undefined;
    loading: boolean;
    error?: AdyenPlatformExperienceError;
    onContactSupport?: () => void;
    showPagination: boolean;
    data: IDisputeListItem[] | undefined;
    activeBalanceAccount?: IBalanceAccountBase;
    onRowClick: (value: IDisputeListItem) => void;
    customColumns?: CustomColumn<StringWithAutocompleteOptions<DisputesTableFields>>[];
    statusGroup: IDisputeStatusGroup;
}

export const DisputesTable: FC<DisputesTableProps> = ({
    error,
    loading,
    balanceAccountId,
    onContactSupport,
    showPagination,
    onRowClick,
    data,
    customColumns,
    activeBalanceAccount,
    statusGroup,
    ...paginationProps
}) => {
    const { i18n } = useCoreContext();
    const { refreshing } = useConfigContext();
    const { dateFormat } = useTimezoneAwareDateFormatting(activeBalanceAccount?.timeZone);

    const [alert, setAlert] = useState<null | { title: string; description: string }>(null);
    const isLoading = useMemo(() => loading || refreshing, [loading, refreshing]);
    const isMobileContainer = useResponsiveContainer(containerQueries.down.xs);

    let limitSelectAriaLabelKey: TranslationKey | undefined = undefined;

    if (showPagination) {
        switch (statusGroup) {
            case 'CHARGEBACKS':
                limitSelectAriaLabelKey = 'disputes.overview.chargebacks.limitSelect.a11y.label';
                break;
            case 'FRAUD_ALERTS':
                limitSelectAriaLabelKey = 'disputes.overview.fraudAlerts.limitSelect.a11y.label';
                break;
            case 'ONGOING_AND_CLOSED':
                limitSelectAriaLabelKey = 'disputes.overview.ongoingAndClosed.limitSelect.a11y.label';
                break;
        }
    }

    const columns = useTableColumns({
        fields: FIELDS,
        fieldsKeys: FIELD_KEYS,
        customColumns,
        columnConfig: useMemo(
            () => ({
                status: {
                    visible: statusGroup === 'ONGOING_AND_CLOSED',
                },
                reason: {
                    visible: statusGroup === 'FRAUD_ALERTS' && !isMobileContainer,
                    flex: 2,
                },
                respondBy: {
                    visible: statusGroup === 'CHARGEBACKS',
                },
                currency: {
                    visible: !isMobileContainer,
                    flex: 0.5,
                },
                disputedAmount: {
                    visible: statusGroup !== 'FRAUD_ALERTS',
                    position: 'right',
                },
                createdAt: {
                    visible: !isMobileContainer || statusGroup === 'FRAUD_ALERTS',
                },
                paymentMethod: {
                    visible: !isMobileContainer,
                },
                disputeReason: {
                    visible: statusGroup !== 'FRAUD_ALERTS' && !isMobileContainer,
                },
                totalPaymentAmount: {
                    visible: statusGroup === 'FRAUD_ALERTS',
                    position: 'right',
                },
            }),
            [isMobileContainer, statusGroup]
        ),
    });

    const removeAlert = useCallback(() => setAlert(null), []);

    const getTimeToDeadline = useCallback(
        (dueDate: string) => {
            if (!dueDate) return '';

            const timeRemaining = getDisputeDeadlineTimeRemaining(dueDate);
            if (!timeRemaining) return '';

            const formattedDate = dateFormat(dueDate, { ...DATE_FORMAT_RESPONSE_DEADLINE, weekday: undefined });
            if (timeRemaining.expired) return formattedDate;

            return timeRemaining.days <= 1
                ? i18n.get('disputes.overview.common.actionNeeded.respondToday', { values: { date: formattedDate } })
                : i18n.get('disputes.overview.common.actionNeeded.respondDays', { values: { days: timeRemaining.days, date: formattedDate } });
        },
        [dateFormat, i18n]
    );

    const EMPTY_TABLE_MESSAGE = {
        title: EMPTY_TABLE_MESSAGE_KEYS[statusGroup].title,
        message: [EMPTY_TABLE_MESSAGE_KEYS[statusGroup].message],
    } satisfies { title: TranslationKey; message: TranslationKey | TranslationKey[] };

    const errorDisplay = useMemo(
        () => () => (
            <DataOverviewError error={error} errorMessage={'disputes.overview.common.errors.listUnavailable'} onContactSupport={onContactSupport} />
        ),
        [error, onContactSupport]
    );

    useEffect(() => {
        if (isLoading) removeAlert();
    }, [isLoading, removeAlert]);

    return (
        <div className={BASE_CLASS}>
            {alert && <Alert onClose={removeAlert} type={AlertTypeOption.WARNING} className={'adyen-pe-disputes-table-alert'} {...alert} />}
            <DataGrid
                autoFitColumns={isMobileContainer}
                errorDisplay={errorDisplay}
                error={error}
                columns={columns}
                data={data}
                loading={isLoading}
                outline={false}
                onRowClick={{ callback: onRowClick }}
                emptyTableMessage={EMPTY_TABLE_MESSAGE}
                customCells={{
                    status: ({ item }) => {
                        return (
                            <div className={cx(classes.cellContent, { [classes.cellContentVStack]: isMobileContainer })}>
                                <DisputeStatusTag dispute={item} />
                                {isMobileContainer && <PaymentMethodCell paymentMethod={item.paymentMethod} />}
                            </div>
                        );
                    },
                    reason: ({ item }) => {
                        return item.reason.title;
                    },
                    respondBy: ({ item }) => {
                        const isUrgent = isDisputeActionNeededUrgently(item);
                        const formattedDate = dateFormat(item.dueDate!, DATE_FORMAT_DISPUTES);
                        // TODO - Check if the API can send the defensibility field in a next iteration
                        const isActionableDispute = true; /* isDisputeActionNeeded(item) && item.defensibility !== 'NOT_ACTIONABLE' */

                        const renderDueDate = () =>
                            isUrgent && isActionableDispute ? (
                                <Tooltip content={getTimeToDeadline(item.dueDate!)}>
                                    <span className={classes.dateContentUrgent}>
                                        <time dateTime={item.dueDate!}>{formattedDate}</time>
                                        {<Icon name={'warning-filled'} />}
                                    </span>
                                </Tooltip>
                            ) : (
                                <time dateTime={item.dueDate!}>{formattedDate}</time>
                            );

                        return (
                            <div className={cx(classes.cellContent, { [classes.cellContentVStack]: isMobileContainer })}>
                                {item.dueDate ? (
                                    <Typography
                                        el={TypographyElement.SPAN}
                                        variant={TypographyVariant.BODY}
                                        className={cx(classes.statusContent, {
                                            [classes.cellTextGrey]: isMobileContainer && !isUrgent,
                                            [classes.statusContentUrgent]: isUrgent,
                                        })}
                                    >
                                        {isMobileContainer ? (
                                            <Translation
                                                translationKey="disputes.overview.common.actionNeeded.dueDate"
                                                fills={{ dueDate: renderDueDate }}
                                            />
                                        ) : (
                                            renderDueDate()
                                        )}
                                    </Typography>
                                ) : null}
                                {isMobileContainer && <PaymentMethodCell paymentMethod={item.paymentMethod} />}
                            </div>
                        );
                    },
                    currency: ({ item }) => {
                        return <Tag>{item.amount.currency}</Tag>;
                    },
                    disputedAmount: ({ item }) => {
                        return (
                            item.amount && (
                                <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                                    {i18n.amount(item.amount.value, item.amount.currency, { hideCurrency: false })}
                                </Typography>
                            )
                        );
                    },
                    createdAt: ({ item }) => {
                        return (
                            <div className={cx(classes.cellContent, { [classes.cellContentVStack]: isMobileContainer })}>
                                <time
                                    dateTime={item.createdAt}
                                    className={cx(classes.statusContent, {
                                        [classes.cellTextGrey]: isMobileContainer,
                                    })}
                                >
                                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                                        {dateFormat(item.createdAt, DATE_FORMAT_DISPUTES)}
                                    </Typography>
                                </time>
                                {isMobileContainer && <PaymentMethodCell paymentMethod={item.paymentMethod} />}
                            </div>
                        );
                    },
                    paymentMethod: ({ item }) => <PaymentMethodCell paymentMethod={item.paymentMethod} />,
                    disputeReason: ({ item }) => <span>{getDisputeReason(i18n, item.reason.category)}</span>,
                    totalPaymentAmount: ({ item }) => {
                        return (
                            item && (
                                <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                                    {i18n.amount(item.amount.value, item.amount.currency, { hideCurrency: false })}
                                </Typography>
                            )
                        );
                    },
                }}
            >
                {showPagination && (
                    <DataGrid.Footer>
                        <Pagination
                            {...paginationProps}
                            ariaLabelKey="disputes.overview.common.pagination.a11y.label"
                            limitSelectAriaLabelKey={limitSelectAriaLabelKey}
                        />
                    </DataGrid.Footer>
                )}
            </DataGrid>
        </div>
    );
};

// packages/domains/disputes/vue/src/DisputesOverview/components/DisputesTable.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import {
    BentoCurrency,
    BentoDataGrid,
    BentoEmptyState,
    BentoList,
    BentoListItem,
    BentoLoadingIndicator,
    BentoPagination,
    BentoTag,
    BentoTooltipDirective as vBentoTooltip,
    BentoTypography,
} from '@adyen/bento-vue3';
import WarningFilledIcon from '@adyen/ui-assets-icons-16/vue/warning-filled';
import RefreshIcon from '@adyen/ui-assets-icons-16/vue/refresh';
import CopyIcon from '@adyen/ui-assets-icons-16/vue/copy';
import type { BentoCurrencyISOCode, BentoDatagridDataItem } from '@adyen/bento-vue3';
import { useCoreContext, useConfigContext } from '@integration-components/core/vue';
import {
    useCustomColumnsData,
    CustomDataCell,
    useResponsiveContainer,
    containerQueries,
    DataOverviewError,
    useTableColumns,
} from '@integration-components/composables-vue';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import { getDisputeDeadlineTimeRemaining, getDisputeReason, isDisputeActionNeededUrgently } from '@integration-components/disputes/domain';
import { DATE_FORMAT_DISPUTES, DATE_FORMAT_RESPONSE_DEADLINE, mergeRecords } from '@integration-components/utils';
import type { CustomColumn, CustomDataRetrieved, IBalanceAccountBase, OnDataRetrievedCallback } from '@integration-components/types';
import type { StringWithAutocompleteOptions } from '@integration-components/utils/types';
import type { IDisputeListItem, IDisputeStatusGroup } from '@integration-components/types/api/models/disputes';
import DisputeStatusTag from './DisputeStatusTag.vue';
import DisputePaymentMethod from './DisputePaymentMethod.vue';
import { DISPUTES_TABLE_FIELDS, EMPTY_TABLE_MESSAGE_KEYS, FIELD_KEYS, type DisputesTableFields } from '../constants';
import styles from './DisputesTable.module.scss';

const props = defineProps<{
    statusGroup: IDisputeStatusGroup;
    loading: boolean;
    error?: Error;
    data: IDisputeListItem[] | undefined;
    activeBalanceAccount?: IBalanceAccountBase;
    showPagination: boolean;
    onContactSupport?: () => void;
    onRowClick?: (dispute: IDisputeListItem) => void;
    customColumns?: CustomColumn<StringWithAutocompleteOptions<DisputesTableFields>>[];
    onDataRetrieve?: OnDataRetrievedCallback<IDisputeListItem[], CustomDataRetrieved[]>;
    hasNext?: boolean;
    hasPrevious?: boolean;
    goToNextPage?: () => void;
    goToPreviousPage?: () => void;
    limit?: number;
    limitOptions?: number[];
    updateLimit?: (limit: number) => void;
    currentPage?: number;
}>();

const { i18n } = useCoreContext();
const config = useConfigContext();

const { dateFormat } = useTimezoneAwareDateFormatting(() => props.activeBalanceAccount?.timeZone);
const isMobile = useResponsiveContainer(containerQueries.down.xs);
const hasMultipleCurrencies = ref(true);

const { columns, customFieldKeys, hasCustomColumn } = useTableColumns({
    fields: DISPUTES_TABLE_FIELDS,
    customColumns: () => props.customColumns,
    fieldsKeys: FIELD_KEYS,
    customColumnDefaults: () => ({ flex: 1, minWidth: 0 }),
    columnConfig: () => {
        const statusGroup = props.statusGroup;
        return {
            status: { visible: statusGroup === 'ONGOING_AND_CLOSED', flex: 1, minWidth: 130 },
            respondBy: { visible: statusGroup === 'CHARGEBACKS', flex: 1, minWidth: 120 },
            createdAt: { visible: true, flex: 1, minWidth: 120 },
            paymentMethod: { visible: true, flex: 1.2, minWidth: 150 },
            disputeReason: { visible: statusGroup !== 'FRAUD_ALERTS', flex: 1.5, minWidth: 180 },
            reason: { visible: statusGroup === 'FRAUD_ALERTS', flex: 2, minWidth: 220 },
            currency: { visible: hasMultipleCurrencies.value, flex: 0.7, minWidth: 90 },
            disputedAmount: { visible: statusGroup !== 'FRAUD_ALERTS', flex: 1, minWidth: 140, numeric: true },
            totalPaymentAmount: { visible: statusGroup === 'FRAUD_ALERTS', flex: 1, minWidth: 140, numeric: true },
        };
    },
    resolveStandardColumnLabel: (field, defaultLabel) =>
        field === 'disputeReason' ? i18n.get('disputes.overview.common.fields.disputeReasonLabel') : defaultLabel,
    resolveCustomColumnLabel: key => (i18n.has(key) ? i18n.get(key) : key),
});

const { customRecords, loadingCustomRecords } = useCustomColumnsData<IDisputeListItem>({
    records: () => props.data ?? [],
    hasCustomColumn: () => hasCustomColumn.value,
    onDataRetrieve: () => props.onDataRetrieve,
    mergeCustomData: ({ records, retrievedData }) =>
        mergeRecords(
            records,
            retrievedData as CustomDataRetrieved[],
            (modified, record) => modified.disputePspReference === record.disputePspReference
        ),
});

watch(
    () => [customRecords.value, loadingCustomRecords.value] as const,
    ([records, isLoadingCustomRecords]) => {
        if (isLoadingCustomRecords) {
            hasMultipleCurrencies.value = true;
            return;
        }
        hasMultipleCurrencies.value = new Set(records.map(dispute => dispute.amount.currency)).size > 1;
    },
    { immediate: true }
);

const isLoading = computed(() => props.loading || config.refreshing || loadingCustomRecords.value);
const showMobilePagination = computed(() => props.showPagination && (props.hasNext || props.hasPrevious));

const gridData = computed<BentoDatagridDataItem[]>(() => {
    const source = customRecords.value as Array<IDisputeListItem & Record<string, any>>;
    if (!source.length) return [];
    const keys = customFieldKeys.value;
    return source.map((dispute, idx) => {
        const row: BentoDatagridDataItem = {
            id: `${dispute.disputePspReference}-${idx}`,
            _raw: dispute,
        };
        for (const key of keys) {
            row[key] = dispute[key];
        }
        return row;
    });
});

const paginationProps = computed(() => {
    if (!props.showPagination) return undefined;
    return {
        page: props.currentPage ?? 1,
        size: props.limit ?? 10,
        hasNext: props.hasNext ?? false,
        hasPrevious: props.hasPrevious ?? false,
        hidePageSize: !props.limitOptions || props.limitOptions.length <= 1,
        hideFirstLastPageButtons: true,
    };
});

const emptyStateProps = computed(() => ({
    image: 'no-results-found' as const,
    variant: 'embedded' as const,
    title: i18n.get(EMPTY_TABLE_MESSAGE_KEYS[props.statusGroup].title),
    description: i18n.get(EMPTY_TABLE_MESSAGE_KEYS[props.statusGroup].message),
}));

function getDispute(item: BentoDatagridDataItem): IDisputeListItem {
    return item._raw as IDisputeListItem;
}

function formatAmount(dispute: IDisputeListItem): string {
    return i18n.amount(dispute.amount.value, dispute.amount.currency, { hideCurrency: false });
}

function getMobileDate(dispute: IDisputeListItem): string {
    return props.statusGroup === 'CHARGEBACKS' && dispute.dueDate ? dispute.dueDate : dispute.createdAt;
}

function isMobileDateUrgent(dispute: IDisputeListItem): boolean {
    return props.statusGroup === 'CHARGEBACKS' && !!dispute.dueDate && isDisputeActionNeededUrgently(dispute);
}

function getTimeToDeadline(dueDate: string): string {
    if (!dueDate) return '';

    const timeRemaining = getDisputeDeadlineTimeRemaining(dueDate);
    if (!timeRemaining) return '';

    const formattedDate = dateFormat(dueDate, { ...DATE_FORMAT_RESPONSE_DEADLINE, weekday: undefined });
    if (timeRemaining.expired) return formattedDate;

    return timeRemaining.days <= 1
        ? i18n.get('disputes.overview.common.actionNeeded.respondToday', { values: { date: formattedDate } })
        : i18n.get('disputes.overview.common.actionNeeded.respondDays', { values: { days: timeRemaining.days, date: formattedDate } });
}

function handleNavigate(page: number) {
    if (isLoading.value) return;
    if (page > (props.currentPage ?? 1)) {
        props.goToNextPage?.();
    } else {
        props.goToPreviousPage?.();
    }
}

function handleItemsPage(size: number) {
    props.updateLimit?.(size);
}

function handleRowClick(item: BentoDatagridDataItem) {
    props.onRowClick?.(getDispute(item));
}

function handleListItemClick(dispute: IDisputeListItem) {
    props.onRowClick?.(dispute);
}
</script>

<template>
    <div :class="styles.root">
        <DataOverviewError
            v-if="props.error"
            :error="props.error"
            :error-message="'disputes.overview.common.errors.listUnavailable'"
            :on-contact-support="props.onContactSupport"
            :variant="isMobile ? 'condensed' : 'embedded'"
            :refresh-icon="RefreshIcon"
            :copy-icon="CopyIcon"
        />

        <template v-else-if="isMobile">
            <div v-if="isLoading" :class="styles.loading" aria-busy="true">
                <BentoLoadingIndicator />
            </div>

            <BentoEmptyState
                v-else-if="!customRecords.length"
                variant="condensed"
                :image="emptyStateProps.image"
                :title="emptyStateProps.title"
                :description="emptyStateProps.description"
            />

            <template v-else>
                <BentoList>
                    <BentoListItem
                        v-for="dispute in customRecords"
                        :key="dispute.disputePspReference"
                        with-chevron
                        show-bottom-divider
                        @click="handleListItemClick(dispute)"
                    >
                        <template #content>
                            <div :class="styles.mobileRow">
                                <div :class="styles.mobileDetails">
                                    <div :class="[styles.mobileDate, isMobileDateUrgent(dispute) ? styles.mobileDateUrgent : '']">
                                        <time :datetime="getMobileDate(dispute)">
                                            {{ dateFormat(getMobileDate(dispute), DATE_FORMAT_DISPUTES) }}
                                        </time>
                                        <WarningFilledIcon v-if="isMobileDateUrgent(dispute)" />
                                    </div>
                                    <DisputePaymentMethod :payment-method="dispute.paymentMethod" />
                                </div>
                                <BentoTypography :class="styles.mobileAmount" variant="body" stronger>
                                    <BentoCurrency
                                        :currency="dispute.amount.currency as BentoCurrencyISOCode"
                                        :value="dispute.amount.value"
                                        :disable-typography="true"
                                    />
                                </BentoTypography>
                            </div>
                        </template>
                    </BentoListItem>
                </BentoList>

                <BentoPagination
                    hide-first-last-page-buttons
                    v-if="showMobilePagination"
                    :page="props.currentPage"
                    :size="props.limit"
                    :has-next="props.hasNext"
                    hide-page-size
                    @navigate="handleNavigate"
                />
            </template>
        </template>

        <BentoDataGrid
            v-else
            :columns="columns"
            :data="gridData"
            :loading="isLoading"
            :pagination="paginationProps"
            :empty-state="emptyStateProps"
            :has-resizable-columns="false"
            :allow-column-drag-and-drop="false"
            :allow-row-clicks="true"
            @row-click="handleRowClick"
            @navigate="handleNavigate"
            @items-page="handleItemsPage"
        >
            <template #item-status="{ item }">
                <div :class="styles.cellContent">
                    <DisputeStatusTag :dispute="getDispute(item)" />
                </div>
            </template>

            <template #item-respondBy="{ item }">
                <div :class="styles.cellContent">
                    <span
                        v-if="getDispute(item).dueDate"
                        :class="[styles.statusContent, isDisputeActionNeededUrgently(getDispute(item)) ? styles.statusContentUrgent : '']"
                    >
                        <span
                            v-if="isDisputeActionNeededUrgently(getDispute(item))"
                            v-bento-tooltip="getTimeToDeadline(getDispute(item).dueDate!)"
                            :class="styles.dateContentUrgent"
                        >
                            <time :datetime="getDispute(item).dueDate">{{ dateFormat(getDispute(item).dueDate!, DATE_FORMAT_DISPUTES) }}</time>
                            <WarningFilledIcon />
                        </span>
                        <time v-else :datetime="getDispute(item).dueDate">{{ dateFormat(getDispute(item).dueDate!, DATE_FORMAT_DISPUTES) }}</time>
                    </span>
                </div>
            </template>

            <template #item-createdAt="{ item }">
                <div :class="styles.cellContent">
                    <time :datetime="getDispute(item).createdAt" :class="styles.statusContent">
                        <BentoTypography variant="body">{{ dateFormat(getDispute(item).createdAt, DATE_FORMAT_DISPUTES) }}</BentoTypography>
                    </time>
                </div>
            </template>

            <template #item-paymentMethod="{ item }">
                <DisputePaymentMethod :payment-method="getDispute(item).paymentMethod" />
            </template>

            <template #item-disputeReason="{ item }">
                <span>{{ getDisputeReason(i18n, getDispute(item).reason?.category) }}</span>
            </template>

            <template #item-reason="{ item }">
                <span>{{ getDispute(item).reason?.title }}</span>
            </template>

            <template #item-currency="{ item }">
                <BentoTag variant="grey" :label="getDispute(item).amount.currency" />
            </template>

            <template #item-disputedAmount="{ item }">
                <BentoTypography variant="body" stronger>
                    {{ formatAmount(getDispute(item)) }}
                </BentoTypography>
            </template>

            <template #item-totalPaymentAmount="{ item }">
                <BentoTypography variant="body" stronger>
                    {{ formatAmount(getDispute(item)) }}
                </BentoTypography>
            </template>

            <template v-for="key in customFieldKeys" #[`item-${key}`]="{ item }" :key="key">
                <CustomDataCell :value="item[key]" />
            </template>
        </BentoDataGrid>
    </div>
</template>
