// adyen-platform-experience-web-vue/src/components/ReportsOverview/components/ReportsOverview.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useCoreContext } from '../../../core/Context';
import ReportsFilters from './ReportsFilters.vue';
import ReportsTable from './ReportsTable.vue';
import { useReportsList } from '../composables/useReportsList';
import { BASE_CLASS } from '../constants';
import type { IBalanceAccountBase } from '../types';
import '../styles/index.scss';

const props = defineProps<{
    balanceAccountId?: string;
    allowLimitSelection?: boolean;
    preferredLimit?: number;
    hideTitle?: boolean;
    onContactSupport?: () => void;
    onFiltersChanged?: (filters: Record<string, string | undefined>) => any;
    dataCustomization?: any;
    balanceAccounts: IBalanceAccountBase[] | undefined;
    isLoadingBalanceAccount: boolean;
}>();

const { i18n } = useCoreContext();

const filterParams = ref<{
    balanceAccountId: string | undefined;
    createdSince: string;
    createdUntil: string;
}>({
    balanceAccountId: undefined,
    createdSince: new Date().toISOString(),
    createdUntil: new Date().toISOString(),
});

function onFiltersChange(params: { balanceAccountId: string | undefined; createdSince: string; createdUntil: string }) {
    filterParams.value = params;
}

const activeBalanceAccount = computed(() => {
    const id = filterParams.value.balanceAccountId;
    return props.balanceAccounts?.find((a: IBalanceAccountBase) => a.id === id);
});

const reportsListResult = useReportsList(() => ({
    fetchEnabled: !!filterParams.value.balanceAccountId,
    balanceAccountId: filterParams.value.balanceAccountId,
    createdSince: filterParams.value.createdSince,
    createdUntil: filterParams.value.createdUntil,
    allowLimitSelection: props.allowLimitSelection,
    preferredLimit: props.preferredLimit,
    onFiltersChanged: props.onFiltersChanged,
    dataCustomization: props.dataCustomization,
}));

const isLoading = computed(
    () =>
        reportsListResult.fetching.value ||
        props.isLoadingBalanceAccount ||
        !props.balanceAccounts ||
        !activeBalanceAccount.value ||
        reportsListResult.loadingCustomRecords.value
);

const displayData = computed(() => {
    if (props.dataCustomization?.list?.onDataRetrieve) {
        return reportsListResult.customRecords.value;
    }
    return reportsListResult.records.value;
});
</script>

<template>
    <div :class="BASE_CLASS">
        <div v-if="!props.hideTitle" class="adyen-pe-reports-overview-header">
            <h2>{{ i18n.get('reports.overview.title') }}</h2>
            <p class="adyen-pe-reports-overview-header__description">{{ i18n.get('reports.overview.generateInfo') }}</p>
        </div>

        <div role="toolbar" class="adyen-pe-reports-overview__toolbar">
            <ReportsFilters :balance-accounts="props.balanceAccounts" :on-change="onFiltersChange" />
        </div>

        <ReportsTable
            :balance-account-id="activeBalanceAccount?.id"
            :loading="isLoading"
            :data="displayData"
            :show-pagination="true"
            :error="reportsListResult.error.value as Error | undefined"
            :on-contact-support="props.onContactSupport"
            :custom-columns="props.dataCustomization?.list?.fields"
            :has-next="reportsListResult.hasNext.value"
            :has-previous="reportsListResult.hasPrevious.value"
            :go-to-next-page="reportsListResult.goToNextPage"
            :go-to-previous-page="reportsListResult.goToPreviousPage"
            :limit="reportsListResult.limit.value"
            :limit-options="reportsListResult.limitOptions.value"
            :update-limit="reportsListResult.updateLimit"
            :current-page="reportsListResult.page.value + 1"
        />
    </div>
</template>

// src/components/external/Reports/ReportsOverview/components/ReportsOverview/ReportsOverview.tsx
import { useCallback, useEffect, useMemo } from 'preact/hooks';
import { useConfigContext } from '../../../../../../core/ConfigContext';
import AdyenPlatformExperienceError from '../../../../../../core/Errors/AdyenPlatformExperienceError';
import { IBalanceAccountBase, IReport } from '../../../../../../types';
import { isFunction } from '../../../../../../utils';
import useBalanceAccountSelection from '../../../../../../hooks/useBalanceAccountSelection';
import useDefaultOverviewFilterParams from '../../../../../../hooks/useDefaultOverviewFilterParams';
import FilterBar, { FilterBarMobileSwitch, useFilterBarState } from '../../../../../internal/FilterBar';
import DateFilter from '../../../../../internal/FilterBar/filters/DateFilter/DateFilter';
import BalanceAccountSelector from '../../../../../internal/FormFields/Select/BalanceAccountSelector';
import { DEFAULT_PAGE_LIMIT, LIMIT_OPTIONS } from '../../../../../internal/Pagination/constants';
import { useCursorPaginatedRecords } from '../../../../../internal/Pagination/hooks';
import { Header } from '../../../../../internal/Header';
import { CustomDataRetrieved, ExternalUIComponentProps, FilterParam, ReportsOverviewComponentProps } from '../../../../../types';
import { FIELDS, ReportsTable } from '../ReportsTable/ReportsTable';
import { BASE_CLASS, EARLIEST_PAYOUT_SINCE_DATE } from './constants';
import './ReportsOverview.scss';
import { useCustomColumnsData } from '../../../../../../hooks/useCustomColumnsData';
import hasCustomField from '../../../../../utils/customData/hasCustomField';
import mergeRecords from '../../../../../utils/customData/mergeRecords';

export const ReportsOverview = ({
    onFiltersChanged,
    balanceAccounts,
    allowLimitSelection = true,
    preferredLimit = DEFAULT_PAGE_LIMIT,
    isLoadingBalanceAccount,
    onContactSupport,
    hideTitle,
    dataCustomization,
}: ExternalUIComponentProps<
    ReportsOverviewComponentProps & { balanceAccounts: IBalanceAccountBase[] | undefined; isLoadingBalanceAccount: boolean }
>) => {
    const { getReports: reportsEndpointCall } = useConfigContext().endpoints;
    const { activeBalanceAccount, balanceAccountSelectionOptions, onBalanceAccountSelection } = useBalanceAccountSelection({ balanceAccounts });
    const { defaultParams, nowTimestamp, refreshNowTimestamp } = useDefaultOverviewFilterParams('reports', activeBalanceAccount);

    const getReports = useCallback(
        async (pageRequestParams: Record<FilterParam | 'cursor', string>, signal?: AbortSignal) => {
            const requestOptions = { signal, errorLevel: 'error' } as const;

            return reportsEndpointCall!(requestOptions, {
                query: {
                    ...pageRequestParams,
                    type: 'payout',
                    createdSince:
                        pageRequestParams[FilterParam.CREATED_SINCE] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_SINCE],
                    createdUntil:
                        pageRequestParams[FilterParam.CREATED_UNTIL] ?? defaultParams.current.defaultFilterParams[FilterParam.CREATED_UNTIL],
                    balanceAccountId: activeBalanceAccount?.id ?? '',
                },
            });
        },
        [activeBalanceAccount?.id, defaultParams, reportsEndpointCall]
    );

    // FILTERS
    const filterBarState = useFilterBarState();
    const _onFiltersChanged = useMemo(() => (isFunction(onFiltersChanged) ? onFiltersChanged : void 0), [onFiltersChanged]);
    const preferredLimitOptions = useMemo(() => (allowLimitSelection ? LIMIT_OPTIONS : undefined), [allowLimitSelection]);

    const { canResetFilters, error, fetching, filters, limit, limitOptions, records, resetFilters, updateFilters, updateLimit, ...paginationProps } =
        useCursorPaginatedRecords<IReport, 'data', string, FilterParam>({
            fetchRecords: getReports,
            dataField: 'data',
            filterParams: defaultParams.current.defaultFilterParams,
            initialFiltersSameAsDefault: true,
            onFiltersChanged: _onFiltersChanged,
            preferredLimit,
            preferredLimitOptions,
            enabled: !!activeBalanceAccount?.id && !!reportsEndpointCall,
        });

    const mergeCustomData = useCallback(
        ({ records, retrievedData }: { records: IReport[]; retrievedData: CustomDataRetrieved[] }) =>
            mergeRecords(records, retrievedData, (modifiedRecord, record) => modifiedRecord.createdAt === record.createdAt),
        []
    );

    const hasCustomColumn = useMemo(() => hasCustomField(dataCustomization?.list?.fields, FIELDS), [dataCustomization?.list?.fields]);
    const { customRecords: reports, loadingCustomRecords } = useCustomColumnsData<IReport>({
        records,
        hasCustomColumn,
        onDataRetrieve: dataCustomization?.list?.onDataRetrieve,
        mergeCustomData,
    });

    useEffect(() => {
        refreshNowTimestamp();
    }, [filters, refreshNowTimestamp]);

    return (
        <div className={BASE_CLASS}>
            <Header hideTitle={hideTitle} titleKey="reports.overview.title" subtitleKey="reports.overview.generateInfo">
                <FilterBarMobileSwitch {...filterBarState} />
            </Header>
            <FilterBar {...filterBarState} ariaLabelKey="reports.overview.filters.label">
                <BalanceAccountSelector
                    activeBalanceAccount={activeBalanceAccount}
                    balanceAccountSelectionOptions={balanceAccountSelectionOptions}
                    onBalanceAccountSelection={onBalanceAccountSelection}
                />
                <DateFilter
                    canResetFilters={canResetFilters}
                    defaultParams={defaultParams}
                    filters={filters}
                    nowTimestamp={nowTimestamp}
                    refreshNowTimestamp={refreshNowTimestamp}
                    sinceDate={EARLIEST_PAYOUT_SINCE_DATE}
                    timezone={'UTC'}
                    updateFilters={updateFilters}
                />
            </FilterBar>
            <ReportsTable
                balanceAccountId={activeBalanceAccount?.id}
                loading={fetching || isLoadingBalanceAccount || !balanceAccounts || !activeBalanceAccount || loadingCustomRecords}
                data={dataCustomization?.list?.onDataRetrieve ? reports : records}
                showPagination={true}
                limit={limit}
                limitOptions={limitOptions}
                onContactSupport={onContactSupport}
                onLimitSelection={updateLimit}
                error={error as AdyenPlatformExperienceError}
                customColumns={dataCustomization?.list?.fields}
                {...paginationProps}
            />
        </div>
    );
};
