// src/components/external/Capital/CapitalOverview/components/GrantAdjustmentDetails/GrantAdjustmentDetails.tsx
import cx from 'classnames';
import { FunctionalComponent, h } from 'preact';
import type { TranslationKey } from '../../../../../../translations';
import type { GrantAdjustmentDetailsProps } from './types';
import './GrantAdjustmentDetails.scss';
import { Header } from '../../../../../internal/Header';
import Button from '../../../../../internal/Button/Button';
import { ButtonVariant } from '../../../../../internal/Button/types';
import Icon from '../../../../../internal/Icon';
import useCoreContext from '../../../../../../core/Context/useCoreContext';

export interface GrantAdjustmentDetailsComponentProps
    extends Pick<GrantAdjustmentDetailsProps, 'onDetailsClose'>,
        Pick<h.JSX.HTMLAttributes, 'className'> {
    headerTitleKey?: TranslationKey;
    headerSubtitleKey?: TranslationKey;
}

export const GrantAdjustmentDetails: FunctionalComponent<GrantAdjustmentDetailsComponentProps> = ({
    children,
    className,
    headerTitleKey,
    headerSubtitleKey,
    onDetailsClose,
}) => {
    const { i18n } = useCoreContext();

    return (
        <div className={cx('adyen-pe-grant-adjustment-details', className)}>
            <Header titleKey={headerTitleKey} subtitleKey={headerSubtitleKey}>
                <Button
                    onClick={onDetailsClose}
                    variant={ButtonVariant.TERTIARY}
                    iconButton
                    classNameModifiers={['circle']}
                    aria-label={i18n.get('common.actions.dismiss.labels.dismiss')}
                >
                    <Icon name="cross" />
                </Button>
            </Header>
            {children}
        </div>
    );
};

// packages/domains/capital/vue/src/CapitalOverview/components/GrantAdjustmentDetails/GrantAdjustmentDetails.vue
<script setup lang="ts">
import { BentoButton, BentoHeader } from '@adyen/bento-vue3';
import CrossIcon from '@adyen/ui-assets-icons-16/vue/cross';
import type { TranslationKey } from '@integration-components/core';
import { useCoreContext } from '@integration-components/core/vue';
import styles from './GrantAdjustmentDetails.module.scss';

const props = defineProps<{
    className?: string;
    headerSubtitleKey?: TranslationKey;
    headerTitleKey?: TranslationKey;
    onDetailsClose: () => void;
}>();

const { i18n } = useCoreContext();
</script>

<template>
    <div :class="[styles.root, props.className]">
        <div :class="styles.header">
            <BentoHeader
                v-if="props.headerTitleKey"
                :title="i18n.get(props.headerTitleKey)"
                :description="props.headerSubtitleKey ? i18n.get(props.headerSubtitleKey) : undefined"
                variant="component"
            />
            <BentoButton variant="tertiary" :aria-label="i18n.get('common.actions.dismiss.labels.dismiss')" @click="props.onDetailsClose">
                <CrossIcon />
            </BentoButton>
        </div>
        <slot />
    </div>
</template>
