// src/components/external/TransactionDetails/components/PaymentRefund/PaymentRefundAmount.tsx
import {
    TX_DATA_CONTAINER,
    TX_DATA_INPUT,
    TX_DATA_INPUT_CONTAINER,
    TX_DATA_INPUT_CONTAINER_SHORT,
    TX_DATA_INPUT_CONTAINER_TEXT,
    TX_DATA_INPUT_CONTAINER_WITH_ERROR,
    TX_DATA_INPUT_HEAD,
} from '../../constants';
import cx from 'classnames';
import { memo } from 'preact/compat';
import { Tag } from '../../../../internal/Tag/Tag';
import { TagVariant } from '../../../../internal/Tag/types';
import { ARIA_ERROR_SUFFIX } from '../../../../../core/Errors/constants';
import { getDecimalAmount, getDivider } from '../../../../../core/Localization/amount/amount-util';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Typography from '../../../../internal/Typography/Typography';
import InputBase from '../../../../internal/FormFields/InputBase';
import useUniqueId from '../../../../../hooks/useUniqueId';
import Icon from '../../../../internal/Icon';

interface PaymentRefundAmountProps {
    currency: string;
    disabled?: boolean;
    onChange?: (value: number) => void;
    value: string | number;
}

const PaymentRefundAmount = memo(({ currency, disabled, onChange, value }: PaymentRefundAmountProps) => {
    const { i18n } = useCoreContext();
    const inputIdentifier = useUniqueId();
    const labelIdentifier = useUniqueId();

    const currencyExponent = Math.log10(getDivider(currency));
    const refundableAmount = parseInt(`${value}`, 10);
    const formattedAmount = getDecimalAmount(refundableAmount, currency).toFixed(currencyExponent);

    const [refundAmount, setRefundAmount] = useState<string | number>(formattedAmount);
    const [validationError, setValidationError] = useState<keyof typeof errorMessages>();

    const errorMessages = useMemo(() => {
        const values = { amount: i18n.amount(refundableAmount, currency) };
        return {
            excess: i18n.get('transactions.details.refund.inputs.amount.errors.excess', { values }),
            negative: i18n.get('transactions.details.refund.inputs.amount.errors.negative'),
            required: i18n.get('transactions.details.refund.inputs.amount.errors.required'),
        } as const;
    }, [i18n, currency, refundableAmount]);

    const errorMessage = validationError && errorMessages[validationError];
    const inputLabel = useMemo(() => i18n.get('transactions.details.refund.inputs.amount.label'), [i18n]);
    const inputElementRef = useRef<HTMLInputElement>(null);

    const onInput = useCallback(
        (target: HTMLInputElement) => {
            let error: typeof validationError;
            let value = target.value.trim();
            const amount = Math.trunc(+`${parseFloat(value)}e${currencyExponent}`) || 0;

            if (amount || value) {
                if (amount < 0) error = 'negative';
                if (amount > refundableAmount) error = 'excess';
            } else error = 'required';

            // Get the decimal separator based on the user's locale
            const decimalSeparator = (1.1).toLocaleString(i18n.locale).match(/\d(.*?)\d/)?.[1] || '.';

            // Split the input value at the decimal separator
            const parts = value.split(decimalSeparator);

            if (parts.length === 2) {
                const integerPart = parts[0]!;
                let decimalPart = parts[1]!;

                if (decimalPart.length >= currencyExponent) {
                    decimalPart = decimalPart.substring(0, currencyExponent);
                    value = integerPart + decimalSeparator + decimalPart;
                    target.value = value;
                }
            }

            setRefundAmount(value);
            setValidationError(error);
            onChange?.(error ? 0 : amount);
        },
        [currencyExponent, refundableAmount, onChange, i18n.locale]
    );

    const cachedRefundableAmountRef = useRef<number>();

    useEffect(() => {
        if (cachedRefundableAmountRef.current !== refundableAmount) {
            cachedRefundableAmountRef.current = refundableAmount;
        } else if (disabled && validationError && inputElementRef.current) {
            inputElementRef.current.value = formattedAmount;
        } else return;

        if (inputElementRef.current) {
            onInput(inputElementRef.current);
        }
    }, [onInput, disabled, formattedAmount, refundableAmount, validationError]);

    return (
        <div className={TX_DATA_CONTAINER}>
            <div className={TX_DATA_INPUT_HEAD}>
                <div id={labelIdentifier}>
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                        {inputLabel}
                    </Typography>
                </div>
            </div>

            <div
                className={cx({
                    [TX_DATA_INPUT_CONTAINER]: true,
                    [TX_DATA_INPUT_CONTAINER_SHORT]: true,
                    [TX_DATA_INPUT_CONTAINER_TEXT]: true,
                    [TX_DATA_INPUT_CONTAINER_WITH_ERROR]: errorMessage,
                })}
            >
                <label htmlFor={inputIdentifier} aria-labelledby={labelIdentifier}>
                    {currency && <Tag label={currency} variant={TagVariant.DEFAULT} />}
                    <InputBase
                        min={0}
                        type="number"
                        className={TX_DATA_INPUT}
                        disabled={disabled}
                        lang={i18n.locale}
                        onInput={evt => onInput(evt.currentTarget)}
                        value={refundAmount}
                        uniqueId={inputIdentifier}
                        ref={inputElementRef}
                    />
                </label>
                {errorMessage && (
                    <div className="adyen-pe-input__refund-invalid-value" id={`${inputIdentifier}${ARIA_ERROR_SUFFIX}`}>
                        <Icon name="cross-circle-fill" />
                        <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                            {errorMessage}
                        </Typography>
                    </div>
                )}
            </div>
        </div>
    );
});

export default PaymentRefundAmount;

// adyen-platform-experience-web-vue/src/components/TransactionDetails/PaymentRefund/PaymentRefundAmount.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { BentoTypography, BentoTag } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import {
    TX_DATA_CONTAINER,
    TX_DATA_INPUT,
    TX_DATA_INPUT_CONTAINER,
    TX_DATA_INPUT_CONTAINER_SHORT,
    TX_DATA_INPUT_CONTAINER_TEXT,
    TX_DATA_INPUT_CONTAINER_WITH_ERROR,
    TX_DATA_INPUT_HEAD,
} from '../constants';

const props = defineProps<{
    currency: string;
    disabled?: boolean;
    onChange?: (value: number) => void;
    value: string | number;
}>();

const { i18n } = useCoreContext();

// Currency exponent (number of decimal places)
function getDivider(currency: string): number {
    try {
        const parts = new Intl.NumberFormat('en-US', { style: 'currency', currency }).formatToParts(1);
        const fraction = parts.find(p => p.type === 'fraction');
        return fraction ? Math.pow(10, fraction.value.length) : 100;
    } catch {
        return 100;
    }
}

function getDecimalAmount(value: number, currency: string): number {
    return value / getDivider(currency);
}

const currencyExponent = computed(() => Math.log10(getDivider(props.currency)));
const refundableAmount = computed(() => parseInt(`${props.value}`, 10));
const formattedAmount = computed(() => getDecimalAmount(refundableAmount.value, props.currency).toFixed(currencyExponent.value));

const refundAmount = ref<string>(formattedAmount.value);
const validationError = ref<'excess' | 'negative' | 'required'>();

const errorMessages = computed(() => {
    const values = { amount: i18n.amount(refundableAmount.value, props.currency) };
    return {
        excess: i18n.get('transactions.details.refund.inputs.amount.errors.excess', { values }),
        negative: i18n.get('transactions.details.refund.inputs.amount.errors.negative'),
        required: i18n.get('transactions.details.refund.inputs.amount.errors.required'),
    };
});

const errorMessage = computed(() => (validationError.value ? errorMessages.value[validationError.value] : undefined));
const inputLabel = computed(() => i18n.get('transactions.details.refund.inputs.amount.label'));

function onInput(event: Event) {
    const target = event.target as HTMLInputElement;
    let error: typeof validationError.value;
    const value = target.value.trim();
    const amount = Math.trunc(+`${parseFloat(value)}e${currencyExponent.value}`) || 0;

    if (amount || value) {
        if (amount < 0) error = 'negative';
        if (amount > refundableAmount.value) error = 'excess';
    } else {
        error = 'required';
    }

    // Get the decimal separator based on the user's locale
    const decimalSeparator = (1.1).toLocaleString(i18n.locale).match(/\d(.*?)\d/)?.[1] || '.';

    // Limit decimal places
    const parts = value.split(decimalSeparator);
    if (parts.length === 2) {
        let decimalPart = parts[1]!;
        if (decimalPart.length >= currencyExponent.value) {
            decimalPart = decimalPart.substring(0, currencyExponent.value);
            target.value = parts[0]! + decimalSeparator + decimalPart;
        }
    }

    refundAmount.value = target.value;
    validationError.value = error;
    props.onChange?.(error ? 0 : amount);
}

// Reset when refundable amount changes
let cachedRefundable: number | undefined;
watch(refundableAmount, val => {
    if (cachedRefundable !== val) {
        cachedRefundable = val;
        refundAmount.value = formattedAmount.value;
        // Re-validate
        const amount = Math.trunc(+`${parseFloat(formattedAmount.value)}e${currencyExponent.value}`) || 0;
        validationError.value = undefined;
        props.onChange?.(amount);
    }
});
</script>

<template>
    <div :class="TX_DATA_CONTAINER">
        <div :class="TX_DATA_INPUT_HEAD">
            <bento-typography variant="body" weight="stronger">
                {{ inputLabel }}
            </bento-typography>
        </div>

        <div
            :class="{
                [TX_DATA_INPUT_CONTAINER]: true,
                [TX_DATA_INPUT_CONTAINER_SHORT]: true,
                [TX_DATA_INPUT_CONTAINER_TEXT]: true,
                [TX_DATA_INPUT_CONTAINER_WITH_ERROR]: !!errorMessage,
            }"
        >
            <label style="display: flex; align-items: center">
                <bento-tag v-if="props.currency" :label="props.currency" variant="grey" />
                <input
                    type="number"
                    :class="TX_DATA_INPUT"
                    :disabled="props.disabled"
                    :lang="i18n.locale"
                    :value="refundAmount"
                    min="0"
                    style="flex: 1; border: none; outline: none; background: transparent; padding: 8px"
                    @input="onInput"
                />
            </label>
            <div v-if="errorMessage" class="adyen-pe-input__refund-invalid-value">
                <span style="color: inherit">&#10006;</span>
                <bento-typography variant="body">
                    {{ errorMessage }}
                </bento-typography>
            </div>
        </div>
    </div>
</template>
