// packages/domains/capital/vue/src/CapitalOverview/components/GrantActionsEmbedded/GrantActionsEmbedded.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue';
import { BentoAlert, BentoButton, BentoModal } from '@adyen/bento-vue3';
import CheckmarkCircleFillIcon from '@adyen/ui-assets-icons-16/vue/checkmark-circle-fill';
import { getMissingActionsMetadata } from '@integration-components/capital/domain';
import { useConfigContext, useCoreContext, useEventDispatcherContext } from '@integration-components/core/vue';
import type { IMissingAction, IMissingActionType } from '@integration-components/types';
import { EMPTY_OBJECT, DATE_FORMAT_MISSING_ACTION } from '@integration-components/utils';
import { useTimezoneAwareDateFormatting } from '@integration-components/composables-vue';
import { GRANT_ACTION_CONFIGS, sharedCapitalOverviewAnalyticsEventProperties } from '../../../../../domain/src/CapitalOverview/constants';
import { GRANT_ACTIONS_EMBEDDED_CLASS_NAMES } from './constants';
import './GrantActionsEmbedded.scss';

const props = defineProps<{
    className?: string;
    expirationDate?: string;
    legalEntityId: string;
    missingActions: IMissingAction[];
}>();

const emit = defineEmits<{
    complete: [];
}>();

const ANALYTICS_EVENT_DELAY_MS = 50;
const { i18n, environment: coreEnvironment } = useCoreContext();
const environment: string | undefined = coreEnvironment;
const config = useConfigContext();
const userEvents = useEventDispatcherContext();
const { dateFormat } = useTimezoneAwareDateFormatting();
const activeAction = ref<IMissingActionType>();
const completedActions = ref<IMissingActionType[]>([]);
const loadedActions = ref(new Set<IMissingActionType>());
const completedActionsWithoutDelay = new Set<IMissingActionType>();
const closeTimeouts = new Map<IMissingActionType, ReturnType<typeof setTimeout>>();

const missingActionsMetadata = computed(() => getMissingActionsMetadata(props.missingActions, completedActions.value));
const areActionsCompleted = computed(() => missingActionsMetadata.value.areActionsCompleted);
const formattedExpirationDate = computed(() => (props.expirationDate ? dateFormat(props.expirationDate, DATE_FORMAT_MISSING_ACTION) : undefined));
const alertTitles = computed(() => ({
    multiple: formattedExpirationDate.value
        ? i18n.get('capital.overview.grants.item.alerts.actionNeededByMany', { values: { date: formattedExpirationDate.value } })
        : i18n.get('capital.overview.grants.item.alerts.actionNeededMany'),
    single: formattedExpirationDate.value
        ? i18n.get('capital.overview.grants.item.alerts.actionNeededBy', { values: { date: formattedExpirationDate.value } })
        : i18n.get('capital.overview.grants.item.alerts.actionNeeded'),
}));
const alertTitle = computed(() => {
    if (areActionsCompleted.value) {
        return i18n.get('capital.overview.grants.item.alerts.actionsCompleted');
    }

    return props.missingActions.length > 1 ? alertTitles.value.multiple : alertTitles.value.single;
});

const fetchToken = async () => {
    const onboardingConfiguration = await config.endpoints.getOnboardingConfiguration?.(EMPTY_OBJECT);
    return { token: onboardingConfiguration?.token ?? '' };
};

const loadKycComponent = async (actionType: IMissingActionType) => {
    if (loadedActions.value.has(actionType)) {
        return;
    }

    if (actionType === 'AnaCredit') {
        await import('@adyen/kyc-components/business-financing');
    } else {
        await import('@adyen/kyc-components/terms-of-service-management');
    }

    loadedActions.value = new Set(loadedActions.value).add(actionType);
};

const close = () => {
    activeAction.value = undefined;
};

const completeAction = () => {
    if (activeAction.value && !completedActions.value.includes(activeAction.value)) {
        completedActions.value = [...completedActions.value, activeAction.value];
    }

    close();
};

const handleActionButtonClick = async (actionType: IMissingActionType) => {
    await loadKycComponent(actionType);
    activeAction.value = actionType;
    userEvents.addEvent?.('Clicked button', {
        ...sharedCapitalOverviewAnalyticsEventProperties,
        subCategory: 'Missing action',
        label: GRANT_ACTION_CONFIGS[actionType].eventLabel,
    });
};

const handleClose = (actionType: IMissingActionType, analyticsProperties: { label: string; subCategory: string }) => {
    close();
    const existingTimeout = closeTimeouts.get(actionType);

    if (existingTimeout) {
        clearTimeout(existingTimeout);
    }

    closeTimeouts.set(
        actionType,
        setTimeout(() => {
            if (!completedActionsWithoutDelay.has(actionType)) {
                userEvents.addEvent?.('Clicked button', {
                    ...sharedCapitalOverviewAnalyticsEventProperties,
                    category: 'Missing action modal',
                    ...analyticsProperties,
                });
            }

            completedActionsWithoutDelay.delete(actionType);
            closeTimeouts.delete(actionType);
        }, ANALYTICS_EVENT_DELAY_MS)
    );
};

const handleBusinessFinancingClose = () => {
    handleClose('AnaCredit', { label: 'Dismissed AnaCredit information', subCategory: 'Information' });
};

const handleBusinessFinancingComplete = () => {
    completedActionsWithoutDelay.add('AnaCredit');
    completeAction();
    userEvents.addEvent?.('Clicked button', {
        ...sharedCapitalOverviewAnalyticsEventProperties,
        category: 'Missing action modal',
        label: 'Submitted AnaCredit information',
        subCategory: 'Information',
    });
};

const handleTermsOfServiceClose = () => {
    handleClose('signToS', { label: 'Dismissed terms & conditions', subCategory: 'Terms & conditions' });
};

const handleTermsOfServiceAccept = () => {
    userEvents.addEvent?.('Clicked button', {
        ...sharedCapitalOverviewAnalyticsEventProperties,
        category: 'Missing action modal',
        label: 'Signed terms & conditions',
        subCategory: 'Terms & conditions',
    });
};

const handleTermsOfServiceComplete = () => {
    completedActionsWithoutDelay.add('signToS');
    completeAction();
    userEvents.addEvent?.('Clicked button', {
        ...sharedCapitalOverviewAnalyticsEventProperties,
        category: 'Missing action modal',
        label: 'Finished terms & conditions',
        subCategory: 'Terms & conditions',
    });
};

watch(areActionsCompleted, isComplete => {
    if (isComplete) {
        emit('complete');
    }
});

onUnmounted(() => {
    closeTimeouts.forEach(timeoutId => clearTimeout(timeoutId));
    closeTimeouts.clear();
});
</script>

<template>
    <div>
        <BentoAlert :class="props.className" :type="areActionsCompleted ? 'highlight' : 'warning'">
            {{ alertTitle }}
            <template #description>
                <div v-if="props.missingActions.length > 1" :class="GRANT_ACTIONS_EMBEDDED_CLASS_NAMES.actionButtonsContainer">
                    <BentoButton
                        v-for="action in props.missingActions"
                        :key="action.type"
                        :class="GRANT_ACTIONS_EMBEDDED_CLASS_NAMES.actionButton"
                        :variant="missingActionsMetadata.primaryActionType === action.type ? 'primary' : 'secondary'"
                        :aria-label="i18n.get(GRANT_ACTION_CONFIGS[action.type].buttonLabelKey)"
                        @click="handleActionButtonClick(action.type)"
                    >
                        <template v-if="completedActions.includes(action.type)" #iconLeft>
                            <CheckmarkCircleFillIcon />
                        </template>
                        {{
                            i18n.get(
                                completedActions.includes(action.type)
                                    ? GRANT_ACTION_CONFIGS[action.type].successButtonLabelKey
                                    : GRANT_ACTION_CONFIGS[action.type].buttonLabelKey
                            )
                        }}
                    </BentoButton>
                </div>
                <BentoButton
                    v-else
                    :class="GRANT_ACTIONS_EMBEDDED_CLASS_NAMES.actionButton"
                    :variant="missingActionsMetadata.primaryActionType === props.missingActions[0]?.type ? 'primary' : 'secondary'"
                    :aria-label="i18n.get(GRANT_ACTION_CONFIGS[props.missingActions[0]!.type].buttonLabelKey)"
                    @click="handleActionButtonClick(props.missingActions[0]!.type)"
                >
                    <template v-if="completedActions.includes(props.missingActions[0]!.type)" #iconLeft>
                        <CheckmarkCircleFillIcon />
                    </template>
                    {{
                        i18n.get(
                            completedActions.includes(props.missingActions[0]!.type)
                                ? GRANT_ACTION_CONFIGS[props.missingActions[0]!.type].successButtonLabelKey
                                : GRANT_ACTION_CONFIGS[props.missingActions[0]!.type].buttonLabelKey
                        )
                    }}
                </BentoButton>
            </template>
        </BentoAlert>

        <BentoModal :is-open="!!activeAction" :is-dismissible="false" :header-with-border="false" size="large" @close-modal="close">
            <span />
            <template #content>
                <adyen-business-financing
                    v-if="activeAction === 'AnaCredit'"
                    :locale.prop="i18n.locale"
                    :environment.prop="environment"
                    :fetchToken.prop="fetchToken"
                    :rootlegalentityid.prop="props.legalEntityId"
                    :oncomplete.prop="handleBusinessFinancingComplete"
                    :onclose.prop="handleBusinessFinancingClose"
                />
                <adyen-terms-of-service-management
                    v-if="activeAction === 'signToS'"
                    :locale.prop="i18n.locale"
                    :environment.prop="environment"
                    :fetchToken.prop="fetchToken"
                    :rootlegalentityid.prop="props.legalEntityId"
                    :onaccept.prop="handleTermsOfServiceAccept"
                    :oncomplete.prop="handleTermsOfServiceComplete"
                    :onclose.prop="handleTermsOfServiceClose"
                />
            </template>
        </BentoModal>
    </div>
</template>

// src/components/external/CapitalOverview/components/GrantActionsEmbedded/GrantActionsEmbedded.tsx
import { Fragment, FunctionalComponent } from 'preact';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Alert from '@integration-components/ui-primitives-preact/Alert/Alert';
import { AlertTypeOption } from '@integration-components/ui-primitives-preact/Alert/types';
import Button from '@integration-components/ui-primitives-preact/Button';
import { useConfigContext } from '../../../../../core/ConfigContext';
import { ButtonVariant } from '@integration-components/ui-primitives-preact/Button/types';
import { IMissingAction, IMissingActionType } from '../../../../../types';
import { GRANT_ACTION_CONFIGS, sharedCapitalOverviewAnalyticsEventProperties } from '../../constants';
import Modal from '@integration-components/ui-primitives-preact/Modal';
import { EMPTY_OBJECT } from '../../../../../utils';
import useEventDispatcherContext from '../../../../../core/Context/eventDispatcher/useEventDispatcherContext';
import { useActionsAlertTitles } from '../../hooks';
import Icon from '@integration-components/ui-primitives-preact/Icon';
import './GrantActionsEmbedded.scss';

const CLASSNAMES = {
    actionButtonsContainer: 'adyen-pe-grant-actions-embedded__action-buttons-container',
    actionButton: 'adyen-pe-grant-actions-embedded__action-button',
};

const ANALYTICS_EVENT_DELAY_MS = 50;

const sharedActionAnalyticsEventProps = {
    ...sharedCapitalOverviewAnalyticsEventProperties,
    category: 'Missing action modal',
};

type GrantActionsEmbeddedProps = {
    className?: string;
    legalEntityId: string;
    missingActions: IMissingAction[];
    expirationDate?: string;
    onComplete: () => void;
};

export const GrantActionsEmbedded: FunctionalComponent<GrantActionsEmbeddedProps> = ({
    className,
    expirationDate,
    legalEntityId,
    missingActions,
    onComplete,
}) => {
    const { i18n, environment } = useCoreContext();
    const userEvents = useEventDispatcherContext();
    const { getOnboardingConfiguration } = useConfigContext().endpoints;
    const completedActionsRef = useRef<Set<IMissingActionType>>(new Set());
    const timeoutIdsRef = useRef<Map<IMissingActionType, ReturnType<typeof setTimeout>>>(new Map());

    const fetchToken = useCallback(async () => {
        const data = await getOnboardingConfiguration?.(EMPTY_OBJECT);
        return { token: data?.token || '' };
    }, [getOnboardingConfiguration]);

    const [actionsWithLoadedComponent, setActionsWithLoadedComponent] = useState<IMissingActionType[]>([]);
    const [activeAction, setActiveAction] = useState<IMissingActionType | undefined>(undefined);
    const [completedActions, setCompletedActions] = useState<IMissingActionType[]>([]);
    const areActionsCompleted = useMemo(() => completedActions.length === missingActions.length, [completedActions.length, missingActions.length]);

    useEffect(() => {
        if (areActionsCompleted) {
            onComplete();
        }
    }, [areActionsCompleted, onComplete]);

    useEffect(() => {
        const timeoutIds = timeoutIdsRef.current;
        return () => {
            timeoutIds.forEach(timeoutId => clearTimeout(timeoutId));
            timeoutIds.clear();
        };
    }, []);

    const loadKYCComponent = useCallback(
        async (actionType: IMissingActionType) => {
            if (!actionsWithLoadedComponent.includes(actionType)) {
                switch (actionType) {
                    case 'AnaCredit':
                        await import('@adyen/kyc-components/business-financing');
                        break;
                    case 'signToS':
                        await import('@adyen/kyc-components/terms-of-service-management');
                        break;
                }

                setActionsWithLoadedComponent(prev => [...prev, actionType]);
            }
        },
        [actionsWithLoadedComponent]
    );

    const handleActionButtonClick = useCallback(
        async (actionType: IMissingActionType) => {
            await loadKYCComponent(actionType);
            setActiveAction(actionType);
            userEvents.addEvent?.('Clicked button', {
                ...sharedCapitalOverviewAnalyticsEventProperties,
                subCategory: 'Missing action',
                label: GRANT_ACTION_CONFIGS[actionType].eventLabel,
            });
        },
        [loadKYCComponent, userEvents]
    );

    const getActionButtonVariant = useCallback(
        (actionType: IMissingActionType) => {
            const primaryAction = missingActions.find(action => !completedActions.includes(action.type));
            return primaryAction?.type === actionType ? ButtonVariant.PRIMARY : ButtonVariant.SECONDARY;
        },
        [completedActions, missingActions]
    );

    const renderActionButton = useCallback(
        (actionType: IMissingActionType) => {
            const isActionCompleted = completedActions.includes(actionType);
            const config = GRANT_ACTION_CONFIGS[actionType];
            return (
                <Button
                    className={CLASSNAMES.actionButton}
                    onClick={() => handleActionButtonClick(actionType)}
                    variant={getActionButtonVariant(actionType)}
                    aria-label={i18n.get(config.buttonLabelKey)}
                    iconLeft={isActionCompleted ? <Icon name="checkmark-circle-fill" /> : undefined}
                >
                    {isActionCompleted ? i18n.get(config.successButtonLabelKey) : i18n.get(config.buttonLabelKey)}
                </Button>
            );
        },
        [completedActions, getActionButtonVariant, handleActionButtonClick, i18n]
    );

    const alertTitles = useActionsAlertTitles(expirationDate);
    const processAlertTitle = useCallback(
        (title: string) => (areActionsCompleted ? i18n.get('capital.overview.grants.item.alerts.actionsCompleted') : title),
        [areActionsCompleted, i18n]
    );
    const alertConfig = useMemo(() => {
        if (missingActions.length > 1) {
            return {
                title: processAlertTitle(alertTitles.multiple),
                description: (
                    <div className={CLASSNAMES.actionButtonsContainer}>
                        {missingActions.map(action => (
                            <Fragment key={action.type}>{renderActionButton(action.type)}</Fragment>
                        ))}
                    </div>
                ),
            };
        } else {
            const actionType = missingActions[0]!.type;
            return {
                title: processAlertTitle(alertTitles.single),
                description: renderActionButton(actionType),
            };
        }
    }, [alertTitles.multiple, alertTitles.single, missingActions, processAlertTitle, renderActionButton]);

    const close = useCallback(() => {
        setActiveAction(undefined);
    }, []);

    const completeAction = useCallback(() => {
        if (activeAction) {
            setCompletedActions(prev => (prev.includes(activeAction) ? prev : [...prev, activeAction]));
        }
        close();
    }, [activeAction, close]);

    const handleClose = useCallback(
        (actionType: IMissingActionType, analyticsProps: { subCategory: string; label: string }) => {
            close();
            const existingTimeout = timeoutIdsRef.current.get(actionType);
            if (existingTimeout !== undefined) {
                clearTimeout(existingTimeout);
            }
            const timeoutId = setTimeout(() => {
                if (!completedActionsRef.current.has(actionType)) {
                    userEvents.addEvent?.('Clicked button', {
                        ...sharedActionAnalyticsEventProps,
                        ...analyticsProps,
                    });
                }
                completedActionsRef.current.delete(actionType);
                timeoutIdsRef.current.delete(actionType);
            }, ANALYTICS_EVENT_DELAY_MS);
            timeoutIdsRef.current.set(actionType, timeoutId);
        },
        [close, userEvents]
    );

    const handleBusinessFinancingClose = useCallback(() => {
        handleClose('AnaCredit', {
            subCategory: 'Information',
            label: 'Dismissed AnaCredit information',
        });
    }, [handleClose]);

    const handleBusinessFinancingComplete = useCallback(() => {
        completedActionsRef.current.add('AnaCredit');
        completeAction();
        userEvents.addEvent?.('Clicked button', {
            ...sharedActionAnalyticsEventProps,
            subCategory: 'Information',
            label: 'Submitted AnaCredit information',
        });
    }, [completeAction, userEvents]);

    const handleTermsOfServiceClose = useCallback(() => {
        handleClose('signToS', {
            subCategory: 'Terms & conditions',
            label: 'Dismissed terms & conditions',
        });
    }, [handleClose]);

    const handleTermsOfServiceAccept = useCallback(() => {
        userEvents.addEvent?.('Clicked button', {
            ...sharedActionAnalyticsEventProps,
            subCategory: 'Terms & conditions',
            label: 'Signed terms & conditions',
        });
    }, [userEvents]);

    const handleTermsOfServiceComplete = useCallback(() => {
        completedActionsRef.current.add('signToS');
        completeAction();
        userEvents.addEvent?.('Clicked button', {
            ...sharedActionAnalyticsEventProps,
            subCategory: 'Terms & conditions',
            label: 'Finished terms & conditions',
        });
    }, [completeAction, userEvents]);

    return (
        <div>
            <Alert
                className={className}
                type={areActionsCompleted ? AlertTypeOption.HIGHLIGHT : AlertTypeOption.WARNING}
                title={alertConfig.title}
                description={alertConfig.description}
            />
            <Modal isOpen={!!activeAction} onClose={close} isDismissible={false} headerWithBorder={false} size="large">
                {activeAction === 'AnaCredit' && (
                    <adyen-business-financing
                        locale={i18n.locale}
                        environment={environment}
                        fetchToken={fetchToken}
                        rootlegalentityid={legalEntityId}
                        oncomplete={handleBusinessFinancingComplete}
                        onclose={handleBusinessFinancingClose}
                    ></adyen-business-financing>
                )}

                {activeAction === 'signToS' && (
                    <adyen-terms-of-service-management
                        locale={i18n.locale}
                        environment={environment}
                        fetchToken={fetchToken}
                        rootlegalentityid={legalEntityId}
                        onaccept={handleTermsOfServiceAccept}
                        oncomplete={handleTermsOfServiceComplete}
                        onclose={handleTermsOfServiceClose}
                    ></adyen-terms-of-service-management>
                )}
            </Modal>
        </div>
    );
};
