// src/components/external/CapitalOverview/components/GrantActionsHosted/GrantActionsHosted.tsx
import { FunctionalComponent } from 'preact';
import { useCallback, useMemo, useState } from 'preact/hooks';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import useEventDispatcherContext from '../../../../../core/Context/eventDispatcher/useEventDispatcherContext';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';
import Button from '@integration-components/ui-components-preact/Button';
import { ButtonVariant } from '@integration-components/types';
import { IMissingAction, IMissingActionType } from '../../../../../types';
import { useConfigContext } from '../../../../../core/ConfigContext';
import useMutation from '../../../../../hooks/useMutation/useMutation';
import { EMPTY_OBJECT } from '../../../../../utils';
import { useActionsAlertTitles } from '../../hooks';
import { getTopWindowHref, setTopWindowHref } from '../GrantActions/utils';
import { GRANT_ACTION_CONFIGS, sharedCapitalOverviewAnalyticsEventProperties } from '../../constants';
import './GrantActionsHosted.scss';

const CLASSNAMES = {
    button: 'adyen-pe-grant-actions-hosted__button',
    buttonLabel: 'adyen-pe-grant-actions-hosted__button-label',
    actionsContainer: 'adyen-pe-grant-actions-hosted__actions-container',
};

type GrantActionsHostedProps = {
    className?: string;
    expirationDate?: string;
    missingActions: IMissingAction[];
};

export const GrantActionsHosted: FunctionalComponent<GrantActionsHostedProps> = ({ className, expirationDate, missingActions }) => {
    const { i18n, updateCore } = useCoreContext();
    const userEvents = useEventDispatcherContext();
    const { anaCreditActionDetails, signToSActionDetails } = useConfigContext().endpoints;

    const [loadingAction, setLoadingAction] = useState<IMissingActionType | null>(null);

    const onRedirect = useCallback((data: { url: string } | undefined) => {
        if (data?.url) {
            setTopWindowHref(data.url);
        } else {
            // If the request was successful but no URL was returned, reset loading state.
            setLoadingAction(null);
        }
    }, []);

    const endpointsByAction = useMemo(
        () => ({
            signToS: signToSActionDetails,
            AnaCredit: anaCreditActionDetails,
        }),
        [anaCreditActionDetails, signToSActionDetails]
    );

    const actionMutation = useMutation({
        queryFn: (actionType: IMissingActionType) => {
            const callbackQuery = {
                query: { redirectUrl: getTopWindowHref(), locale: i18n.locale },
            };

            return endpointsByAction[actionType]?.(EMPTY_OBJECT, callbackQuery);
        },
        options: {
            onSuccess: onRedirect,
            // Reset the loading state when the mutation finishes (success or error)
            onError: () => {
                setLoadingAction(null);
            },
        },
    });

    const logMissingActionEvent = useCallback(
        (label: string) => {
            userEvents.addEvent?.('Clicked link', {
                ...sharedCapitalOverviewAnalyticsEventProperties,
                subCategory: 'Missing action',
                label,
            });
        },
        [userEvents]
    );

    const renderActionButton = useCallback(
        (actionType: IMissingActionType) => (
            <Button
                className={CLASSNAMES.button}
                onClick={() => {
                    try {
                        setLoadingAction(actionType);
                        void actionMutation.mutate(actionType);
                    } finally {
                        logMissingActionEvent(GRANT_ACTION_CONFIGS[actionType].eventLabel);
                    }
                }}
                variant={ButtonVariant.TERTIARY}
                aria-label={i18n.get(GRANT_ACTION_CONFIGS[actionType].buttonLabelKey)}
                disabled={actionMutation.isLoading}
                state={loadingAction === actionType ? 'loading' : undefined}
            >
                <span className={CLASSNAMES.buttonLabel}>{i18n.get(GRANT_ACTION_CONFIGS[actionType].buttonLabelKey)}</span>
            </Button>
        ),
        [actionMutation, i18n, loadingAction, logMissingActionEvent]
    );

    const alertTitles = useActionsAlertTitles(expirationDate);
    const alertConfig = useMemo(() => {
        if (missingActions.length > 1) {
            return {
                title: alertTitles.multiple,
                description: (
                    <ol className={CLASSNAMES.actionsContainer}>
                        {missingActions.map(action => (
                            <li key={action.type}>{renderActionButton(action.type)}</li>
                        ))}
                    </ol>
                ),
            };
        } else {
            const actionType = missingActions[0]!.type;
            return {
                title: alertTitles.single,
                description: renderActionButton(actionType),
            };
        }
    }, [alertTitles.multiple, alertTitles.single, missingActions, renderActionButton]);

    if (actionMutation.error) {
        return (
            <Alert
                className={className}
                type={AlertTypeOption.CRITICAL}
                title={i18n.get('capital.overview.grants.item.alerts.somethingWentWrong')}
                description={
                    <Button className={CLASSNAMES.button} onClick={updateCore}>
                        {i18n.get('common.actions.refresh.labels.default')}
                    </Button>
                }
            />
        );
    }

    return <Alert className={className} type={AlertTypeOption.WARNING} title={alertConfig.title} description={alertConfig.description} />;
};

// packages/domains/capital/vue/src/CapitalOverview/components/GrantActionsHosted/GrantActionsHosted.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { BentoAlert, BentoButton } from '@adyen/bento-vue3';
import { useTimezoneAwareDateFormatting } from '@integration-components/composables-vue';
import { useConfigContext, useCoreContext, useEventDispatcherContext } from '@integration-components/core/vue';
import type { IMissingAction, IMissingActionType } from '@integration-components/types';
import { EMPTY_OBJECT, DATE_FORMAT_MISSING_ACTION } from '@integration-components/utils';
import { GRANT_ACTION_CONFIGS, sharedCapitalOverviewAnalyticsEventProperties } from '../../../../../domain/src/CapitalOverview/constants';
import { GRANT_ACTIONS_HOSTED_CLASS_NAMES } from './constants';
import './GrantActionsHosted.scss';

const props = defineProps<{
    className?: string;
    expirationDate?: string;
    missingActions: IMissingAction[];
}>();

const { i18n, refreshComponent } = useCoreContext();
const config = useConfigContext();
const userEvents = useEventDispatcherContext();
const { dateFormat } = useTimezoneAwareDateFormatting();
const loadingAction = ref<IMissingActionType>();
const error = ref<Error>();

const formattedExpirationDate = computed(() => (props.expirationDate ? dateFormat(props.expirationDate, DATE_FORMAT_MISSING_ACTION) : undefined));
const alertTitle = computed(() => {
    const key =
        props.missingActions.length > 1 ? 'capital.overview.grants.item.alerts.actionNeededMany' : 'capital.overview.grants.item.alerts.actionNeeded';
    const keyWithDate =
        props.missingActions.length > 1
            ? 'capital.overview.grants.item.alerts.actionNeededByMany'
            : 'capital.overview.grants.item.alerts.actionNeededBy';

    return formattedExpirationDate.value ? i18n.get(keyWithDate, { values: { date: formattedExpirationDate.value } }) : i18n.get(key);
});

const getTopWindowHref = () => window.top?.location.href || window.location.href;

const redirectTopWindow = (url: string) => {
    if (window.top) {
        window.top.location.href = url;
    } else {
        window.location.href = url;
    }
};

const redirectToHostedAction = async (actionType: IMissingActionType) => {
    const endpoint = actionType === 'AnaCredit' ? config.endpoints.anaCreditActionDetails : config.endpoints.signToSActionDetails;

    if (!endpoint) {
        loadingAction.value = undefined;
        return;
    }

    loadingAction.value = actionType;
    error.value = undefined;

    try {
        const response = await endpoint(EMPTY_OBJECT, {
            query: { locale: i18n.locale, redirectUrl: getTopWindowHref() },
        });

        if (response.url) {
            redirectTopWindow(response.url);
        } else {
            loadingAction.value = undefined;
        }
    } catch (requestError) {
        error.value = requestError as Error;
        loadingAction.value = undefined;
    }
};

const handleActionClick = (actionType: IMissingActionType) => {
    try {
        void redirectToHostedAction(actionType);
    } finally {
        userEvents.addEvent?.('Clicked link', {
            ...sharedCapitalOverviewAnalyticsEventProperties,
            subCategory: 'Missing action',
            label: GRANT_ACTION_CONFIGS[actionType].eventLabel,
        });
    }
};
</script>

<template>
    <BentoAlert v-if="error" :class="props.className" type="critical">
        {{ i18n.get('capital.overview.grants.item.alerts.somethingWentWrong') }}
        <template #actions>
            <BentoButton :class="GRANT_ACTIONS_HOSTED_CLASS_NAMES.button" @click="refreshComponent">
                {{ i18n.get('common.actions.refresh.labels.default') }}
            </BentoButton>
        </template>
    </BentoAlert>

    <BentoAlert v-else :class="props.className" type="warning">
        {{ alertTitle }}
        <template #description>
            <ol v-if="props.missingActions.length > 1" :class="GRANT_ACTIONS_HOSTED_CLASS_NAMES.actionsContainer">
                <li v-for="action in props.missingActions" :key="action.type">
                    <BentoButton
                        :class="GRANT_ACTIONS_HOSTED_CLASS_NAMES.button"
                        variant="tertiary"
                        :aria-label="i18n.get(GRANT_ACTION_CONFIGS[action.type].buttonLabelKey)"
                        :disabled="!!loadingAction"
                        :state="loadingAction === action.type ? 'loading' : undefined"
                        @click="handleActionClick(action.type)"
                    >
                        {{ i18n.get(GRANT_ACTION_CONFIGS[action.type].buttonLabelKey) }}
                    </BentoButton>
                </li>
            </ol>
            <BentoButton
                v-else
                :class="GRANT_ACTIONS_HOSTED_CLASS_NAMES.button"
                variant="tertiary"
                :aria-label="i18n.get(GRANT_ACTION_CONFIGS[props.missingActions[0]!.type].buttonLabelKey)"
                :disabled="!!loadingAction"
                :state="loadingAction === props.missingActions[0]?.type ? 'loading' : undefined"
                @click="handleActionClick(props.missingActions[0]!.type)"
            >
                {{ i18n.get(GRANT_ACTION_CONFIGS[props.missingActions[0]!.type].buttonLabelKey) }}
            </BentoButton>
        </template>
    </BentoAlert>
</template>
