// adyen-platform-experience-web-vue/src/components/TransactionDetails/TransactionDataContent.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import useRefundMetadata from './composables/useRefundMetadata';
import PaymentDetails from './PaymentDetails/PaymentDetails.vue';
import PaymentRefund from './PaymentRefund/PaymentRefund.vue';
import { ActiveView, type TransactionDetails, type TransactionDetailsProps } from './types';
import type { ILineItem } from './types';

const props = defineProps<{
    dataCustomization?: TransactionDetailsProps['dataCustomization'];
    extraFields: Record<string, any> | undefined;
    fetchingTransaction: boolean;
    refreshTransaction: () => void;
    transaction: TransactionDetails;
    transactionNavigator: any;
}>();

const activeView = ref<ActiveView>(ActiveView.DETAILS);
const locked = ref(false);

const {
    fullRefundFailed,
    fullRefundInProgress,
    refundableAmount,
    refundAmounts,
    refundAvailable,
    refundCurrency,
    refundDisabled,
    refundedAmount,
    refundedState,
    refundMode,
    refundLocked,
} = useRefundMetadata(() => props.transaction);

const refundIsLocked = computed(() => refundLocked.value || locked.value);
const refundIsDisabled = computed(() => refundDisabled.value || refundIsLocked.value);

const lineItems = computed<readonly ILineItem[]>(() => Object.freeze(props.transaction.lineItems ?? []));

// Reset locked state when refundLocked changes
watch(refundLocked, val => {
    if (val) {
        locked.value = false;
    }
});

function setActiveView(view: ActiveView) {
    activeView.value = view;
}

function setLocked(val: boolean) {
    locked.value = val;
}
</script>

<template>
    <!-- Loading skeleton -->
    <template v-if="props.fetchingTransaction">
        <div class="adyen-pe-overview-details__skeleton">
            <div v-for="n in 5" :key="n" class="skeleton-row"></div>
        </div>
    </template>

    <!-- Refund view -->
    <template v-else-if="activeView === ActiveView.REFUND">
        <PaymentRefund
            :currency="refundCurrency"
            :disabled="refundIsDisabled"
            :line-items="lineItems"
            :max-amount="refundableAmount"
            :mode="refundMode"
            :refresh-transaction="props.refreshTransaction"
            :refunded-amount="refundedAmount"
            :refunding-amounts="refundAmounts.in_progress ?? []"
            :set-active-view="setActiveView"
            :set-locked="setLocked"
            :transaction="props.transaction"
        />
    </template>

    <!-- Details view (default) -->
    <template v-else>
        <PaymentDetails
            :data-customization="props.dataCustomization"
            :extra-fields="props.extraFields"
            :full-refund-failed="fullRefundFailed"
            :full-refund-in-progress="fullRefundInProgress"
            :refund-amounts="refundAmounts"
            :refund-available="refundAvailable"
            :refund-currency="refundCurrency"
            :refund-disabled="refundIsDisabled"
            :refunded-amount="refundedAmount"
            :refunded-state="refundedState"
            :refund-locked="refundIsLocked"
            :set-active-view="setActiveView"
            :transaction="props.transaction"
            :transaction-navigator="props.transactionNavigator"
        />
    </template>
</template>

<style scoped>
.skeleton-row {
    height: 20px;
    background: #e0e0e0;
    border-radius: 4px;
    margin-bottom: 12px;
    animation: pulse 1.5s infinite;
}

@keyframes pulse {
    0%,
    100% {
        opacity: 1;
    }
    50% {
        opacity: 0.5;
    }
}
</style>

// src/components/external/Transactions/TransactionDetails/components/TransactionData/TransactionDataContent.tsx
import PaymentRefund from '../PaymentRefund/PaymentRefund';
import PaymentDetails from '../PaymentDetails/PaymentDetails';
import useRefundMetadata from '../../hooks/useRefundMetadata';
import useTransaction from '../../hooks/useTransaction';
import DataOverviewDetailsSkeleton from '../../../../../internal/DataOverviewDetails/DataOverviewDetailsSkeleton';
import { ActiveView, TransactionDetails, TransactionDetailsProps } from '../../types';
import { useLandedPageEvent } from '../../../../../../hooks/useAnalytics/useLandedPageEvent';
import { useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { useModalContext } from '../../../../../internal/Modal/Modal';
import { sharedTransactionDetailsEventProperties } from '../../constants';
import { EMPTY_ARRAY } from '../../../../../../utils';
import { ILineItem } from '../../../../../../types';
import './TransactionData.scss';

type UseTransactionResult = ReturnType<typeof useTransaction>;

export interface TransactionDataContentProps extends Omit<UseTransactionResult, 'error' | 'transaction'> {
    dataCustomization?: TransactionDetailsProps['dataCustomization'];
    extraFields: Record<string, any> | undefined;
    transaction: TransactionDetails;
}

export const TransactionDataContent = ({
    dataCustomization,
    extraFields,
    fetchingTransaction,
    refreshTransaction,
    transaction,
    transactionNavigator,
}: TransactionDataContentProps) => {
    const [activeView, setActiveView] = useState(ActiveView.DETAILS);
    const [locked, setLocked] = useState(false);

    const { withinModal } = useModalContext();

    const {
        fullRefundFailed,
        fullRefundInProgress,
        refundableAmount,
        refundAmounts,
        refundAvailable,
        refundCurrency,
        refundDisabled,
        refundedAmount,
        refundedState,
        refundMode,
        refundLocked,
    } = useRefundMetadata(transaction);

    const cachedRefundLocked = useRef(refundLocked);
    const refundIsDisabled = useMemo(() => refundDisabled || locked, [refundDisabled, locked]);
    const refundIsLocked = useMemo(() => refundLocked || locked, [refundLocked, locked]);

    const lineItems = useMemo<readonly ILineItem[]>(() => Object.freeze(transaction.lineItems ?? EMPTY_ARRAY), [transaction.lineItems]);

    useLandedPageEvent({
        ...sharedTransactionDetailsEventProperties,
        ...(withinModal && { fromPage: 'Transactions overview' }),
    });

    useEffect(() => {
        if ((cachedRefundLocked.current = refundLocked)) {
            // Refund has been locked while a refund is still in progress
            // Rely only on the refundLocked state
            // Reset the local locked state
            setLocked(false);
        }
    }, [refundLocked]);

    if (fetchingTransaction) {
        return <DataOverviewDetailsSkeleton skeletonRowNumber={5} />;
    }

    switch (activeView) {
        case ActiveView.REFUND:
            return (
                <PaymentRefund
                    currency={refundCurrency}
                    disabled={refundIsDisabled}
                    lineItems={lineItems}
                    maxAmount={refundableAmount}
                    mode={refundMode}
                    refreshTransaction={refreshTransaction}
                    refundedAmount={refundedAmount}
                    refundingAmounts={refundAmounts.in_progress ?? EMPTY_ARRAY}
                    setActiveView={setActiveView}
                    setLocked={setLocked}
                    transaction={transaction}
                />
            );

        default:
            return (
                <PaymentDetails
                    dataCustomization={dataCustomization}
                    extraFields={extraFields}
                    fullRefundFailed={fullRefundFailed}
                    fullRefundInProgress={fullRefundInProgress}
                    refundAmounts={refundAmounts}
                    refundAvailable={refundAvailable}
                    refundCurrency={refundCurrency}
                    refundDisabled={refundIsDisabled}
                    refundedAmount={refundedAmount}
                    refundedState={refundedState}
                    refundLocked={refundIsLocked}
                    setActiveView={setActiveView}
                    transaction={transaction}
                    transactionNavigator={transactionNavigator}
                />
            );
    }
};

export default TransactionDataContent;
