// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentDetails/PaymentDetailsActions.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/vue';
import { BentoButtonActions } from '@adyen/bento-vue3';
import { TX_DATA_ACTION_BAR, TX_DATA_CONTAINER, sharedTransactionDetailsEventProperties } from '@integration-components/transactions/domain';
import { ActiveView } from '@integration-components/transactions/domain';
import type { TransactionDetails } from '@integration-components/transactions/domain';
import type { useTransaction } from '../../composables/useTransaction';

type TransactionNavigatorState = ReturnType<typeof useTransaction>['transactionNavigator']['value'];

const props = defineProps<{
    extraFields: Record<string, any> | undefined;
    refundAvailable: boolean;
    refundDisabled: boolean;
    setActiveView: (view: ActiveView) => void;
    transaction: TransactionDetails;
    transactionNavigator: TransactionNavigatorState;
}>();

const { i18n } = useCoreContext();
const userEvents = useEventDispatcherContext();

const navigatorState = computed(() => props.transactionNavigator);

const transactionNavigation = computed<'backToRefund' | 'goToPayment' | undefined>(() => {
    const { currentTransaction, canNavigateBackward, canNavigateForward } = navigatorState.value;
    if (currentTransaction !== props.transaction.id) return undefined;
    if (canNavigateBackward) return 'backToRefund';
    if (canNavigateForward) return 'goToPayment';
    return undefined;
});

const primaryAction = computed(() => {
    if (!props.refundAvailable) return undefined;
    return {
        disabled: props.refundDisabled,
        event: () => {
            if (!props.refundDisabled) props.setActiveView(ActiveView.REFUND);
        },
        title: i18n.get('transactions.details.actions.refund'),
        variant: 'primary' as const,
    };
});

const secondaryAction = computed(() => {
    const nav = transactionNavigation.value;
    if (!nav) return undefined;
    const isBack = nav === 'backToRefund';
    const title = i18n.get(isBack ? 'transactions.details.actions.backToRefund' : 'transactions.details.actions.goToPayment');
    const navAction = isBack ? navigatorState.value.backward : navigatorState.value.forward;
    const eventLabel = isBack ? 'Return to refund' : 'Go to payment';
    return {
        disabled: false,
        event: () => {
            navAction();
            userEvents.addEvent?.('Clicked button', { ...sharedTransactionDetailsEventProperties, label: eventLabel });
        },
        title,
        variant: 'secondary' as const,
    };
});

const customActions = computed(() =>
    Object.values(props.extraFields ?? [])
        .filter(f => (f as any)?.type === 'button')
        .map((action: any) => ({
            title: action.value,
            variant: 'secondary' as const,
            event: action.config?.action,
        }))
);

const actions = computed(() => [primaryAction.value, secondaryAction.value, ...customActions.value].filter(Boolean) as any[]);
</script>

<template>
    <div v-if="actions.length > 0" :class="[TX_DATA_CONTAINER, TX_DATA_ACTION_BAR]">
        <BentoButtonActions :actions="actions" />
    </div>
</template>

// src/components/external/TransactionDetails/components/PaymentDetails/PaymentDetailsActions.tsx
import cx from 'classnames';
import { memo } from 'preact/compat';
import { useMemo } from 'preact/hooks';
import { ActiveView, TransactionDetails } from '../../types';
import { ButtonVariant } from '../../../../internal/Button/types';
import { ButtonActionObject, ButtonActionsLayoutBasic, ButtonActionsList } from '../../../../internal/Button/ButtonActions/types';
import { TX_DATA_ACTION_BAR, TX_DATA_CONTAINER, sharedTransactionDetailsEventProperties } from '../../constants';
import { TransactionDataContentProps } from '../TransactionData/TransactionDataContent';
import ButtonActions from '../../../../internal/Button/ButtonActions/ButtonActions';
import useEventDispatcherContext from '../../../../../core/Context/eventDispatcher/useEventDispatcherContext';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Icon from '../../../../internal/Icon';

export interface PaymentDetailsActionsProps {
    extraFields: Record<string, any> | undefined;
    refundAvailable: boolean;
    refundDisabled: boolean;
    setActiveView: (activeView: ActiveView) => void;
    transaction: TransactionDetails;
    transactionNavigator: TransactionDataContentProps['transactionNavigator'];
}

const PaymentDetailsActions = ({
    extraFields,
    refundAvailable,
    refundDisabled,
    setActiveView,
    transaction,
    transactionNavigator,
}: PaymentDetailsActionsProps) => {
    const userEvents = useEventDispatcherContext();
    const { currentTransaction: currentTransactionId, canNavigateBackward, canNavigateForward, backward, forward } = transactionNavigator;
    const { i18n } = useCoreContext();

    const actionButtons = useMemo(
        () => ({
            backToRefund: { title: i18n.get('transactions.details.actions.backToRefund'), eventLabel: 'Return to refund' } as const,
            goToPayment: { title: i18n.get('transactions.details.actions.goToPayment'), eventLabel: 'Go to payment' } as const,
            refund: { title: i18n.get('transactions.details.actions.refund') } as const,
        }),
        [i18n]
    );

    const transactionNavigation = useMemo<'backToRefund' | 'goToPayment' | undefined>(() => {
        if (currentTransactionId !== transaction.id) return;
        if (canNavigateBackward) return 'backToRefund' satisfies keyof typeof actionButtons;
        if (canNavigateForward) return 'goToPayment' satisfies keyof typeof actionButtons;
    }, [canNavigateBackward, canNavigateForward, currentTransactionId, transaction.id]);

    const primaryAction = useMemo<Readonly<ButtonActionObject> | undefined>(() => {
        if (refundAvailable) {
            return {
                disabled: refundDisabled,
                event: () => {
                    if (!refundDisabled) setActiveView(ActiveView.REFUND);
                },
                title: actionButtons.refund.title,
                variant: ButtonVariant.PRIMARY,
            } as const;
        }
    }, [actionButtons, refundAvailable, refundDisabled, setActiveView]);

    const secondaryAction = useMemo<Readonly<ButtonActionObject> | undefined>(() => {
        if (transactionNavigation) {
            const actionButton = actionButtons[transactionNavigation];
            const isBackNavigation = transactionNavigation === 'backToRefund';
            const transactionNavigationAction = isBackNavigation ? backward : forward;
            return {
                disabled: false,
                event: () => {
                    try {
                        transactionNavigationAction();
                    } finally {
                        userEvents.addEvent?.('Clicked button', {
                            ...sharedTransactionDetailsEventProperties,
                            label: actionButton.eventLabel,
                        });
                    }
                },
                renderTitle: (title: string) => (
                    <>
                        <Icon name="angle-right" style={{ transform: `scaleX(${isBackNavigation ? -1 : 1})` }} />
                        <span>{title}</span>
                    </>
                ),
                title: actionButton.title,
                variant: ButtonVariant.SECONDARY,
            } as const;
        }
    }, [actionButtons, backward, forward, transactionNavigation, userEvents]);

    const customActions = useMemo<ButtonActionsList>(
        () =>
            Object.values(extraFields || [])
                .filter(field => field?.type === 'button')
                .map(action => ({
                    title: action.value,
                    variant: ButtonVariant.SECONDARY,
                    event: action.config?.action,
                    classNames: action.config?.className ? [action.config.className] : [],
                })),
        [extraFields]
    );

    const actions = useMemo(
        () => [primaryAction, secondaryAction, ...customActions].filter(Boolean) as ButtonActionsList,
        [primaryAction, secondaryAction, customActions]
    );

    return actions.length > 0 ? (
        <div className={cx(TX_DATA_CONTAINER, TX_DATA_ACTION_BAR)}>
            <ButtonActions actions={actions} layout={ButtonActionsLayoutBasic.BUTTONS_END} />
        </div>
    ) : null;
};

export default memo(PaymentDetailsActions);
