// adyen-platform-experience-web-vue/src/components/TransactionDetails/PaymentDetails/PaymentDetailsSummary.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoStructuredList, BentoStructuredListItem, BentoTypography } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import { TX_DATA_LIST } from '../constants';
import type { TransactionDetails, TransactionAmount } from '../types';

const props = defineProps<{
    transaction: TransactionDetails;
}>();

const { i18n } = useCoreContext();

interface SummaryItem {
    id?: string;
    label: string;
    value: string | null;
    strongest?: boolean;
    tooltip?: string;
}

function getFormattedAmount(amount?: TransactionAmount): string | null {
    if (!amount) return null;
    const { value, currency } = amount;
    return `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
}

function getAdjustmentTypeLabel(type: string): string {
    const key = `transactions.details.summary.adjustments.types.${type}`;
    return i18n.has(key) ? i18n.get(key) : type;
}

function getAdjustmentTypeInfo(type: string): string | undefined {
    const key = `transactions.details.summary.adjustmentTypes.${type}.info`;
    return i18n.has(key) ? i18n.get(key) : undefined;
}

const summaryItems = computed<SummaryItem[]>(() => {
    const { additions, deductions, amountBeforeDeductions, netAmount, originalAmount } = props.transaction;

    const items: (SummaryItem | null)[] = [
        // Original amount
        originalAmount && ((additions && additions.length > 0) || originalAmount.value !== amountBeforeDeductions.value)
            ? {
                  id: 'originalAmount',
                  label: i18n.get('transactions.details.summary.fields.originalAmount'),
                  value: getFormattedAmount(originalAmount),
              }
            : null,

        // Additions
        ...(additions?.map(({ type, ...amount }) => ({
            label: getAdjustmentTypeLabel(type),
            value: getFormattedAmount(amount),
        })) ?? []),

        // Gross amount
        { id: 'grossAmount', label: i18n.get('transactions.details.summary.fields.grossAmount'), value: getFormattedAmount(amountBeforeDeductions) },

        // Deductions
        ...(deductions?.map(({ type, ...amount }) => ({
            label: getAdjustmentTypeLabel(type),
            value: getFormattedAmount(amount),
            tooltip: getAdjustmentTypeInfo(type),
        })) ?? []),

        // Net amount
        { id: 'netAmount', label: i18n.get('transactions.details.summary.fields.netAmount'), value: getFormattedAmount(netAmount), strongest: true },
    ];

    return items.filter((item): item is SummaryItem => item !== null);
});
</script>

<template>
    <div :class="TX_DATA_LIST">
        <bento-structured-list>
            <bento-structured-list-item v-for="(item, index) in summaryItems" :key="item.id || index" :label="item.label" :label-info="item.tooltip">
                <bento-typography variant="body" :weight="item.strongest ? 'stronger' : undefined">
                    {{ item.value }}
                </bento-typography>
            </bento-structured-list-item>
        </bento-structured-list>
    </div>
</template>

// src/components/external/TransactionDetails/components/PaymentDetails/PaymentDetailsSummary.tsx
import { memo } from 'preact/compat';
import { IAmount } from '../../../../../types';
import { isNullish } from '../../../../../utils';
import { useCallback, useMemo } from 'preact/hooks';
import { TransactionDetails } from '../../types';
import { TranslationKey } from '../../../../../translations';
import { TX_DATA_LABEL, TX_DATA_LIST } from '../../constants';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { getTransactionAmountAdjustmentType } from '../../../../utils/translation/getters';
import { StructuredListProps } from '../../../../internal/StructuredList/types';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Typography from '../../../../internal/Typography/Typography';
import StructuredList from '../../../../internal/StructuredList';
import cx from 'classnames';

const paymentAmountKeys = {
    grossAmount: 'transactions.details.summary.fields.grossAmount',
    netAmount: 'transactions.details.summary.fields.netAmount',
    originalAmount: 'transactions.details.summary.fields.originalAmount',
} satisfies Record<string, TranslationKey>;

const SKIP_ITEM: StructuredListProps['items'][number] = null!;

export interface PaymentDetailsSummaryProps {
    transaction: TransactionDetails;
}

const PaymentDetailsSummary = ({ transaction }: PaymentDetailsSummaryProps) => {
    const { i18n } = useCoreContext();

    const summaryListItems = useMemo<StructuredListProps['items']>(() => {
        const { additions, deductions, amountBeforeDeductions, netAmount, originalAmount } = transaction;

        const getFormattedAmount = (amount?: IAmount) => {
            if (isNullish(amount)) return null;
            const { value, currency } = amount;
            return i18n.amount(value, currency);
        };

        const listItems: StructuredListProps['items'] = [
            // original amount
            originalAmount && ((additions && additions.length > 0) || originalAmount.value !== amountBeforeDeductions.value)
                ? {
                      id: 'originalAmount',
                      key: paymentAmountKeys.originalAmount,
                      value: getFormattedAmount(originalAmount),
                  }
                : SKIP_ITEM,

            // additions
            ...(additions?.map(({ type, ...amount }) => ({
                key: getTransactionAmountAdjustmentType(i18n, type) as TranslationKey,
                value: getFormattedAmount(amount),
            })) ?? []),

            // amountBeforeDeductions
            {
                id: 'grossAmount',
                key: paymentAmountKeys.grossAmount,
                value: getFormattedAmount(amountBeforeDeductions),
            },

            // deductions
            ...(deductions?.map(({ type, ...amount }) => ({
                key: getTransactionAmountAdjustmentType(i18n, type) as TranslationKey,
                value: getFormattedAmount(amount),
            })) ?? []),

            // netAmount
            {
                id: 'netAmount',
                key: paymentAmountKeys.netAmount,
                value: getFormattedAmount(netAmount),
            },
        ];

        return listItems.filter(Boolean);
    }, [i18n, transaction]);

    const renderListPropertyLabel = useCallback<NonNullable<StructuredListProps['renderLabel']>>(
        label => <div className={cx(TX_DATA_LABEL)}>{label}</div>,
        []
    );

    const renderListPropertyValue = useCallback<NonNullable<StructuredListProps['renderValue']>>((val, key) => {
        const stronger = key === paymentAmountKeys.netAmount;
        const strongest = key === paymentAmountKeys.grossAmount;
        const variant = stronger ? TypographyVariant.SUBTITLE : TypographyVariant.BODY;
        return (
            <Typography el={TypographyElement.DIV} variant={variant} stronger={stronger} strongest={strongest}>
                {val}
            </Typography>
        );
    }, []);

    return (
        <StructuredList
            classNames={TX_DATA_LIST}
            items={summaryListItems}
            layout="5-7"
            renderLabel={renderListPropertyLabel}
            renderValue={renderListPropertyValue}
        />
    );
};

export default memo(PaymentDetailsSummary);
