// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentDetails/PaymentRefundAlerts.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoAlert } from '@adyen/bento-vue3';
import { TX_REFUND_STATUSES_CONTAINER } from '@integration-components/transactions/domain';
import { RefundedState, REFUND_STATUSES } from '@integration-components/transactions/domain';

const props = defineProps<{
    fullRefundFailed: boolean;
    fullRefundInProgress: boolean;
    refundAmounts: Readonly<Record<(typeof REFUND_STATUSES)[number], readonly number[] | undefined>>;
    refundCurrency: string;
    refundedAmount: number;
    refundedState: RefundedState;
    refundLocked: boolean;
}>();

const { i18n } = useCoreContext();

const listFormatter = computed(() => new Intl.ListFormat(i18n.locale, { type: 'conjunction' }));

function formatAmountsList(amounts: readonly number[]): string {
    return listFormatter.value.format(amounts.map(a => i18n.amount(a, props.refundCurrency)));
}

interface AlertItem {
    type: 'highlight' | 'warning';
    description: string;
}

const alerts = computed<AlertItem[]>(() => {
    const list: AlertItem[] = [];

    if (props.refundedState === RefundedState.FULL) {
        list.push({ type: 'highlight', description: i18n.get('transactions.details.refund.alerts.refundedFull') });
    } else {
        if (props.refundedAmount > 0) {
            const values = { amount: formatAmountsList([props.refundedAmount]) };
            list.push({ type: 'highlight', description: i18n.get('transactions.details.refund.alerts.refundedAmount', { values }) });
        }

        if (props.refundLocked) {
            list.push({ type: 'highlight', description: i18n.get('transactions.details.refund.alerts.inProgressBlocked') });
        } else {
            const inProgress = props.refundAmounts.in_progress ?? [];
            if (inProgress.length > 0) {
                if (props.fullRefundInProgress) {
                    list.push({ type: 'highlight', description: i18n.get('transactions.details.refund.alerts.inProgress') });
                } else {
                    const values = { amount: formatAmountsList(inProgress) };
                    list.push({ type: 'highlight', description: i18n.get('transactions.details.refund.alerts.inProgressAmount', { values }) });
                }
            }

            const failed = props.refundAmounts.failed ?? [];
            if (failed.length > 0) {
                if (props.fullRefundFailed) {
                    list.push({ type: 'warning', description: i18n.get('transactions.details.refund.alerts.notPossible') });
                } else {
                    const values = { amount: formatAmountsList(failed) };
                    list.push({ type: 'warning', description: i18n.get('transactions.details.refund.alerts.notPossibleAmount', { values }) });
                }
            }
        }
    }

    return list;
});
</script>

<template>
    <div v-if="alerts.length > 0" :class="TX_REFUND_STATUSES_CONTAINER">
        <BentoAlert v-for="(alert, idx) in alerts" :key="idx" :type="alert.type" variant="tip">
            <template #description>{{ alert.description }}</template>
        </BentoAlert>
    </div>
</template>

// src/components/external/TransactionDetails/components/PaymentDetails/PaymentRefundAlerts.tsx
import { memo } from 'preact/compat';
import { ComponentChild } from 'preact';
import { RefundedState } from '../../types';
import { useCallback, useEffect, useMemo, useRef } from 'preact/hooks';
import { REFUND_STATUSES, TX_REFUND_STATUSES_CONTAINER } from '../../constants';
import { AlertProps, AlertTypeOption, AlertVariantOption } from '../../../../internal/Alert/types';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Alert from '../../../../internal/Alert/Alert';

const baseAlertProps = {
    type: AlertTypeOption.HIGHLIGHT,
    variant: AlertVariantOption.TIP,
} as const;

export interface PaymentRefundAlertsProps {
    fullRefundFailed: boolean;
    fullRefundInProgress: boolean;
    refundAmounts: Readonly<Record<(typeof REFUND_STATUSES)[number], readonly number[] | undefined>>;
    refundCurrency: string;
    refundedAmount: number;
    refundedState: RefundedState;
    refundLocked: boolean;
}

const PaymentRefundAlerts = memo(
    ({
        fullRefundFailed,
        fullRefundInProgress,
        refundAmounts,
        refundCurrency,
        refundedAmount,
        refundedState,
        refundLocked,
    }: PaymentRefundAlertsProps) => {
        const { i18n } = useCoreContext();

        const getFormattedAmountsList = useMemo(() => {
            const listFormatter = new Intl.ListFormat(i18n.locale, { type: 'conjunction' });
            return (amounts: readonly number[]) => listFormatter.format(amounts.map(amount => i18n.amount(amount, refundCurrency)));
        }, [i18n, refundCurrency]);

        const nextAlert = useCallback(<T extends AlertProps>({ description, ...alertProps }: Partial<T>) => {
            alerts.current.push(<Alert {...baseAlertProps} {...alertProps} description={description} />);
        }, []);

        const alerts = useRef<ComponentChild[]>([]);

        if (refundedState === RefundedState.FULL) {
            nextAlert({ description: i18n.get('transactions.details.refund.alerts.refundedFull') });
        } else {
            if (refundedAmount > 0) {
                const values = { amount: getFormattedAmountsList([refundedAmount]) };
                nextAlert({ description: i18n.get('transactions.details.refund.alerts.refundedAmount', { values }) });
            }

            if (refundLocked) {
                nextAlert({ description: i18n.get('transactions.details.refund.alerts.inProgressBlocked') });
            } else {
                if (refundAmounts.in_progress && refundAmounts.in_progress.length > 0) {
                    if (fullRefundInProgress) {
                        nextAlert({ description: i18n.get('transactions.details.refund.alerts.inProgress') });
                    } else {
                        const values = { amount: getFormattedAmountsList(refundAmounts.in_progress) };
                        nextAlert({ description: i18n.get('transactions.details.refund.alerts.inProgressAmount', { values }) });
                    }
                }

                if (refundAmounts.failed && refundAmounts.failed.length > 0) {
                    const type = AlertTypeOption.WARNING;
                    if (fullRefundFailed) {
                        nextAlert({ type, description: i18n.get('transactions.details.refund.alerts.notPossible') });
                    } else {
                        const values = { amount: getFormattedAmountsList(refundAmounts.failed) };
                        nextAlert({ type, description: i18n.get('transactions.details.refund.alerts.notPossibleAmount', { values }) });
                    }
                }
            }
        }

        useEffect(() => {
            alerts.current = [];
        });

        return alerts.current.length > 0 ? <div className={TX_REFUND_STATUSES_CONTAINER}>{alerts.current}</div> : null;
    }
);

export default PaymentRefundAlerts;
