// adyen-platform-experience-web-vue/src/components/TransactionDetails/PaymentDetails/PaymentDetailsTimeline.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoTimeline, BentoTimelineItem, BentoStructuredList, BentoStructuredListItem, BentoTypography, BentoDateFormat } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import { TX_TIMELINE_LABEL, TX_TIMELINE_VALUE } from '../constants';
import type { TransactionDetails, TransactionEvent } from '../types';

const props = defineProps<{
    transaction: TransactionDetails;
}>();

const { i18n } = useCoreContext();

const events = computed(() => props.transaction.events ?? []);

function makeTimestamp(createdAt: string): { date: Date; format: BentoDateFormat } {
    const date = new Date(createdAt);
    return { date, format: 'LLL dd, yyyy, H:mm' as BentoDateFormat };
}

function getEventType(event: TransactionEvent): string {
    const typeKey = `transactions.details.timeline.types.${event.type}`;
    const formattedType = i18n.has(typeKey) ? i18n.get(typeKey) : event.type;

    // Hardcoded type mapping matching the Preact implementation
    if (event.status.toLowerCase().includes('refund')) return 'Refund';
    if (event.status.toLowerCase().includes('auth')) return 'Capture';
    return formattedType;
}

function getEventStatus(event: TransactionEvent): string {
    const statusKey = `transactions.details.timeline.statuses.${event.status}`;
    return i18n.has(statusKey) ? i18n.get(statusKey) : event.status;
}

function formatEventAmount(event: TransactionEvent): string {
    const { value, currency } = event.amount;
    return `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
}
</script>

<template>
    <template v-if="events.length > 0">
        <bento-timeline>
            <bento-timeline-item
                v-for="(event, index) in events"
                :key="index"
                :title="getEventType(event)"
                :timestamp="makeTimestamp(event.createdAt)"
            >
                <bento-structured-list>
                    <bento-structured-list-item :label="i18n.get('transactions.details.timeline.fields.amount')">
                        <template #label>
                            <bento-typography variant="caption" :class="TX_TIMELINE_LABEL">
                                {{ i18n.get('transactions.details.timeline.fields.amount') }}
                            </bento-typography>
                        </template>
                        <bento-typography variant="caption" :class="TX_TIMELINE_VALUE">
                            {{ formatEventAmount(event) }}
                        </bento-typography>
                    </bento-structured-list-item>
                    <bento-structured-list-item :label="i18n.get('transactions.details.timeline.fields.status')">
                        <template #label>
                            <bento-typography variant="caption" :class="TX_TIMELINE_LABEL">
                                {{ i18n.get('transactions.details.timeline.fields.status') }}
                            </bento-typography>
                        </template>
                        <bento-typography variant="caption" :class="TX_TIMELINE_VALUE">
                            {{ getEventStatus(event) }}
                        </bento-typography>
                    </bento-structured-list-item>
                </bento-structured-list>
            </bento-timeline-item>
        </bento-timeline>
    </template>
</template>

// src/components/external/TransactionDetails/components/PaymentDetails/PaymentDetailsTimeline.tsx
import { memo } from 'preact/compat';
import { useMemo } from 'preact/hooks';
import { uniqueId } from '../../../../../utils';
import { TransactionDetails } from '../../types';
import { TX_TIMELINE_LABEL, TX_TIMELINE_VALUE } from '../../constants';
import { getTransactionTimelineTxStatus, getTransactionTimelineTxType } from '../../../../utils/translation/getters';
import { StructuredListItem, StructuredListProps } from '../../../../internal/StructuredList/types';
import { TimelineDateFormat, TimelineTimestamp } from '../../../../internal/Timeline/types';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { TimelineItem } from '../../../../internal/Timeline/components/TimelineItem';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Typography from '../../../../internal/Typography/Typography';
import StructuredList from '../../../../internal/StructuredList';
import Timeline from '../../../../internal/Timeline/Timeline';

export interface PaymentDetailsTimelineProps {
    transaction: TransactionDetails;
}

interface PaymentDetailsTimelineItemProps {
    event: NonNullable<TransactionDetails['events']>[number];
    defaultTimestamp: TimelineTimestamp;
}

const PaymentDetailsTimeline = ({ transaction }: PaymentDetailsTimelineProps) => {
    const createdAt = transaction.createdAt;
    const events = transaction.events;
    const timezone = transaction.balanceAccount?.timeZone;

    const defaultTimestamp = useMemo<TimelineTimestamp>(
        () => ({
            format: TimelineDateFormat.FULL_DATE_EXACT_TIME_WITHOUT_SECONDS,
            date: new Date(createdAt),
            timezone,
        }),
        [createdAt, timezone]
    );

    const eventKeys = useMemo(() => {
        const map = new WeakMap<NonNullable<typeof events>[number], string>();
        events?.forEach(event => map.set(event, uniqueId()));
        return map;
    }, [events]);

    return events ? (
        <Timeline showMore={{ limit: 2, placement: 'before-last' }}>
            {events.map(event => (
                <PaymentDetailsTimeline.Item key={eventKeys.get(event)} event={event} defaultTimestamp={defaultTimestamp} />
            ))}
        </Timeline>
    ) : null;
};

const renderTimelineListPropertyLabel: NonNullable<StructuredListProps['renderLabel']> = label => (
    <Typography el={TypographyElement.DIV} variant={TypographyVariant.CAPTION} className={TX_TIMELINE_LABEL}>
        {label}
    </Typography>
);

const renderTimelineListPropertyValue: NonNullable<StructuredListProps['renderValue']> = label => (
    <Typography el={TypographyElement.DIV} variant={TypographyVariant.CAPTION} className={TX_TIMELINE_VALUE}>
        {label}
    </Typography>
);

PaymentDetailsTimeline.Item = memo(({ defaultTimestamp, event }: PaymentDetailsTimelineItemProps) => {
    const { amount, createdAt, status, type } = event;
    const { i18n } = useCoreContext();

    const timestamp = useMemo<TimelineTimestamp>(() => ({ ...defaultTimestamp, date: new Date(createdAt) }), [defaultTimestamp, createdAt]);
    const formattedType = useMemo(() => getTransactionTimelineTxType(i18n, type)!, [i18n, type]);
    const items = useMemo<StructuredListItem[]>(() => {
        const { currency, value } = amount;
        const formattedAmount = `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
        const formattedStatus = getTransactionTimelineTxStatus(i18n, status)!;
        return [
            { key: 'transactions.details.timeline.fields.amount', value: formattedAmount },
            { key: 'transactions.details.timeline.fields.status', value: formattedStatus },
        ] as const;
    }, [i18n, amount, status]);

    // [TODO] - Remove this harcoded type once the team reviews all statuses and types and have less number of different strings, and more friendly ones.
    const fixedType = status.toLowerCase().includes('refund') ? 'Refund' : status.toLowerCase().includes('auth') ? 'Capture' : formattedType;

    return (
        <TimelineItem title={fixedType} timestamp={timestamp}>
            <StructuredList
                align="start"
                layout="3-9"
                items={items}
                renderLabel={renderTimelineListPropertyLabel}
                renderValue={renderTimelineListPropertyValue}
            />
        </TimelineItem>
    );
});

export default memo(PaymentDetailsTimeline);
