// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentRefund/PaymentRefundReason.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoDropdown, BentoTypography } from '@adyen/bento-vue3';
import {
    getTransactionRefundReason,
    REFUND_REASONS,
    TX_DATA_CONTAINER,
    TX_DATA_INPUT_CONTAINER,
    TX_DATA_INPUT_CONTAINER_SHORT,
    TX_DATA_INPUT_HEAD,
} from '@integration-components/transactions/domain';
import type { RefundReason } from '@integration-components/transactions/domain';

const props = defineProps<{
    disabled: boolean;
    reason: RefundReason;
}>();

const emit = defineEmits<{
    change: [reason: RefundReason];
}>();

const { i18n } = useCoreContext();

const refundReasons = computed(() =>
    REFUND_REASONS.map(r => ({
        label: getTransactionRefundReason(i18n, r) as string,
        value: r,
    }))
);
</script>

<template>
    <div :class="TX_DATA_CONTAINER">
        <div :class="TX_DATA_INPUT_HEAD">
            <BentoTypography variant="body" stronger>
                {{ i18n.get('transactions.details.refund.inputs.reason.label') }}
            </BentoTypography>
        </div>
        <div :class="[TX_DATA_INPUT_CONTAINER, TX_DATA_INPUT_CONTAINER_SHORT]">
            <BentoDropdown
                :placeholder="i18n.get('transactions.details.refund.inputs.reason.label')"
                :items="refundReasons"
                :value="props.reason"
                :disabled="props.disabled"
                @change="(v: string) => emit('change', v as RefundReason)"
            />
        </div>
    </div>
</template>

// src/components/external/TransactionDetails/components/PaymentRefund/PaymentRefundReason.tsx
import { REFUND_REASONS, TX_DATA_CONTAINER, TX_DATA_INPUT_CONTAINER, TX_DATA_INPUT_CONTAINER_SHORT, TX_DATA_INPUT_HEAD } from '../../constants';
import { RefundReason } from '../../types';
import { useCallback, useMemo } from 'preact/hooks';
import { getTransactionRefundReason } from '../../../../utils/translation/getters';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Typography from '../../../../internal/Typography/Typography';
import Select from '../../../../internal/FormFields/Select';
import useUniqueId from '../../../../../hooks/useUniqueId';

export interface PaymentRefundReasonProps {
    disabled: boolean;
    onChange: (reason: RefundReason) => void;
    reason: RefundReason;
}

const PaymentRefundReason = ({ disabled, onChange, reason }: PaymentRefundReasonProps) => {
    const { i18n } = useCoreContext();
    const selectLabelId = useUniqueId();
    const selectLabel = useMemo(() => i18n.get('transactions.details.refund.inputs.reason.label'), [i18n]);

    const refundReasons = useMemo(
        () =>
            REFUND_REASONS.map(reason => ({
                name: getTransactionRefundReason(i18n, reason) as string,
                id: reason,
            })),
        [i18n]
    );

    const onReasonChange = useCallback(
        (evt: { target?: { value: RefundReason } }) => {
            const reason = evt.target?.value;
            reason && onChange(reason);
        },
        [onChange]
    );

    return (
        <div className={TX_DATA_CONTAINER}>
            <div id={selectLabelId} className={TX_DATA_INPUT_HEAD}>
                <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                    {selectLabel}
                </Typography>
            </div>

            <div className={`${TX_DATA_INPUT_CONTAINER} ${TX_DATA_INPUT_CONTAINER_SHORT}`}>
                <Select
                    aria-labelledby={selectLabelId}
                    filterable={false}
                    multiSelect={false}
                    readonly={disabled}
                    items={refundReasons}
                    onChange={onReasonChange}
                    selected={reason}
                />
            </div>
        </div>
    );
};

export default PaymentRefundReason;
