// packages/domains/capital/preact/src/CapitalOffer/components/CapitalOffer/CapitalOffer.tsx
import { FunctionalComponent } from 'preact';
import { useCallback, useMemo, useState } from 'preact/hooks';
import { ExternalUIComponentProps, IGrantOfferResponseDTO } from '@integration-components/types';
import { useConfigContext } from '@integration-components/core/preact';
import { useFetch } from '@integration-components/hooks-preact';
import { useLandedPageEvent } from '@integration-components/hooks-preact/useEventDispatcher/useLandedPageEvent';
import { EMPTY_OBJECT } from '@integration-components/utils';
import { CapitalOfferProps } from '../../types';
import { CapitalErrorMessageDisplay } from '../utils/CapitalErrorMessageDisplay';
import { CAPITAL_OFFER_CLASS_NAMES, sharedCapitalOfferAnalyticsEventProperties } from './constants';
import { CapitalHeader } from '../../../internal/CapitalHeader';
import { CapitalOfferSelection } from '../CapitalOfferSelection/CapitalOfferSelection';
import { CapitalOfferSummary } from '../CapitalOfferSummary/CapitalOfferSummary';
import './CapitalOffer.scss';
import { getEnhancedCapitalState } from '../../../utils/capital/getCapitalState';
import { useSupportedRegions } from '../../../utils/capital/useSupportedRegions';

type CapitalOfferState = 'OfferSelection' | 'OfferSummary';

const sharedAnalyticsEventProperties = {
    ...sharedCapitalOfferAnalyticsEventProperties,
    subCategory: 'Capital offer',
} as const;

export const CapitalOffer: FunctionalComponent<ExternalUIComponentProps<CapitalOfferProps>> = ({
    externalCapitalState,
    hideTitle,
    onContactSupport,
    onFundsRequest,
    onOfferDismiss,
    onOfferSelect,
}) => {
    const [selectedAmount, setSelectedAmount] = useState<number | undefined>(undefined);
    const [selectedTerm, setSelectedTerm] = useState<number | undefined>(undefined);
    const [selectedOffer, setSelectedOffer] = useState<IGrantOfferResponseDTO>();

    const { getCapitalState } = useConfigContext().endpoints;
    const supportedRegions = useSupportedRegions();

    const { data: internalCapitalState, error: capitalStateError } = useFetch({
        fetchOptions: { enabled: !externalCapitalState && !!getCapitalState },
        queryFn: useCallback(async () => {
            return getCapitalState?.(EMPTY_OBJECT, { query: EMPTY_OBJECT });
        }, [getCapitalState]),
    });

    const state = useMemo(
        () => externalCapitalState || (internalCapitalState && getEnhancedCapitalState(internalCapitalState, supportedRegions)),
        [externalCapitalState, internalCapitalState, supportedRegions]
    );

    const onOfferSelectHandler = useCallback(
        (data: IGrantOfferResponseDTO) => {
            if (onOfferSelect) {
                onOfferSelect(data);
            } else {
                setSelectedOffer(data);
            }
        },
        [onOfferSelect]
    );

    const capitalOfferState = useMemo<CapitalOfferState>(() => {
        return selectedOffer ? 'OfferSummary' : 'OfferSelection';
    }, [selectedOffer]);

    useLandedPageEvent({ ...sharedAnalyticsEventProperties, label: 'Capital offer' });

    if (state && (!state.isRegionSupported || !state.dynamicOffer)) {
        return (
            <div className={CAPITAL_OFFER_CLASS_NAMES.errorContainer}>
                <CapitalHeader hideTitle={hideTitle} region={state.region} titleKey={'capital.common.title'} />
                <CapitalErrorMessageDisplay unsupportedRegion={!state.isRegionSupported} emptyGrantOffer={!state.dynamicOffer} />
            </div>
        );
    }

    return (
        <div className={CAPITAL_OFFER_CLASS_NAMES.base}>
            <CapitalHeader
                hasDivider
                hideTitle={hideTitle}
                region={state?.region}
                titleKey={capitalOfferState === 'OfferSummary' ? 'capital.offer.summary.title' : 'capital.offer.selection.title'}
            />
            {capitalOfferState === 'OfferSelection' && (
                <CapitalOfferSelection
                    selectedAmount={selectedAmount}
                    onSelectedAmountChange={setSelectedAmount}
                    selectedTerm={selectedTerm}
                    onSelectedTermChange={setSelectedTerm}
                    capitalState={state}
                    capitalStateError={capitalStateError}
                    onOfferDismiss={onOfferDismiss}
                    onOfferSelect={onOfferSelectHandler}
                    onContactSupport={onContactSupport}
                />
            )}
            {capitalOfferState === 'OfferSummary' && (
                <CapitalOfferSummary
                    grantOffer={selectedOffer!}
                    capitalState={state}
                    onBack={() => setSelectedOffer(undefined)}
                    onFundsRequest={onFundsRequest}
                    onContactSupport={onContactSupport}
                />
            )}
        </div>
    );
};

// packages/domains/capital/vue/src/CapitalOffer/components/CapitalOffer.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { IGrantOfferResponseDTO } from '@integration-components/types';
import { getIsEarlyRenewal, sharedCapitalOfferAnalyticsEventProperties } from '@integration-components/capital/domain';
import { useLandedPageEvent } from '@integration-components/composables-vue';
import OfferSelection from './OfferSelection.vue';
import OfferSummary from './OfferSummary.vue';
import type { CapitalOfferComponentProps } from '../types';
import { useCapitalState } from '../composables/useCapitalState';
import CapitalHeader from '../../shared/CapitalHeader/CapitalHeader.vue';
import CapitalErrorMessageDisplay from '../../shared/CapitalErrorMessageDisplay.vue';

const props = defineProps<CapitalOfferComponentProps>();

const selectedAmount = ref<number>();
const selectedTerm = ref<number>();
const selectedOffer = ref<IGrantOfferResponseDTO>();
const externalCapitalState = computed(() => props.externalCapitalState);
const { capitalState: backendCapitalState, error: capitalStateError } = useCapitalState(() => !externalCapitalState.value);
const capitalState = computed(() => externalCapitalState.value ?? backendCapitalState.value);

useLandedPageEvent(
    () => ({
        ...sharedCapitalOfferAnalyticsEventProperties,
        subCategory: 'Capital offer',
        label: 'Capital offer',
        isEarlyRenewal: capitalState.value ? getIsEarlyRenewal(capitalState.value) : false,
    }),
    () => !!capitalState.value
);

const handleOfferSelect = (offer: IGrantOfferResponseDTO) => {
    if (props.onOfferSelect) {
        props.onOfferSelect(offer);
        return;
    }

    selectedOffer.value = offer;
};

const handleSummaryBack = () => {
    selectedOffer.value = undefined;
};
</script>

<template>
    <CapitalHeader
        :hide-title="props.hideTitle"
        :region="capitalState?.region"
        :title-key="selectedOffer ? 'capital.offer.summary.title' : 'capital.offer.selection.title'"
    />
    <CapitalErrorMessageDisplay
        v-if="capitalStateError"
        :error="capitalStateError"
        :on-back="props.onOfferDismiss"
        :on-contact-support="props.onContactSupport"
    />
    <template v-else-if="capitalState">
        <CapitalErrorMessageDisplay
            v-if="!capitalState.isRegionSupported || !capitalState.dynamicOffer"
            :empty-grant-offer="!capitalState.dynamicOffer"
            :unsupported-region="!capitalState.isRegionSupported"
        />
        <OfferSelection
            v-else-if="!selectedOffer"
            :capital-state="capitalState"
            :selected-amount="selectedAmount"
            :selected-term="selectedTerm"
            :on-selected-amount-change="value => (selectedAmount = value)"
            :on-selected-term-change="term => (selectedTerm = term)"
            :on-offer-select="handleOfferSelect"
            :on-contact-support="props.onContactSupport"
            :on-offer-dismiss="props.onOfferDismiss"
        />
        <OfferSummary
            v-else
            :capital-state="capitalState"
            :grant-offer="selectedOffer"
            :on-back="handleSummaryBack"
            :on-funds-request="props.onFundsRequest"
            :on-contact-support="props.onContactSupport"
        />
    </template>
</template>
