// packages/domains/capital/preact/src/CapitalOverview/components/GrantDetails/GrantDetails.tsx
import { FunctionalComponent } from 'preact';
import { useCallback, useMemo } from 'preact/hooks';
import { useCoreContext } from '@integration-components/core/preact';
import { CAPITAL_REPAYMENT_FREQUENCY, calculatePercentageFromBasisPoints, getEnhancedGrant } from '@integration-components/capital/domain';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import { GRANT_DETAILS_CLASS_NAMES } from './constants';
import { GrantDetailsProps } from './types';
import './GrantDetails.scss';
import StructuredList from '@integration-components/ui-components-preact/StructuredList';
import { StructuredListItem } from '@integration-components/ui-components-preact/StructuredList/types';
import { Translation } from '@integration-components/ui-components-preact/Translation';
import { Tooltip } from '@integration-components/ui-components-preact/Tooltip/Tooltip';

export const GrantDetails: FunctionalComponent<GrantDetailsProps> = ({ grant }) => {
    const { i18n } = useCoreContext();
    const formatAmount = useCallback((amount: { value: number; currency: string }) => i18n.amount(amount.value, amount.currency), [i18n]);
    const structuredListItems = useMemo<StructuredListItem[]>(() => {
        const enhancedGrant = getEnhancedGrant(grant);
        const items: StructuredListItem[] = [
            {
                key: 'capital.common.fields.remainingAmount',
                value: i18n.amount(enhancedGrant.remainingGrantAmount.value, enhancedGrant.remainingGrantAmount.currency),
            },
            { key: 'capital.common.fields.remainingFees', value: formatAmount(enhancedGrant.remainingFeesAmount) },
            { key: 'capital.common.fields.repaidAmount', value: formatAmount(enhancedGrant.repaidGrantAmount) },
            { key: 'capital.common.fields.repaidFees', value: formatAmount(enhancedGrant.repaidFeesAmount) },
            {
                key: 'capital.common.fields.dailyRepaymentRate',
                value: `${i18n.get('capital.common.values.percentage', {
                    values: { percentage: calculatePercentageFromBasisPoints(enhancedGrant.repaymentRate) },
                })}`,
            },
            {
                key: 'capital.common.fields.expectedRepaymentPeriod',
                value: i18n.get('capital.common.values.daysWithDaysLeft', {
                    values: {
                        days: enhancedGrant.expectedRepaymentPeriodDays,
                        daysLeft: enhancedGrant.repaymentPeriodLeft,
                    },
                }),
            },
            { key: 'capital.common.fields.totalFees', value: formatAmount(enhancedGrant.feesAmount) },
            { key: 'capital.common.fields.totalRepaymentAmount', value: formatAmount(enhancedGrant.totalAmount) },
            { key: 'capital.common.fields.repaymentThreshold', value: formatAmount(enhancedGrant.thresholdAmount) },
            { key: 'capital.common.fields.grantID', value: enhancedGrant.id },
            { key: 'capital.common.fields.accountDescription', value: enhancedGrant.balanceAccountDescription },
            { key: 'capital.common.fields.accountID', value: enhancedGrant.balanceAccountCode },
        ];

        if (enhancedGrant.maximumRepaymentPeriodMonths) {
            items.splice(5, 0, {
                key: 'capital.common.fields.maximumRepaymentPeriod',
                value: i18n.get('capital.common.values.numberOfMonths', { values: { months: enhancedGrant.maximumRepaymentPeriodMonths } }),
            });
        }

        return items;
    }, [grant, formatAmount, i18n]);

    return (
        <div className={GRANT_DETAILS_CLASS_NAMES.base}>
            <div className={GRANT_DETAILS_CLASS_NAMES.content}>
                <div className={GRANT_DETAILS_CLASS_NAMES.header}>
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                        <Typography el={TypographyElement.PARAGRAPH} variant={TypographyVariant.BODY}>
                            <Translation
                                translationKey="capital.overview.grants.item.details.requestedFunds"
                                fills={{
                                    amount: (
                                        <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} strongest>
                                            {i18n.amount(grant.grantAmount.value, grant.grantAmount.currency)}
                                        </Typography>
                                    ),
                                }}
                            />
                        </Typography>
                    </Typography>
                </div>
                <StructuredList
                    renderLabel={(val, key) =>
                        key === 'capital.common.fields.repaymentThreshold' ? (
                            <Tooltip
                                isUnderlineVisible
                                content={i18n.get('capital.common.fields.repaymentThreshold.description', {
                                    values: { days: CAPITAL_REPAYMENT_FREQUENCY },
                                })}
                            >
                                <span>
                                    <Typography
                                        className={GRANT_DETAILS_CLASS_NAMES.label}
                                        el={TypographyElement.SPAN}
                                        variant={TypographyVariant.CAPTION}
                                    >
                                        {val}
                                    </Typography>
                                </span>
                            </Tooltip>
                        ) : (
                            <Typography className={GRANT_DETAILS_CLASS_NAMES.label} el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                                {val}
                            </Typography>
                        )
                    }
                    renderValue={val => (
                        <Typography el={TypographyElement.SPAN} stronger variant={TypographyVariant.CAPTION}>
                            {val}
                        </Typography>
                    )}
                    items={structuredListItems}
                />
            </div>
        </div>
    );
};

// packages/domains/capital/vue/src/CapitalOverview/components/GrantDetails/GrantDetails.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoStructuredList, BentoStructuredListItem, BentoTypography } from '@adyen/bento-vue3';
import { CAPITAL_REPAYMENT_FREQUENCY, calculatePercentageFromBasisPoints, getEnhancedGrant } from '@integration-components/capital/domain';
import type { TranslationKey } from '@integration-components/core';
import { useCoreContext } from '@integration-components/core/vue';
import type { IGrant } from '@integration-components/types';
import { GRANT_DETAILS_CLASS_NAMES } from './constants';
import './GrantDetails.scss';

type GrantDetailItem = {
    key: TranslationKey;
    labelInfo?: string;
    value: string;
};

const props = defineProps<{
    grant: IGrant;
}>();

const { i18n } = useCoreContext();

const requestedFunds = computed(() => i18n.amount(props.grant.grantAmount.value, props.grant.grantAmount.currency));
const requestedFundsText = computed(() =>
    i18n.get('capital.overview.grants.item.details.requestedFunds', {
        values: { amount: requestedFunds.value },
    })
);

const structuredListItems = computed<GrantDetailItem[]>(() => {
    const enhancedGrant = getEnhancedGrant(props.grant);
    const formatAmount = (amount: { value: number; currency: string }) => i18n.amount(amount.value, amount.currency);
    const items: GrantDetailItem[] = [
        {
            key: 'capital.common.fields.remainingAmount',
            value: formatAmount(enhancedGrant.remainingGrantAmount),
        },
        { key: 'capital.common.fields.remainingFees', value: formatAmount(enhancedGrant.remainingFeesAmount) },
        { key: 'capital.common.fields.repaidAmount', value: formatAmount(enhancedGrant.repaidGrantAmount) },
        { key: 'capital.common.fields.repaidFees', value: formatAmount(enhancedGrant.repaidFeesAmount) },
        {
            key: 'capital.common.fields.dailyRepaymentRate',
            value: i18n.get('capital.common.values.percentage', {
                values: { percentage: calculatePercentageFromBasisPoints(enhancedGrant.repaymentRate) },
            }),
        },
        {
            key: 'capital.common.fields.expectedRepaymentPeriod',
            value: i18n.get('capital.common.values.daysWithDaysLeft', {
                values: {
                    days: enhancedGrant.expectedRepaymentPeriodDays,
                    daysLeft: enhancedGrant.repaymentPeriodLeft,
                },
            }),
        },
        { key: 'capital.common.fields.totalFees', value: formatAmount(enhancedGrant.feesAmount) },
        { key: 'capital.common.fields.totalRepaymentAmount', value: formatAmount(enhancedGrant.totalAmount) },
        {
            key: 'capital.common.fields.repaymentThreshold',
            labelInfo: i18n.get('capital.common.fields.repaymentThreshold.description', {
                values: { days: CAPITAL_REPAYMENT_FREQUENCY },
            }),
            value: formatAmount(enhancedGrant.thresholdAmount),
        },
        { key: 'capital.common.fields.grantID', value: enhancedGrant.id },
        { key: 'capital.common.fields.accountDescription', value: enhancedGrant.balanceAccountDescription ?? '' },
        { key: 'capital.common.fields.accountID', value: enhancedGrant.balanceAccountCode ?? '' },
    ];

    if (enhancedGrant.maximumRepaymentPeriodMonths) {
        items.splice(5, 0, {
            key: 'capital.common.fields.maximumRepaymentPeriod',
            value: i18n.get('capital.common.values.numberOfMonths', {
                values: { months: enhancedGrant.maximumRepaymentPeriodMonths },
            }),
        });
    }

    return items;
});
</script>

<template>
    <div :class="GRANT_DETAILS_CLASS_NAMES.base">
        <div :class="GRANT_DETAILS_CLASS_NAMES.content">
            <div :class="GRANT_DETAILS_CLASS_NAMES.header">
                <BentoTypography variant="body">
                    {{ requestedFundsText }}
                </BentoTypography>
            </div>

            <BentoStructuredList>
                <BentoStructuredListItem v-for="item in structuredListItems" :key="item.key" :label="i18n.get(item.key)" :label-info="item.labelInfo">
                    <BentoTypography el="span" variant="caption" stronger>
                        {{ item.value }}
                    </BentoTypography>
                </BentoStructuredListItem>
            </BentoStructuredList>
        </div>
    </div>
</template>
