// packages/domains/capital/vue/src/CapitalOverview/components/GrantsDisplay/GrantsDisplay.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { BentoAlert, BentoButton, BentoList, BentoListItem, BentoSegmentedControl, type BentoSegmentedControlItem } from '@adyen/bento-vue3';
import { getGrantConfig, getGroupedGrants, getHasGrantGroups, type EnhancedCapitalState } from '@integration-components/capital/domain';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/vue';
import { GRANT_ADJUSTMENT_DETAILS, sharedCapitalOverviewAnalyticsEventProperties } from '../../../../../domain/src/CapitalOverview/constants';
import type { IGrant } from '@integration-components/types';
import CapitalHeader from '../../../shared/CapitalHeader/CapitalHeader.vue';
import GrantItem from '../GrantItem/GrantItem.vue';
import GrantRepaymentDetails from '../GrantRepaymentDetails/GrantRepaymentDetails.vue';
import './GrantsDisplay.scss';

const props = defineProps<{
    capitalState: EnhancedCapitalState;
    grants: IGrant[];
    hideTitle?: boolean;
    onNewOfferRequest: () => void;
}>();

const { i18n } = useCoreContext();
const userEvents = useEventDispatcherContext();

const analyticsProperties = {
    ...sharedCapitalOverviewAnalyticsEventProperties,
    subCategory: 'Grants overview',
} as const;

const selectedGrantGroup = ref<'active' | 'inactive'>('active');
type GrantAdjustmentDetail = 'revocation' | 'unscheduledRepayment';
const selectedGrantDetail = ref<GrantAdjustmentDetail>();
const selectedGrant = ref<IGrant>();
const grantGroups = computed(() => getGroupedGrants(props.grants));
const hasGrantGroups = computed(() => getHasGrantGroups(grantGroups.value));
const maxAmount = computed(() => props.capitalState.dynamicOffer?.maxAmount);
const selectedGrantConfig = computed(() => (selectedGrant.value ? getGrantConfig(selectedGrant.value) : undefined));
const shouldShowRepaymentDetails = computed(
    () =>
        selectedGrant.value &&
        selectedGrantDetail.value === GRANT_ADJUSTMENT_DETAILS.unscheduledRepayment &&
        selectedGrantConfig.value?.hasUnscheduledRepaymentDetails
);

const grantGroupItems = computed<BentoSegmentedControlItem[]>(() => [
    { label: i18n.get('capital.overview.grants.list.tabs.labels.inProgress'), value: 'active' },
    { label: i18n.get('capital.overview.grants.list.tabs.labels.closed'), value: 'inactive' },
]);

const displayedGrants = computed(() => {
    if (!hasGrantGroups.value) {
        return props.grants;
    }

    return selectedGrantGroup.value === 'active' ? grantGroups.value.ongoing : grantGroups.value.closed;
});

const onNewOfferRequestWithTracking = () => {
    try {
        props.onNewOfferRequest();
    } finally {
        userEvents.addEvent?.('Clicked button', { ...analyticsProperties, label: 'Request a new loan' });
    }
};

const showGrantDetails = (grant: IGrant, detail?: GrantAdjustmentDetail) => {
    selectedGrantDetail.value = detail;
    selectedGrant.value = grant;
};

const getShowGrantDetails = (grant: IGrant) => (detail?: GrantAdjustmentDetail) => {
    showGrantDetails(grant, detail);
};

const hideGrantDetails = () => {
    selectedGrantDetail.value = undefined;
};

onMounted(() => {
    userEvents.addEvent?.('Landed on page', { ...analyticsProperties, label: 'Capital overview' });
});
</script>

<template>
    <GrantRepaymentDetails v-if="shouldShowRepaymentDetails && selectedGrant" :grant="selectedGrant" :on-details-close="hideGrantDetails" />

    <div v-else class="adyen-pe-grant-list">
        <CapitalHeader :hide-title="props.hideTitle" :region="props.capitalState.region" title-key="capital.common.title" />

        <div v-if="maxAmount" class="adyen-pe-grant-list__new-grant-banner">
            <BentoAlert type="highlight">
                {{ i18n.get('capital.overview.grants.newGrant.title.part1') }}
                <strong>
                    {{
                        i18n.get('capital.overview.grants.newGrant.title.part2', {
                            values: { amount: i18n.amount(maxAmount.value, maxAmount.currency, { minimumFractionDigits: 0 }) },
                        })
                    }}
                </strong>
                <template v-if="props.capitalState.renewableGrants.length" #description>
                    {{ i18n.get('capital.overview.grants.newGrant.earlyRenewalNotice') }}
                </template>
                <template #actions>
                    <BentoButton class="adyen-pe-grant-list__offer-button" @click="onNewOfferRequestWithTracking">
                        {{ i18n.get('capital.overview.grants.newGrant.actions.newGrant') }}
                    </BentoButton>
                </template>
            </BentoAlert>
        </div>

        <BentoSegmentedControl
            v-if="hasGrantGroups"
            v-model="selectedGrantGroup"
            :aria-label="i18n.get('capital.overview.grants.list.tabs.a11y.label')"
            :items="grantGroupItems"
        />

        <BentoList class="adyen-pe-grant-list__items">
            <BentoListItem v-for="grant in displayedGrants" :key="grant.id">
                <template #content>
                    <GrantItem :grant="grant" :show-details="getShowGrantDetails(grant)" />
                </template>
            </BentoListItem>
        </BentoList>
    </div>
</template>

// packages/domains/capital/preact/src/CapitalOverview/components/GrantList/GrantsDisplay.tsx
import { IGrant } from '@integration-components/types';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/preact';
import { useLandedPageEvent } from '@integration-components/hooks-preact/useEventDispatcher/useLandedPageEvent';
import { BaseList } from '@integration-components/ui-components-preact/BaseList/BaseList';
import { GrantItem } from '../GrantItem/GrantItem';
import { FunctionalComponent } from 'preact';
import { GrantAdjustmentDetail, GrantAdjustmentDetailCallback } from '../GrantAdjustmentDetails/types';
import { GrantRepaymentDetails } from '../GrantRepaymentDetails/GrantRepaymentDetails';
import { GRANT_ADJUSTMENT_DETAILS, sharedCapitalOverviewAnalyticsEventProperties } from '../../../../../domain/src/CapitalOverview/constants';
import SegmentedControl from '@integration-components/ui-components-preact/SegmentedControl/SegmentedControl';
import { useCallback, useMemo, useState } from 'preact/hooks';
import { CapitalHeader } from '../../../internal/CapitalHeader';
import Button from '@integration-components/ui-components-preact/Button/Button';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import InfoBox from '@integration-components/ui-components-preact/InfoBox';
import { EnhancedCapitalState, getHasGrantGroups, getGroupedGrants, getGrantConfig } from '@integration-components/capital/domain';

const sharedAnalyticsEventProperties = {
    ...sharedCapitalOverviewAnalyticsEventProperties,
    subCategory: 'Grants overview',
} as const;

const List = ({ grants, showDetails }: { grants: IGrant[]; showDetails: GrantAdjustmentDetailCallback }) => {
    return (
        <BaseList classNames={'adyen-pe-grant-list__items'}>
            {grants.map(grant => (
                <li key={grant.id}>
                    <GrantItem grant={grant} showDetails={showDetails.bind(null, grant)} />
                </li>
            ))}
        </BaseList>
    );
};

interface GrantsDisplayProps {
    capitalState: EnhancedCapitalState;
    grants: IGrant[];
    hideTitle?: boolean;
    onNewOfferRequest: () => void;
}

export const GrantsDisplay: FunctionalComponent<GrantsDisplayProps> = ({ capitalState, grants, hideTitle, onNewOfferRequest }) => {
    const [selectedGrantDetail, setSelectedGrantDetail] = useState<GrantAdjustmentDetail>();
    const [selectedGrant, setSelectedGrant] = useState<IGrant>();
    const { i18n } = useCoreContext();

    const userEvents = useEventDispatcherContext();

    const grantGroups = useMemo(() => getGroupedGrants(grants), [grants]);
    const hasGrantGroups = useMemo(() => getHasGrantGroups(grantGroups), [grantGroups]);

    const maxAmount = useMemo(() => capitalState.dynamicOffer?.maxAmount, [capitalState.dynamicOffer?.maxAmount]);

    const onNewOfferRequestWithTracking = useCallback<typeof onNewOfferRequest>(() => {
        try {
            return onNewOfferRequest();
        } finally {
            userEvents.addEvent?.('Clicked button', { ...sharedAnalyticsEventProperties, label: 'Request a new loan' });
        }
    }, [onNewOfferRequest, userEvents]);

    const selectedGrantConfig = useMemo(() => selectedGrant && getGrantConfig(selectedGrant), [selectedGrant]);

    const hideGrantDetails = useCallback(() => setSelectedGrantDetail(undefined), []);

    const showGrantDetails = useCallback<GrantAdjustmentDetailCallback>((grant, detail) => {
        setSelectedGrantDetail(detail);
        setSelectedGrant(grant);
    }, []);

    useLandedPageEvent({ ...sharedAnalyticsEventProperties, label: 'Capital overview' });

    if (
        selectedGrant &&
        selectedGrantDetail === GRANT_ADJUSTMENT_DETAILS.unscheduledRepayment &&
        selectedGrantConfig?.hasUnscheduledRepaymentDetails
    ) {
        return <GrantRepaymentDetails grant={selectedGrant} onDetailsClose={hideGrantDetails} />;
    }

    return (
        <div className="adyen-pe-grant-list">
            <CapitalHeader hideTitle={hideTitle} region={capitalState.region} titleKey={'capital.common.title'} />

            {capitalState.dynamicOffer && maxAmount ? (
                <InfoBox className="adyen-pe-grant-list__new-grant-banner">
                    <Typography variant={TypographyVariant.BODY}>
                        {i18n.get('capital.overview.grants.newGrant.title.part1')}
                        <strong>
                            {i18n.get('capital.overview.grants.newGrant.title.part2', {
                                values: {
                                    amount: i18n.amount(maxAmount.value, maxAmount.currency, {
                                        minimumFractionDigits: 0,
                                    }),
                                },
                            })}
                        </strong>
                    </Typography>

                    {!!capitalState.renewableGrants.length && (
                        <Typography variant={TypographyVariant.CAPTION} className="adyen-pe-grant-list__early-renewal-notice">
                            {i18n.get('capital.overview.grants.newGrant.earlyRenewalNotice')}
                        </Typography>
                    )}

                    <Button onClick={onNewOfferRequestWithTracking} className={'adyen-pe-grant-list__offer-button'} align="center">
                        {i18n.get('capital.overview.grants.newGrant.actions.newGrant')}
                    </Button>
                </InfoBox>
            ) : null}

            {hasGrantGroups ? (
                <SegmentedControl
                    items={[
                        {
                            label: 'capital.overview.grants.list.tabs.labels.inProgress',
                            content: <List grants={grantGroups.ongoing} showDetails={showGrantDetails} />,
                            id: 'active',
                        },
                        {
                            label: 'capital.overview.grants.list.tabs.labels.closed',
                            content: <List grants={grantGroups.closed} showDetails={showGrantDetails} />,
                            id: 'inactive',
                        },
                    ]}
                    activeItem={'active'}
                    aria-label={i18n.get('capital.overview.grants.list.tabs.a11y.label')}
                />
            ) : (
                <List grants={grants} showDetails={showGrantDetails} />
            )}
        </div>
    );
};
