// packages/domains/capital/vue/src/CapitalOverview/components/GrantList.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { EnhancedCapitalState, OnFundsRequestCallback } from '@integration-components/capital/domain';
import type { IGrant } from '@integration-components/types';
import GrantsDisplay from './GrantsDisplay/GrantsDisplay.vue';
import CapitalOffer from '../../CapitalOffer/components/CapitalOffer.vue';

const props = defineProps<{
    capitalState: EnhancedCapitalState;
    grants: IGrant[];
    hideTitle?: boolean;
    onFundsRequest?: OnFundsRequestCallback;
    onGrantListUpdateRequest: (data: IGrant) => void;
    onContactSupport?: () => void;
    onOfferDismiss?: (goToPreviousStep: () => void) => void;
}>();

const isCapitalOfferVisible = ref(false);
const goBackToPreviousStep = () => {
    isCapitalOfferVisible.value = false;
};

const goToNextStep = () => {
    isCapitalOfferVisible.value = true;
};

const goBackToList = () => {
    if (props.onOfferDismiss) {
        props.onOfferDismiss(goBackToPreviousStep);
    } else {
        goBackToPreviousStep();
    }
};

const handleFundsRequest: OnFundsRequestCallback = (data, renewsGrantId) => {
    if (props.onFundsRequest) {
        props.onFundsRequest(data, renewsGrantId);
    } else {
        props.onGrantListUpdateRequest({ ...data, renewsGrantId });
        isCapitalOfferVisible.value = false;
    }
};
</script>

<template>
    <CapitalOffer
        v-if="isCapitalOfferVisible"
        :hide-title="props.hideTitle"
        :on-funds-request="handleFundsRequest"
        :external-capital-state="props.capitalState"
        :on-offer-dismiss="goBackToList"
        :on-contact-support="props.onContactSupport"
    />
    <GrantsDisplay v-else :grants="grants" :hide-title="props.hideTitle" :capital-state="props.capitalState" :on-new-offer-request="goToNextStep" />
</template>

// packages/domains/capital/preact/src/CapitalOverview/components/GrantList/GrantList.tsx
import { FunctionalComponent } from 'preact';
import './GrantList.scss';
import { useCallback, useState } from 'preact/hooks';
import { CapitalOffer } from '../../../CapitalOffer/components/CapitalOffer/CapitalOffer';
import { GrantsDisplay } from './GrantsDisplay';
import { IGrant } from '@integration-components/types';
import { EnhancedCapitalState, OnFundsRequestCallback } from '@integration-components/capital/domain';

interface GrantListProps {
    capitalState: EnhancedCapitalState;
    grants: IGrant[];
    hideTitle?: boolean;
    onFundsRequest?: OnFundsRequestCallback;
    onGrantListUpdateRequest: (data: IGrant) => void;
    onOfferDismiss?: (goToPreviousStep: () => void) => void;
}

export const GrantList: FunctionalComponent<GrantListProps> = ({
    capitalState,
    grants,
    hideTitle,
    onFundsRequest,
    onGrantListUpdateRequest,
    onOfferDismiss,
}) => {
    const [isCapitalOfferVisible, setIsCapitalOfferVisible] = useState<boolean>(false);

    const goBackToPreviousStep = useCallback(() => setIsCapitalOfferVisible(false), []);
    const goToNextStep = useCallback(() => setIsCapitalOfferVisible(true), []);

    const goBackToList = useCallback(() => {
        if (onOfferDismiss) {
            onOfferDismiss(goBackToPreviousStep);
        } else {
            goBackToPreviousStep();
        }
    }, [goBackToPreviousStep, onOfferDismiss]);

    const handleFundsRequest = useCallback<OnFundsRequestCallback>(
        (data, renewsGrantId) => {
            if (onFundsRequest) {
                onFundsRequest(data, renewsGrantId);
            } else {
                onGrantListUpdateRequest({ ...data, renewsGrantId });
                setIsCapitalOfferVisible(false);
            }
        },
        [onFundsRequest, onGrantListUpdateRequest]
    );

    return (
        <>
            {isCapitalOfferVisible ? (
                <CapitalOffer
                    externalCapitalState={capitalState}
                    hideTitle={hideTitle}
                    onFundsRequest={handleFundsRequest}
                    onOfferDismiss={goBackToList}
                />
            ) : (
                <GrantsDisplay grants={grants} hideTitle={hideTitle} capitalState={capitalState} onNewOfferRequest={goToNextStep} />
            )}
        </>
    );
};
