// src/components/external/PayByLink/PaymentLinkCreation/components/PaymentLinkCreationContainer/PaymentLinkCreationContainer.tsx
import { ExternalUIComponentProps, PaymentLinkCreationComponentProps } from '../../../../../types';
import { PaymentLinkCreationFormContainer } from '../PaymentLinkCreationFormContainer/PaymentLinkCreationFormContainer';
import '../../PaymentLinkCreation.scss';
import { useState } from 'preact/hooks';
import { FormSuccess } from '../Form/FormSuccess/FormSuccess';
import { PaymentLinkDetails } from '../../../PaymentLinkDetails/components/PaymentLinkDetails/PaymentLinkDetails';

type PaymentLinkCreationState = 'Creation' | 'Success' | 'Details';

const PaymentLinkCreationContainer = (props: ExternalUIComponentProps<PaymentLinkCreationComponentProps> & { embeddedInOverview?: boolean }) => {
    const [state, setState] = useState<PaymentLinkCreationState>('Creation');
    const [paymentLinkUrl, setPaymentLinkUrl] = useState<string>('');
    const [paymentLinkId, setPaymentLinkId] = useState<string>('');

    return (
        <div className="adyen-pe-payment-link-creation">
            {(() => {
                switch (state) {
                    case 'Creation':
                        return (
                            <PaymentLinkCreationFormContainer
                                {...props}
                                onPaymentLinkCreated={data => {
                                    props.onPaymentLinkCreated?.(data);
                                    setPaymentLinkUrl(data.paymentLink?.url ?? '');
                                    setPaymentLinkId(data.paymentLink?.paymentLinkId ?? '');
                                    setState('Success');
                                }}
                            />
                        );
                    case 'Success':
                        return (
                            <div>
                                <FormSuccess paymentLinkUrl={paymentLinkUrl} onGoToDetails={() => setState('Details')} />
                            </div>
                        );
                    case 'Details':
                        return <PaymentLinkDetails id={paymentLinkId} />;
                    default:
                        return null;
                }
            })()}
        </div>
    );
};

export default PaymentLinkCreationContainer;

// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/PaymentLinkCreationContainer/PaymentLinkCreationContainer.vue
<script setup lang="ts">
import { ref } from 'vue';
import PaymentLinkCreationForm from '../PaymentLinkCreationFormContainer/PaymentLinkCreationForm.vue';
import PaymentLinkDetails from '../../../PaymentLinkDetails/components/PaymentLinkDetails/PaymentLinkDetails.vue';
import FormSuccess from '../Form/FormSuccess/FormSuccess.vue';
import type { PaymentLinkCreationFormValues, CreatedPaymentLink, PaymentLinkCreationProps } from '../../../../../domain/src';
import '@adyen/bento-vue3/styles/bento-light';
import styles from './PaymentLinkCreationContainer.module.scss';

type PaymentLinkCreationContainerProps = PaymentLinkCreationProps & {
    embeddedInOverview?: boolean;
};

const props = defineProps<PaymentLinkCreationContainerProps>();

type CreationState = 'Creation' | 'Success' | 'Details';

const state = ref<CreationState>('Creation');
const paymentLinkUrl = ref('');
const paymentLinkId = ref('');

function handleCreated(data: PaymentLinkCreationFormValues & { paymentLink: CreatedPaymentLink }) {
    props.onPaymentLinkCreated?.(data);
    paymentLinkUrl.value = data.paymentLink?.url ?? '';
    paymentLinkId.value = data.paymentLink?.paymentLinkId ?? '';
    state.value = 'Success';
}

function handleShowDetails() {
    if (props.onShowDetails) {
        props.onShowDetails?.({ id: paymentLinkId.value, url: paymentLinkUrl.value });
    } else {
        state.value = 'Details';
    }
}
</script>

<template>
    <div :class="styles.root">
        <PaymentLinkCreationForm
            v-if="state === 'Creation'"
            :fields-config="props.fieldsConfig"
            :store-ids="props.storeIds"
            :hide-title="props.hideTitle"
            :on-creation-dismiss="props.onCreationDismiss"
            :on-contact-support="props.onContactSupport"
            :embedded-in-overview="props.embeddedInOverview"
            @payment-link-created="handleCreated"
        />
        <FormSuccess v-if="state === 'Success'" :payment-link-url="paymentLinkUrl" :on-show-details="handleShowDetails" />
        <PaymentLinkDetails v-if="state === 'Details'" :id="paymentLinkId" :on-contact-support="props.onContactSupport" />
    </div>
</template>
