// packages/domains/transactions/vue/src/TransactionsOverview/components/TransactionsExport/TransactionsExport.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useCoreContext, useConfigContext, useEventDispatcherContext } from '@integration-components/core/vue';
import {
    BentoAlert,
    BentoButton,
    BentoDivider,
    BentoPopover,
    BentoTag,
    BentoToggle,
    BentoTypography,
    useBentoToastController,
    useClickOutside,
} from '@adyen/bento-vue3';
import { useDownload, useUniqueId } from '@integration-components/composables-vue';
import { isFunction, downloadBlob, EMPTY_ARRAY } from '@integration-components/utils';
import { useTransactionsOverviewContext } from '../../composables/useTransactionsOverviewState';
import { EXPORT_COLUMNS, DEFAULT_EXPORT_COLUMNS } from '../../constants';
import { TRANSACTION_ANALYTICS_CATEGORY, TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } from '@integration-components/transactions/domain';
import type { TranslationKey } from '@integration-components/core';
import DownloadIcon from '@adyen/ui-assets-icons-16/vue/download';
import styles from './TransactionsExport.module.scss';

const props = defineProps<{ disabled?: boolean }>();

const { i18n } = useCoreContext();
const config = useConfigContext();
const userEvents = useEventDispatcherContext();
const { filters } = useTransactionsOverviewContext();

const { addToast } = useBentoToastController();
let activeExportErrorToast: ReturnType<typeof addToast> | undefined;

const popoverOpen = ref(false);
const exportStarted = ref(false);
const exportColumns = ref<readonly (typeof EXPORT_COLUMNS)[number][]>(DEFAULT_EXPORT_COLUMNS);

const targetElement = ref<HTMLElement | null>(null);
const popoverRef = ref<HTMLElement | null>(null);
const exportButtonId = `elem-${useUniqueId()}`;

const sharedAnalyticsProps = { category: TRANSACTION_ANALYTICS_CATEGORY, subCategory: TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } as const;

const canDownloadTransactions = computed(() => isFunction(config.endpoints.downloadTransactions));

const activeFilters = computed<readonly TranslationKey[]>(() => {
    const { balanceAccountId, paymentPspReference, createdSince, createdUntil, categories, currencies } = filters.value;
    return [
        ...(balanceAccountId ? (['transactions.overview.export.filters.types.account'] as const) : EMPTY_ARRAY),
        ...(createdSince && createdUntil ? (['transactions.overview.export.filters.types.date'] as const) : EMPTY_ARRAY),
        ...(categories.length ? (['transactions.overview.export.filters.types.category'] as const) : EMPTY_ARRAY),
        ...(currencies.length ? (['transactions.overview.export.filters.types.currency'] as const) : EMPTY_ARRAY),
        ...(paymentPspReference ? (['transactions.overview.export.filters.types.paymentPspReference'] as const) : EMPTY_ARRAY),
    ] as readonly TranslationKey[];
});

const exportParams = computed(() => ({
    balanceAccountId: filters.value.balanceAccountId ?? '',
    createdSince: filters.value.createdSince,
    createdUntil: filters.value.createdUntil,
    categories: filters.value.categories as string[],
    currencies: filters.value.currencies as string[],
    statuses: filters.value.statuses as string[],
    paymentPspReference: filters.value.paymentPspReference,
    sortDirection: 'desc' as const,
    columns: exportColumns.value as string[],
}));

const { isFetching, error } = useDownload(
    'downloadTransactions',
    () => ({ query: exportParams.value }),
    () => canDownloadTransactions.value && popoverOpen.value && exportStarted.value && exportColumns.value.length > 0,
    data => downloadBlob(data as any)
);

watch(error, err => {
    if (err) {
        activeExportErrorToast = addToast({ text: i18n.get('transactions.overview.export.actions.error') });
    }
});

watch(popoverOpen, isOpen => {
    if (isOpen) {
        activeExportErrorToast?.dismiss();
    } else {
        exportColumns.value = DEFAULT_EXPORT_COLUMNS;
    }
});

watch(
    exportStarted,
    started => {
        if (!started) return;
        exportStarted.value = false;

        let exportedFields: 'All' | 'Custom' | 'Default' = 'Custom';
        let exportingOnlyDefaultFields = true;
        let exportingAllFields = true;

        EXPORT_COLUMNS.forEach(column => {
            const isExportedField = exportColumns.value.includes(column);
            const isDefaultField = DEFAULT_EXPORT_COLUMNS.includes(column);
            exportingOnlyDefaultFields &&= isExportedField ? isDefaultField : !isDefaultField;
            exportingAllFields &&= isExportedField;
        });

        if (exportingAllFields) exportedFields = 'All';
        else if (exportingOnlyDefaultFields) exportedFields = 'Default';

        userEvents.addEvent?.('Completed export', { ...sharedAnalyticsProps, exportedFields });
    },
    { flush: 'post' }
);

watch(isFetching, (fetching, wasFetching) => {
    if (wasFetching && !fetching) {
        popoverOpen.value = false;
    }
});

useClickOutside(
    popoverRef,
    () => {
        if (popoverOpen.value) {
            dismissPopover();
        }
    },
    { ignore: [targetElement] }
);

const masterSwitchChecked = computed(() => exportColumns.value.length === EXPORT_COLUMNS.length);

const columnSwitches = computed(() =>
    EXPORT_COLUMNS.map(column => ({
        column,
        label: i18n.get(`transactions.overview.export.columns.types.${column}` as TranslationKey),
        checked: exportColumns.value.includes(column),
    }))
);

function togglePopover() {
    if (popoverOpen.value) {
        userEvents.addEvent?.('Cancelled export', sharedAnalyticsProps);
    } else {
        userEvents.addEvent?.('Clicked button', { ...sharedAnalyticsProps, label: 'Export' });
    }
    popoverOpen.value = !popoverOpen.value;
}

function dismissPopover() {
    userEvents.addEvent?.('Cancelled export', sharedAnalyticsProps);
    popoverOpen.value = false;
}

function onMasterSwitchChange(checked: boolean) {
    exportColumns.value = checked ? EXPORT_COLUMNS : EMPTY_ARRAY;
}

function onColumnChange(column: (typeof EXPORT_COLUMNS)[number], checked: boolean) {
    if (checked) {
        if (!exportColumns.value.includes(column)) {
            exportColumns.value = [...exportColumns.value, column];
        }
    } else {
        exportColumns.value = exportColumns.value.filter(c => c !== column);
    }
}

function startExport() {
    exportStarted.value = true;
}

const popoverActions = computed(() => [
    {
        disabled: !exportColumns.value.length,
        event: startExport,
        title: i18n.get('transactions.overview.export.actions.download'),
        ...(isFetching.value ? ({ state: 'loading' } as const) : {}),
    },
    {
        event: dismissPopover,
        title: i18n.get('transactions.overview.export.actions.cancel'),
    },
]);
</script>

<template>
    <div v-if="canDownloadTransactions">
        <BentoButton
            :id="exportButtonId"
            ref="targetElement"
            variant="secondary"
            :disabled="props.disabled || isFetching"
            :aria-label="i18n.get('transactions.overview.export.button.label')"
            aria-haspopup="dialog"
            :aria-expanded="popoverOpen"
            @click="togglePopover"
        >
            <template #iconLeft>
                <DownloadIcon />
            </template>
            {{ isFetching ? i18n.get('transactions.overview.export.button.inProgress') : i18n.get('transactions.overview.export.button.label') }}
        </BentoButton>

        <BentoPopover
            v-if="popoverOpen"
            ref="popoverRef"
            :open="popoverOpen"
            :target-element="targetElement ?? undefined"
            position="bottom-end"
            :dismissible="false"
            :disable-focus-trap="false"
            :actions="popoverActions"
            @dismiss="dismissPopover"
        >
            <div :class="styles.popoverSections">
                <div :class="styles.filters">
                    <BentoTypography variant="body" strongest>
                        {{ `${i18n.get('transactions.overview.export.filters.title')}:` }}
                    </BentoTypography>
                    <BentoTag v-for="filter in activeFilters" :key="filter" variant="grey" :label="i18n.get(filter)" />
                </div>

                <BentoDivider />

                <div :class="styles.columns">
                    <BentoTypography variant="body" strongest>
                        {{ i18n.get('transactions.overview.export.columns.title') }}
                    </BentoTypography>
                    <BentoToggle label-position="after" :value="masterSwitchChecked" @input="onMasterSwitchChange">
                        {{ i18n.get('transactions.overview.export.columns.types.all', { values: { count: EXPORT_COLUMNS.length } }) }}
                    </BentoToggle>
                    <BentoToggle
                        v-for="{ column, label, checked } in columnSwitches"
                        :key="column"
                        label-position="after"
                        :value="checked"
                        @input="(val: boolean) => onColumnChange(column, val)"
                    >
                        {{ label }}
                    </BentoToggle>
                </div>
            </div>

            <BentoAlert type="highlight">
                <template #default>
                    {{ i18n.get('transactions.overview.export.actions.download.info') }}
                </template>
            </BentoAlert>
        </BentoPopover>
    </div>
</template>

// src/components/external/Transactions/TransactionsOverview/components/TransactionsExport/TransactionsExport.tsx
import { h } from 'preact';
import cx from 'classnames';
import Icon from '../../../../../internal/Icon';
import Spinner from '../../../../../internal/Spinner';
import Popover from '../../../../../internal/Popover/Popover';
import Typography from '../../../../../internal/Typography/Typography';
import useCoreContext from '../../../../../../core/Context/useCoreContext';
import useDownload from '../../../../../internal/Button/DownloadButton/useDownload';
import useAnalyticsContext from '../../../../../../core/Context/analytics/useAnalyticsContext';
import ToggleSwitch, { ToggleSwitchProps } from '../../../../../internal/ToggleSwitch/ToggleSwitch';
import ButtonActions from '../../../../../internal/Button/ButtonActions/ButtonActions';
import FilterButton from '../../../../../internal/FilterBar/components/FilterButton/FilterButton';
import { ButtonActionObject, ButtonActionsLayoutBasic } from '../../../../../internal/Button/ButtonActions/types';
import { containerQueries, useResponsiveContainer } from '../../../../../../hooks/useResponsiveContainer';
import { PopoverContainerPosition, PopoverContainerVariant } from '../../../../../internal/Popover/types';
import { TypographyElement, TypographyVariant } from '../../../../../internal/Typography/types';
import { downloadBlob, EMPTY_ARRAY, isFunction, uniqueId } from '../../../../../../utils';
import { DEFAULT_EXPORT_COLUMNS, EXPORT_COLUMNS, TRANSACTION_ANALYTICS_CATEGORY, TRANSACTION_ANALYTICS_SUBCATEGORY_LIST } from '../../constants';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { useConfigContext } from '../../../../../../core/ConfigContext';
import { ButtonVariant } from '../../../../../internal/Button/types';
import { fixedForwardRef } from '../../../../../../utils/preact';
import { getTransactionsFilterQueryParams } from '../utils';
import { TranslationKey } from '../../../../../../translations';
import { TransactionsFilters } from '../../types';
import { PropsWithChildren } from 'preact/compat';
import { classes } from './constants';
import './TransactionsExport.scss';
import { EndpointDownloadStreamData } from '../../../../../../types/api/endpoints';
import Alert from '../../../../../internal/Alert/Alert';
import { AlertTypeOption } from '../../../../../internal/Alert/types';
import { Tag } from '../../../../../internal/Tag/Tag';

const sharedAnalyticsEventProperties = {
    category: TRANSACTION_ANALYTICS_CATEGORY,
    subCategory: TRANSACTION_ANALYTICS_SUBCATEGORY_LIST,
} as const;

/* HELPER COMPONENTS */
const Text = ({
    children,
    el = TypographyElement.DIV,
    variant = TypographyVariant.BODY,
    ...typographyProps
}: PropsWithChildren<{
    el?: TypographyElement;
    variant?: TypographyVariant;
    stronger?: boolean;
    className?: string;
    id?: string;
}>) => (
    <Typography {...typographyProps} el={el} variant={variant}>
        {children}
    </Typography>
);

const ExportColumn = fixedForwardRef<PropsWithChildren<{ className?: string } & ToggleSwitchProps>, HTMLInputElement>(
    ({ children, className, ...toggleSwitchProps }, ref) => (
        <ToggleSwitch ref={ref} className={cx([classes.popoverColumn, className])} {...toggleSwitchProps} name="columns">
            <Text el={TypographyElement.SPAN}>{children}</Text>
        </ToggleSwitch>
    )
);

const SectionTitle = ({ children, ...textProps }: PropsWithChildren<{ id?: string }>) => (
    <Text {...textProps} className={classes.popoverSectionTitle} stronger>
        {children}
    </Text>
);

const TransactionsExport = ({ disabled, filters }: { disabled?: boolean; filters: Readonly<TransactionsFilters> }) => {
    const { i18n } = useCoreContext();
    const userEvents = useAnalyticsContext();
    const isSmContainer = useResponsiveContainer(containerQueries.down.xs);

    const [popoverOpen, setPopoverOpen] = useState(false);
    const [exportStarted, setExportStarted] = useState(false);
    const [exportColumns, setExportColumns] = useState([] as readonly (typeof EXPORT_COLUMNS)[number][]);

    const popoverOpenRef = useRef(popoverOpen);

    const [activeFilters, exportParams] = useMemo(() => {
        const { balanceAccount, paymentPspReference, createdDate, categories, currencies /*, statuses*/ } = filters;

        const activeFilters: readonly TranslationKey[] = [
            ...(balanceAccount?.id ? (['transactions.overview.export.filters.types.account'] as const) : EMPTY_ARRAY),
            ...(createdDate ? (['transactions.overview.export.filters.types.date'] as const) : EMPTY_ARRAY),
            // ...(statuses.length ? (['transactions.overview.export.filters.types.status'] as const) : EMPTY_ARRAY),
            ...(categories.length ? (['transactions.overview.export.filters.types.category'] as const) : EMPTY_ARRAY),
            ...(currencies.length ? (['transactions.overview.export.filters.types.currency'] as const) : EMPTY_ARRAY),
            ...(paymentPspReference ? (['transactions.overview.export.filters.types.paymentPspReference'] as const) : EMPTY_ARRAY),
        ] as const;

        const exportParams = {
            ...getTransactionsFilterQueryParams(filters),
            sortDirection: 'desc' as const,
        };

        return [activeFilters, exportParams];
    }, [filters]);

    const { downloadTransactions } = useConfigContext().endpoints;
    const canDownloadTransactions = isFunction(downloadTransactions);
    const canExportTransactions = canDownloadTransactions && popoverOpen && exportStarted && !!exportColumns.length;

    const dismissPopover = useCallback(
        (exportCancelled = true) => {
            setPopoverOpen(false);
            if (!exportCancelled) return;
            userEvents.addEvent?.('Cancelled export', sharedAnalyticsEventProperties);
        },
        [userEvents]
    );

    const onExportSuccess = useCallback(
        (data: EndpointDownloadStreamData) => {
            downloadBlob(data);
            dismissPopover(false);
        },
        [dismissPopover]
    );

    const { error, isFetching } = useDownload(
        'downloadTransactions',
        { query: { ...exportParams, columns: exportColumns } },
        canExportTransactions,
        onExportSuccess
    );

    const exportButtonRef = useRef<HTMLButtonElement | null>(null);
    const exportButtonLabel = useMemo(() => i18n.get('transactions.overview.export.button.label'), [i18n]);
    const exportingButtonLabel = useMemo(() => i18n.get('transactions.overview.export.button.inProgress'), [i18n]);
    const cancelButtonLabel = useMemo(() => i18n.get('transactions.overview.export.actions.cancel'), [i18n]);
    const downloadButtonLabel = useMemo(() => i18n.get('transactions.overview.export.actions.download'), [i18n]);
    const activeFiltersTitle = useMemo(() => i18n.get('transactions.overview.export.filters.title'), [i18n]);
    const exportColumnsTitle = useMemo(() => i18n.get('transactions.overview.export.columns.title'), [i18n]);
    const exportColumnsTitleId = useMemo(uniqueId, []);

    const columnSwitches = useMemo(
        () =>
            EXPORT_COLUMNS.map(column => ({
                label: i18n.get(`transactions.overview.export.columns.types.${column}`),
                id: uniqueId(),
                value: column,
            })),
        [i18n]
    );

    const masterSwitchLabel = useMemo(() => {
        return i18n.get('transactions.overview.export.columns.types.all', {
            values: { count: EXPORT_COLUMNS.length },
        });
    }, [i18n]);

    const masterSwitchId = useMemo(uniqueId, []);
    const masterSwitchRef = useRef<HTMLInputElement | null>(null);
    const masterSwitchAriaControls = useMemo(() => columnSwitches.map(({ id }) => id).join(' '), [columnSwitches]);
    const masterSwitchChecked = exportColumns.length === EXPORT_COLUMNS.length;

    const onExportColumnChange = useCallback(
        (evt: h.JSX.TargetedEvent<HTMLInputElement>) => {
            const checkbox = evt.currentTarget;
            const checkedColumn = checkbox.value as (typeof EXPORT_COLUMNS)[number];
            const checked = checkbox.checked;

            const isMasterSwitch = checkbox.id === masterSwitchId;

            setExportColumns(exportColumns => {
                if (isMasterSwitch) return checked ? EXPORT_COLUMNS : EMPTY_ARRAY;
                if (EXPORT_COLUMNS.includes(checkedColumn)) {
                    const columnIndex = exportColumns.indexOf(checkedColumn);
                    if (checked) {
                        // Include checked column
                        if (columnIndex < 0) return [...exportColumns, checkedColumn];
                    } else if (columnIndex >= 0) {
                        // Exclude unchecked column
                        return [...exportColumns.slice(0, columnIndex), ...exportColumns.slice(columnIndex + 1)];
                    }
                }
                return exportColumns;
            });
        },
        [masterSwitchId]
    );

    const openPopover = useCallback(() => {
        if (popoverOpenRef.current) return;
        setPopoverOpen(true);
        userEvents.addEvent?.('Clicked button', { ...sharedAnalyticsEventProperties, label: 'Export' });
    }, [userEvents]);

    const cancelAction = useMemo<ButtonActionObject>(
        () => ({
            event: () => dismissPopover(),
            variant: ButtonVariant.SECONDARY,
            title: cancelButtonLabel,
        }),
        [cancelButtonLabel, dismissPopover]
    );

    const downloadAction = useMemo<ButtonActionObject>(
        () => ({
            disabled: !exportColumns.length,
            event: () => setExportStarted(true),
            variant: ButtonVariant.PRIMARY,
            title: downloadButtonLabel,
            state: isFetching ? 'loading' : 'default',
        }),
        [downloadButtonLabel, exportColumns.length, isFetching]
    );

    useEffect(() => {
        if (!(popoverOpenRef.current = popoverOpen)) {
            setExportColumns(DEFAULT_EXPORT_COLUMNS);
        }
    }, [popoverOpen]);

    useEffect(() => {
        if (exportStarted) {
            setExportStarted(false);

            let exportedFields: 'All' | 'Custom' | 'Default' = 'Custom';
            let exportingOnlyDefaultFields = true;
            let exportingAllFields = true;

            EXPORT_COLUMNS.forEach(column => {
                const isExportedField = exportColumns.includes(column);
                const isDefaultField = DEFAULT_EXPORT_COLUMNS.includes(column);
                exportingOnlyDefaultFields &&= isExportedField ? isDefaultField : !isDefaultField;
                exportingAllFields &&= isExportedField;
            });

            if (exportingAllFields) {
                exportedFields = 'All';
            } else if (exportingOnlyDefaultFields) {
                exportedFields = 'Default';
            }

            userEvents.addEvent?.('Completed export', {
                ...sharedAnalyticsEventProperties,
                exportedFields,
            });
        }
    }, [exportColumns, exportStarted, userEvents]);

    useEffect(() => {
        (function attemptFocusCapture() {
            if (masterSwitchRef.current) {
                masterSwitchRef.current.focus();
            } else requestAnimationFrame(attemptFocusCapture);
        })();
    }, []);

    const renderAlertError = useCallback(
        () => (
            <Alert className={classes.popoverActionsAlert} type={AlertTypeOption.CRITICAL}>
                <Typography variant={TypographyVariant.BODY}>{i18n.get('transactions.overview.export.actions.error')}</Typography>
            </Alert>
        ),
        [i18n]
    );

    return canDownloadTransactions ? (
        <div className={classes.root}>
            <FilterButton
                aria-label={exportButtonLabel}
                ref={exportButtonRef}
                className={classes.button}
                classNameModifiers={popoverOpen ? ['active'] : undefined}
                disabled={disabled || isFetching}
                onClick={openPopover}
                tabIndex={0}
            >
                <div className="adyen-pe-filter-button__default-container">
                    <Text className="adyen-pe-filter-button__label">
                        {isFetching ? <Spinner size="x-small" /> : <Icon name="download" />}
                        {!isSmContainer && <span>{isFetching ? exportingButtonLabel : exportButtonLabel}</span>}
                    </Text>
                </div>
            </FilterButton>

            {popoverOpen && (
                <Popover
                    disableFocusTrap={false}
                    dismissible={false}
                    dismiss={dismissPopover}
                    open={popoverOpen}
                    position={isSmContainer ? PopoverContainerPosition.BOTTOM : PopoverContainerPosition.BOTTOM_RIGHT}
                    variant={PopoverContainerVariant.POPOVER}
                    showOverlay={isSmContainer}
                    targetElement={exportButtonRef}
                    title={exportButtonLabel}
                >
                    <div className={classes.popover}>
                        <div className={classes.popoverSections}>
                            <div className={cx(classes.popoverSection, classes.filtersSection)}>
                                <SectionTitle>{`${activeFiltersTitle}:`}</SectionTitle>
                                {activeFilters.map(filter => (
                                    <Tag label={i18n.get(filter)} key={filter} />
                                ))}
                            </div>

                            <div className={cx(classes.popoverSection, classes.columnsSection)}>
                                <div role="group" aria-labelledby={exportColumnsTitleId}>
                                    <SectionTitle id={exportColumnsTitleId}>{exportColumnsTitle}</SectionTitle>
                                    <div className={classes.popoverSectionContent}>
                                        <ExportColumn
                                            ref={masterSwitchRef}
                                            className={classes.popoverColumnAll}
                                            aria-controls={masterSwitchAriaControls}
                                            checked={masterSwitchChecked}
                                            onChange={onExportColumnChange}
                                            id={masterSwitchId}
                                            disabled={isFetching}
                                        >
                                            {masterSwitchLabel}
                                        </ExportColumn>

                                        {columnSwitches.map(({ id, label, value }) => (
                                            <ExportColumn
                                                checked={exportColumns.includes(value)}
                                                onChange={onExportColumnChange}
                                                value={value}
                                                key={value}
                                                id={id}
                                                disabled={isFetching}
                                            >
                                                {label}
                                            </ExportColumn>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className={classes.popoverActions}>
                            <Alert
                                type={AlertTypeOption.HIGHLIGHT}
                                className={classes.popoverActionsAlert}
                                title={i18n.get('transactions.overview.export.actions.download.info')}
                            />
                            {error && renderAlertError()}
                            <ButtonActions actions={[downloadAction, cancelAction]} layout={ButtonActionsLayoutBasic.BUTTONS_END} />
                        </div>
                    </div>
                </Popover>
            )}
        </div>
    ) : null;
};

export default TransactionsExport;
