// packages/domains/payByLink/vue/src/PaymentLinkDetails/components/PaymentLinkSkeleton/PaymentLinkSkeleton.vue
<script setup lang="ts">
import styles from './PaymentLinkSkeleton.module.scss';

const TAB_LABEL_COUNT = 3;
const FIELD_COUNT = 6;
</script>

<template>
    <div :class="styles.root">
        <div :class="styles.summaryContainer">
            <div :class="styles.status" />
            <div :class="styles.amount" />
            <div :class="styles.expirationDate" />
        </div>
        <div :class="styles.tabsContainer">
            <div :class="styles.tabLabelsContainer">
                <div v-for="index in TAB_LABEL_COUNT" :key="index" :class="styles.tabLabel" />
            </div>
            <div :class="styles.fieldsContainer">
                <div v-for="index in FIELD_COUNT" :key="index" :class="styles.fieldContainer">
                    <div :class="styles.fieldLabel" />
                    <div :class="styles.fieldValue" />
                </div>
            </div>
        </div>
    </div>
</template>

// src/components/external/PaymentLinkDetails/components/PaymentLinkSkeleton/PaymentLinkSkeleton.tsx
import './PaymentLinkSkeleton.scss';

const CLASSNAMES = {
    root: 'adyen-pe-payment-link-skeleton',
    summaryContainer: 'adyen-pe-payment-link-skeleton__summary-container',
    status: 'adyen-pe-payment-link-skeleton__status',
    amount: 'adyen-pe-payment-link-skeleton__amount',
    expirationDate: 'adyen-pe-payment-link-skeleton__expiration-date',
    tabsContainer: 'adyen-pe-payment-link-skeleton__tabs-container',
    tabLabelsContainer: 'adyen-pe-payment-link-skeleton__tab-labels-container',
    tabLabel: 'adyen-pe-payment-link-skeleton__tab-label',
    fieldsContainer: 'adyen-pe-payment-link-skeleton__fields-container',
    fieldContainer: 'adyen-pe-payment-link-skeleton__field-container',
    fieldLabel: 'adyen-pe-payment-link-skeleton__field-label',
    fieldValue: 'adyen-pe-payment-link-skeleton__field-value',
};

export const PaymentLinkSkeleton = () => {
    return (
        <div className={CLASSNAMES.root}>
            <div className={CLASSNAMES.summaryContainer}>
                <div className={CLASSNAMES.status}></div>
                <div className={CLASSNAMES.amount}></div>
                <div className={CLASSNAMES.expirationDate}></div>
            </div>
            <div className={CLASSNAMES.tabsContainer}>
                <div className={CLASSNAMES.tabLabelsContainer}>
                    {[...Array(3)].map((_, index) => (
                        <div key={index} className={CLASSNAMES.tabLabel}></div>
                    ))}
                </div>
                <div className={CLASSNAMES.fieldsContainer}>
                    {[...Array(6)].map((_, index) => (
                        <div key={index} className={CLASSNAMES.fieldContainer}>
                            <div className={CLASSNAMES.fieldLabel}></div>
                            <div className={CLASSNAMES.fieldValue}></div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};
