// src/components/external/CapitalOverview/components/GrantActions/GrantActions.tsx
import { FunctionalComponent } from 'preact';
import { useCallback } from 'preact/hooks';
import { IMissingAction } from '../../../../../types';
import { useConfigContext } from '../../../../../core/ConfigContext';
import { useFetch } from '../../../../../hooks/useFetch';
import { GrantActionsEmbedded } from '../GrantActionsEmbedded/GrantActionsEmbedded';
import { EMPTY_OBJECT } from '../../../../../utils';
import { GrantActionsHosted } from '../GrantActionsHosted/GrantActionsHosted';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import './GrantActions.scss';
import { useMissingActionsPolling } from './hooks/useMissingActionsPolling';

const CLASSNAMES = {
    actionsTitleSkeleton: 'adyen-pe-grant-actions__actions-title-skeleton',
    actionsDescriptionSkeleton: 'adyen-pe-grant-actions__actions-description-skeleton',
};

type GrantActionsProps = {
    grantId: string;
    missingActions: IMissingAction[];
    offerExpiresAt?: string;
    className?: string;
    onComplete: () => void;
};

export const GrantActions: FunctionalComponent<GrantActionsProps> = ({
    grantId,
    missingActions: initialMissingActions,
    offerExpiresAt,
    className,
    onComplete,
}) => {
    const { getOnboardingConfiguration } = useConfigContext().endpoints;
    const { missingActions, isPollingComplete, forcePollingComplete } = useMissingActionsPolling({ grantId, initialMissingActions });

    const onboardingConfigurationQuery = useFetch({
        fetchOptions: {
            enabled: isPollingComplete && !!missingActions.length,
            onError: forcePollingComplete,
        },
        queryFn: useCallback(async () => {
            return getOnboardingConfiguration?.(EMPTY_OBJECT);
        }, [getOnboardingConfiguration]),
    });

    if (!missingActions.length) {
        return null;
    }

    if (!isPollingComplete || onboardingConfigurationQuery.isFetching) {
        return (
            <Alert
                className={className}
                type={AlertTypeOption.WARNING}
                title={<div className={CLASSNAMES.actionsTitleSkeleton}></div>}
                description={<div className={CLASSNAMES.actionsDescriptionSkeleton}></div>}
            />
        );
    }

    return onboardingConfigurationQuery.data ? (
        <GrantActionsEmbedded
            className={className}
            expirationDate={offerExpiresAt}
            legalEntityId={onboardingConfigurationQuery.data.legalEntityId}
            missingActions={missingActions}
            onComplete={onComplete}
        />
    ) : (
        <GrantActionsHosted missingActions={missingActions} expirationDate={offerExpiresAt} className={className} />
    );
};

// packages/domains/capital/vue/src/CapitalOverview/components/GrantActions/GrantActions.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { BentoAlert } from '@adyen/bento-vue3';
import { useConfigContext } from '@integration-components/core/vue';
import type { IOnboardingConfiguration, IMissingAction } from '@integration-components/types';
import { EMPTY_OBJECT, isFunction } from '@integration-components/utils';
import GrantActionsEmbedded from '../GrantActionsEmbedded/GrantActionsEmbedded.vue';
import GrantActionsHosted from '../GrantActionsHosted/GrantActionsHosted.vue';
import { useMissingActionsPolling } from '../../composables/useMissingActionsPolling';
import styles from './GrantActions.module.scss';

const props = defineProps<{
    className?: string;
    grantId: string;
    missingActions: IMissingAction[];
    offerExpiresAt?: string;
}>();

const emit = defineEmits<{
    complete: [];
}>();

const config = useConfigContext();
const onboardingConfiguration = ref<IOnboardingConfiguration>();
const isFetchingOnboardingConfiguration = ref(false);
const { forcePollingComplete, isPollingComplete, missingActions } = useMissingActionsPolling({
    grantId: () => props.grantId,
    initialMissingActions: () => props.missingActions,
});
const getOnboardingConfiguration = computed(() => config.endpoints.getOnboardingConfiguration);

const fetchOnboardingConfiguration = async () => {
    const endpoint = getOnboardingConfiguration.value;

    if (!isFunction(endpoint)) {
        return;
    }

    isFetchingOnboardingConfiguration.value = true;

    try {
        onboardingConfiguration.value = await endpoint(EMPTY_OBJECT);
    } catch {
        forcePollingComplete();
    } finally {
        isFetchingOnboardingConfiguration.value = false;
    }
};

watch(
    () => [isPollingComplete.value, missingActions.value.length] as const,
    ([isComplete, missingActionsLength]) => {
        if (isComplete && missingActionsLength) {
            void fetchOnboardingConfiguration();
        }
    },
    { immediate: true }
);
</script>

<template>
    <template v-if="missingActions.length">
        <BentoAlert v-if="!isPollingComplete || isFetchingOnboardingConfiguration" :class="props.className" type="warning">
            <div :class="styles.actionsTitleSkeleton" />
            <template #description>
                <div :class="styles.actionsDescriptionSkeleton" />
            </template>
        </BentoAlert>
        <GrantActionsEmbedded
            v-else-if="onboardingConfiguration"
            :class-name="props.className"
            :expiration-date="props.offerExpiresAt"
            :legal-entity-id="onboardingConfiguration.legalEntityId"
            :missing-actions="missingActions"
            @complete="emit('complete')"
        />
        <GrantActionsHosted v-else :class-name="props.className" :expiration-date="props.offerExpiresAt" :missing-actions="missingActions" />
    </template>
</template>
