// packages/domains/transactions/preact/src/TransactionDetails/components/PaymentRefund/PaymentRefundAmount.tsx
import {
    TX_DATA_CONTAINER,
    TX_DATA_INPUT,
    TX_DATA_INPUT_CONTAINER,
    TX_DATA_INPUT_CONTAINER_SHORT,
    TX_DATA_INPUT_CONTAINER_TEXT,
    TX_DATA_INPUT_CONTAINER_WITH_ERROR,
    TX_DATA_INPUT_HEAD,
} from '../../constants';
import cx from 'classnames';
import { memo } from 'preact/compat';
import { Tag } from '@integration-components/ui-components-preact/Tag/Tag';
import { TagVariant } from '@integration-components/ui-components-preact/Tag/types';
import { ARIA_ERROR_SUFFIX } from '@integration-components/core/Errors/constants';
import { getDecimalAmount, getDivider, normalizeAmountInput } from '@integration-components/core/Localization/amount/amount-util';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import { useCallback, useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { useCoreContext } from '@integration-components/core/preact';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import InputBase from '@integration-components/ui-components-preact/FormFields/InputBase';
import { useUniqueId } from '@integration-components/hooks-preact';
import Icon from '@integration-components/ui-components-preact/Icon';

interface PaymentRefundAmountProps {
    currency: string;
    disabled?: boolean;
    onChange?: (value: number) => void;
    value: string | number;
}

const PaymentRefundAmount = memo(({ currency, disabled, onChange, value }: PaymentRefundAmountProps) => {
    const { i18n } = useCoreContext();
    const inputIdentifier = useUniqueId();
    const labelIdentifier = useUniqueId();

    const currencyExponent = Math.log10(getDivider(currency));
    const refundableAmount = parseInt(`${value}`, 10);
    const formattedAmount = getDecimalAmount(refundableAmount, currency).toFixed(currencyExponent);

    const [refundAmount, setRefundAmount] = useState<string | number>(formattedAmount);
    const [validationError, setValidationError] = useState<keyof typeof errorMessages>();

    const errorMessages = useMemo(() => {
        const values = { amount: i18n.amount(refundableAmount, currency) };
        return {
            excess: i18n.get('transactions.details.refund.inputs.amount.errors.excess', { values }),
            negative: i18n.get('transactions.details.refund.inputs.amount.errors.negative'),
            required: i18n.get('transactions.details.refund.inputs.amount.errors.required'),
        } as const;
    }, [i18n, currency, refundableAmount]);

    const errorMessage = validationError && errorMessages[validationError];
    const inputLabel = useMemo(() => i18n.get('transactions.details.refund.inputs.amount.label'), [i18n]);
    const inputElementRef = useRef<HTMLInputElement>(null);

    const onInput = useCallback(
        (target: HTMLInputElement) => {
            let error: typeof validationError;
            const { displayValue: value, amount, localeDecimalSeparator } = normalizeAmountInput(target.value, i18n.locale, currency);
            const isInvalid = Number.isNaN(Number.parseFloat(value.replace(localeDecimalSeparator, '.')));

            if (isInvalid || value === '') {
                error = 'required';
            } else if (amount < 0) {
                error = 'negative';
            } else if (amount > refundableAmount) {
                error = 'excess';
            }

            target.value = value;
            setRefundAmount(value);
            setValidationError(error);
            onChange?.(error ? 0 : amount);
        },
        [currency, refundableAmount, onChange, i18n.locale]
    );

    const cachedRefundableAmountRef = useRef<number>();

    useEffect(() => {
        if (cachedRefundableAmountRef.current !== refundableAmount) {
            cachedRefundableAmountRef.current = refundableAmount;
        } else if (disabled && validationError && inputElementRef.current) {
            inputElementRef.current.value = formattedAmount;
        } else return;

        if (inputElementRef.current) {
            onInput(inputElementRef.current);
        }
    }, [onInput, disabled, formattedAmount, refundableAmount, validationError]);

    return (
        <div className={TX_DATA_CONTAINER}>
            <div className={TX_DATA_INPUT_HEAD}>
                <div id={labelIdentifier}>
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                        {inputLabel}
                    </Typography>
                </div>
            </div>

            <div
                className={cx({
                    [TX_DATA_INPUT_CONTAINER]: true,
                    [TX_DATA_INPUT_CONTAINER_SHORT]: true,
                    [TX_DATA_INPUT_CONTAINER_TEXT]: true,
                    [TX_DATA_INPUT_CONTAINER_WITH_ERROR]: errorMessage,
                })}
            >
                <label htmlFor={inputIdentifier} aria-labelledby={labelIdentifier}>
                    {currency && <Tag label={currency} variant={TagVariant.DEFAULT} />}
                    <InputBase
                        min={0}
                        type="number"
                        className={TX_DATA_INPUT}
                        disabled={disabled}
                        lang={i18n.locale}
                        onInput={evt => onInput(evt.currentTarget)}
                        value={refundAmount}
                        uniqueId={inputIdentifier}
                        ref={inputElementRef}
                    />
                </label>
                {errorMessage && (
                    <div className="adyen-pe-input__refund-invalid-value" id={`${inputIdentifier}${ARIA_ERROR_SUFFIX}`}>
                        <Icon name="cross-circle-fill" />
                        <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                            {errorMessage}
                        </Typography>
                    </div>
                )}
            </div>
        </div>
    );
});

export default PaymentRefundAmount;

// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentRefund/PaymentRefundAmount.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoInputField, BentoTypography } from '@adyen/bento-vue3';
import {
    TX_DATA_CONTAINER,
    TX_DATA_INPUT_CONTAINER,
    TX_DATA_INPUT_CONTAINER_SHORT,
    TX_DATA_INPUT_CONTAINER_TEXT,
    TX_DATA_INPUT_CONTAINER_WITH_ERROR,
    TX_DATA_INPUT_HEAD,
} from '../../../../../domain/src';
import { getDecimalAmount, getDivider, normalizeAmountInput } from '@integration-components/core/Localization/amount/amount-util';
import { useUniqueId } from '@integration-components/composables-vue';

const props = defineProps<{
    currency: string;
    disabled?: boolean;
    value: string | number;
}>();

const emit = defineEmits<{
    change: [value: number];
}>();

const { i18n } = useCoreContext();
const inputId = useUniqueId();

const currencyExponent = computed(() => Math.log10(getDivider(props.currency)));
const refundableAmount = computed(() => parseInt(`${props.value}`, 10));
const formattedDefault = computed(() => getDecimalAmount(refundableAmount.value, props.currency).toFixed(currencyExponent.value));

const inputValue = ref<string>(formattedDefault.value);
const validationError = ref<'excess' | 'negative' | 'required' | undefined>(undefined);

const errorMessages = computed(() => {
    const values = { amount: i18n.amount(refundableAmount.value, props.currency) };
    return {
        excess: i18n.get('transactions.details.refund.inputs.amount.errors.excess', { values }),
        negative: i18n.get('transactions.details.refund.inputs.amount.errors.negative'),
        required: i18n.get('transactions.details.refund.inputs.amount.errors.required'),
    };
});

const errorMessage = computed(() => validationError.value && errorMessages.value[validationError.value]);

const containerClass = computed(() => ({
    [TX_DATA_INPUT_CONTAINER]: true,
    [TX_DATA_INPUT_CONTAINER_SHORT]: true,
    [TX_DATA_INPUT_CONTAINER_TEXT]: true,
    [TX_DATA_INPUT_CONTAINER_WITH_ERROR]: !!errorMessage.value,
}));

watch(
    () => props.value,
    () => {
        inputValue.value = formattedDefault.value;
        validationError.value = undefined;
        emit('change', refundableAmount.value);
    },
    { immediate: true }
);

function onInput(rawValue: string) {
    const { displayValue: value, amount } = normalizeAmountInput(rawValue, i18n.locale, props.currency);
    const isInvalid = Number.isNaN(Number.parseFloat(rawValue));
    let error: typeof validationError.value;

    if (isInvalid || value === '') {
        error = 'required';
    } else if (amount < 0) {
        error = 'negative';
    } else if (amount > refundableAmount.value) {
        error = 'excess';
    }

    inputValue.value = value;
    validationError.value = error;
    emit('change', error ? 0 : amount);
}
</script>

<template>
    <div :class="TX_DATA_CONTAINER">
        <div :class="TX_DATA_INPUT_HEAD">
            <BentoTypography variant="body" stronger>{{ i18n.get('transactions.details.refund.inputs.amount.label') }}</BentoTypography>
        </div>
        <div :class="containerClass">
            <BentoInputField
                :id="inputId"
                variant="static-value"
                type="number"
                :disabled="props.disabled"
                :value="inputValue"
                :min="0"
                :errorMessage="errorMessage || undefined"
                :lang="i18n.locale"
                @input="onInput"
            >
                <template v-if="props.currency" #staticValue>{{ props.currency }}</template>
            </BentoInputField>
        </div>
    </div>
</template>
