// packages/domains/transactions/preact/src/TransactionDetails/components/PaymentRefund/PaymentRefundActions.tsx
import cx from 'classnames';
import { useEffect, useMemo } from 'preact/hooks';
import { RefundReason, RefundResult } from '../../types';
import { ButtonVariant } from '@integration-components/types';
import { ButtonActionsLayoutBasic } from '@integration-components/types';
import { TX_DATA_ACTION_BAR, TX_DATA_CONTAINER, sharedTransactionDetailsEventProperties } from '../../constants';
import ButtonActions from '@integration-components/ui-components-preact/Button/ButtonActions/ButtonActions';
import { useConfigContext, useCoreContext, useEventDispatcherContext } from '@integration-components/core/preact';
import useMutation from '@integration-components/hooks-preact/useMutation/useMutation';

export interface PaymentRefundActionsProps {
    beginRefund: () => void;
    currency: string;
    disabled: boolean;
    maxAmount: number;
    refundAmount: number;
    refundedAmount: number;
    refundingAmounts: readonly number[];
    refundReason: RefundReason;
    setRefundInProgress: (inProgress: boolean) => void;
    setRefundResult: (result: RefundResult) => void;
    showDetails: () => void;
    transactionId: string;
}

const PaymentRefundActions = ({
    beginRefund,
    currency,
    disabled,
    maxAmount,
    refundAmount,
    refundedAmount,
    refundingAmounts,
    refundReason,
    setRefundInProgress,
    setRefundResult,
    showDetails,
    transactionId,
}: PaymentRefundActionsProps) => {
    const { initiateRefund } = useConfigContext().endpoints;
    const { isLoading, mutate: refundTransaction } = useMutation({ queryFn: initiateRefund });
    const { i18n } = useCoreContext();

    const amountWithinRange = refundAmount > 0 && refundAmount <= maxAmount;
    const isFullRefundAmount = refundedAmount === 0 && refundingAmounts.length === 0 && refundAmount === maxAmount;
    const refundDisabled = disabled || isLoading || !amountWithinRange;

    const backButtonLabel = useMemo(() => i18n.get('transactions.details.refund.actions.back'), [i18n]);

    const refundButtonLabelsWithoutAmount = useMemo(
        () => ({
            idle: i18n.get('transactions.details.refund.actions.refund.labels.payment'),
            inProgress: `${i18n.get('transactions.details.refund.actions.refund.labels.inProgress')}..`,
        }),
        [i18n]
    );

    const refundButtonLabelWithAmount = useMemo(() => {
        const values = { amount: i18n.amount(refundAmount, currency) };
        return i18n.get('transactions.details.refund.actions.refund.labels.amount', { values });
    }, [i18n, currency, refundAmount]);

    const refundButtonLabel = isLoading
        ? refundButtonLabelsWithoutAmount.inProgress
        : amountWithinRange
          ? refundButtonLabelWithAmount
          : refundButtonLabelsWithoutAmount.idle;

    const userEvents = useEventDispatcherContext();

    const primaryAction = {
        disabled: refundDisabled,
        event: async () => {
            if (refundDisabled) return;

            beginRefund();

            userEvents.addEvent?.('Completed refund', {
                ...sharedTransactionDetailsEventProperties,
                isFullRefund: isFullRefundAmount,
                refundReason,
            });

            try {
                const path = { transactionId };
                const payload = { amount: { currency, value: refundAmount }, refundReason };
                await refundTransaction({ contentType: 'application/json', body: payload }, { path });
                setRefundResult('done');
            } catch {
                setRefundResult('error');
            }
        },
        state: isLoading ? 'loading' : undefined,
        title: refundButtonLabel,
        variant: ButtonVariant.PRIMARY,
        ariaLabel: isLoading ? refundButtonLabelWithAmount : refundButtonLabel,
    } as const;

    const secondaryAction = {
        disabled: disabled,
        event: showDetails,
        title: backButtonLabel,
        variant: ButtonVariant.SECONDARY,
    } as const;

    useEffect(() => setRefundInProgress(isLoading), [isLoading, setRefundInProgress]);

    return (
        <div className={cx(TX_DATA_CONTAINER, TX_DATA_ACTION_BAR)}>
            <ButtonActions actions={[primaryAction, secondaryAction]} layout={ButtonActionsLayoutBasic.BUTTONS_END} />
        </div>
    );
};

export default PaymentRefundActions;

// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentRefund/PaymentRefundActions.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useCoreContext, useConfigContext, useEventDispatcherContext } from '@integration-components/core/vue';
import { BentoButtonActions } from '@adyen/bento-vue3';
import { TX_DATA_ACTION_BAR, TX_DATA_CONTAINER, sharedTransactionDetailsEventProperties } from '@integration-components/transactions/domain';
import { isFunction } from '@integration-components/utils';
import type { RefundReason, RefundResult } from '@integration-components/transactions/domain';

const props = defineProps<{
    beginRefund: () => void;
    currency: string;
    disabled: boolean;
    maxAmount: number;
    refundAmount: number;
    refundedAmount: number;
    refundingAmounts: readonly number[];
    refundReason: RefundReason;
    setRefundInProgress: (inProgress: boolean) => void;
    setRefundResult: (result: RefundResult) => void;
    showDetails: () => void;
    transactionId: string;
}>();

const { i18n } = useCoreContext();
const config = useConfigContext();
const userEvents = useEventDispatcherContext();

const isLoading = ref(false);

const amountWithinRange = computed(() => props.refundAmount > 0 && props.refundAmount <= props.maxAmount);
const isFullRefund = computed(() => props.refundedAmount === 0 && props.refundingAmounts.length === 0 && props.refundAmount === props.maxAmount);
const refundDisabled = computed(() => props.disabled || isLoading.value || !amountWithinRange.value);

const refundButtonLabel = computed(() => {
    if (isLoading.value) {
        return `${i18n.get('transactions.details.refund.actions.refund.labels.inProgress')}..`;
    }
    if (amountWithinRange.value) {
        const values = { amount: i18n.amount(props.refundAmount, props.currency) };
        return i18n.get('transactions.details.refund.actions.refund.labels.amount', { values });
    }
    return i18n.get('transactions.details.refund.actions.refund.labels.payment');
});

watch(isLoading, v => props.setRefundInProgress(v));

async function handleRefund() {
    if (refundDisabled.value) return;
    const fn = config.endpoints.initiateRefund;
    if (!isFunction(fn)) return;

    props.beginRefund();
    userEvents.addEvent?.('Completed refund', {
        ...sharedTransactionDetailsEventProperties,
        isFullRefund: isFullRefund.value,
        refundReason: props.refundReason,
    });

    isLoading.value = true;
    try {
        await fn(
            {
                contentType: 'application/json',
                body: { amount: { currency: props.currency, value: props.refundAmount }, refundReason: props.refundReason },
            },
            { path: { transactionId: props.transactionId } }
        );
        props.setRefundResult('done');
    } catch {
        props.setRefundResult('error');
    } finally {
        isLoading.value = false;
    }
}

const primaryAction = computed(() => ({
    disabled: refundDisabled.value,
    event: handleRefund,
    title: refundButtonLabel.value,
    variant: 'primary' as const,
    state: isLoading.value ? ('loading' as const) : undefined,
}));

const secondaryAction = computed(() => ({
    disabled: props.disabled,
    event: props.showDetails,
    title: i18n.get('transactions.details.refund.actions.back'),
    variant: 'secondary' as const,
}));
</script>

<template>
    <div :class="[TX_DATA_CONTAINER, TX_DATA_ACTION_BAR]">
        <BentoButtonActions :actions="[primaryAction, secondaryAction]" />
    </div>
</template>
