// packages/domains/payByLink/preact/src/PaymentLinkCreation/components/PaymentLinkCreationFormContainer/FormStepRenderer.tsx
import { LinkCreationFormStep } from '../types';
import { CustomerDetailsForm } from '../Form/CustomerDetailsForm/CustomerDetailsForm';
import { PaymentDetailsForm } from '../Form/PaymentDetailsForm/PaymentDetailsForm';
import { FormSummary } from '../Form/Summary/FormSummary';
import { StoreForm } from '../Form/StoreForm/StoreForm';
import { Dispatch, SetStateAction } from 'preact/compat';
import { IPaymentLinkSettings, IPaymentLinkStore, IPaymentLinkConfiguration, IPaymentLinkCountry } from '@integration-components/types';
import { StateUpdater } from 'preact/hooks';
import { StoreIds } from '../../../PaymentLinksOverview/types';

type FormStepRendererProps = {
    setShowTermsAndConditions: Dispatch<StateUpdater<boolean>>;
    currentFormStep: LinkCreationFormStep;
    settingsData?: IPaymentLinkSettings;
    storeIds?: StoreIds;
    storesData?: {
        data: IPaymentLinkStore[];
    };
    selectItems: {
        id: string;
        name: string;
    }[];
    termsAndConditionsProvisioned: boolean;
    configurationData?: IPaymentLinkConfiguration;
    isSameAddress: boolean;
    setIsSameAddress: Dispatch<SetStateAction<boolean>>;
    countriesData?: {
        data: IPaymentLinkCountry[];
    };
    isFetchingCountries: boolean;
    countryDatasetData?: Array<{ id: string; name: string }>;
    isFetchingCountryDataset: boolean;
};

export const FormStepRenderer = ({
    setShowTermsAndConditions,
    currentFormStep,
    settingsData,
    storeIds,
    storesData,
    selectItems,
    termsAndConditionsProvisioned,
    configurationData,
    isSameAddress,
    setIsSameAddress,
    countriesData,
    isFetchingCountries,
    countryDatasetData,
    isFetchingCountryDataset,
}: FormStepRendererProps) => {
    switch (currentFormStep) {
        case 'store':
            return (
                <StoreForm
                    setShowTermsAndConditions={setShowTermsAndConditions}
                    settingsData={settingsData}
                    storeIds={storeIds}
                    storesData={storesData?.data}
                    selectItems={selectItems}
                    termsAndConditionsProvisioned={termsAndConditionsProvisioned}
                />
            );
        case 'payment':
            return <PaymentDetailsForm configuration={configurationData} />;
        case 'customer':
            return (
                <CustomerDetailsForm
                    isSameAddress={isSameAddress}
                    setIsSameAddress={setIsSameAddress}
                    countriesData={countriesData}
                    isFetchingCountries={isFetchingCountries}
                    countryDatasetData={countryDatasetData}
                    isFetchingCountryDataset={isFetchingCountryDataset}
                />
            );
        case 'summary':
            return <FormSummary countryDatasetData={countryDatasetData} />;
        default:
            return <PaymentDetailsForm configuration={configurationData} />;
    }
};

// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/PaymentLinkCreationFormContainer/FormStepRenderer.vue
<script setup lang="ts">
import StoreForm from '../Form/StoreForm/StoreForm.vue';
import PaymentDetailsForm from '../Form/PaymentDetailsForm/PaymentDetailsForm.vue';
import CustomerDetailsForm from '../Form/CustomerDetailsForm/CustomerDetailsForm.vue';
import FormSummary from '../Form/Summary/FormSummary.vue';
import type { IPaymentLinkConfiguration, IPaymentLinkCountry, IPaymentLinkSettings, IPaymentLinkStore } from '@integration-components/types';

const props = defineProps<{
    currentFormStep: string;
    selectItems: { id: string; name: string; description?: string }[];
    settingsData?: IPaymentLinkSettings;
    storesData?: { data?: IPaymentLinkStore[] };
    configurationData?: IPaymentLinkConfiguration;
    countriesData?: { data?: IPaymentLinkCountry[] };
    countryDatasetData?: { id: string; name: string }[];
    isFetchingCountries: boolean;
    isFetchingCountryDataset: boolean;
    termsAndConditionsProvisioned: boolean;
    canModifySettings: boolean;
    isSameAddress: boolean;
    onContactSupport?: () => void;
}>();

const emit = defineEmits<{
    'update:isSameAddress': [value: boolean];
    setupTermsAndConditions: [];
}>();
</script>

<template>
    <StoreForm
        v-if="props.currentFormStep === 'store'"
        :select-items="props.selectItems"
        :settings-data="props.settingsData"
        :stores-data="props.storesData?.data"
        :terms-and-conditions-provisioned="props.termsAndConditionsProvisioned"
        :can-modify-settings="props.canModifySettings"
        @setup-terms-and-conditions="emit('setupTermsAndConditions')"
    />
    <PaymentDetailsForm v-else-if="props.currentFormStep === 'payment'" :configuration="props.configurationData" />
    <CustomerDetailsForm
        v-else-if="props.currentFormStep === 'customer'"
        :is-same-address="props.isSameAddress"
        :countries-data="props.countriesData"
        :country-dataset-data="props.countryDatasetData"
        :is-fetching-countries="props.isFetchingCountries"
        :is-fetching-country-dataset="props.isFetchingCountryDataset"
        @update:is-same-address="(value: boolean) => emit('update:isSameAddress', value)"
    />
    <FormSummary v-else-if="props.currentFormStep === 'summary'" :select-items="props.selectItems" :country-dataset-data="props.countryDatasetData" />
</template>
