// adyen-platform-experience-web-vue/src/components/TransactionsOverview/components/AmountSkeleton.vue
<script setup lang="ts">
const props = defineProps<{
    isLoading?: boolean;
    hasMargin?: boolean;
    width?: string;
}>();

const BASE_CLASS = 'adyen-pe-amount-skeleton';
</script>

<template>
    <span
        :class="[
            BASE_CLASS,
            { [`${BASE_CLASS}--loading`]: props.isLoading },
            { [`${BASE_CLASS}--margin`]: props.hasMargin },
        ]"
        :style="{ width: props.width }"
    />
</template>

// packages/lib/src/components/external/Transactions/components/TransactionTotals/AmountSkeleton.tsx
import cx from 'classnames';

const AmountSkeleton = ({ isLoading }: { isLoading: boolean }) => {
    return (
        <span
            className={cx('adyen-fp-transactions-total__skeleton', {
                'adyen-fp--transactions-total-skeleton--loading': isLoading,
            })}
        ></span>
    );
};

export default AmountSkeleton;
