// packages/domains/transactions/preact/src/TransactionDetails/components/PaymentDetails/PaymentDetailsProperties.tsx
import { memo } from 'preact/compat';
import { useCallback, useMemo } from 'preact/hooks';
import { TranslationKey } from '@integration-components/core';
import { TransactionDetails, TransactionDetailsProps } from '../../types';
import { StructuredListProps } from '@integration-components/ui-primitives-preact/StructuredList/types';
import { getTransactionRefundReason } from '@integration-components/transactions/domain';
import { isCustomDataObject } from '@integration-components/ui-primitives-preact/DataGrid/components/TableCells';
import { TypographyElement, TypographyVariant } from '@integration-components/ui-primitives-preact/Typography/types';
import { TX_DATA_LABEL, TX_DATA_LIST, TX_DETAILS_FIELDS_REMAPS, sharedTransactionDetailsEventProperties } from '../../constants';
import { normalizeCustomFields } from '@integration-components/utils';
import { useCoreContext, useEventDispatcherContext } from '@integration-components/core/preact';
import StructuredList from '@integration-components/ui-primitives-preact/StructuredList';
import Typography from '@integration-components/ui-primitives-preact/Typography/Typography';
import Icon from '@integration-components/ui-primitives-preact/DataGrid/components/Icon';
import CopyText from '@integration-components/ui-primitives-preact/CopyText/CopyText';
import Link from '@integration-components/ui-primitives-preact/Link/Link';
import cx from 'classnames';

const copyButtonAnalyticsEventProperties = {
    ...sharedTransactionDetailsEventProperties,
    sectionName: 'Details',
    label: 'Copy button',
} as const;

const paymentDataKeys = {
    account: 'transactions.details.fields.account',
    id: 'transactions.details.fields.referenceID',
    merchantReference: 'transactions.details.fields.merchantReference',
    pspReference: 'transactions.details.fields.pspReference',
    refundPspReference: 'transactions.details.fields.refundPspReference',
    refundReason: 'transactions.details.fields.refundReason',
} satisfies Record<string, TranslationKey>;

const paymentDataCopyButtonKeys = {
    id: 'transactions.details.actions.copyReferenceID',
    merchantReference: 'transactions.details.actions.copyMerchantReference',
    pspReference: 'transactions.details.actions.copyPspReference',
} satisfies Record<string, TranslationKey>;

const SKIP_ITEM: StructuredListProps['items'][number] = null!;

export interface PaymentDetailsPropertiesProps {
    dataCustomization?: TransactionDetailsProps['dataCustomization'];
    extraFields: Record<string, any> | undefined;
    transaction: TransactionDetails;
}

const PaymentDetailsProperties = ({ dataCustomization, extraFields, transaction }: PaymentDetailsPropertiesProps) => {
    const { i18n } = useCoreContext();

    const standardPropertiesList = useMemo<StructuredListProps['items']>(() => {
        const { balanceAccount, category, id, merchantReference, paymentPspReference, refundMetadata } = transaction;
        const account = balanceAccount?.description || balanceAccount?.id;
        const isRefundTransaction = category === 'Refund';

        const customizedFields = normalizeCustomFields(dataCustomization?.details?.fields, TX_DETAILS_FIELDS_REMAPS, transaction);

        const listItems: StructuredListProps['items'] = [
            // balance account
            account ? { id: 'account', key: paymentDataKeys.account, value: account } : SKIP_ITEM,

            // refund reason
            isRefundTransaction && refundMetadata?.refundReason
                ? {
                      id: 'refundReason',
                      key: paymentDataKeys.refundReason,
                      value: getTransactionRefundReason(i18n, refundMetadata.refundReason),
                  }
                : SKIP_ITEM,

            // reference id
            {
                id: 'id',
                key: paymentDataKeys.id,
                value: (
                    <PaymentDetailsProperties.CopyText
                        copyButtonAriaLabelKey={paymentDataCopyButtonKeys.id}
                        trackingName="Reference ID"
                        textToCopy={id}
                    />
                ),
            },

            // merchant reference
            merchantReference
                ? {
                      id: 'merchantReference',
                      key: paymentDataKeys.merchantReference,
                      value: (
                          <PaymentDetailsProperties.CopyText
                              copyButtonAriaLabelKey={paymentDataCopyButtonKeys.merchantReference}
                              trackingName="Merchant reference"
                              textToCopy={merchantReference}
                          />
                      ),
                  }
                : SKIP_ITEM,

            // payment psp reference
            paymentPspReference
                ? {
                      id: 'paymentPspReference',
                      key: paymentDataKeys.pspReference,
                      value: (
                          <PaymentDetailsProperties.CopyText
                              copyButtonAriaLabelKey={paymentDataCopyButtonKeys.pspReference}
                              trackingName="PSP reference"
                              textToCopy={paymentPspReference}
                          />
                      ),
                  }
                : SKIP_ITEM,

            // refund psp reference
            isRefundTransaction && refundMetadata?.refundPspReference
                ? {
                      id: 'refundPspReference',
                      key: paymentDataKeys.refundPspReference,
                      value: refundMetadata.refundPspReference,
                  }
                : SKIP_ITEM,
        ] as const;

        const isVisibleField = customizedFields
            ? (id: string) => customizedFields.find(field => field.key === id)?.visibility !== 'hidden'
            : () => true;

        return listItems.filter(item => item?.id && isVisibleField(item.id));
    }, [i18n, dataCustomization, transaction]);

    const customPropertiesList = useMemo<StructuredListProps['items']>(
        () =>
            Object.entries(extraFields || {})
                .filter(([, value]) => value?.type !== 'button')
                .map(([key, value]) => ({
                    key: key as TranslationKey,
                    value: isCustomDataObject(value) ? value.value : value,
                    type: isCustomDataObject(value) ? value.type : 'text',
                    config: isCustomDataObject(value) ? value.config : undefined,
                })),
        [extraFields]
    );

    const listItems = useMemo(() => [...standardPropertiesList, ...customPropertiesList], [customPropertiesList, standardPropertiesList]);

    const renderListPropertyLabel = useCallback<NonNullable<StructuredListProps['renderLabel']>>(
        label => <div className={TX_DATA_LABEL}>{label}</div>,
        []
    );

    const renderListPropertyValue = useCallback<NonNullable<StructuredListProps['renderValue']>>((val, key, type, config) => {
        if (config) {
            switch (type) {
                case 'icon':
                    return (
                        <div className={cx(config.className, 'adyen-pe-transaction-data__list-icon-value')}>
                            <Icon url={config.src} alt={config.alt || val} />
                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                                {' '}
                                {val}
                            </Typography>
                        </div>
                    );
                case 'link':
                    return (
                        <Link classNames={[cx(config.className)]} href={config.href} target={config.target || '_blank'}>
                            {val}
                        </Link>
                    );
            }
        }
        return (
            <Typography el={TypographyElement.DIV} variant={TypographyVariant.BODY} className={cx(config?.className)}>
                {val}
            </Typography>
        );
    }, []);

    return (
        <StructuredList
            align="start"
            layout="5-7"
            items={listItems}
            classNames={TX_DATA_LIST}
            renderLabel={renderListPropertyLabel}
            renderValue={renderListPropertyValue}
        />
    );
};

interface PaymentDetailsPropertiesCopyTextProps {
    copyButtonAriaLabelKey: TranslationKey;
    textToCopy: string;
    trackingName?: string;
}

PaymentDetailsProperties.CopyText = memo(({ trackingName, ...copyTextProps }: PaymentDetailsPropertiesCopyTextProps) => {
    const userEvents = useEventDispatcherContext();

    const onCopyText = useCallback(() => {
        if (trackingName) {
            userEvents.addEvent?.('Clicked button', {
                ...copyButtonAnalyticsEventProperties,
                subSectionName: trackingName,
            });
        }
    }, [trackingName, userEvents]);

    return <CopyText {...copyTextProps} onCopyText={onCopyText} showCopyTextTooltip={false} type="Default" />;
});

export default memo(PaymentDetailsProperties);

// adyen-platform-experience-web-vue/src/components/TransactionDetails/PaymentDetails/PaymentDetailsProperties.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoStructuredList, BentoStructuredListItem, BentoTypography, BentoLink } from '@adyen/bento-vue3';
import { useCoreContext } from '../../../core/Context';
import { TX_DATA_LABEL, TX_DATA_LIST, TX_DETAILS_FIELDS_REMAPS } from '../constants';
import { normalizeCustomFields } from '../utils';
import { REFUND_REASONS_KEYS } from '../constants';
import type { TransactionDetails, TransactionDetailsProps } from '../types';

const props = defineProps<{
    dataCustomization?: TransactionDetailsProps['dataCustomization'];
    extraFields: Record<string, any> | undefined;
    transaction: TransactionDetails;
}>();

const { i18n } = useCoreContext();

function getTransactionRefundReason(reason: string): string {
    const key = REFUND_REASONS_KEYS[reason];
    if (key && i18n.has(key)) return i18n.get(key);
    return reason;
}

interface ListItem {
    id?: string;
    label: string;
    value: string;
    copyable?: boolean;
    type?: string;
    config?: Record<string, any>;
}

const standardProperties = computed<ListItem[]>(() => {
    const { balanceAccount, category, id, merchantReference, paymentPspReference, refundMetadata } = props.transaction;
    const account = balanceAccount?.description || balanceAccount?.id;
    const isRefundTransaction = category === 'Refund';

    const customizedFields = normalizeCustomFields(props.dataCustomization?.details?.fields, TX_DETAILS_FIELDS_REMAPS, props.transaction);
    const isVisibleField = customizedFields
        ? (fieldId: string) => customizedFields.find(field => field.key === fieldId)?.visibility !== 'hidden'
        : () => true;

    const items: (ListItem | null)[] = [
        account && isVisibleField('account') ? { id: 'account', label: i18n.get('transactions.details.fields.account'), value: account } : null,

        isRefundTransaction && refundMetadata?.refundReason && isVisibleField('refundReason')
            ? {
                  id: 'refundReason',
                  label: i18n.get('transactions.details.fields.refundReason'),
                  value: getTransactionRefundReason(refundMetadata.refundReason),
              }
            : null,

        isVisibleField('id') ? { id: 'id', label: i18n.get('transactions.details.fields.referenceID'), value: id, copyable: true } : null,

        merchantReference && isVisibleField('merchantReference')
            ? { id: 'merchantReference', label: i18n.get('transactions.details.fields.merchantReference'), value: merchantReference, copyable: true }
            : null,

        paymentPspReference && isVisibleField('paymentPspReference')
            ? { id: 'paymentPspReference', label: i18n.get('transactions.details.fields.pspReference'), value: paymentPspReference, copyable: true }
            : null,

        isRefundTransaction && refundMetadata?.refundPspReference && isVisibleField('refundPspReference')
            ? {
                  id: 'refundPspReference',
                  label: i18n.get('transactions.details.fields.refundPspReference'),
                  value: refundMetadata.refundPspReference,
              }
            : null,
    ];

    return items.filter((item): item is ListItem => item !== null);
});

const customProperties = computed<ListItem[]>(() => {
    if (!props.extraFields) return [];
    return Object.entries(props.extraFields)
        .filter(([, value]) => value?.type !== 'button')
        .map(([key, value]) => {
            const isCustomObj = value && typeof value === 'object' && 'value' in value;
            return {
                label: key,
                value: isCustomObj ? value.value : value,
                type: isCustomObj ? value.type : 'text',
                config: isCustomObj ? value.config : undefined,
            };
        });
});

const allProperties = computed(() => [...standardProperties.value, ...customProperties.value]);

function copyToClipboard(text: string) {
    navigator.clipboard.writeText(text).catch(() => {
        // Fallback for older browsers
        const textarea = document.createElement('textarea');
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
    });
}
</script>

<template>
    <div :class="TX_DATA_LIST">
        <bento-structured-list>
            <bento-structured-list-item v-for="item in allProperties" :key="item.id || item.label" :label="item.label">
                <template #label>
                    <div :class="TX_DATA_LABEL">{{ item.label }}</div>
                </template>
                <!-- <template #value> -->
                <template v-if="item.config?.href">
                    <bento-link :to="item.config.href" :target="item.config.target || '_blank'">
                        {{ item.value }}
                    </bento-link>
                </template>
                <template v-else>
                    <div style="display: flex; align-items: center; gap: 4px">
                        <bento-typography variant="body">{{ item.value }}</bento-typography>
                        <button
                            v-if="item.copyable"
                            style="background: none; border: none; cursor: pointer; padding: 2px; opacity: 0.6"
                            :aria-label="i18n.get('transactions.details.actions.copyReferenceID')"
                            @click="copyToClipboard(item.value)"
                        >
                            &#x2398;
                        </button>
                    </div>
                </template>
                <!-- </template> -->
            </bento-structured-list-item>
        </bento-structured-list>
    </div>
</template>
