// packages/domains/transactions/preact/src/TransactionDetails/components/PaymentDetails/PaymentDetailsStatusBox.tsx
import cx from 'classnames';
import StatusBox from '../../../../../../../../src/components/internal/StatusBox/StatusBox';
import useStatusBoxData from '../../../../../../../../src/components/internal/StatusBox/useStatusBox';
import { useCoreContext } from '@integration-components/core/preact';
import { getTransactionCategory } from '@integration-components/transactions/domain';
import { getAmountStyleForTransaction, getRefundTypeForTransaction } from '../../utils';
import { TX_DATA_AMOUNT, TX_DATA_CONTAINER, TX_DATA_TAGS, TX_STATUS_BOX } from '../../constants';
import { RefundedState, RefundType, TransactionDetails } from '../../types';
import { TagVariant } from '../../../../../../../../src/components/internal/Tag/types';
import { Tag } from '../../../../../../../../src/components/internal/Tag/Tag';
import { useMemo } from 'preact/hooks';
import { memo } from 'preact/compat';

export interface PaymentDetailsStatusBoxProps {
    refundedState: RefundedState;
    transaction: TransactionDetails;
}

const PaymentDetailsStatusBox = ({ refundedState, transaction }: PaymentDetailsStatusBoxProps) => {
    const statusBoxOptions = useStatusBoxData({
        timezone: transaction.balanceAccount?.timeZone,
        createdAt: transaction.createdAt,
        amountData: transaction.netAmount,
        paymentMethodData: transaction.paymentMethod,
        bankAccount: transaction.bankAccount,
    });

    const statusBoxClassNames = useMemo(
        () => ({
            amount: `${TX_DATA_AMOUNT}--${getAmountStyleForTransaction(transaction)}`,
        }),
        [transaction]
    );

    const statusBoxTags = useMemo(
        () => <PaymentDetailsStatusBox.StatusTags transaction={transaction} refundedState={refundedState} />,
        [transaction, refundedState]
    );

    return (
        <div className={cx(TX_DATA_CONTAINER, TX_STATUS_BOX)}>
            <StatusBox {...statusBoxOptions} classNames={statusBoxClassNames} tag={statusBoxTags} />
        </div>
    );
};

PaymentDetailsStatusBox.StatusTags = memo(({ transaction, refundedState }: PaymentDetailsStatusBoxProps) => {
    const { i18n } = useCoreContext();
    const { category } = transaction;

    const refundType = getRefundTypeForTransaction(transaction);

    return (
        <div className={TX_DATA_TAGS}>
            {/*{status && <Tag label={getTransactionStatus(i18n, status)} variant={getTagVariantForTransaction(transaction)} />}*/}
            {category && <Tag label={getTransactionCategory(i18n, category)} variant={TagVariant.DEFAULT} />}

            {/* refund type: only available for transaction.category == Refund */}
            {refundType && (
                <>
                    {refundType === RefundType.FULL && (
                        <Tag label={i18n.get('transactions.details.common.refundTypes.full')} variant={TagVariant.SUCCESS} />
                    )}
                    {refundType === RefundType.PARTIAL && (
                        <Tag label={i18n.get('transactions.details.common.refundTypes.partial')} variant={TagVariant.BLUE} />
                    )}
                </>
            )}

            {refundedState === RefundedState.FULL && (
                <Tag label={i18n.get('transactions.details.common.refundedStates.full')} variant={TagVariant.SUCCESS} />
            )}
            {refundedState === RefundedState.PARTIAL && (
                <Tag label={i18n.get('transactions.details.common.refundedStates.partial')} variant={TagVariant.BLUE} />
            )}
        </div>
    );
});

export default memo(PaymentDetailsStatusBox);

// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentDetails/PaymentDetailsStatusBox.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import { BentoTypography, BentoTag, BentoCard, BentoPaymentMethod } from '@adyen/bento-vue3';
import './PaymentDetailsStatusBox.scss';
import {
    getTransactionCategory,
    getAmountStyleForTransaction,
    getRefundTypeForTransaction,
    TX_DATA_CONTAINER,
    TX_STATUS_BOX,
    TX_DATA_AMOUNT,
    TX_DATA_TAGS,
    TX_DATA_PAY_METHOD,
    TX_DATA_PAY_METHOD_LOGO_CONTAINER,
    TX_DATA_PAY_METHOD_DETAIL,
    RefundedState,
    RefundType,
} from '../../../../../domain/src';
import type { TransactionDetails } from '../../../../../domain/src';
import { parsePaymentMethodType, DATE_FORMAT_TRANSACTION_DETAILS } from '@integration-components/utils';

const props = defineProps<{
    refundedState: RefundedState;
    transaction: TransactionDetails;
}>();

const { i18n } = useCoreContext();
const { dateFormat } = useTimezoneAwareDateFormatting(() => props.transaction.balanceAccount?.timeZone);

const amountStyle = computed(() => getAmountStyleForTransaction(props.transaction));
const refundType = computed(() => getRefundTypeForTransaction(props.transaction));
const formattedDate = computed(() => dateFormat(props.transaction.createdAt, DATE_FORMAT_TRANSACTION_DETAILS));
const formattedAmount = computed(() => {
    const { value, currency } = props.transaction.netAmount;
    return `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
});

const amountClass = computed(() => [`${TX_DATA_AMOUNT}--${amountStyle.value}`]);
const paymentMethodType = computed(() => props.transaction.paymentMethod?.type ?? 'bankTransfer');
const paymentMethodDetail = computed(() => {
    if (props.transaction.paymentMethod) return parsePaymentMethodType(props.transaction.paymentMethod, 'detail');
    return props.transaction.bankAccount?.accountNumberLastFourDigits ?? null;
});
</script>

<template>
    <BentoCard>
        <template #content>
            <div :class="[TX_DATA_CONTAINER, TX_STATUS_BOX]">
                <div :class="TX_DATA_TAGS">
                    <BentoTag
                        v-if="props.transaction.category"
                        variant="grey"
                        :label="getTransactionCategory(i18n, props.transaction.category) as string"
                    />

                    <template v-if="refundType">
                        <BentoTag
                            v-if="refundType === RefundType.FULL"
                            variant="green"
                            :label="i18n.get('transactions.details.common.refundTypes.full')"
                        />
                        <BentoTag
                            v-else-if="refundType === RefundType.PARTIAL"
                            variant="blue"
                            :label="i18n.get('transactions.details.common.refundTypes.partial')"
                        />
                    </template>

                    <BentoTag
                        v-if="props.refundedState === RefundedState.FULL"
                        variant="green"
                        :label="i18n.get('transactions.details.common.refundedStates.full')"
                    />
                    <BentoTag
                        v-else-if="props.refundedState === RefundedState.PARTIAL"
                        variant="blue"
                        :label="i18n.get('transactions.details.common.refundedStates.partial')"
                    />
                </div>

                <div :class="[TX_DATA_AMOUNT, ...amountClass]">
                    <BentoTypography variant="title" large>{{ formattedAmount }}</BentoTypography>
                </div>

                <div v-if="props.transaction.paymentMethod || props.transaction.bankAccount" :class="TX_DATA_PAY_METHOD">
                    <div :class="TX_DATA_PAY_METHOD_LOGO_CONTAINER">
                        <BentoPaymentMethod :type="paymentMethodType" />
                    </div>
                    <BentoTypography v-if="paymentMethodDetail" variant="title" :class="TX_DATA_PAY_METHOD_DETAIL">
                        {{ paymentMethodDetail }}
                    </BentoTypography>
                </div>

                <time :datetime="props.transaction.createdAt">
                    <BentoTypography variant="body">{{ formattedDate }}</BentoTypography>
                </time>
            </div>
        </template>
    </BentoCard>
</template>
