// src/components/external/TransactionDetails/components/PaymentDetails/PaymentDetailsSummary.tsx
import { memo } from 'preact/compat';
import { IAmount } from '../../../../../types';
import { isNullish } from '../../../../../utils';
import { useCallback, useMemo } from 'preact/hooks';
import { TransactionDetails } from '../../types';
import { TranslationKey } from '../../../../../translations';
import { TX_DATA_LABEL, TX_DATA_LIST } from '../../constants';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { getTransactionAmountAdjustmentType } from '../../../../utils/translation/getters';
import { StructuredListProps } from '../../../../internal/StructuredList/types';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import Typography from '../../../../internal/Typography/Typography';
import StructuredList from '../../../../internal/StructuredList';
import cx from 'classnames';

const paymentAmountKeys = {
    grossAmount: 'transactions.details.summary.fields.grossAmount',
    netAmount: 'transactions.details.summary.fields.netAmount',
    originalAmount: 'transactions.details.summary.fields.originalAmount',
} satisfies Record<string, TranslationKey>;

const SKIP_ITEM: StructuredListProps['items'][number] = null!;

export interface PaymentDetailsSummaryProps {
    transaction: TransactionDetails;
}

const PaymentDetailsSummary = ({ transaction }: PaymentDetailsSummaryProps) => {
    const { i18n } = useCoreContext();

    const summaryListItems = useMemo<StructuredListProps['items']>(() => {
        const { additions, deductions, amountBeforeDeductions, netAmount, originalAmount } = transaction;

        const getFormattedAmount = (amount?: IAmount) => {
            if (isNullish(amount)) return null;
            const { value, currency } = amount;
            return i18n.amount(value, currency);
        };

        const listItems: StructuredListProps['items'] = [
            // original amount
            originalAmount && ((additions && additions.length > 0) || originalAmount.value !== amountBeforeDeductions.value)
                ? {
                      id: 'originalAmount',
                      key: paymentAmountKeys.originalAmount,
                      value: getFormattedAmount(originalAmount),
                  }
                : SKIP_ITEM,

            // additions
            ...(additions?.map(({ type, ...amount }) => ({
                key: getTransactionAmountAdjustmentType(i18n, type) as TranslationKey,
                value: getFormattedAmount(amount),
            })) ?? []),

            // amountBeforeDeductions
            {
                id: 'grossAmount',
                key: paymentAmountKeys.grossAmount,
                value: getFormattedAmount(amountBeforeDeductions),
            },

            // deductions
            ...(deductions?.map(({ type, ...amount }) => ({
                key: getTransactionAmountAdjustmentType(i18n, type) as TranslationKey,
                value: getFormattedAmount(amount),
            })) ?? []),

            // netAmount
            {
                id: 'netAmount',
                key: paymentAmountKeys.netAmount,
                value: getFormattedAmount(netAmount),
            },
        ];

        return listItems.filter(Boolean);
    }, [i18n, transaction]);

    const renderListPropertyLabel = useCallback<NonNullable<StructuredListProps['renderLabel']>>(
        label => <div className={cx(TX_DATA_LABEL)}>{label}</div>,
        []
    );

    const renderListPropertyValue = useCallback<NonNullable<StructuredListProps['renderValue']>>((val, key) => {
        const stronger = key === paymentAmountKeys.netAmount;
        const strongest = key === paymentAmountKeys.grossAmount;
        const variant = stronger ? TypographyVariant.SUBTITLE : TypographyVariant.BODY;
        return (
            <Typography el={TypographyElement.DIV} variant={variant} stronger={stronger} strongest={strongest}>
                {val}
            </Typography>
        );
    }, []);

    return (
        <StructuredList
            classNames={TX_DATA_LIST}
            items={summaryListItems}
            layout="5-7"
            renderLabel={renderListPropertyLabel}
            renderValue={renderListPropertyValue}
        />
    );
};

export default memo(PaymentDetailsSummary);

// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentDetails/PaymentDetailsSummary.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { BentoStructuredList, BentoStructuredListItem, BentoTypography } from '@adyen/bento-vue3';
import {
    getTransactionAmountAdjustmentType,
    getTransactionAmountAdjustmentTypeInformation,
    TX_DATA_LIST,
} from '@integration-components/transactions/domain';
import { isNullish } from '@integration-components/utils';
import type { TransactionDetails } from '@integration-components/transactions/domain';
import type { IAmount } from '@integration-components/types';
import type { TranslationKey } from '@integration-components/core';

const props = defineProps<{
    transaction: TransactionDetails;
}>();

const { i18n } = useCoreContext();

const paymentAmountKeys = {
    grossAmount: 'transactions.details.summary.fields.grossAmount',
    netAmount: 'transactions.details.summary.fields.netAmount',
    originalAmount: 'transactions.details.summary.fields.originalAmount',
} as const;

function formatAmount(amount?: IAmount): string | null {
    if (isNullish(amount)) return null;
    return `${i18n.amount(amount.value, amount.currency, { hideCurrency: true })} ${amount.currency}`;
}

interface SummaryItem {
    key: TranslationKey;
    value: string | null;
    tooltip?: string | null;
    stronger?: boolean;
}

const summaryItems = computed<SummaryItem[]>(() => {
    const { additions, deductions, amountBeforeDeductions, netAmount, originalAmount } = props.transaction;

    const items: (SummaryItem | null)[] = [
        originalAmount && ((additions && additions.length > 0) || originalAmount.value !== amountBeforeDeductions.value)
            ? { key: paymentAmountKeys.originalAmount as TranslationKey, value: formatAmount(originalAmount) }
            : null,

        ...(additions?.map(({ type, ...amount }) => ({
            key: getTransactionAmountAdjustmentType(i18n, type) as TranslationKey,
            value: formatAmount(amount),
        })) ?? []),

        { key: paymentAmountKeys.grossAmount as TranslationKey, value: formatAmount(amountBeforeDeductions) },

        ...(deductions?.map(({ type, ...amount }) => ({
            key: getTransactionAmountAdjustmentType(i18n, type) as TranslationKey,
            value: formatAmount(amount),
            tooltip: getTransactionAmountAdjustmentTypeInformation(i18n, type) as string | null,
        })) ?? []),

        { key: paymentAmountKeys.netAmount as TranslationKey, value: formatAmount(netAmount), stronger: true },
    ];

    return items.filter(Boolean) as SummaryItem[];
});
</script>

<template>
    <BentoStructuredList :class="TX_DATA_LIST">
        <BentoStructuredListItem v-for="item in summaryItems" :key="item.key" :label="i18n.get(item.key)" :search-tooltip="item.tooltip ?? undefined">
            <BentoTypography variant="body" :strongest="item.stronger">
                {{ item.value }}
            </BentoTypography>
        </BentoStructuredListItem>
    </BentoStructuredList>
</template>
