// packages/domains/transactions/preact/src/TransactionDetails/components/PaymentDetails/PaymentDetailsTimeline.tsx
import { memo } from 'preact/compat';
import { useMemo } from 'preact/hooks';
import { uniqueId } from '@integration-components/utils';
import { TransactionDetails } from '../../types';
import { TX_TIMELINE_LABEL, TX_TIMELINE_VALUE } from '../../constants';
import { getTransactionTimelineTxStatus, getTransactionTimelineTxType } from '@integration-components/transactions/domain';
import { StructuredListItem, StructuredListProps } from '../../../../../../../../src/components/internal/StructuredList/types';
import { TimelineDateFormat, TimelineTimestamp } from '../../../../../../../../src/components/internal/Timeline/types';
import { TypographyElement, TypographyVariant } from '../../../../../../../../src/components/internal/Typography/types';
import { TimelineItem } from '../../../../../../../../src/components/internal/Timeline/components/TimelineItem';
import { useCoreContext } from '@integration-components/core/preact';
import Typography from '../../../../../../../../src/components/internal/Typography/Typography';
import StructuredList from '../../../../../../../../src/components/internal/StructuredList';
import Timeline from '../../../../../../../../src/components/internal/Timeline/Timeline';

export interface PaymentDetailsTimelineProps {
    transaction: TransactionDetails;
}

interface PaymentDetailsTimelineItemProps {
    event: NonNullable<TransactionDetails['events']>[number];
    defaultTimestamp: TimelineTimestamp;
}

const PaymentDetailsTimeline = ({ transaction }: PaymentDetailsTimelineProps) => {
    const createdAt = transaction.createdAt;
    const events = transaction.events;
    const timezone = transaction.balanceAccount?.timeZone;

    const defaultTimestamp = useMemo<TimelineTimestamp>(
        () => ({
            format: TimelineDateFormat.FULL_DATE_EXACT_TIME_WITHOUT_SECONDS,
            date: new Date(createdAt),
            timezone,
        }),
        [createdAt, timezone]
    );

    const eventKeys = useMemo(() => {
        const map = new WeakMap<NonNullable<typeof events>[number], string>();
        events?.forEach(event => map.set(event, uniqueId()));
        return map;
    }, [events]);

    return events ? (
        <Timeline showMore={{ limit: 2, placement: 'before-last' }}>
            {events.map(event => (
                <PaymentDetailsTimeline.Item key={eventKeys.get(event)} event={event} defaultTimestamp={defaultTimestamp} />
            ))}
        </Timeline>
    ) : null;
};

const renderTimelineListPropertyLabel: NonNullable<StructuredListProps['renderLabel']> = label => (
    <Typography el={TypographyElement.DIV} variant={TypographyVariant.CAPTION} className={TX_TIMELINE_LABEL}>
        {label}
    </Typography>
);

const renderTimelineListPropertyValue: NonNullable<StructuredListProps['renderValue']> = label => (
    <Typography el={TypographyElement.DIV} variant={TypographyVariant.CAPTION} className={TX_TIMELINE_VALUE}>
        {label}
    </Typography>
);

PaymentDetailsTimeline.Item = memo(({ defaultTimestamp, event }: PaymentDetailsTimelineItemProps) => {
    const { amount, createdAt, status, type } = event;
    const { i18n } = useCoreContext();

    const timestamp = useMemo<TimelineTimestamp>(() => ({ ...defaultTimestamp, date: new Date(createdAt) }), [defaultTimestamp, createdAt]);
    const formattedType = useMemo(() => getTransactionTimelineTxType(i18n, type)!, [i18n, type]);
    const items = useMemo<StructuredListItem[]>(() => {
        const { currency, value } = amount;
        const formattedAmount = `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
        const formattedStatus = getTransactionTimelineTxStatus(i18n, status)!;
        return [
            { key: 'transactions.details.timeline.fields.amount', value: formattedAmount },
            { key: 'transactions.details.timeline.fields.status', value: formattedStatus },
        ] as const;
    }, [i18n, amount, status]);

    // [TODO] - Remove this harcoded type once the team reviews all statuses and types and have less number of different strings, and more friendly ones.
    const fixedType = status.toLowerCase().includes('refund') ? 'Refund' : status.toLowerCase().includes('auth') ? 'Capture' : formattedType;

    return (
        <TimelineItem title={fixedType} timestamp={timestamp}>
            <StructuredList
                align="start"
                layout="3-9"
                items={items}
                renderLabel={renderTimelineListPropertyLabel}
                renderValue={renderTimelineListPropertyValue}
            />
        </TimelineItem>
    );
});

export default memo(PaymentDetailsTimeline);

// packages/domains/transactions/vue/src/TransactionDetails/components/PaymentDetails/PaymentDetailsTimeline.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import { BentoDateFormat, BentoTimeline, BentoTimelineItem, BentoTimelineShowMorePlacement } from '@adyen/bento-vue3';
import { getTransactionTimelineTxStatus, getTransactionTimelineTxType } from '../../../../../domain/src';
import { DATE_FORMAT_TRANSACTIONS } from '@integration-components/utils/datetime/formats';
import type { TransactionDetails } from '../../../../../domain/src';

const props = defineProps<{
    transaction: TransactionDetails;
}>();

const { i18n } = useCoreContext();
const { dateFormat } = useTimezoneAwareDateFormatting(() => props.transaction.balanceAccount?.timeZone);

const events = computed(() => props.transaction.events ?? []);

function formatAmount(value: number, currency: string): string {
    return `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
}

function getFixedType(status: string, formattedType: string): string {
    if (status.toLowerCase().includes('refund')) return 'Refund';
    if (status.toLowerCase().includes('auth')) return 'Capture';
    return formattedType;
}

function formatTimestamp(date: string): string {
    return dateFormat(date, DATE_FORMAT_TRANSACTIONS);
}
</script>

<template>
    <BentoTimeline v-if="events.length" :show-more="{ limit: 2, placement: BentoTimelineShowMorePlacement.BEFORE_LAST }">
        <BentoTimelineItem
            v-for="(event, index) in events"
            :key="`${event.createdAt}-${event.status}-${index}`"
            :title="getFixedType(event.status, getTransactionTimelineTxType(i18n, event.type) as string)"
            :timestamp="{
                date: new Date(event.createdAt),
                format: BentoDateFormat.FULL_DATE_TIME_WITHOUT_PERIOD,
                value: formatTimestamp(event.createdAt),
            }"
            :dataList="[
                {
                    label: i18n.get('transactions.details.timeline.fields.amount'),
                    value: formatAmount(event.amount.value, event.amount.currency),
                },
                {
                    label: i18n.get('transactions.details.timeline.fields.status'),
                    value: getTransactionTimelineTxStatus(i18n, event.status) as string,
                },
            ]"
        />
    </BentoTimeline>
</template>
