// packages/domains/transactions/vue/src/TransactionsOverview/components/InsightsTotals/InsightsTotals.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCoreContext } from '@integration-components/core/vue';
import { ErrorMessageDisplay } from '@integration-components/composables-vue';
import { BentoDivider, BentoList, BentoListItem, BentoTypography } from '@adyen/bento-vue3';
import { getTransactionCategory } from '@integration-components/transactions/domain';
import type { CurrencyLookupRecord } from '../../composables/useCurrenciesLookup';
import type { useTransactionsTotals } from '../../composables/useTransactionsTotals';
import styles from './InsightsTotals.module.scss';

const props = defineProps<{
    currency?: string;
    currenciesLookupResult: ReturnType<typeof import('../../composables/useCurrenciesLookup').useCurrenciesLookup>;
    transactionsTotalsResult: ReturnType<typeof useTransactionsTotals>;
}>();

const { i18n } = useCoreContext();

const data = computed<CurrencyLookupRecord['totals'] | undefined>(() => {
    if (!props.currency) return undefined;
    return props.currenciesLookupResult.currenciesDictionary.value[props.currency]?.totals;
});

const isLoading = computed(() => props.transactionsTotalsResult.isWaiting.value);

function formatAmount(value: number, currency: string): string {
    return `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
}

const incomingsBreakdown = computed(() =>
    (data.value?.breakdown?.incomings ?? []).map((item: any, idx: number) => ({
        id: `incoming-${idx}`,
        label: getTransactionCategory(i18n, item.category) as string,
        value: formatAmount(item.value, data.value!.currency),
    }))
);

const expensesBreakdown = computed(() =>
    (data.value?.breakdown?.expenses ?? []).map((item: any, idx: number) => ({
        id: `expense-${idx}`,
        label: getTransactionCategory(i18n, item.category) as string,
        value: formatAmount(item.value, data.value!.currency),
    }))
);
</script>

<template>
    <div>
        <template v-if="isLoading">
            <div>
                <span />
                <div :class="styles.breakdowns">
                    <div v-for="n in 2" :key="n" :class="styles.breakdown">
                        <span />
                    </div>
                </div>
            </div>
        </template>

        <template v-else-if="props.transactionsTotalsResult.error.value">
            <ErrorMessageDisplay
                :error-info="{
                    title: 'transactions.common.errors.somethingWentWrong',
                    messages: ['transactions.common.errors.retry'],
                    refreshComponent: true,
                }"
                :on-refresh="props.transactionsTotalsResult.refresh"
                with-image
                :outlined="false"
                :absolute-position="false"
                :with-background="false"
            />
        </template>

        <template v-else-if="data">
            <div :class="styles.amountDisplay">
                <BentoTypography variant="body">
                    {{ i18n.get('transactions.overview.totals.tags.periodResult') }}
                </BentoTypography>
                <div :class="styles.amountDisplayAmount">
                    <BentoTypography variant="title" medium>
                        {{ i18n.amount(data.total, data.currency, { hideCurrency: true }) }}
                    </BentoTypography>
                    <BentoTypography variant="title" medium>
                        {{ data.currency }}
                    </BentoTypography>
                </div>
            </div>

            <div :class="styles.breakdowns">
                <div :class="styles.breakdown">
                    <div :class="styles.amountDisplay">
                        <BentoTypography variant="body">
                            {{ i18n.get('transactions.overview.totals.tags.incoming') }}
                        </BentoTypography>
                        <div :class="styles.amountDisplayAmount">
                            <BentoTypography variant="body" strongest>
                                {{ i18n.amount(data.incomings, data.currency, { hideCurrency: true }) }}
                            </BentoTypography>
                            <BentoTypography variant="body" strongest>
                                {{ data.currency }}
                            </BentoTypography>
                        </div>
                    </div>
                    <BentoList v-if="incomingsBreakdown.length" :class="styles.breakdownList">
                        <BentoListItem
                            v-for="(item, index) in incomingsBreakdown"
                            :key="item.id"
                            :label="item.label"
                            :show-bottom-divider="index < incomingsBreakdown.length - 1"
                        >
                            <template #end>
                                <BentoTypography variant="body">{{ item.value }}</BentoTypography>
                            </template>
                        </BentoListItem>
                    </BentoList>
                </div>

                <BentoDivider :class="styles.divider" variant="vertical" />

                <div :class="styles.breakdown">
                    <div :class="styles.amountDisplay">
                        <BentoTypography variant="body">
                            {{ i18n.get('transactions.overview.totals.tags.outgoing') }}
                        </BentoTypography>
                        <div :class="styles.amountDisplayAmount">
                            <BentoTypography variant="body" strongest>
                                {{ i18n.amount(data.expenses, data.currency, { hideCurrency: true }) }}
                            </BentoTypography>
                            <BentoTypography variant="body" strongest>
                                {{ data.currency }}
                            </BentoTypography>
                        </div>
                    </div>
                    <BentoList v-if="expensesBreakdown.length" :class="styles.breakdownList">
                        <BentoListItem
                            v-for="(item, index) in expensesBreakdown"
                            :key="item.id"
                            :label="item.label"
                            :show-bottom-divider="index < expensesBreakdown.length - 1"
                        >
                            <template #end>
                                <BentoTypography variant="body">{{ item.value }}</BentoTypography>
                            </template>
                        </BentoListItem>
                    </BentoList>
                </div>
            </div>
        </template>
    </div>
</template>

// src/components/external/TransactionsOverview/components/InsightsTotals/InsightsTotals.tsx
import cx from 'classnames';
import { memo } from 'preact/compat';
import { useMemo } from 'preact/hooks';
import { classes } from './constants';
import { TranslationKey } from '../../../../../translations';
import { ITransactionCategory } from '../../../../../types';
import { getTransactionCategory } from '../../../../utils/translation/getters';
import { StructuredListItem } from '../../../../internal/StructuredList/types';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { ErrorMessageDisplay } from '../../../../internal/ErrorMessageDisplay/ErrorMessageDisplay';
import AmountDisplay, { AmountDisplayProps } from '../AmountDisplay/AmountDisplay';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import useTransactionsTotals from '../../hooks/useTransactionsTotals';
import useCurrenciesLookup from '../../hooks/useCurrenciesLookup';
import Typography from '../../../../internal/Typography/Typography';
import StructuredList from '../../../../internal/StructuredList';
import './InsightsTotals.scss';

interface InsightsTotalsProps {
    currency?: string;
    currenciesLookupResult: ReturnType<typeof useCurrenciesLookup>;
    transactionsTotalsResult: ReturnType<typeof useTransactionsTotals>;
}

const InsightsTotals = ({ currency, currenciesLookupResult, transactionsTotalsResult }: InsightsTotalsProps) => {
    const { i18n } = useCoreContext();
    const { currenciesDictionary } = currenciesLookupResult;

    const data = (currency && currenciesDictionary[currency]?.totals) || undefined;

    if (transactionsTotalsResult.isWaiting || !data) {
        const breakdownArray = Array.from({ length: 2 });
        const breakdownListArray = Array.from({ length: 3 });
        const className = cx(classes.skeleton, classes.skeletonLoading);

        return (
            <div className={classes.root}>
                <span className={cx(className, classes.skeletonAmount, classes.skeletonAmountLarge)} />

                <div className={classes.breakdowns}>
                    {breakdownArray.map((_, index) => (
                        <div className={classes.breakdown} key={`breakdown-${index}`}>
                            <span className={cx(className, classes.skeletonAmount)} />

                            <div className={classes.breakdownList}>
                                {breakdownListArray.map((_, index) => (
                                    <span className={className} key={`breakdown-${index}`} />
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        );
    }

    return (
        <div className={classes.root}>
            {transactionsTotalsResult.error ? (
                <div className={classes.errorContainer}>
                    <ErrorMessageDisplay
                        title={'common.errors.somethingWentWrong'}
                        message={['common.errors.retry']}
                        absolutePosition={false}
                        outlined={false}
                        withImage
                        refreshComponent
                        onRefreshComponent={transactionsTotalsResult.refresh}
                    />
                </div>
            ) : (
                <>
                    <AmountDisplay
                        amount={data.total}
                        currency={data.currency}
                        label={i18n.get('transactions.overview.totals.tags.periodResult')}
                        large
                    />

                    <div className={classes.breakdowns}>
                        <InsightsTotals.Breakdown
                            amount={data.incomings}
                            breakdown={data.breakdown.incomings}
                            currency={data.currency}
                            label={i18n.get('transactions.overview.totals.tags.incoming')}
                        />
                        <InsightsTotals.Breakdown
                            amount={data.expenses}
                            breakdown={data.breakdown.expenses}
                            currency={data.currency}
                            label={i18n.get('transactions.overview.totals.tags.outgoing')}
                        />
                    </div>
                </>
            )}
        </div>
    );
};

interface BreakdownProps extends AmountDisplayProps {
    ariaLabel?: string;
    breakdown: readonly { category: ITransactionCategory; value: number }[];
}

InsightsTotals.Breakdown = ({ ariaLabel, breakdown, ...amountDisplayProps }: BreakdownProps) => {
    const { currency } = amountDisplayProps;
    const { i18n } = useCoreContext();

    const listItems = useMemo(
        () =>
            breakdown.map(
                ({ category, value }): StructuredListItem => ({
                    key: getTransactionCategory(i18n, category) as TranslationKey,
                    value: `${i18n.amount(value, currency)} ${currency}`,
                })
            ),
        [i18n, breakdown, currency]
    );

    return (
        <div className={classes.breakdown}>
            <AmountDisplay {...amountDisplayProps} />
            <StructuredList
                items={listItems}
                aria-label={ariaLabel}
                classNames={classes.breakdownList}
                renderLabel={label => (
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                        {label}
                    </Typography>
                )}
                renderValue={value => (
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION} stronger>
                        {value}
                    </Typography>
                )}
            />
        </div>
    );
};

export default memo(InsightsTotals);
