// packages/domains/capital/vue/src/CapitalOverview/components/GrantRepaymentDetails/GrantRepaymentDetails.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoDivider, BentoTypography } from '@adyen/bento-vue3';
import { getBankAccount, getTransferInstrumentIds } from '@integration-components/capital/domain';
import { useCoreContext } from '@integration-components/core/vue';
import type { IGrant } from '@integration-components/types';
import AccountDetails from '../AccountDetails/AccountDetails.vue';
import GrantAdjustmentDetails from '../GrantAdjustmentDetails/GrantAdjustmentDetails.vue';
import styles from './GrantRepaymentDetails.module.scss';

const props = defineProps<{
    grant: IGrant;
    onDetailsClose: () => void;
}>();

const { i18n } = useCoreContext();
const bankAccount = computed(() => getBankAccount(props.grant));
const transferInstrumentIds = computed(() => getTransferInstrumentIds(props.grant));
const addingBeneficiaryInstruction = computed(() =>
    bankAccount.value
        ? i18n.get('capital.overview.repayment.instructions.addingBeneficiary', {
              values: { beneficiaryName: bankAccount.value.beneficiaryName },
          })
        : undefined
);
</script>

<template>
    <GrantAdjustmentDetails
        v-if="bankAccount"
        :class="styles.root"
        header-title-key="capital.overview.repayment.title"
        header-subtitle-key="capital.overview.repayment.subtitle"
        :on-details-close="props.onDetailsClose"
    >
        <div :class="styles.repaymentAccount">
            <BentoTypography variant="body" stronger>
                {{ i18n.get('capital.overview.repayment.accountDetails.title') }}
            </BentoTypography>
            <AccountDetails :bank-account="bankAccount" />
        </div>

        <div :class="styles.notice">
            <template v-if="transferInstrumentIds.length">
                <div>
                    <BentoTypography el="span" variant="caption" stronger>
                        {{ i18n.get('capital.overview.repayment.transferInstruments') }}
                    </BentoTypography>

                    <ul :class="styles.transferInstrumentList">
                        <li v-for="transferInstrumentId in transferInstrumentIds" :key="transferInstrumentId" :class="styles.transferInstrumentItem">
                            <BentoTypography el="span" variant="caption">
                                {{ transferInstrumentId }}
                            </BentoTypography>
                        </li>
                    </ul>
                </div>
                <BentoDivider />
            </template>

            <div>
                <BentoTypography el="span" variant="caption" stronger>
                    {{ i18n.get('capital.overview.repayment.instructions.title') }}
                </BentoTypography>
                <ol :class="styles.instructionList">
                    <li>
                        <BentoTypography el="span" variant="caption">
                            {{ addingBeneficiaryInstruction }}
                        </BentoTypography>
                    </li>
                    <li>
                        <BentoTypography el="span" variant="caption">
                            {{ i18n.get('capital.overview.repayment.instructions.sendingPayment') }}
                        </BentoTypography>
                    </li>
                    <li>
                        <BentoTypography el="span" variant="caption">
                            {{ i18n.get('capital.overview.repayment.instructions.waiting') }}
                        </BentoTypography>
                    </li>
                </ol>
            </div>

            <BentoTypography el="span" variant="caption" :class="styles.verifiedBankAccountDetails">
                {{ i18n.get('capital.overview.repayment.instructions.verifiedAccount') }}
            </BentoTypography>
        </div>
    </GrantAdjustmentDetails>
</template>

// src/components/external/CapitalOverview/components/GrantRepaymentDetails/GrantRepaymentDetails.tsx
import { FunctionalComponent } from 'preact';
import { useMemo } from 'preact/hooks';
import useCoreContext from '../../../../../core/Context/useCoreContext';
import type { GrantAdjustmentDetailsProps } from '../GrantAdjustmentDetails/types';
import Typography from '../../../../internal/Typography/Typography';
import { TypographyElement, TypographyVariant } from '../../../../internal/Typography/types';
import { AccountDetails } from '../AccountDetails/AccountDetails';
import { GrantAdjustmentDetails } from '../GrantAdjustmentDetails/GrantAdjustmentDetails';
import './GrantRepaymentDetails.scss';
import { Divider } from '../../../../internal/Divider/Divider';
import { Translation } from '../../../../internal/Translation';

const BASE_CLASS = 'adyen-pe-grant-repayment-details';

const CLASS_NAMES = {
    instructionList: `${BASE_CLASS}__instruction-list`,
    notice: `${BASE_CLASS}__notice`,
    repaymentAccount: `${BASE_CLASS}__repayment-account`,
    transferInstrumentItem: `${BASE_CLASS}__transfer-instrument-item`,
    transferInstrumentList: `${BASE_CLASS}__transfer-instrument-list`,
    verifiedBankAccountDetails: `${BASE_CLASS}__verified-bank-account-details`,
};

export const GrantRepaymentDetails: FunctionalComponent<GrantAdjustmentDetailsProps> = ({ grant, onDetailsClose }) => {
    const { i18n } = useCoreContext();

    const bankAccount = useMemo(() => {
        // There can be more than one unscheduled repayment account, however, we are only showing the first one.
        // If there be any need to show the rest of them in the future, some updates will be required.
        return grant.unscheduledRepaymentAccounts?.[0];
    }, [grant.unscheduledRepaymentAccounts]);

    return bankAccount ? (
        <GrantAdjustmentDetails
            className={BASE_CLASS}
            onDetailsClose={onDetailsClose}
            headerTitleKey="capital.overview.repayment.title"
            headerSubtitleKey="capital.overview.repayment.subtitle"
        >
            <div className={CLASS_NAMES.repaymentAccount}>
                <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} stronger>
                    {i18n.get('capital.overview.repayment.accountDetails.title')}
                </Typography>
                <AccountDetails bankAccount={bankAccount} />
            </div>
            <div className={CLASS_NAMES.notice}>
                {!!grant.transferInstruments?.length && (
                    <>
                        <div>
                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION} stronger>
                                {i18n.get('capital.overview.repayment.transferInstruments')}
                            </Typography>

                            <ul className={CLASS_NAMES.transferInstrumentList}>
                                {grant.transferInstruments?.map(({ accountIdentifier }) => (
                                    <li key={accountIdentifier} className={CLASS_NAMES.transferInstrumentItem}>
                                        <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                                            {accountIdentifier}
                                        </Typography>
                                    </li>
                                ))}
                            </ul>
                        </div>
                        <Divider />
                    </>
                )}
                <div>
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION} stronger>
                        {i18n.get('capital.overview.repayment.instructions.title')}
                    </Typography>
                    <ul className={CLASS_NAMES.instructionList}>
                        <li>
                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                                <Translation
                                    translationKey={'capital.overview.repayment.instructions.addingBeneficiary'}
                                    fills={{
                                        beneficiaryName: (
                                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION} stronger>
                                                {bankAccount.beneficiaryName}
                                            </Typography>
                                        ),
                                    }}
                                />
                            </Typography>
                        </li>
                        <li>
                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                                {i18n.get('capital.overview.repayment.instructions.sendingPayment')}
                            </Typography>
                        </li>
                        <li>
                            <Typography el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                                {i18n.get('capital.overview.repayment.instructions.waiting')}
                            </Typography>
                        </li>
                    </ul>
                </div>
                <Typography className={CLASS_NAMES.verifiedBankAccountDetails} el={TypographyElement.SPAN} variant={TypographyVariant.CAPTION}>
                    {i18n.get('capital.overview.repayment.instructions.verifiedAccount')}
                </Typography>
            </div>
        </GrantAdjustmentDetails>
    ) : null;
};
