// packages/domains/payByLink/vue/src/PaymentLinkSettings/components/SecondaryNav.vue
<script setup lang="ts">
import { BentoTypography } from '@adyen/bento-vue3';
import type { MenuItemType, PaymentLinkSettingsItem } from '../types';
import styles from './SecondaryNav.module.scss';

defineProps<{
    items: MenuItemType[];
    activeValue: PaymentLinkSettingsItem | null;
}>();

const emit = defineEmits<{
    select: [value: PaymentLinkSettingsItem];
}>();
</script>

<template>
    <nav :class="styles.root">
        <ul :class="styles.list">
            <li v-for="item in items" :key="item.value">
                <button
                    type="button"
                    :class="[styles.item, { [styles.itemActive]: item.value === activeValue }]"
                    :aria-current="item.value === activeValue ? 'true' : undefined"
                    @click="emit('select', item.value)"
                >
                    <BentoTypography variant="body" el="span">{{ item.label }}</BentoTypography>
                </button>
            </li>
        </ul>
    </nav>
</template>

// src/components/internal/SecondaryNav/SecondaryNav.tsx
import './SecondaryNav.scss';
import cx from 'classnames';

interface SecondaryNavProps {
    className?: string;
    items: { value: string; label: string }[];
    activeValue: string;
    onValueChange: (value: string) => void;
}

export const SecondaryNav = ({ className, items, activeValue, onValueChange }: SecondaryNavProps) => {
    return (
        <aside className={cx('adyen-pe-secondary-nav', className)}>
            <ul className="adyen-pe-secondary-nav__list">
                {items.map(item => (
                    <li className="adyen-pe-secondary-nav__list-item">
                        <button
                            aria-selected={item.value === activeValue}
                            className={cx('adyen-pe-secondary-nav__item', { 'adyen-pe-secondary-nav__item--active': item.value === activeValue })}
                            onClick={() => {
                                onValueChange(item.value);
                            }}
                        >
                            <p data-testid="typography" className="adyen-pe-secondary-nav__item-label">
                                {item.label}
                            </p>
                        </button>
                    </li>
                ))}
            </ul>
        </aside>
    );
};
