// packages/domains/capital/vue/src/CapitalOverview/components/GrantList/GrantList.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { EnhancedCapitalState, OnFundsRequestCallback } from '@integration-components/capital/domain';
import type { IGrant } from '@integration-components/types';

const props = defineProps<{
    capitalState: EnhancedCapitalState;
    grants: IGrant[];
    hideTitle?: boolean;
    onFundsRequest?: OnFundsRequestCallback;
    onGrantListUpdateRequest: (data: IGrant) => void;
    onOfferDismiss?: (goToPreviousStep: () => void) => void;
}>();

const isCapitalOfferVisible = ref(false);
console.log(props);
// const goBackToPreviousStep = () => {
//     isCapitalOfferVisible.value = false;
// };

// const goToNextStep = () => {
//     isCapitalOfferVisible.value = true;
// };
//
// const goBackToList = () => {
//     if (props.onOfferDismiss) {
//         props.onOfferDismiss(goBackToPreviousStep);
//     } else {
//         goBackToPreviousStep();
//     }
// };
//
// const handleFundsRequest: OnFundsRequestCallback = (data, renewsGrantId) => {
//     if (props.onFundsRequest) {
//         props.onFundsRequest(data, renewsGrantId);
//     } else {
//         props.onGrantListUpdateRequest({ ...data, renewsGrantId });
//         isCapitalOfferVisible.value = false;
//     }
// };
</script>

<template>
    <!-- TODO: Render CapitalOffer when the Vue component is available. -->
    <div v-if="isCapitalOfferVisible" />
    <!-- TODO: Render GrantsDisplay when the Vue component is available. -->
    <div v-else />
</template>

// src/components/external/Capital/CapitalOverview/components/GrantList/GrantList.tsx
import { FunctionalComponent } from 'preact';
import { GrantListProps } from './types';
import './GrantList.scss';
import { useCallback, useState } from 'preact/hooks';
import { CapitalOffer } from '../../../CapitalOffer/components/CapitalOffer/CapitalOffer';
import { GrantsDisplay } from './GrantsDisplay';
import { IGrant } from '../../../../../../types';

export const GrantList: FunctionalComponent<GrantListProps> = ({
    externalDynamicOffersConfig,
    grantList,
    newOfferAvailable,
    onFundsRequest,
    onGrantListUpdateRequest,
    onOfferDismiss,
}) => {
    const [isCapitalOfferVisible, setIsCapitalOfferVisible] = useState<boolean>(false);

    const goBackToPreviousStep = useCallback(() => setIsCapitalOfferVisible(false), []);
    const goToNextStep = useCallback(() => setIsCapitalOfferVisible(true), []);

    const goBackToList = useCallback(() => {
        onOfferDismiss ? onOfferDismiss(goBackToPreviousStep) : goBackToPreviousStep();
    }, [goBackToPreviousStep, onOfferDismiss]);

    const handleFundsRequest = useCallback(
        (data: IGrant) => {
            if (onFundsRequest) {
                onFundsRequest(data);
            } else {
                onGrantListUpdateRequest(data);
                setIsCapitalOfferVisible(false);
            }
        },
        [onFundsRequest, onGrantListUpdateRequest]
    );

    return (
        <>
            {isCapitalOfferVisible ? (
                <CapitalOffer
                    externalDynamicOffersConfig={externalDynamicOffersConfig}
                    onFundsRequest={handleFundsRequest}
                    onOfferDismiss={goBackToList}
                />
            ) : (
                <GrantsDisplay grantList={grantList} newOfferAvailable={newOfferAvailable} onNewOfferRequest={goToNextStep} />
            )}
        </>
    );
};
