// packages/domains/payByLink/preact/src/PaymentLinkDetails/components/PaymentLinkSummary/PaymentLinkSummary.tsx
import { useMemo } from 'preact/hooks';
import { useCoreContext } from '@integration-components/core/preact';
import Card from '@integration-components/ui-components-preact/Card/Card';
import { Tag } from '@integration-components/ui-components-preact/Tag/Tag';
import { TagVariant } from '@integration-components/ui-components-preact/Tag/types';
import { TypographyVariant, TypographyElement } from '@integration-components/ui-components-preact/Typography/types';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { DATE_FORMAT_PAYMENT_LINK_DETAILS_SUMMARY } from '@integration-components/utils';
import { IPaymentLinkStatus, IPaymentLinkDetails } from '@integration-components/types';
import { useTimezoneAwareDateFormatting } from '@integration-components/hooks-preact';
import './PaymentLinkSummary.scss';

const CLASSNAMES = {
    root: 'adyen-pe-payment-link-summary',
    content: 'adyen-pe-payment-link-summary__content',
    expiresLabel: 'adyen-pe-payment-link-summary__expires-label',
};

type PaymentLinkSummaryProps = {
    paymentLink: IPaymentLinkDetails;
};

export const PaymentLinkSummary = ({ paymentLink }: PaymentLinkSummaryProps) => {
    const { i18n } = useCoreContext();
    const { dateFormat } = useTimezoneAwareDateFormatting();
    const status = paymentLink?.linkInformation.status;
    const getStatusVariant = (status: IPaymentLinkStatus): TagVariant => {
        switch (status) {
            case 'active':
                return TagVariant.BLUE;
            case 'completed':
                return TagVariant.SUCCESS;
            case 'expired':
                return TagVariant.DEFAULT;
            case 'paymentPending':
                return TagVariant.WARNING;
            default:
                return TagVariant.DEFAULT;
        }
    };

    const formattedAmount = useMemo(() => {
        if (!paymentLink?.linkInformation.amount) return null;
        const { value, currency } = paymentLink.linkInformation.amount;
        return `${i18n.amount(value, currency, { hideCurrency: true })} ${currency}`;
    }, [i18n, paymentLink?.linkInformation.amount]);

    return (
        <Card classNameModifiers={[CLASSNAMES.root]}>
            <div className={CLASSNAMES.content}>
                <Tag variant={getStatusVariant(status)}>
                    {i18n.has(`payByLink.common.status.${status}`)
                        ? i18n.get(`payByLink.common.status.${status}`)
                        : paymentLink?.linkInformation.status}
                </Tag>
                <Typography variant={TypographyVariant.TITLE} large>
                    {formattedAmount}
                </Typography>
                <div>
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY} className={CLASSNAMES.expiresLabel}>
                        {`${i18n.get('payByLink.details.fields.expiresOn')}: `}
                    </Typography>
                    <Typography el={TypographyElement.SPAN} variant={TypographyVariant.BODY}>
                        {dateFormat(paymentLink.linkInformation.expirationDate, DATE_FORMAT_PAYMENT_LINK_DETAILS_SUMMARY)}
                    </Typography>
                </div>
            </div>
        </Card>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkDetails/components/PaymentLinkSummary/PaymentLinkSummary.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoCard, BentoTag, BentoTypography } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import { DATE_FORMAT_PAYMENT_LINK_DETAILS_SUMMARY } from '@integration-components/utils';
import {
    getPaymentLinkStatusLabel,
    getPaymentLinkStatusTagVariant,
    type PaymentLinkStatusTagVariant,
} from '@integration-components/payByLink/domain';
import type { IPaymentLinkDetails } from '@integration-components/types';
import styles from './PaymentLinkSummary.module.scss';

const TAG_VARIANT_MAP = {
    info: 'blue',
    success: 'green',
    neutral: 'grey',
    warning: 'orange',
} as const satisfies Record<PaymentLinkStatusTagVariant, string>;

const props = defineProps<{
    paymentLink: IPaymentLinkDetails;
}>();

const { i18n } = useCoreContext();
const { dateFormat } = useTimezoneAwareDateFormatting();

const status = computed(() => props.paymentLink.linkInformation.status);
const statusLabel = computed(() => getPaymentLinkStatusLabel(i18n, status.value));
const statusVariant = computed(() => TAG_VARIANT_MAP[getPaymentLinkStatusTagVariant(status.value)]);

const formattedAmount = computed(() => {
    const { amount } = props.paymentLink.linkInformation;
    if (!amount) return null;
    return `${i18n.amount(amount.value, amount.currency, { hideCurrency: true })} ${amount.currency}`;
});

const formattedExpirationDate = computed(() =>
    dateFormat(props.paymentLink.linkInformation.expirationDate, DATE_FORMAT_PAYMENT_LINK_DETAILS_SUMMARY)
);
</script>

<template>
    <BentoCard>
        <template #content>
            <div :class="styles.content">
                <BentoTag v-if="statusLabel" :label="statusLabel" :variant="statusVariant" />
                <BentoTypography variant="title" large>
                    {{ formattedAmount }}
                </BentoTypography>
                <div>
                    <BentoTypography el="span" variant="body" :class="styles.expiresLabel">
                        {{ `${i18n.get('payByLink.details.fields.expiresOn')}: ` }}
                    </BentoTypography>
                    <BentoTypography el="span" variant="body">
                        {{ formattedExpirationDate }}
                    </BentoTypography>
                </div>
            </div>
        </template>
    </BentoCard>
</template>
